RAW2CALOHIT: histmgr::HistogramOutput Class Reference
histmgr::HistogramOutput Class Reference
Processor which writes histogram groups to files at the end of the processing.
#include <HistogramOutput.hh>
Public Member Functions
Processor * newProcessor ()
void init ()
Called at the begin of the job before anything is read.
void end ()
Called for every run, e.g.
Protected Attributes
StringVec _fileFolderAssignment
Detailed Description
Processor which writes histogram groups to files at the end of the processing.
The histogram groups and their destination files are specified by marlin processor parameters. Each histogram group can be written to a seperate file.
Definition at line 22 of file HistogramOutput.hh.
Member Function Documentation
void histmgr::HistogramOutput::end ()
Called for every run, e.g.
overwrite to initialize run dependent histograms.Called for every event - the working horse.
Definition at line 117 of file HistogramOutput.cc.
References histmgr::HistMgr::writeHistograms().
void histmgr::HistogramOutput::init ()
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Definition at line 57 of file HistogramOutput.cc.
References histmgr::HistMgr::assignFileName(), and histmgr::HistMgr::warnOnUnassigned().
The documentation for this class was generated from the following files:
HistogramOutput.hh
HistogramOutput.cc