RAW2CALOHIT: CALICE::NVector_t< T, dimension > Class Template Reference
CALICE::NVector_t< T, dimension > Class Template Reference
Simple n-dimensional vector (size of the vector is defined at compile time) Provides methods to add and subtract vectors or multiply and divide by scalars.
#include <NVector_t.hh>
Public Member Functions
NVector_t & clear ()
Set all elements to zero.
UInt_t n () const
Get the dimension of the vector.
NVector_t & set (const T *array)
Set the elements of the vector from the given array.
Float_t & operator[] (UInt_t index)
get the element of the given index (read and write access).
const Float_t & operator[] (UInt_t index) const
get the element of the given index (read access only).
NVector_t & operator+= (const NVector_t &a)
Add a vector having the same dimension to this vector.
NVector_t & operator-= (const NVector_t &a)
Subtract a vector having the same dimension to this vector.
NVector_t & operator*= (const float c)
Multiply this vector by a scalar.
NVector_t & operator/= (const float c)
Divide this vector by a scalar.
Float_t * data ()
get a pointer to the underlying array (read and write access).
const Float_t * data () const
get a pointer to the underlying array (read only access).
Private Attributes
Float_t _x [dimension]
Friends
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator- (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Subtract two vectors of the same dimension.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator+ (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Add two vectors of the same dimension.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator* (const NVector_t< _T, _dimension > &a, float c)
Multiply a vector by a scalar.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator* (float c, const NVector_t< _T, _dimension > &a)
Multiply a vector by a scalar.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator/ (const NVector_t< _T, _dimension > &a, float c)
Divide a vector by a scalar.
template<class _T , int _dimension>
Double_t norm (const NVector_t< _T, _dimension > &a)
Euclidean Norm of a vector.
template<class _T , int _dimension>
Double_t dot (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Scalar product of two vectors of the same dimension.
ThreeVector_t cross (const ThreeVector_t &a, const ThreeVector_t &b)
cross product of two three dimensional vectors.
Detailed Description
template<class T, int dimension>
class CALICE::NVector_t< T, dimension >
Simple n-dimensional vector (size of the vector is defined at compile time) Provides methods to add and subtract vectors or multiply and divide by scalars.
There are also functions to calculate the scalar and cross products (the latter for three dimensional vectors only). A flat array (currently floats only) can be casted to an NVector_t: lcio::CalorimeterHit *a_hit; NVector_t<Float_t,3> *vector=static_cast<NVector_t<Float_t,3> *>(a_hit->getPosition());
Definition at line 12 of file NVector_t.hh.
Member Function Documentation
template<class T, int dimension> NVector_t& CALICE::NVector_t< T, dimension >::clear () inline
Set all elements to zero.
Todo:
: this only works for simple types like int, float, double.
Definition at line 45 of file NVector_t.hh.
template<class T, int dimension> Float_t* CALICE::NVector_t< T, dimension >::data () inline
get a pointer to the underlying array (read and write access).
Definition at line 139 of file NVector_t.hh.
Referenced by CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise().
template<class T, int dimension> const Float_t* CALICE::NVector_t< T, dimension >::data () const inline
get a pointer to the underlying array (read only access).
Todo:
float ? not T ?
Definition at line 142 of file NVector_t.hh.
template<class T, int dimension> NVector_t& CALICE::NVector_t< T, dimension >::operator*= (const float c) inline
Multiply this vector by a scalar.
Todo:
the argument should not be a float but T ?
Definition at line 125 of file NVector_t.hh.
template<class T, int dimension> NVector_t& CALICE::NVector_t< T, dimension >::operator+= (const NVector_t< T, dimension > & a) inline
Add a vector having the same dimension to this vector.
FIXME: The compiler should create an error message if vectors of different dimensions are added Does this happen ?
Definition at line 108 of file NVector_t.hh.
template<class T, int dimension> NVector_t& CALICE::NVector_t< T, dimension >::operator-= (const NVector_t< T, dimension > & a) inline
Subtract a vector having the same dimension to this vector.
FIXME: The compiler should create an error message if vectors of different dimensions are added Does this happen ?
Definition at line 117 of file NVector_t.hh.
template<class T, int dimension> NVector_t& CALICE::NVector_t< T, dimension >::operator/= (const float c) inline
Divide this vector by a scalar.
Todo:
the argument should not be a float but T ?
Definition at line 133 of file NVector_t.hh.
template<class T, int dimension> Float_t& CALICE::NVector_t< T, dimension >::operator[] (UInt_t index) inline
get the element of the given index (read and write access).
Parameters
index the index of the element (0 to dimension - 1).
Returns
reference to the element of the given index (read and write access). When the preprocessor variable BOUNDARY_CHECK is defined the validity of index is checked and an exception std::runtime_error is thrown in case of violations.
Definition at line 71 of file NVector_t.hh.
template<class T, int dimension> const Float_t& CALICE::NVector_t< T, dimension >::operator[] (UInt_t index) const inline
get the element of the given index (read access only).
Parameters
index the index of the element (0 to dimension - 1).
Returns
reference to the element of the given index (read access only). When the preprocessor variable BOUNDARY_CHECK is defined the validity of index is checked and an exception std::runtime_error is thrown in case of violations.
Definition at line 91 of file NVector_t.hh.
template<class T, int dimension> NVector_t& CALICE::NVector_t< T, dimension >::set (const T * array) inline
Set the elements of the vector from the given array.
It is assumed that the array contains the correct amount of elements (dimension of the vector). If the dimension of the given array is smaller than the dimension of this vector then the result will be undefined.
Definition at line 59 of file NVector_t.hh.
Referenced by CALICE::Box::minDistanceToPoints(), CALICE::Clusteriser::processEvent(), and CALICE::MipSelect::processEvent().
Friends And Related Function Documentation
template<class T, int dimension> template<class _T , int _dimension> NVector_t<_T,_dimension> operator* (const NVector_t< _T, _dimension > & a, float c) friend
Multiply a vector by a scalar.
Todo:
replace float by _T?
Definition at line 182 of file NVector_t.hh.
template<class T, int dimension> template<class _T , int _dimension> NVector_t<_T,_dimension> operator* (float c, const NVector_t< _T, _dimension > & a) friend
Multiply a vector by a scalar.
Todo:
replace float by _T?
Definition at line 171 of file NVector_t.hh.
template<class T, int dimension> template<class _T , int _dimension> NVector_t<_T,_dimension> operator/ (const NVector_t< _T, _dimension > & a, float c) friend
Divide a vector by a scalar.
Todo:
replace float by _T?
Definition at line 193 of file NVector_t.hh.
Field Documentation
template<class T, int dimension> Float_t CALICE::NVector_t< T, dimension >::_x[dimension] private
Todo:
float ? not T ?
Todo:
float ? not T ?
Definition at line 142 of file NVector_t.hh.
Referenced by CALICE::NVector_t< Float_t, 3 >::clear(), CALICE::NVector_t< Float_t, 3 >::data(), CALICE::NVector_t< Float_t, 3 >::operator*=(), CALICE::NVector_t< Float_t, 3 >::operator+=(), CALICE::NVector_t< Float_t, 3 >::operator-=(), CALICE::NVector_t< Float_t, 3 >::operator/=(), CALICE::NVector_t< Float_t, 3 >::operator[](), and CALICE::NVector_t< Float_t, 3 >::set().
The documentation for this class was generated from the following file:
NVector_t.hh