RAW2CALOHIT: CALICE::CellParameterAccess Class Reference
CALICE::CellParameterAccess Class Reference
Wrapper around the cell parameter collection to facilitate the access.
#include <CellParameterAccess.hh>
Public Member Functions
CellParameterAccess (const std::string &col_name, EVENT::LCEvent *evtP)
Create a simple wrapper to easily access the cell parameters from the LCCollection.
UInt_t getIndexOffset (UInt_t module_index) const
Get the index of the first cell of the given module.
UInt_t getIndex (UInt_t module_index, UInt_t cell_index) const
Get the cell index for the given module and cell index.
CellParameter getCellParameter (UInt_t module_index, UInt_t cell_index)
Get the cell parameters of the specified cell (read/write).
const CellParameter getCellParameter (UInt_t module_index, UInt_t cell_index) const
Get the cell parameters of the specified cell (read only).
CellParameter getCellParameter (UInt_t index)
Get the cell parameters of the specified cell (read/write).
const CellParameter getCellParameter (UInt_t index) const
Get the cell parameters of the specified cell (read only).
Private Attributes
LCCollection * _cellParameterCol
The collection of the cell parameters.
IntVec _indexOffset
copy of the array which contains the index offset of the modules.
Detailed Description
Wrapper around the cell parameter collection to facilitate the access.
Definition at line 17 of file CellParameterAccess.hh.
Constructor & Destructor Documentation
CALICE::CellParameterAccess::CellParameterAccess (const std::string & col_name, EVENT::LCEvent * evtP) inline
Create a simple wrapper to easily access the cell parameters from the LCCollection.
Exceptions
DataNotAvailableException if the cell paramter collection does not access.
Definition at line 23 of file CellParameterAccess.hh.
References _cellParameterCol, and _indexOffset.
Member Function Documentation
CellParameter CALICE::CellParameterAccess::getCellParameter (UInt_t module_index, UInt_t cell_index) inline
Get the cell parameters of the specified cell (read/write).
Parameters
module_index the index of the module (starting from zero).
cell_index the index of the cell on the specified module (starting from zero).
Returns
a reference of the cell parameters (read/write access).
Definition at line 75 of file CellParameterAccess.hh.
References _cellParameterCol, and getIndex().
Referenced by CALICE::PedestalNoiseHistograms::processEvent().
const CellParameter CALICE::CellParameterAccess::getCellParameter (UInt_t module_index, UInt_t cell_index) const inline
Get the cell parameters of the specified cell (read only).
Parameters
module_index the index of the module (starting from zero).
cell_index the index of the cell on the specified module (starting from zero).
Returns
a reference of the cell parameters (read only access).
Definition at line 87 of file CellParameterAccess.hh.
References _cellParameterCol, and getIndex().
CellParameter CALICE::CellParameterAccess::getCellParameter (UInt_t index) inline
Get the cell parameters of the specified cell (read/write).
Parameters
index the internal index of the cell (combination of module and cell index).
Returns
a reference of the cell parameters (read/write access). The internal index is composed of an offset, which depends on the module, to which the cell index is added.
Definition at line 106 of file CellParameterAccess.hh.
References _cellParameterCol.
const CellParameter CALICE::CellParameterAccess::getCellParameter (UInt_t index) const inline
Get the cell parameters of the specified cell (read only).
Parameters
index the internal index of the cell (combination of module and cell index).
Returns
a reference of the cell parameters (read only access). The internal index is composed of an offset, which depends on the module, to which the cell index is added.
Definition at line 125 of file CellParameterAccess.hh.
References _cellParameterCol.
UInt_t CALICE::CellParameterAccess::getIndex (UInt_t module_index, UInt_t cell_index) const inline
Get the cell index for the given module and cell index.
If the code was compiled with BOUNDARY_CHECK defined an exception is thrown if the module index or cell index is larger than the number of modules.or cells.
Definition at line 51 of file CellParameterAccess.hh.
References _cellParameterCol, _indexOffset, and getIndexOffset().
Referenced by getCellParameter().
UInt_t CALICE::CellParameterAccess::getIndexOffset (UInt_t module_index) const inline
Get the index of the first cell of the given module.
If the code was compiled with BOUNDARY_CHECK defined an exception is thrown if the module index is larger than the number of modules.
Definition at line 35 of file CellParameterAccess.hh.
References _indexOffset.
Referenced by getIndex().
Field Documentation
IntVec CALICE::CellParameterAccess::_indexOffset private
copy of the array which contains the index offset of the modules.
This is array is a prameter of the collection.
Definition at line 140 of file CellParameterAccess.hh.
Referenced by CellParameterAccess(), getIndex(), and getIndexOffset().
The documentation for this class was generated from the following file:
CellParameterAccess.hh