RAW2CALOHIT: CALICE::HoldScanAnalysis Class Reference
CALICE::HoldScanAnalysis Class Reference
Create Signal histograms per pad of all hits of all reconstructed clusters.
#include <HoldScanAnalysis.hh>
Public Member Functions
Processor * newProcessor ()
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (LCRunHeader *run)
Called for every run, e.g.
void processEvent (LCEvent *evtP)
Called for every event - the working horse.
void end ()
Protected Types
enum EHistType { kHistSignalPerHoldValue, kHistTotalSignalPerHoldValue, kNHist }
Protected Member Functions
void createHistograms ()
create and register histogram collections.
void feConfChanged (EVENT::LCCollection *col)
Handle changes of Fe configuration data.
void moduleTypeChanged (lcio::LCCollection *col)
void moduleLocationChanged (lcio::LCCollection *col)
void moduleConnectionChanged (lcio::LCCollection *col)
Protected Member Functions inherited from CALICE::VRawADCValueProcessor
VRawADCValueProcessor (const std::string &processor_name)
void init ()
virtual void stagePositionChanged (lcio::LCCollection *col)
void showCollectionParameters (LCCollection *colP)
void correctModuleDescriptionOrder (LCCollection *colP)
Protected Attributes
FloatVec _signalHistPar
binning of the per hold value histograms.
std::string _clusterColName
std::string _feConfColName
histmgr::Key_t _histGroupKey
Key for the histogram group.
int _nHistMax
Maximum number of hold values for which signal histograms can be created (parameter)
int _minNumberOfHits
Minimum number of hits of accepted clusters (parameter).
Float_t _minClusterSignal
Minimum signal of accepted clusters (parameter).
ConditionsChangeDelegator
< HoldScanAnalysis > _feConfChange
ModuleIndexReverseLookup _indexLookup
LCCollection * _nHitsHistogram
LCCollection * _clusterSignalHistogram
LCCollection * _holdValueContainer
histmgr::Key_t _histKey [kNHist]
UInt_t _nHist
std::map< int, UInt_t > _holdStartMap
std::vector< UInt_t > _histogramIndex
UInt_t _nClusters
UInt_t _nMissingHoldChanges
UInt_t _moduleIndexOutOfRange
UInt_t _nBeamOrCosmicsEvents
UInt_t _currentCommonHoldStart
Protected Attributes inherited from CALICE::VRawADCValueProcessor
MappingAndAlignment _mapping
std::string _adcColName
Name of the input collection (INPUT).
std::string _colNameModuleDescription
Name of the conditions data collection containing module descriptions.
std::string _colNameModuleLocation
Name of the conditions data collection containing module location.
std::string _colNameModuleConnection
Name of the conditions data collection containing module location.
std::string _colNameStageCollection
Name of the conditions data collection containing stage positions.
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleTypeChange
helper class to listen for changes of the module types (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleLocationChange
helper class to listen for changes of the location of modules (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleConnectionChange
helper class to listen for changes of the connection between modules and the DAQ front-ends (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _stagePositionChange
helper class to listen for changes of stage positions (conditions data)
unsigned int _wrongOrderTill
Detailed Description
Create Signal histograms per pad of all hits of all reconstructed clusters.
This class derives from VRawADCValueProcessor, since the information about the detector is needed to setup the signal histograms.
Definition at line 25 of file HoldScanAnalysis.hh.
Member Function Documentation
void CALICE::HoldScanAnalysis::createHistograms () protected
create and register histogram collections.
Definition at line 105 of file HoldScanAnalysis.cc.
References histmgr::HistMgr::createHistogramGroup(), and histmgr::HistMgr::createHistograms().
void CALICE::HoldScanAnalysis::init ()
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Definition at line 128 of file HoldScanAnalysis.cc.
References histmgr::HistMgr::createHistograms().
void CALICE::HoldScanAnalysis::processEvent (LCEvent * evtP)
Called for every event - the working horse.
Definition at line 161 of file HoldScanAnalysis.cc.
References histmgr::FloatHistogram1D::fill(), histmgr::HistMgr::getHistogramCollection(), and histmgr::HistogramCollection_t::histogram().
void CALICE::HoldScanAnalysis::processRunHeader (LCRunHeader * run) inline
Called for every run, e.g.
overwrite to initialize run dependent histograms.
Definition at line 43 of file HoldScanAnalysis.hh.
Field Documentation
histmgr::Key_t CALICE::HoldScanAnalysis::_histGroupKey protected
Key for the histogram group.
Definition at line 63 of file HoldScanAnalysis.hh.
Float_t CALICE::HoldScanAnalysis::_minClusterSignal protected
Minimum signal of accepted clusters (parameter).
Definition at line 68 of file HoldScanAnalysis.hh.
int CALICE::HoldScanAnalysis::_minNumberOfHits protected
Minimum number of hits of accepted clusters (parameter).
Definition at line 67 of file HoldScanAnalysis.hh.
FloatVec CALICE::HoldScanAnalysis::_signalHistPar protected
binning of the per hold value histograms.
Definition at line 56 of file HoldScanAnalysis.hh.
The documentation for this class was generated from the following files:
HoldScanAnalysis.hh
HoldScanAnalysis.cc