RAW2CALOHIT: HistPar Class Reference
HistPar Class Reference
Class to describe the binning of equidistant histograms.
#include <HistPar.hh>
Public Member Functions
HistPar ()
Default constructor.
HistPar (UInt_t n_bins, Float_t x_min, Float_t x_max)
Constructor.
HistPar & setNBins (UInt_t n_bins)
Set the number of bins.
HistPar & setXMin (Float_t x_min)
Set the lower edge of the first bin.
HistPar & setXMax (Float_t x_max)
set the upper edge of the last bin.
UInt_t nBins () const
The number of bins to be used.
Float_t xMin () const
The lower edge of the first bin.
Float_t xMax () const
The upper edge of the last bin.
Protected Attributes
UInt_t _nBins
Float_t _xMin
Float_t _xMax
Detailed Description
Class to describe the binning of equidistant histograms.
Definition at line 8 of file HistPar.hh.
Constructor & Destructor Documentation
HistPar::HistPar () inline
Default constructor.
The binning defined by the default constructor is invalid.
Definition at line 14 of file HistPar.hh.
HistPar::HistPar (UInt_t n_bins, Float_t x_min, Float_t x_max) inline
Constructor.
See Also
setNBins,setXMin,setXmax
Definition at line 19 of file HistPar.hh.
Member Function Documentation
UInt_t HistPar::nBins () const inline
The number of bins to be used.
This does not include overflow and underflow bins. Thus, generally two more bins will be used to store the overflow and the underflow.
Definition at line 41 of file HistPar.hh.
Referenced by histmgr::FloatHistogram1D::FloatHistogram1D(), histmgr::FloatHistogram2D::FloatHistogram2D(), histmgr::Profile1D::Profile1D(), and histmgr::Histogram1D::setBinning().
HistPar& HistPar::setNBins (UInt_t n_bins) inline
Set the number of bins.
This does not include overflow and underflow bins. Thus, generally two more bins will be used to store the overflow and the underflow.
Definition at line 25 of file HistPar.hh.
HistPar& HistPar::setXMax (Float_t x_max) inline
set the upper edge of the last bin.
Everything above this value will be directed to the overflow bin.
Definition at line 35 of file HistPar.hh.
HistPar& HistPar::setXMin (Float_t x_min) inline
Set the lower edge of the first bin.
Everything below this value will be directed to the underflow bin.
Definition at line 30 of file HistPar.hh.
Float_t HistPar::xMax () const inline
The upper edge of the last bin.
Everything above this value will be directed to the overflow bin.
Definition at line 51 of file HistPar.hh.
Referenced by histmgr::Histogram1D::setBinning().
Float_t HistPar::xMin () const inline
The lower edge of the first bin.
Everything below this value will be directed to the underflow bin.
Definition at line 46 of file HistPar.hh.
Referenced by histmgr::Histogram1D::setBinning().
The documentation for this class was generated from the following file:
HistPar.hh