RAW2CALOHIT: histmgr::Histogram2DCollection_t Class Reference
histmgr::Histogram2DCollection_t Class Reference
One or two dimensional collection of histograms.
#include <Histogram2DCollection_t.hh>
Public Member Functions
Histogram2DCollection_t (const std::string &collection_name, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &x_par, const HistPar &y_par) noexcept(false)
Create a collection of histograms which will have the same binning and the same name (except of a numeric extension).
Histogram2DCollection_t (const std::string &collection_name, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &x_par, const HistPar &y_par)
Create a collection of histograms which will have the same binning and the same name (except of a numeric extension).
Histogram2DCollection_t (lcio::LCCollection *histograms, lcio::IntVec *indices)
Histogram2DCollection_t (lcio::LCCollection *histograms)
Create a histogram collection from lcio collection.
Histogram2DCollection_t (const Histogram2DCollection_t &a)
copy constructor.
Histogram2DCollection_t ()
Default constructor.
void deleteCollection ()
delete the histogram collection and the index array This method exists instead of a destrctor to prevent copying the arrays (FIXME)
void deleteSharedStorage ()
lcio::LCCollection * createHistograms (const std::string &collection_name, const EVENT::StringVec &name_list, UInt_t n_hist, const HistPar &x_par, const HistPar &y_par) noexcept(false)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * createHistograms (const std::string &collection_name, const EVENT::StringVec &name_list, const lcio::IntVec &n_hist_list, const HistPar &x_par, const HistPar &y_par) noexcept(false)
create several histograms which will have the same binning and the same name (except of a numeric extension).
lcio::LCCollection * collection ()
get the unique group id
const lcio::LCCollection * collection () const
get the collection of histograms (read only).
UInt_t n () const
get the number of histograms in the one dimensional collection.
bool is2D () const
Return true if the histogram collection is two instead of one diemensional.
UInt_t nMajor () const
get the number of histograms in the one dimensional collection.
UInt_t nMinor (UInt_t major_index) const
get the number of histograms in the one dimensional collection.
const FloatHistogram2D * histogram (UInt_t index) const
Get one histogram of the collection (read only).
FloatHistogram2D * histogram (UInt_t index)
Get one histogram of the collection.
FloatHistogram2D * histogram (UInt_t major_index, UInt_t minor_index)
Get one histogram of the collection which is organised as a two dimensional array.
const FloatHistogram2D * histogram (UInt_t major_index, UInt_t minor_index) const
Get one histogram of the collection which is organised as a two dimensional array (read only).
const std::string & getName (UInt_t major_index) const
Get the name of the specified element of the histogram collection.
Public Member Functions inherited from reference_counter
int references () const
int isUsed () const
Static Protected Attributes
static const std::string __histogramNameParameterName
Private Member Functions
void copyNames () const
Copy the names from the collection to an accessible vector.
Private Attributes
lcio::LCCollection * _histogramCol
the histogram collection
lcio::IntVec * _majorIndex
optional list of offset to form a two dimensional array out of the list.
lcio::StringVec _nameList
A vector which contains one name for all histograms of the collection or a name for each element.
Static Private Attributes
static const std::string __majorIndexParameterName
static const std::string __defaultHistogramName
Friends
class HistMgr
Additional Inherited Members
Protected Member Functions inherited from reference_counter
int unref ()
reference_counter * ref ()
Detailed Description
One or two dimensional collection of histograms.
Definition at line 16 of file Histogram2DCollection_t.hh.
Constructor & Destructor Documentation
histmgr::Histogram2DCollection_t::Histogram2DCollection_t (const std::string & collection_name, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & x_par, const HistPar & y_par) inline noexcept
Create a collection of histograms which will have the same binning and the same name (except of a numeric extension).
Parameters
collection_name the name of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist the number of histograms to be created
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis of the histogram
The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 33 of file Histogram2DCollection_t.hh.
References createHistograms().
histmgr::Histogram2DCollection_t::Histogram2DCollection_t (const std::string & collection_name, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & x_par, const HistPar & y_par) inline
Create a collection of histograms which will have the same binning and the same name (except of a numeric extension).
Parameters
collection_name the of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist_list the number of histograms to be created
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis of the histogram
Returns
pointer to the histogram collection
The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 60 of file Histogram2DCollection_t.hh.
References createHistograms().
histmgr::Histogram2DCollection_t::Histogram2DCollection_t (lcio::LCCollection * histograms, lcio::IntVec * indices) inline
Parameters
histograms the linearised one or two dimensional collection of histograms
indices optional list of indicies used to give two dimensional access to the histogram list. for each possible index of the first dimension is needed which contains the offset in the list. The second index is added to this offset.
Definition at line 78 of file Histogram2DCollection_t.hh.
References _majorIndex.
histmgr::Histogram2DCollection_t::Histogram2DCollection_t (lcio::LCCollection * histograms) inline
Create a histogram collection from lcio collection.
Parameters
histograms the linearised one or two dimensional collection of histograms (two dimensional collections have the collection parameter "major"). The method does not verify whether the lcio collection really is a histogram collection. However, if the collection has the parameter "major" it creates an index vector (costly operation) assuming that it is a 2d array instead of a 1d array(i.e. collection). The unique group id remains undedfined since it is not stored in the lcio collection.
Definition at line 105 of file Histogram2DCollection_t.hh.
References _majorIndex.
Member Function Documentation
lcio::LCCollection* histmgr::Histogram2DCollection_t::collection () inline
get the unique group id
get the collection of histograms. The index array needed for the two dimensional acces is added as a parameter named "major".
Definition at line 209 of file Histogram2DCollection_t.hh.
References _histogramCol.
const lcio::LCCollection* histmgr::Histogram2DCollection_t::collection () const inline
get the collection of histograms (read only).
The index array needed for the two dimensional acces is added as a parameter named "major".
Definition at line 214 of file Histogram2DCollection_t.hh.
References _histogramCol.
void histmgr::Histogram2DCollection_t::copyNames () const inline private
Copy the names from the collection to an accessible vector.
The vector of histogram names is attached as a parameter to the LCCollection.
Definition at line 362 of file Histogram2DCollection_t.hh.
References _histogramCol, and _nameList.
Referenced by getName().
lcio::LCCollection * histmgr::Histogram2DCollection_t::createHistograms (const std::string & collection_name, const EVENT::StringVec & name_list, UInt_t n_hist, const HistPar & x_par, const HistPar & y_par) noexcept
create several histograms which will have the same binning and the same name (except of a numeric extension).
Parameters
collection_name the of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist the number of histograms to be created
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis of the histogram
Returns
pointer to the histogram collection.
The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 16 of file Histogram2DCollection_t.cc.
Referenced by Histogram2DCollection_t().
lcio::LCCollection * histmgr::Histogram2DCollection_t::createHistograms (const std::string & collection_name, const EVENT::StringVec & name_list, const lcio::IntVec & n_hist_list, const HistPar & x_par, const HistPar & y_par) noexcept
create several histograms which will have the same binning and the same name (except of a numeric extension).
Parameters
collection_name the of the histogram collection
name_list a vector containing the names of the histograms whose length is either equals n_hist or is zero. In the latter case the collection name is used for the all histograms.
n_hist_list the number of histograms to be created
x_par the binning of the x-axis of the histogram
y_par the binning of the y-axis of the histogram
Returns
pointer to the histogram collection
The histograms are only written to a file if the histogram group, to which this histogram belongs, is assigned to a file (histmgr::HistMgr::assignFileName).
Definition at line 70 of file Histogram2DCollection_t.cc.
const std::string& histmgr::Histogram2DCollection_t::getName (UInt_t major_index) const inline
Get the name of the specified element of the histogram collection.
Parameters
major_index the index of the histogram element or in case of an 2D histogram array the major index.
Returns
a reference to the name.
Definition at line 332 of file Histogram2DCollection_t.hh.
References _nameList, and copyNames().
Field Documentation
lcio::IntVec* histmgr::Histogram2DCollection_t::_majorIndex private
optional list of offset to form a two dimensional array out of the list.
Definition at line 373 of file Histogram2DCollection_t.hh.
Referenced by deleteCollection(), histogram(), Histogram2DCollection_t(), is2D(), nMajor(), and nMinor().
lcio::StringVec histmgr::Histogram2DCollection_t::_nameList mutable private
A vector which contains one name for all histograms of the collection or a name for each element.
Definition at line 375 of file Histogram2DCollection_t.hh.
Referenced by copyNames(), and getName().
The documentation for this class was generated from the following files:
Histogram2DCollection_t.hh
Histogram2DCollection_t.cc