RAW2CALOHIT: CALICE::PedestalNoiseHistograms Class Reference
CALICE::PedestalNoiseHistograms Class Reference
Public Member Functions
Processor * newProcessor ()
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (LCRunHeader *run)
Called for every run, e.g.
void processEvent (LCEvent *evtP)
Called for every event - the working horse.
void end ()
Protected Types
enum EH1Type { kH1Noise, kH1Pedestal, kNH1 }
Protected Member Functions
void moduleTypeChanged (lcio::LCCollection *col)
void moduleLocationChanged (lcio::LCCollection *col)
void moduleConnectionChanged (lcio::LCCollection *col)
void detectorChanged ()
void createHistograms ()
Protected Member Functions inherited from CALICE::VRawADCValueProcessor
VRawADCValueProcessor (const std::string &processor_name)
void init ()
virtual void stagePositionChanged (lcio::LCCollection *col)
void showCollectionParameters (LCCollection *colP)
void correctModuleDescriptionOrder (LCCollection *colP)
Protected Attributes
std::string _cellParameterCollectionName
IntVec _eventPar
histmgr::Key_t _histogramGroupKey
lcio::FloatVec _noiseHistPar
lcio::FloatVec _adcHistPar
histmgr::Key_t _histKey [kNH1]
UInt_t _missingCellParameters
Protected Attributes inherited from CALICE::VRawADCValueProcessor
MappingAndAlignment _mapping
std::string _adcColName
Name of the input collection (INPUT).
std::string _colNameModuleDescription
Name of the conditions data collection containing module descriptions.
std::string _colNameModuleLocation
Name of the conditions data collection containing module location.
std::string _colNameModuleConnection
Name of the conditions data collection containing module location.
std::string _colNameStageCollection
Name of the conditions data collection containing stage positions.
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleTypeChange
helper class to listen for changes of the module types (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleLocationChange
helper class to listen for changes of the location of modules (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleConnectionChange
helper class to listen for changes of the connection between modules and the DAQ front-ends (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _stagePositionChange
helper class to listen for changes of stage positions (conditions data)
unsigned int _wrongOrderTill
Detailed Description
Definition at line 14 of file PedestalNoiseHistograms.hh.
Member Function Documentation
void CALICE::PedestalNoiseHistograms::init ()
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Definition at line 76 of file PedestalNoiseHistograms.cc.
References histmgr::HistMgr::createHistogramGroup().
void CALICE::PedestalNoiseHistograms::processEvent (LCEvent * evtP)
Called for every event - the working horse.
Definition at line 89 of file PedestalNoiseHistograms.cc.
References histmgr::FloatHistogram1D::fill(), CALICE::CellParameterAccess::getCellParameter(), histmgr::HistMgr::getHistogramCollection(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), and histmgr::HistogramCollection_t::histogram().
void CALICE::PedestalNoiseHistograms::processRunHeader (LCRunHeader * run) inline
Called for every run, e.g.
overwrite to initialize run dependent histograms.
Definition at line 31 of file PedestalNoiseHistograms.hh.
The documentation for this class was generated from the following files:
PedestalNoiseHistograms.hh
PedestalNoiseHistograms.cc