RAW2CALOHIT: histmgr::FloatHistogram2D Class Reference
histmgr::FloatHistogram2D Class Reference
A 1-dimensional histogram using float values for the bins.
#include <FloatHistogram2D.hh>
Public Member Functions
FloatHistogram2D (UInt_t id, const HistPar &binning_x, const HistPar &binning_y)
Create a histogram with a certain binning.
FloatHistogram2D (lcio::LCObject *a_obj)
FloatHistogram2D (const FloatHistogram2D &a)
void fill (Float_t value_x, Float_t value_y, Float_t weight=1.)
fill a value into the histogram
void reset ()
reset the histograms and the number of entries
UInt_t binIndex (UInt_t binx_i, UInt_t biny_i) const
Get the 1d bin index.
void addToBinContent (UInt_t bin_index, Float_t value)
manipulate a histogram bin
void setBinContent (UInt_t bin_index, Float_t value)
manipulate a histogram bin
Float_t binContent (UInt_t bin_index) const
Float_t xOverflow (UInt_t biny_i) const
Float_t xUnderflow (UInt_t biny_i) const
Float_t yOverflow (UInt_t binx_i) const
Float_t yUnderflow (UInt_t binx_i) const
Float_t xUnderflow () const
Float_t xOverflow () const
Float_t yUnderflow () const
Float_t yOverflow () const
Float_t xMean () const
Float_t xRms (bool natural=false) const
Root mean square as defined by ROOT.
Float_t xVariance () const
Variance.
Float_t yMean () const
Float_t yRms (bool natural=false) const
Root mean square as defined by ROOT.
Float_t yVariance () const
Variance.
Double_t integral (UInt_t x0_i, UInt_t x1_i, UInt_t y0_i, UInt_t y1_i) const
sum contents of bins within the given range
lcio::LCObject * clone () const
Public Member Functions inherited from histmgr::Histogram2D
virtual int id () const
Return the id of the underlying LCGenericObjectImpl.
UInt_t xFirstBinIndex () const
UInt_t xLastBinIndex () const
UInt_t yFirstBinIndex () const
UInt_t yLastBinIndex () const
UInt_t xUnderflowBinIndex () const
UInt_t xOverflowBinIndex () const
UInt_t yUnderflowBinIndex () const
UInt_t yOverflowBinIndex () const
UInt_t xNBins () const
Float_t xMin () const
Float_t xMax () const
UInt_t yNBins () const
Float_t yMin () const
Float_t yMax () const
Float_t xBinCenter (UInt_t bin_index)
Float_t xBinLowEdge (UInt_t bin_index)
Float_t xBinWidth (UInt_t)
Float_t yBinCenter (UInt_t bin_index)
Float_t yBinLowEdge (UInt_t bin_index)
Float_t yBinWidth (UInt_t)
UInt_t calice_id ()
Double_t entries () const
void addToEntries (Double_t weight)
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
const std::string getTypeName () const
const std::string getDataDescription () const
Private Member Functions
UInt_t nXBinsTotal () const
UInt_t nBinsTotal () const
Additional Inherited Members
Protected Member Functions inherited from histmgr::Histogram2D
Histogram2D (lcio::LCObject *a_obj)
void setBinning (const HistPar &x_bins, const HistPar &y_bins)
void setXtoBins ()
void setYtoBins ()
UInt_t xBinIndex (Float_t value) const
UInt_t yBinIndex (Float_t value) const
UInt_t getContainerSize () const
lcio::LCGenericObjectImpl * obj ()
const lcio::LCGenericObjectImpl * obj () const
Protected Attributes inherited from histmgr::Histogram2D
lcio::LCGenericObjectImpl * _obj
bool _createdObject
Double_t _xToBin
Double_t _yToBin
Static Protected Attributes inherited from histmgr::Histogram2D
static const std::string __typeName ="Histogram2D"
static const std::string __description ="Histogram2D"
Detailed Description
A 1-dimensional histogram using float values for the bins.
Definition at line 12 of file FloatHistogram2D.hh.
Constructor & Destructor Documentation
histmgr::FloatHistogram2D::FloatHistogram2D (UInt_t id, const HistPar & binning_x, const HistPar & binning_y)
Create a histogram with a certain binning.
Parameters
id a unique histogram ID,
binning_x number of bins and range of the axis
binning_y number of bins and range of the axis
Todo:
a name would be better than an ID but a string can not be easily stored in an LCGenericObject
Definition at line 8 of file FloatHistogram2D.cc.
References HistPar::nBins(), and reset().
Member Function Documentation
Double_t histmgr::FloatHistogram2D::integral (UInt_t x0_i, UInt_t x1_i, UInt_t y0_i, UInt_t y1_i) const
sum contents of bins within the given range
Parameters
x0_i index of the first bin along x
x1_i index of the last bin (included in the sum) along x
y0_i index of the first bin along y
y1_i index of the last bin (included in the sum) along y
Returns
the sum of the bins
Definition at line 143 of file FloatHistogram2D.cc.
Float_t histmgr::FloatHistogram2D::xRms (bool natural = false) const
Root mean square as defined by ROOT.
divided by n
Definition at line 65 of file FloatHistogram2D.cc.
References binIndex().
Float_t histmgr::FloatHistogram2D::xVariance () const
Variance.
divided by n-1
Float_t histmgr::FloatHistogram2D::yRms (bool natural = false) const
Root mean square as defined by ROOT.
divided by n
Definition at line 115 of file FloatHistogram2D.cc.
References binIndex().
Float_t histmgr::FloatHistogram2D::yVariance () const
Variance.
divided by n-1
The documentation for this class was generated from the following files:
FloatHistogram2D.hh
FloatHistogram2D.cc