RAW2CALOHIT: histmgr::Profile1D Class Reference
histmgr::Profile1D Class Reference
A 1-dimensional histogram using float values for the bins.
#include <Profile1D.hh>
Public Member Functions
Profile1D (UInt_t id, const HistPar &binning)
Create a histogram with a certain binning.
Profile1D (lcio::LCObject *a_obj)
Profile1D (const Profile1D &a)
void fill (Float_t x_value, Double_t value, Double_t weight=1.)
fill a value into the histogram
void reset ()
reset the histograms and the number of entries
Double_t sum (UInt_t bin_index) const
manipulate a histogram bin
Double_t sum2 (UInt_t bin_index) const
Double_t mean (UInt_t bin_index) const
Double_t sigma (UInt_t bin_index) const
Return the rms of the bin.
Double_t rms (UInt_t bin_index) const
Double_t min (UInt_t bin_index) const
Double_t max (UInt_t bin_index) const
Double_t sumOfWeights (UInt_t bin_index) const
void calculate ()
Float_t mean () const
Float_t rms () const
Root mean square as defined by ROOT.
Float_t variance () const
Variance.
lcio::LCObject * clone () const
Public Member Functions inherited from histmgr::Histogram1D
virtual int id () const
Return the id of the underlying LCGenericObjectImpl.
UInt_t firstBinIndex () const
Return the index of the first bin not below the minimum axis value.
UInt_t lastBinIndex () const
Return the index of the last bin not above the maximum axis value.
UInt_t underflowBinIndex () const
Return the index of the bin below the minimum axis value (underflow bin).
UInt_t overflowBinIndex () const
Return the index of the bin above the maximum axis value (overflow bin).
UInt_t nBins () const
Return the number of bins.
Float_t xMin () const
The minimum axis value (lower edge of the histogram range).
Float_t xMax () const
The maximum axis value (upper edge of the histogram range).
Float_t binCenter (UInt_t bin_index) const
Return the axis value of the centre of the given bin.
Float_t binLowEdge (UInt_t bin_index) const
Float_t binWidth (UInt_t) const
Return the width of the given bin.
UInt_t calice_id ()
Return the id of the histogram.
Double_t entries () const
Return the number of entries of the histogram.
Protected Types
enum EBinType {
kSum, kSum2, kMin, kMax,
kWeightSum, kNBinTypes
}
Protected Member Functions
void addToBinContent (UInt_t type_i, UInt_t bin_index, Double_t value)
void setBinContent (UInt_t type_i, UInt_t bin_index, Double_t value)
Double_t binContent (UInt_t type_i, UInt_t bin_index) const
bool isCalculated (UInt_t bin_index) const
UInt_t getValueIndex (UInt_t type_i, UInt_t bin_index) const
Protected Member Functions inherited from histmgr::Histogram1D
Histogram1D (lcio::LCObject *a_obj)
void addToEntries (Double_t weight)
Add weight to the number of entries.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
const std::string getTypeName () const
const std::string getDataDescription () const
void setBinning (const HistPar &bins)
Store the binning of the histogram.
UInt_t binIndex (Float_t value) const
Calculate and return the bin index for the given axis value.
lcio::LCGenericObjectImpl * obj ()
const lcio::LCGenericObjectImpl * obj () const
Additional Inherited Members
Protected Attributes inherited from histmgr::Histogram1D
lcio::LCGenericObjectImpl * _obj
bool _createdObject
Static Protected Attributes inherited from histmgr::Histogram1D
static const std::string __typeName ="Histogram1D"
static const std::string __description ="Histogram1D"
Detailed Description
A 1-dimensional histogram using float values for the bins.
Definition at line 13 of file Profile1D.hh.
Constructor & Destructor Documentation
histmgr::Profile1D::Profile1D (UInt_t id, const HistPar & binning)
Create a histogram with a certain binning.
Parameters
id a unique histogram ID,
binning number of bins and range of the axis
Todo:
a name would be better than an ID but a string can not be easily stored in an LCGenericObject
Definition at line 8 of file Profile1D.cc.
References HistPar::nBins(), reset(), and histmgr::Histogram1D::setBinning().
Member Function Documentation
Float_t histmgr::Profile1D::rms () const
Root mean square as defined by ROOT.
divided by n
Definition at line 63 of file Profile1D.cc.
References histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), sum(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
Referenced by sigma().
Double_t histmgr::Profile1D::sigma (UInt_t bin_index) const inline
Return the rms of the bin.
deprecated.
Definition at line 81 of file Profile1D.hh.
References rms().
Double_t histmgr::Profile1D::sum (UInt_t bin_index) const inline
manipulate a histogram bin
manipulate a histogram bin
Definition at line 201 of file Profile1D.hh.
Referenced by rms(), and variance().
Float_t histmgr::Profile1D::variance () const
Variance.
divided by n-1
Definition at line 94 of file Profile1D.cc.
References histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), sum(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
The documentation for this class was generated from the following files:
Profile1D.hh
Profile1D.cc