RAW2CALOHIT: CALICE::TriggerAnalysis Class Reference
CALICE::TriggerAnalysis Class Reference
Search for good trigger words.
#include <TriggerAnalysis.hh>
Public Member Functions
Processor * newProcessor ()
void init ()
Set up conditions data handler, verify parameters et.c.
void processEvent (LCEvent *evtP)
Called for every run (does nothing.)
void end ()
Private Attributes
std::string _parNameTriggerMainWord
Par.
unsigned int _nEvents
unsigned int _missingTriggerEventData
histmgr::Key_t _histGroupKey
Key for the histogram group.
histmgr::Key_t _histTriggerOnPosisitonKey
Key for the trigger on position histograms.
histmgr::Key_t _histTriggerLengthKey
Key for the trigger pulse length histograms.
Detailed Description
Search for good trigger words.
Definition at line 22 of file TriggerAnalysis.hh.
Member Function Documentation
void CALICE::TriggerAnalysis::processEvent (LCEvent * evtP)
Called for every run (does nothing.)
Search good trigger words. If no good trigger word is found a damaged flag is set in the event header.
Definition at line 135 of file TriggerAnalysis.cc.
References histmgr::FloatHistogram1D::fill(), histmgr::HistMgr::getHistogramCollection(), and histmgr::HistogramCollection_t::histogram().
Field Documentation
histmgr::Key_t CALICE::TriggerAnalysis::_histGroupKey private
Key for the histogram group.
Definition at line 58 of file TriggerAnalysis.hh.
histmgr::Key_t CALICE::TriggerAnalysis::_histTriggerLengthKey private
Key for the trigger pulse length histograms.
Definition at line 60 of file TriggerAnalysis.hh.
histmgr::Key_t CALICE::TriggerAnalysis::_histTriggerOnPosisitonKey private
Key for the trigger on position histograms.
Definition at line 59 of file TriggerAnalysis.hh.
std::string CALICE::TriggerAnalysis::_parNameTriggerMainWord private
Par.
name of the trigger main word.
Definition at line 53 of file TriggerAnalysis.hh.
The documentation for this class was generated from the following files:
TriggerAnalysis.hh
TriggerAnalysis.cc