RAW2CALOHIT: CALICE::AverageHistoryGraphs Class Reference
CALICE::AverageHistoryGraphs Class Reference
Public Member Functions
Processor * newProcessor ()
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (LCRunHeader *run)
Called for every run, e.g.
void processEvent (LCEvent *evtP)
Called for every event - the working horse.
void end ()
Protected Types
enum EGraphType {
kGraphMean, kGraphRMS, kGraphMin, kGraphMax,
kGraphWeight, kNGraphTypes
}
enum EHistoryType {
kADCHistory, kNoiseHistory, kPedestalHistory, kHitHistory,
kNHistoryGraphs
}
enum EStampType {
kHistoryStamp, kHistoryConfStamp, kHistoryStateStamp, kHistoryStateValue,
kNHistoryStamps
}
Protected Member Functions
void configurationChanged (EVENT::LCCollection *)
void moduleTypeChanged (lcio::LCCollection *col)
void moduleLocationChanged (lcio::LCCollection *col)
void moduleConnectionChanged (lcio::LCCollection *col)
void resizeArrays ()
Protected Member Functions inherited from CALICE::VRawADCValueProcessor
VRawADCValueProcessor (const std::string &processor_name)
void init ()
virtual void stagePositionChanged (lcio::LCCollection *col)
void showCollectionParameters (LCCollection *colP)
void correctModuleDescriptionOrder (LCCollection *colP)
Protected Attributes
Int_t _useTimeStamp
IntVec _eventPar
Int_t _avADCNMax
Float_t _signalCut
Int_t _skipCalibrationEventsAlways
std::string _cellParameterCollectionName
std::vector< std::vector
< Average_t > > _avValues [kNHistoryGraphs]
bool _avADCIsValid
UInt_t _avADCn
std::vector< std::vector
< Average_t > > _avADC
std::vector< std::vector
< UInt_t > > _nHits
StringVec _monitorConf
vector
< ConditionsChangeDelegator
< AverageHistoryGraphs > > _confChanges
bool _confChanged
UInt_t _nConfigurationChanges
Int_t _wasState
UInt_t _nStateChanges
histmgr::Key_t _graphGroupKey
std::vector< histmgr::Key_t > _avValueHistoryKey
histmgr::Key_t _stateChangeHistoryKey
histmgr::Key_t _confChangeHistoryKey
Protected Attributes inherited from CALICE::VRawADCValueProcessor
MappingAndAlignment _mapping
std::string _adcColName
Name of the input collection (INPUT).
std::string _colNameModuleDescription
Name of the conditions data collection containing module descriptions.
std::string _colNameModuleLocation
Name of the conditions data collection containing module location.
std::string _colNameModuleConnection
Name of the conditions data collection containing module location.
std::string _colNameStageCollection
Name of the conditions data collection containing stage positions.
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleTypeChange
helper class to listen for changes of the module types (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleLocationChange
helper class to listen for changes of the location of modules (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleConnectionChange
helper class to listen for changes of the connection between modules and the DAQ front-ends (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _stagePositionChange
helper class to listen for changes of stage positions (conditions data)
unsigned int _wrongOrderTill
Static Protected Attributes
static const char * __graphTypeNames [kNGraphTypes]
static const char * __historyGraphNames [kNHistoryGraphs]
static UInt_t __nSamplesPerChip =18
static UInt_t __nChips =12
Detailed Description
Definition at line 17 of file AverageHistoryGraphs.hh.
Member Function Documentation
void CALICE::AverageHistoryGraphs::init ()
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Definition at line 121 of file AverageHistoryGraphs.cc.
References histmgr::HistMgr::createGraphCollection(), histmgr::HistMgr::createHistogramGroup(), and histmgr::HistMgr::lockGroup().
void CALICE::AverageHistoryGraphs::processEvent (LCEvent * evtP)
Called for every event - the working horse.
Definition at line 251 of file AverageHistoryGraphs.cc.
References CALICE::VRawADCValueProcessor::_adcColName, histmgr::GraphCollection_t::appendXValue(), histmgr::HistMgr::getGraphCollection(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), and histmgr::GraphCollection_t::setYValue().
void CALICE::AverageHistoryGraphs::processRunHeader (LCRunHeader * run) inline
Called for every run, e.g.
overwrite to initialize run dependent histograms.
Definition at line 34 of file AverageHistoryGraphs.hh.
Field Documentation
const char * CALICE::AverageHistoryGraphs::__graphTypeNames static protected
Initial value:
={
    "mean",
    "rms",
    "min",
    "max",
    "weight"
  }
Definition at line 61 of file AverageHistoryGraphs.hh.
const char * CALICE::AverageHistoryGraphs::__historyGraphNames static protected
Initial value:
={
    "ADCHistory",
    "NoiseHistory",
    "PedestalHistory",
    "HitHistory"
  }
Definition at line 62 of file AverageHistoryGraphs.hh.
The documentation for this class was generated from the following files:
AverageHistoryGraphs.hh
AverageHistoryGraphs.cc