RAW2CALOHIT: histmgr::FloatHistogram1D Class Reference
histmgr::FloatHistogram1D Class Reference
A 1-dimensional histogram using float values for the bins.
#include <FloatHistogram1D.hh>
Public Member Functions
FloatHistogram1D (UInt_t id, const HistPar &binning)
Create a histogram with a certain binning.
FloatHistogram1D (lcio::LCObject *a_obj)
FloatHistogram1D (const FloatHistogram1D &a)
void fill (Float_t value, Float_t weight=1.)
fill a value into the histogram
void reset ()
reset the histograms and the number of entries
void addToBinContent (UInt_t bin_index, Float_t value)
manipulate a histogram bin
void setBinContent (UInt_t bin_index, Float_t value)
manipulate a histogram bin
Float_t binContent (UInt_t bin_index) const
Float_t overflow () const
Float_t underflow () const
Float_t mean () const
Float_t rms () const
Root mean square as defined by ROOT.
Float_t variance () const
Variance.
Double_t integral (UInt_t first_bin, UInt_t last_bin) const
sum contentes of bins within the given range
lcio::LCObject * clone () const
Public Member Functions inherited from histmgr::Histogram1D
virtual int id () const
Return the id of the underlying LCGenericObjectImpl.
UInt_t firstBinIndex () const
Return the index of the first bin not below the minimum axis value.
UInt_t lastBinIndex () const
Return the index of the last bin not above the maximum axis value.
UInt_t underflowBinIndex () const
Return the index of the bin below the minimum axis value (underflow bin).
UInt_t overflowBinIndex () const
Return the index of the bin above the maximum axis value (overflow bin).
UInt_t nBins () const
Return the number of bins.
Float_t xMin () const
The minimum axis value (lower edge of the histogram range).
Float_t xMax () const
The maximum axis value (upper edge of the histogram range).
Float_t binCenter (UInt_t bin_index) const
Return the axis value of the centre of the given bin.
Float_t binLowEdge (UInt_t bin_index) const
Float_t binWidth (UInt_t) const
Return the width of the given bin.
UInt_t calice_id ()
Return the id of the histogram.
Double_t entries () const
Return the number of entries of the histogram.
Additional Inherited Members
Protected Member Functions inherited from histmgr::Histogram1D
Histogram1D (lcio::LCObject *a_obj)
void addToEntries (Double_t weight)
Add weight to the number of entries.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
const std::string getTypeName () const
const std::string getDataDescription () const
void setBinning (const HistPar &bins)
Store the binning of the histogram.
UInt_t binIndex (Float_t value) const
Calculate and return the bin index for the given axis value.
lcio::LCGenericObjectImpl * obj ()
const lcio::LCGenericObjectImpl * obj () const
Protected Attributes inherited from histmgr::Histogram1D
lcio::LCGenericObjectImpl * _obj
bool _createdObject
Static Protected Attributes inherited from histmgr::Histogram1D
static const std::string __typeName ="Histogram1D"
static const std::string __description ="Histogram1D"
Detailed Description
A 1-dimensional histogram using float values for the bins.
Definition at line 12 of file FloatHistogram1D.hh.
Constructor & Destructor Documentation
histmgr::FloatHistogram1D::FloatHistogram1D (UInt_t id, const HistPar & binning)
Create a histogram with a certain binning.
Parameters
id a unique histogram ID,
binning number of bins and range of the axis
Todo:
a name would be better than an ID but a string can not be easily stored in an LCGenericObject
Definition at line 8 of file FloatHistogram1D.cc.
References HistPar::nBins(), reset(), and histmgr::Histogram1D::setBinning().
Member Function Documentation
Double_t histmgr::FloatHistogram1D::integral (UInt_t first_bin, UInt_t last_bin) const
sum contentes of bins within the given range
Parameters
first_bin index of the first bin
last_bin index of the last bin (included in the sum)
Returns
the sum of the bins
Definition at line 109 of file FloatHistogram1D.cc.
Float_t histmgr::FloatHistogram1D::rms () const
Root mean square as defined by ROOT.
divided by n
Definition at line 61 of file FloatHistogram1D.cc.
References histmgr::Histogram1D::entries(), histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
Float_t histmgr::FloatHistogram1D::variance () const
Variance.
divided by n-1
Definition at line 85 of file FloatHistogram1D.cc.
References histmgr::Histogram1D::entries(), histmgr::Histogram1D::firstBinIndex(), histmgr::Histogram1D::lastBinIndex(), histmgr::Histogram1D::nBins(), histmgr::Histogram1D::xMax(), and histmgr::Histogram1D::xMin().
The documentation for this class was generated from the following files:
FloatHistogram1D.hh
FloatHistogram1D.cc