RAW2CALOHIT: histmgr::HistMgr::Group_t Class Reference
histmgr::HistMgr::Group_t Class Reference
Public Member Functions
void deleteSharedStorage ()
Called by the destructor of KeyMap_t .
HistogramGroupData_t & header ()
Get the histogram/graph group header.
const HistogramGroupData_t & header () const
Get the histogram/graph group header.
bool hasHistogramCollections () const
Return true if the Histogram group contains collections of histograms.
void setHistogramCollection (const Key_t &a_key, HistogramCollection_t *ref)
Install the histogram collection and assign the key.
bool histogramCollectionExists (const Key_t &a_key) const
Verify whether a histogram collection exists.
HistogramCollection_t & histogramCollection (const Key_t &a_key)
Get the histogram collection addressed by the key.
const HistogramCollection_t & histogramCollection (const Key_t &a_key) const
Get the histogram collection addressed by the key (read only).
bool hasHistogram2DCollections () const
Return true if the Histogram group contains collections of 2D histograms.
void setHistogram2DCollection (const Key_t &a_key, Histogram2DCollection_t *ref)
Install the histogram collection and assign the key.
bool histogram2DCollectionExists (const Key_t &a_key) const
Verify whether a histogram collection exists.
Histogram2DCollection_t & histogram2DCollection (const Key_t &a_key)
Get the histogram collection addressed by the key.
const Histogram2DCollection_t & histogram2DCollection (const Key_t &a_key) const
Get the histogram collection addressed by the key (read only).
bool hasProfileCollections () const
Return true if the Histogram group contains collections of profile histograms.
void setProfileCollection (const Key_t &a_key, ProfileCollection_t *ref)
Install the histogram collection and assign the key.
bool profileCollectionExists (const Key_t &a_key) const
Verify whether a histogram collection exists.
ProfileCollection_t & profileCollection (const Key_t &a_key)
Get the histogram collection addressed by the key.
const ProfileCollection_t & profileCollection (const Key_t &a_key) const
Get the histogram collection addressed by the key (read only).
bool hasGraphCollections () const
Return true if the Histogram group contains collections of graphs.
void setGraphCollection (const Key_t &a_key, GraphCollection_t *ref)
Install the histogram collection and assign the key.
bool graphCollectionExists (const Key_t &a_key) const
Verify whether a histogram collection exists.
GraphCollection_t & graphCollection (const Key_t &a_key)
Get the graph collection addressed by the key.
const GraphCollection_t & graphCollection (const Key_t &a_key) const
Get the graph collection addressed by the key (read only).
bool hasCollection (ECollectionType type) const
Return true if the collection contains still elements.
std::pair
< KeyMapBase_t::NameMap_t::const_iterator,
KeyMapBase_t::NameMap_t::const_iterator > nameListIterators (ECollectionType type) const
Get the begin and end iterators of the name list.
Protected Member Functions
const KeyMapBase_t * getNameListConst (ECollectionType &type) const
const KeyMapBase_t * getNameList (ECollectionType &type) const
KeyMapBase_t * getNameList (ECollectionType &type)
Protected Attributes
HistogramGroupData_t _header
KeyMap_t< accounting_ptr
< HistogramCollection_t > > _histogramList
KeyMap_t< accounting_ptr
< Histogram2DCollection_t > > _histogram2DList
KeyMap_t< accounting_ptr
< ProfileCollection_t > > _profileList
KeyMap_t< accounting_ptr
< GraphCollection_t > > _graphList
Friends
class HistMgr
Detailed Description
Definition at line 99 of file HistMgr.hh.
Member Function Documentation
HistogramGroupData_t& histmgr::HistMgr::Group_t::header () inline
Get the histogram/graph group header.
The header contains the assignment to files and folders.
Definition at line 110 of file HistMgr.hh.
Referenced by histmgr::HistMgr::assignFileName(), and histmgr::HistMgr::writeHistograms().
const HistogramGroupData_t& histmgr::HistMgr::Group_t::header () const inline
Get the histogram/graph group header.
(read only). The header contains the assignment to files and folders.
Definition at line 115 of file HistMgr.hh.
std::pair<KeyMapBase_t::NameMap_t::const_iterator, KeyMapBase_t::NameMap_t::const_iterator> histmgr::HistMgr::Group_t::nameListIterators (ECollectionType type) const inline
Get the begin and end iterators of the name list.
This can be used to generate a name list of all the elements.
Definition at line 218 of file HistMgr.hh.
Referenced by histmgr::HistMgr::fillHistogramCollectionList().
The documentation for this class was generated from the following file:
HistMgr.hh