RAW2CALOHIT: CALICE::SimpleHitSearch Class Reference
CALICE::SimpleHitSearch Class Reference
Marlin Processor to search and reconstruct colorimeter hits.
#include <SimpleHitSearch.hh>
Public Member Functions
Processor * newProcessor ()
construct a new Processor (required by Marlin.
SimpleHitSearch ()
default constructor.
~SimpleHitSearch ()
destructor.
void init ()
Called at the begin of the job before anything is read.
void processRunHeader (LCRunHeader *run)
Called for every run (does nothing.)
void processEvent (LCEvent *evtP)
Calculate Pedestals and Noise and search and reconstruct calorimeter hits.
void end ()
Static Public Member Functions
static NoiseParameterArray_t & getCellParameters ()
Protected Types
enum EState {
kStateUnknown, kStateSkipEvent, kStateCosmics, kStateBeam,
kStatePedestals, kStateInitialPedestals, kStateRefinePedestals, kStateCalibration,
kNStates
}
typedef void(SimpleHitSearch::* ProcessFunc_t)(EVENT::LCEvent *evtP)
Protected Member Functions
void changeState (EState new_state)
Change the state to the one specified.
bool stateTransition ()
Change the state.
void callStateFunc (LCEvent *evtP)
Call the event processing functions of the current state (state function).
void skipEvents (LCEvent *evtP)
Skip events.
void processCosmics (LCEvent *evtP)
Process cosmics events.
void processBeamEvents (LCEvent *evtP)
Process beam events.
void processPedestalEvents (LCEvent *evtP)
Process pedestal events.
void processFirstPedestalEvents (LCEvent *evtP)
Process events to get the first idea of the pedestals.
void processPedestalEventsWithHitRejection (LCEvent *evtP)
Refine the initial guess of the pedestals.
void skipCalibrationEvents (LCEvent *evtP)
Skip events for which the calibration chip is on.
void fullReset ()
Reset the arrays which contain the pedestals and the noise, hit counter etc.
void resetForInitialPedestalNoiseCalculation ()
Initialise the pedestal/noise arrays for the initial pedestal/noise estimate.
void resetForPedestalNoiseReCalculation ()
Initialise the pedestal/noise arrays for the pedestal/noise estimate (An initial pedestal/noise estimate is assumed).
void resetHitCounter ()
void resetSaturationCounter ()
void accumulateEventsForInitialPedestalNoiseCalculation (LCEvent *evtP)
Accumulate data to calculate pedestals and the noise.
void accumulateEventsForPedestalNoiseCalculationWithHitRejection (LCEvent *evtP)
Accumulate data to calculate pedestals and the noise with hit rejection.
void accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection (LCEvent *evtP)
Accumulate data to calculate pedestals and the noise.
void calculatePedestalNoiseAndDeclareCellsDead ()
Calculate pedestals and noise using the gathered information of the accumalted events.
void searchHits (LCEvent *evt)
Search hits without adjusting noise and pedestals (suitable for test beam data).
void searchHitsAndAdjustPedestalsAndNoise (LCEvent *evtP)
Search hits and adjust the pedestal and noise of cells with a signal below the cut _signalCut (suitable for cosmics data).
void buildCellParameters ()
Create and initialise the array which will contain for all cells the pedestals and the noise and further status information.
void showNoiseStat () const
Show per layer statistics about the noise and the pedestals.
void showCurrentNoiseStat () const
Show per layer statistics about the noise and the pedestals (during pedestal noise accumulation).
Float_t calculatePedestalCorrection (UInt_t module_i, Float_t *adc_values_per_module) const
calculculate an average pedestal correction for one module.
vector< Float_t > calculateSignalInducedPedestalCorrection (UInt_t module_i, const Float_t *adc_values_per_module) const
Float_t getCalibratedValue (UInt_t module_index, UInt_t cell_index, Float_t pedestal_subtracted_adc_value) const
Protected Member Functions inherited from CALICE::VRawADCValueProcessor
VRawADCValueProcessor (const std::string &processor_name)
void init ()
virtual void stagePositionChanged (lcio::LCCollection *col)
virtual void moduleConnectionChanged (lcio::LCCollection *col)
void showCollectionParameters (LCCollection *colP)
void correctModuleDescriptionOrder (LCCollection *colP)
Protected Attributes
ProcessFunc_t _stateFunc [kNStates]
ProcessFunc_t _theStateFunc
EState _isState
Protected Attributes inherited from CALICE::VRawADCValueProcessor
MappingAndAlignment _mapping
std::string _adcColName
Name of the input collection (INPUT).
std::string _colNameModuleDescription
Name of the conditions data collection containing module descriptions.
std::string _colNameModuleLocation
Name of the conditions data collection containing module location.
std::string _colNameModuleConnection
Name of the conditions data collection containing module location.
std::string _colNameStageCollection
Name of the conditions data collection containing stage positions.
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleTypeChange
helper class to listen for changes of the module types (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleLocationChange
helper class to listen for changes of the location of modules (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _moduleConnectionChange
helper class to listen for changes of the connection between modules and the DAQ front-ends (conditions data)
ConditionsChangeDelegator
< VRawADCValueProcessor > _stagePositionChange
helper class to listen for changes of stage positions (conditions data)
unsigned int _wrongOrderTill
Private Member Functions
void moduleTypeChanged (lcio::LCCollection *col)
void moduleLocationChanged (lcio::LCCollection *col)
void detectorTransformationChanged (lcio::LCCollection *col)
void referenceTransformationChanged (lcio::LCCollection *col)
Private Attributes
bool _pedestalNoiseIsKnown
Calibration * _calibration
TriggerBits _triggerConf
Variable which contains the current trigger configuration.
TriggerBits _lastTriggerConf
Variable which contains the trigger configuration of the previous event.
TriggerBits _triggerEvent
Variable which contains the current trigger main word.
LCCollection * _cellParameterCollection
std::string _cellParameterCollectionName
CellParameterArray_t _cellParameter
RunInformation _runInfo
int _runnum
TFile * _hfile
TH1F * p_Ped [30][9][36]
bool _isDead [30][9][36]
IntVec _adcRange
FloatVec _noiseRange
FloatVec _pedestalRange
Float_t _pedestalChangeCut
Float_t _maxPedestalChange
Maximum allowed pedestal change.
Int_t _removeMaximumInNEvents
Float_t _maxHitOccupancy
Maximum number of tolerated hits.
Int_t _minNEventsForPedestalNoiseUpdate
Minimum number of events to be accumulated before the pedestals and noise are calculated (parameter).
Int_t _updatePedestalsEveryNEvents
Update pedestals every n events, during pedestal triggers.
Int_t _weightOfOldPedestalNoise
Weight given to old pedestals and noise when using a new value to adjust the pedestals and the noise (parameter).
Float_t _shiftPedestalFactor
When processing pedestal events, shift pedestals by average values measured on one module times this factor.
Int_t _skipFirstNEvents
Skip the first n events (parameter).
Int_t _skipNEventsAfterConfChanges
Skip n events after configuration changes (parameter).
Int_t _skipNEvents
Skip the next n events (not a parameter).
Int_t _skipCalibrationEventsAlways
Skip events in which the calibration chip was turned on.
Int_t _skipNEventsAfterSlowConfRecords
Events skipped after slow or configuration records.
Int_t _skipDirtyEventsInPedestalCalculation
Events skipped during pedestal calculation because they are considered to be dirty.
Float_t _toleratedSaturationFraction
Float_t _signalThreshold
Signals above the signal threshold and ...
FloatVec _noiseCutVec
above the noise cut are considered to be hits.
Float_t _noiseCut
will be set by the first element of the _noiseCutVec
Float_t _noiseCutForPedestalNoiseCalculation
will be set by the second element of the _noiseCutVec (if available).
int _nNegativeSignalsPerModule
maximum number of negative signals per module.
std::string _hitColName
Name of the hit collection (OUTPUT).
std::string _rawhitColName
Name of the raw hit collection (optional OUTPUT).
bool _writeRawHits
Save the output collection containing RawCalorimeterHits.
bool _saveEcalNoise
Save the Noise value in the database.
std::string _dbInit
DBInit string.
std::string _folderNoise
Variable containing folder name for Ecal Noise.
std::string _colNameDetectorTransformation
Name of the conditions data collection which describes the position and the rotation of the detector.
std::string _colNameReferenceTransformation
Name of the conditions data collection which describes the reference position and rotation.
std::string _calibrationObjectName
Name of the Calibration object to be used (will be created using the CalibrationFactory)
std::string _calibrationConstantColName
Name of the conditions data collection containing the calibration constants.
std::string _parNameTriggerConf
Name of the event parameter which contains the current trigger configuration.
std::string _parNameTriggerEvent
Name of the event parameter which contains the current trigger main word.
std::string _parNameTriggerPreHistory
std::string _parNameTriggerPostHistory
std::string _parNameRecoState
Name of the event parameter which will be filled with the current state of the reconstruction.
std::string _parNameEventEnergy
Parameter name of the event energy.
std::string _parNamePedestalCorrection
Parameter name of the event energy.
ConditionsChangeDelegator
< SimpleHitSearch > _detectorTransformationChange
helper class to listen for changes of the detector position or rotation.
ConditionsChangeDelegator
< SimpleHitSearch > _referenceTransformationChange
helper class to listen for changes of the reference position or rotation.
UInt_t _nPedestalEvents
UInt_t _nPedestalEventsTotal
UInt_t _nPedestalEventSets
UInt_t _nEvents
UInt_t _nEventsTotal
UInt_t _nEventsWithHits
UInt_t _nEventsWithHitsTotal
UInt_t _nEventsSkipped
UInt_t _eventCounterForMaximumRejection
UInt_t _uncoveredTriggerCounter
UInt_t _nEventsWithoutADC
UInt_t _rejectedEvents
UInt_t _rejectBecauseOfError
UInt_t _rejectBecauseTooManyHits
UInt_t _rejectBecauseOfMissingADCBlocks
UInt_t _nEventsWithMissingAdcBlocks
Int_t _viewConnectionTree
vector< Float_t > _moduleBuffer
vector< Float_t > _avNoisePerModule
lcio::StringVec _maskedErrorNames
Names of alle masked errors (proc.
unsigned int _errorMask
bit mask of all errors to be ignored.
Bool_t _calibrationOn
UInt_t _lastEvent
Detailed Description
Marlin Processor to search and reconstruct colorimeter hits.
The hits are selected using a signal-over-noise threshold or a signal threshold (can be chosen at compile time by defining the environment variable (FIXED_THRESHOLD -> signal threshold). The class takes care of the pedestal and noise calculation. The hit position is calculated using information stored in a LCCD conditions database. Moreover, the signal is calibrated if a proper calibration object exists. Currently, there is only the NoOpCalibration which does nothing.
Definition at line 46 of file SimpleHitSearch.hh.
Member Enumeration Documentation
enum CALICE::SimpleHitSearch::EState protected
Enumerator
kStateUnknown
0: unknown state.
kStateSkipEvent
1: events are skipped unprocessed.
kStateCosmics
2: events are treated as cosmics (low, signals at random locations).
kStateBeam
3: events are treated as beam events (high, localised signals).
kStatePedestals
4: events are treated as pedestal/noise events (no signals).
kStateInitialPedestals
5: pedestals and noise are estimated assuming little signal at random locations.
kStateRefinePedestals
6: pedestal and noise estimates are improved assuming little signal at random locations.
kStateCalibration
7: There are permanent (calibration) signals at specific locations .
Definition at line 97 of file SimpleHitSearch.hh.
Constructor & Destructor Documentation
CALICE::SimpleHitSearch::SimpleHitSearch ()
default constructor.
defines and registers its parameters.
Definition at line 67 of file SimpleHitSearch.cc.
References _calibrationConstantColName, _calibrationObjectName, _colNameDetectorTransformation, _colNameReferenceTransformation, _dbInit, _folderNoise, _hitColName, _maskedErrorNames, _maxHitOccupancy, _maxPedestalChange, _minNEventsForPedestalNoiseUpdate, _noiseCutVec, _parNameEventEnergy, _parNamePedestalCorrection, _parNameRecoState, _parNameTriggerConf, _parNameTriggerEvent, _rawhitColName, _saveEcalNoise, _shiftPedestalFactor, _signalThreshold, _skipCalibrationEventsAlways, _skipFirstNEvents, _skipNEventsAfterConfChanges, _skipNEventsAfterSlowConfRecords, _updatePedestalsEveryNEvents, _weightOfOldPedestalNoise, _writeRawHits, changeState(), kStateBeam, kStateCalibration, kStateCosmics, kStateInitialPedestals, kStatePedestals, kStateRefinePedestals, kStateSkipEvent, kStateUnknown, processBeamEvents(), processCosmics(), processFirstPedestalEvents(), processPedestalEvents(), processPedestalEventsWithHitRejection(), and skipEvents().
Referenced by newProcessor().
Member Function Documentation
void CALICE::SimpleHitSearch::accumulateEventsForInitialPedestalNoiseCalculation (LCEvent * evtP) protected
Accumulate data to calculate pedestals and the noise.
It is assumed that the event sample does not contain any hits. Otherwise The noise and the pedestals will be biased to larger values.
Definition at line 1326 of file SimpleHitSearch.cc.
References CALICE::VRawADCValueProcessor::_adcColName, CALICE::CellParameter::add(), buildCellParameters(), CALICE::CellParameter::getMaxValue(), CALICE::CellParameter::incrementSaturationCounter(), CALICE::CellParameter::isDead(), CALICE::CellParameter::setMaxValue(), and CALICE::CellParameter::sub().
Referenced by processFirstPedestalEvents().
void CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejection (LCEvent * evtP) protected
Accumulate data to calculate pedestals and the noise with hit rejection.
Values which are above the threshold _signalCutForPedestalNoiseCalculation are not considered in the pedestal and noise calculation. If the threshold is too low the pedestals and the noise will be biased to lower values. If the threshold is too high and there are many hits the pedestals and the noise will be biased to higher values. This method is suitable for events with little amount of hits which are clearly separated from the pedestals.
Definition at line 1394 of file SimpleHitSearch.cc.
References CALICE::VRawADCValueProcessor::_adcColName, _noiseCutForPedestalNoiseCalculation, _shiftPedestalFactor, CALICE::CellParameter::add(), buildCellParameters(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), CALICE::CellParameter::incrementSaturationCounter(), and CALICE::CellParameter::isDead().
Referenced by processBeamEvents(), processPedestalEvents(), and processPedestalEventsWithHitRejection().
void CALICE::SimpleHitSearch::accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection (LCEvent * evtP) protected
Accumulate data to calculate pedestals and the noise.
If the pedestal shifts by more than the threshold _pedestalChangeCut than the old pedestal is shifted. As a consequence the precision on the pedestal is lousy, the noise may be biased to lower values. This method is suitable for noise events which were taken over a long periode which suffers large and discrete shifts of the pedestals.
Todo:
useful?
See Also
calculatePedestalNoiseAndDeclareCellsDead
Definition at line 1474 of file SimpleHitSearch.cc.
References CALICE::VRawADCValueProcessor::_adcColName, _noiseCutForPedestalNoiseCalculation, CALICE::CellParameter::add(), buildCellParameters(), CALICE::CellParameter::getMeanADCValue(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), CALICE::CellParameter::incrementSaturationCounter(), CALICE::CellParameter::isDead(), and CALICE::CellParameter::shiftPedestal().
void CALICE::SimpleHitSearch::buildCellParameters () protected
Create and initialise the array which will contain for all cells the pedestals and the noise and further status information.
See Also
CellParameter
Definition at line 2519 of file SimpleHitSearch.cc.
References Calibration::checkForCalibrationConstantsOfModule(), and Calibration::isValid().
Referenced by accumulateEventsForInitialPedestalNoiseCalculation(), accumulateEventsForPedestalNoiseCalculationWithHitRejection(), accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection(), searchHits(), and searchHitsAndAdjustPedestalsAndNoise().
Float_t CALICE::SimpleHitSearch::calculatePedestalCorrection (UInt_t module_i, Float_t * adc_values_per_module) const protected
calculculate an average pedestal correction for one module.
Parameters
module_i the module index
adc_values_per_module an array which has for each cell of the module one adc value or -FLT_MAX for dead cells.
Returns
an additive correction which should be applied to all pedestals of the module.
Definition at line 2828 of file SimpleHitSearch.cc.
Referenced by searchHits().
void CALICE::SimpleHitSearch::calculatePedestalNoiseAndDeclareCellsDead () protected
Calculate pedestals and noise using the gathered information of the accumalted events.
See Also
accumulateEventsForInitialPedestalNoiseCalculation, accumulateEventsForPedestalNoiseCalculationWithHitRejection, accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection
Definition at line 1540 of file SimpleHitSearch.cc.
References _maxPedestalChange, CALICE::CellParameter::calculate(), histmgr::FloatHistogram1D::fill(), histmgr::HistMgr::getHistogramCollection(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), CALICE::CellParameter::getSaturationCounter(), histmgr::HistogramCollection_t::histogram(), CALICE::CellParameter::isDead(), and CALICE::CellParameter::setDead().
Referenced by processPedestalEvents(), and stateTransition().
void CALICE::SimpleHitSearch::callStateFunc (LCEvent * evtP) inline protected
Call the event processing functions of the current state (state function).
See Also
skipEvents, processCosmics, processBeamEvents, processPedestalEvents, processFirstPedestalEvents
processPedestalEventsWithHitRejection, skipCalibrationEvents,
Definition at line 130 of file SimpleHitSearch.hh.
Referenced by processBeamEvents(), processCosmics(), processEvent(), processFirstPedestalEvents(), processPedestalEventsWithHitRejection(), skipCalibrationEvents(), and skipEvents().
void CALICE::SimpleHitSearch::init ()
Called at the begin of the job before anything is read.
Use to initialize the processor, e.g. book histograms.
Definition at line 484 of file SimpleHitSearch.cc.
References _calibrationConstantColName, _calibrationObjectName, _colNameDetectorTransformation, CALICE::VRawADCValueProcessor::_colNameModuleDescription, _colNameReferenceTransformation, _detectorTransformationChange, _errorMask, _maskedErrorNames, _minNEventsForPedestalNoiseUpdate, _noiseCut, _noiseCutForPedestalNoiseCalculation, _noiseCutVec, _parNameEventEnergy, _referenceTransformationChange, _skipCalibrationEventsAlways, _skipDirtyEventsInPedestalCalculation, _skipFirstNEvents, _skipNEvents, _updatePedestalsEveryNEvents, changeState(), CalibrationFactory::createCalibrationObject(), histmgr::HistMgr::createHistogramGroup(), fullReset(), CalibrationFactory::getInstance(), kStateCalibration, kStateSkipEvent, CalibrationFactory::listKits(), histmgr::HistMgr::lockGroup(), and skipCalibrationEvents().
void CALICE::SimpleHitSearch::processBeamEvents (LCEvent * evtP) protected
Process beam events.
State function called if _isState = kStateBeam or if kStateCalibration (configurable).
Definition at line 961 of file SimpleHitSearch.cc.
References _triggerConf, _triggerEvent, accumulateEventsForPedestalNoiseCalculationWithHitRejection(), callStateFunc(), searchHits(), and stateTransition().
Referenced by SimpleHitSearch().
void CALICE::SimpleHitSearch::processCosmics (LCEvent * evtP) protected
Process cosmics events.
State function called if _isState = kStateCosmics.
Definition at line 948 of file SimpleHitSearch.cc.
References _triggerConf, callStateFunc(), searchHitsAndAdjustPedestalsAndNoise(), and stateTransition().
Referenced by SimpleHitSearch().
void CALICE::SimpleHitSearch::processEvent (LCEvent * evtP)
Calculate Pedestals and Noise and search and reconstruct calorimeter hits.
The class needs as input the ADC value collection and produces a CalorimeterHit collection.
Depending on the trigger configuration, the pedestal and noise are either calculated from random triggers (test beam data) or it is assumed that the hit distribution is sparse and randomly distributed over the detector (cosmics data). In the latter case the pedestals and noise are calculated initially from the first events assuming the events do not contain any hits. Then, the initial guess is slowly adjusted. Otherwise the pedestals and the noise are calculted from pedestal events.
The event processing method depends on the state (EState) of the analysis. The state transition is trigger by trigger configuration changes, changes of the calibration chip configuration, knowledge about the pedestals and noise.
See Also
searchHit
ssearchHitsAndAdjustPedestalsAndNoise, stateTransition
Definition at line 1186 of file SimpleHitSearch.cc.
References _parNameRecoState, _parNameTriggerConf, _parNameTriggerEvent, _skipNEvents, _skipNEventsAfterConfChanges, _skipNEventsAfterSlowConfRecords, _triggerConf, _triggerEvent, callStateFunc(), changeState(), histmgr::FloatHistogram1D::fill(), histmgr::HistMgr::getHistogramCollection(), histmgr::HistogramCollection_t::histogram(), kStateSkipEvent, and stateTransition().
void CALICE::SimpleHitSearch::processFirstPedestalEvents (LCEvent * evtP) protected
Process events to get the first idea of the pedestals.
State function called if the pedestal and noise is not yet known and if the events are either pedestal or cosmics events.
Definition at line 1002 of file SimpleHitSearch.cc.
References _minNEventsForPedestalNoiseUpdate, _skipDirtyEventsInPedestalCalculation, _triggerEvent, accumulateEventsForInitialPedestalNoiseCalculation(), callStateFunc(), and stateTransition().
Referenced by SimpleHitSearch().
void CALICE::SimpleHitSearch::processPedestalEvents (LCEvent * evtP) protected
Process pedestal events.
State function called if _isState = kStatePedestals
Definition at line 979 of file SimpleHitSearch.cc.
References _skipDirtyEventsInPedestalCalculation, _triggerEvent, _updatePedestalsEveryNEvents, accumulateEventsForPedestalNoiseCalculationWithHitRejection(), calculatePedestalNoiseAndDeclareCellsDead(), and resetForPedestalNoiseReCalculation().
Referenced by SimpleHitSearch().
void CALICE::SimpleHitSearch::processPedestalEventsWithHitRejection (LCEvent * evtP) protected
Refine the initial guess of the pedestals.
State function called subsequent to processFirstPedestalEvents and if the events are either pedestal or cosmics events.
Definition at line 1027 of file SimpleHitSearch.cc.
References _minNEventsForPedestalNoiseUpdate, _skipDirtyEventsInPedestalCalculation, _triggerEvent, accumulateEventsForPedestalNoiseCalculationWithHitRejection(), callStateFunc(), and stateTransition().
Referenced by SimpleHitSearch().
void CALICE::SimpleHitSearch::searchHits (LCEvent * evt) protected
Search hits without adjusting noise and pedestals (suitable for test beam data).
This method is only useful in cases in which cells rarely contain hits (like cosmics data). Test beam data usually has hits always at the same place.
Parameters
evt pointer to a event which contains the ADC value collection.
Definition at line 1676 of file SimpleHitSearch.cc.
References CALICE::VRawADCValueProcessor::_adcColName, _errorMask, _maxHitOccupancy, _maxPedestalChange, _noiseCut, _parNameEventEnergy, _parNamePedestalCorrection, _rawhitColName, _signalThreshold, _writeRawHits, buildCellParameters(), calculatePedestalCorrection(), histmgr::FloatHistogram1D::fill(), histmgr::FloatHistogram2D::fill(), histmgr::HistMgr::getHistogram2DCollection(), histmgr::HistMgr::getHistogramCollection(), Calibration::getMiniumADCForMipThreshold(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getPedestal(), histmgr::HistogramCollection_t::histogram(), histmgr::Histogram2DCollection_t::histogram(), CALICE::CellParameter::incrementNHits(), CALICE::CellParameter::incrementSaturationCounter(), CALICE::CellParameter::isDead(), histmgr::Histogram2DCollection_t::n(), CALICE::NoiseParameter::setDead(), CALICE::NoiseParameter::setGeomCellIndex(), CALICE::NoiseParameter::setNoise(), CALICE::CellParameter::setOldPedestal(), CALICE::NoiseParameter::setPedestal(), CALICE::CellParameter::setPedestal(), CALICE::NoiseParameter::setPedestalBeforeGC(), and CALICE::NoiseParameter::setPedestalBeforeSIC().
Referenced by processBeamEvents().
void CALICE::SimpleHitSearch::searchHitsAndAdjustPedestalsAndNoise (LCEvent * evtP) protected
Search hits and adjust the pedestal and noise of cells with a signal below the cut _signalCut (suitable for cosmics data).
This method is only useful in cases in which cells rarely contain hits (like cosmics data). Test beam data usually has hits always at the same place.
Parameters
evtP pointer to a event which contains the ADC value collection.
Definition at line 2278 of file SimpleHitSearch.cc.
References CALICE::VRawADCValueProcessor::_adcColName, _errorMask, _hitColName, _maxHitOccupancy, _noiseCut, _signalThreshold, _weightOfOldPedestalNoise, CALICE::CellParameter::adjustPedestalNoise(), buildCellParameters(), CALICE::NVector_t< T, dimension >::data(), histmgr::FloatHistogram1D::fill(), histmgr::HistMgr::getHistogramCollection(), Calibration::getMiniumADCForMipThreshold(), CALICE::CellParameter::getNoise(), CALICE::CellParameter::getOldNoise(), CALICE::CellParameter::getOldPedestal(), CALICE::CellParameter::getPedestal(), histmgr::HistogramCollection_t::histogram(), CALICE::CellParameter::incrementNHits(), CALICE::CellParameter::incrementSaturationCounter(), and CALICE::CellParameter::isDead().
Referenced by processCosmics().
void CALICE::SimpleHitSearch::showCurrentNoiseStat () const protected
Show per layer statistics about the noise and the pedestals (during pedestal noise accumulation).
This method calculates the pedestals and the noise itself from the accumulated sums. Will show incorrect results after the pedestals and the noise have been calculated.
Definition at line 1651 of file SimpleHitSearch.cc.
References CALICE::CellParameter::getNValues(), CALICE::CellParameter::getOldNoise(), CALICE::CellParameter::getOldPedestal(), and CALICE::CellParameter::isDead().
void CALICE::SimpleHitSearch::skipCalibrationEvents (LCEvent * evtP) protected
Skip events for which the calibration chip is on.
State function which skip events until the calibration chip is switched off (configurable).
Definition at line 937 of file SimpleHitSearch.cc.
References _triggerConf, callStateFunc(), and stateTransition().
Referenced by init().
void CALICE::SimpleHitSearch::skipEvents (LCEvent * evtP) protected
Skip events.
State function called for the first n events (configurable) and for n events after configuration changes.
Definition at line 923 of file SimpleHitSearch.cc.
References _skipNEvents, _triggerConf, callStateFunc(), and stateTransition().
Referenced by SimpleHitSearch().
bool CALICE::SimpleHitSearch::stateTransition () protected
Change the state.
return true if the state changed.
Definition at line 1052 of file SimpleHitSearch.cc.
References _minNEventsForPedestalNoiseUpdate, _skipNEvents, _triggerConf, calculatePedestalNoiseAndDeclareCellsDead(), changeState(), histmgr::FloatHistogram1D::fill(), histmgr::HistMgr::getHistogramCollection(), histmgr::HistogramCollection_t::histogram(), kStateBeam, kStateCalibration, kStateCosmics, kStateInitialPedestals, kStatePedestals, kStateRefinePedestals, kStateSkipEvent, resetForInitialPedestalNoiseCalculation(), resetForPedestalNoiseReCalculation(), and showNoiseStat().
Referenced by processBeamEvents(), processCosmics(), processEvent(), processFirstPedestalEvents(), processPedestalEventsWithHitRejection(), skipCalibrationEvents(), and skipEvents().
Field Documentation
std::string CALICE::SimpleHitSearch::_calibrationConstantColName private
Name of the conditions data collection containing the calibration constants.
Definition at line 357 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_colNameDetectorTransformation private
Name of the conditions data collection which describes the position and the rotation of the detector.
Definition at line 351 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_colNameReferenceTransformation private
Name of the conditions data collection which describes the reference position and rotation.
Definition at line 353 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
ConditionsChangeDelegator<SimpleHitSearch> CALICE::SimpleHitSearch::_detectorTransformationChange private
helper class to listen for changes of the detector position or rotation.
Definition at line 373 of file SimpleHitSearch.hh.
Referenced by init().
unsigned int CALICE::SimpleHitSearch::_errorMask private
bit mask of all errors to be ignored.
Definition at line 458 of file SimpleHitSearch.hh.
Referenced by init(), searchHits(), and searchHitsAndAdjustPedestalsAndNoise().
std::string CALICE::SimpleHitSearch::_hitColName private
Name of the hit collection (OUTPUT).
Definition at line 342 of file SimpleHitSearch.hh.
Referenced by searchHitsAndAdjustPedestalsAndNoise(), and SimpleHitSearch().
TriggerBits CALICE::SimpleHitSearch::_lastTriggerConf private
Variable which contains the trigger configuration of the previous event.
Definition at line 282 of file SimpleHitSearch.hh.
lcio::StringVec CALICE::SimpleHitSearch::_maskedErrorNames private
Names of alle masked errors (proc.
parameter)
Definition at line 457 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
Float_t CALICE::SimpleHitSearch::_maxHitOccupancy private
Maximum number of tolerated hits.
Events with more hits are rejected (parameter).
Definition at line 309 of file SimpleHitSearch.hh.
Referenced by searchHits(), searchHitsAndAdjustPedestalsAndNoise(), and SimpleHitSearch().
Float_t CALICE::SimpleHitSearch::_maxPedestalChange private
Maximum allowed pedestal change.
Definition at line 305 of file SimpleHitSearch.hh.
Referenced by calculatePedestalNoiseAndDeclareCellsDead(), searchHits(), and SimpleHitSearch().
Int_t CALICE::SimpleHitSearch::_minNEventsForPedestalNoiseUpdate private
Minimum number of events to be accumulated before the pedestals and noise are calculated (parameter).
Definition at line 312 of file SimpleHitSearch.hh.
Referenced by init(), processFirstPedestalEvents(), processPedestalEventsWithHitRejection(), SimpleHitSearch(), and stateTransition().
int CALICE::SimpleHitSearch::_nNegativeSignalsPerModule private
maximum number of negative signals per module.
Definition at line 340 of file SimpleHitSearch.hh.
Float_t CALICE::SimpleHitSearch::_noiseCutForPedestalNoiseCalculation private
will be set by the second element of the _noiseCutVec (if available).
Definition at line 338 of file SimpleHitSearch.hh.
Referenced by accumulateEventsForPedestalNoiseCalculationWithHitRejection(), accumulateEventsForPedestalNoiseCalculationWithHitRejectionAndPedestalShiftDetection(), and init().
FloatVec CALICE::SimpleHitSearch::_noiseCutVec private
above the noise cut are considered to be hits.
This vector contains a cut for the hit search and for the hit rejection during noise calculation
Definition at line 334 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_parNameEventEnergy private
Parameter name of the event energy.
If left blank nothing will be added.
Definition at line 367 of file SimpleHitSearch.hh.
Referenced by init(), searchHits(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_parNamePedestalCorrection private
Parameter name of the event energy.
If left blank nothing will be added.
Definition at line 369 of file SimpleHitSearch.hh.
Referenced by searchHits(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_parNameRecoState private
Name of the event parameter which will be filled with the current state of the reconstruction.
Definition at line 365 of file SimpleHitSearch.hh.
Referenced by processEvent(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_parNameTriggerConf private
Name of the event parameter which contains the current trigger configuration.
Definition at line 359 of file SimpleHitSearch.hh.
Referenced by processEvent(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_parNameTriggerEvent private
Name of the event parameter which contains the current trigger main word.
Definition at line 360 of file SimpleHitSearch.hh.
Referenced by processEvent(), and SimpleHitSearch().
std::string CALICE::SimpleHitSearch::_rawhitColName private
Name of the raw hit collection (optional OUTPUT).
Definition at line 343 of file SimpleHitSearch.hh.
Referenced by searchHits(), and SimpleHitSearch().
ConditionsChangeDelegator<SimpleHitSearch> CALICE::SimpleHitSearch::_referenceTransformationChange private
helper class to listen for changes of the reference position or rotation.
Definition at line 376 of file SimpleHitSearch.hh.
Referenced by init().
bool CALICE::SimpleHitSearch::_saveEcalNoise private
Save the Noise value in the database.
Definition at line 345 of file SimpleHitSearch.hh.
Referenced by SimpleHitSearch().
Float_t CALICE::SimpleHitSearch::_shiftPedestalFactor private
When processing pedestal events, shift pedestals by average values measured on one module times this factor.
Definition at line 320 of file SimpleHitSearch.hh.
Referenced by accumulateEventsForPedestalNoiseCalculationWithHitRejection(), and SimpleHitSearch().
Float_t CALICE::SimpleHitSearch::_signalThreshold private
Signals above the signal threshold and ...
Definition at line 333 of file SimpleHitSearch.hh.
Referenced by searchHits(), searchHitsAndAdjustPedestalsAndNoise(), and SimpleHitSearch().
Int_t CALICE::SimpleHitSearch::_skipCalibrationEventsAlways private
Skip events in which the calibration chip was turned on.
Definition at line 327 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
Int_t CALICE::SimpleHitSearch::_skipDirtyEventsInPedestalCalculation private
Events skipped during pedestal calculation because they are considered to be dirty.
Definition at line 329 of file SimpleHitSearch.hh.
Referenced by init(), processFirstPedestalEvents(), processPedestalEvents(), and processPedestalEventsWithHitRejection().
Int_t CALICE::SimpleHitSearch::_skipFirstNEvents private
Skip the first n events (parameter).
Definition at line 323 of file SimpleHitSearch.hh.
Referenced by init(), and SimpleHitSearch().
Int_t CALICE::SimpleHitSearch::_skipNEvents private
Skip the next n events (not a parameter).
Definition at line 325 of file SimpleHitSearch.hh.
Referenced by init(), processEvent(), skipEvents(), and stateTransition().
Int_t CALICE::SimpleHitSearch::_skipNEventsAfterConfChanges private
Skip n events after configuration changes (parameter).
Definition at line 324 of file SimpleHitSearch.hh.
Referenced by processEvent(), and SimpleHitSearch().
Int_t CALICE::SimpleHitSearch::_skipNEventsAfterSlowConfRecords private
Events skipped after slow or configuration records.
Definition at line 328 of file SimpleHitSearch.hh.
Referenced by processEvent(), and SimpleHitSearch().
TriggerBits CALICE::SimpleHitSearch::_triggerConf private
Variable which contains the current trigger configuration.
Definition at line 281 of file SimpleHitSearch.hh.
Referenced by processBeamEvents(), processCosmics(), processEvent(), skipCalibrationEvents(), skipEvents(), and stateTransition().
TriggerBits CALICE::SimpleHitSearch::_triggerEvent private
Variable which contains the current trigger main word.
Definition at line 284 of file SimpleHitSearch.hh.
Referenced by processBeamEvents(), processEvent(), processFirstPedestalEvents(), processPedestalEvents(), and processPedestalEventsWithHitRejection().
Int_t CALICE::SimpleHitSearch::_updatePedestalsEveryNEvents private
Update pedestals every n events, during pedestal triggers.
Definition at line 315 of file SimpleHitSearch.hh.
Referenced by init(), processPedestalEvents(), and SimpleHitSearch().
Int_t CALICE::SimpleHitSearch::_weightOfOldPedestalNoise private
Weight given to old pedestals and noise when using a new value to adjust the pedestals and the noise (parameter).
Definition at line 317 of file SimpleHitSearch.hh.
Referenced by searchHitsAndAdjustPedestalsAndNoise(), and SimpleHitSearch().
bool CALICE::SimpleHitSearch::_writeRawHits private
Save the output collection containing RawCalorimeterHits.
Definition at line 344 of file SimpleHitSearch.hh.
Referenced by searchHits(), and SimpleHitSearch().
The documentation for this class was generated from the following files:
SimpleHitSearch.hh
SimpleHitSearch.cc