CLUSTERING: DeepAnalysis Class Reference
DeepAnalysis Class Reference
Cluster finding and analysis.
#include <DeepAnalysis.hh>
Data Structures
class Cluster
Cluster is the main object to work with and to keep the main results of the analisys Cluster consists of its properties: like parameters of the inertia tensor, average density, whole volume, a few topological Chisq and pointers to first and last hits in cluster.
class Detector
Class for detector and algorithm parameters.
class Group
Class for general multipurpose grouping.
class Hit
Class for hit: consists of:
class HitGroup
This class is not a cluster, but this is as it said in name – Group of Hits, that has a boundaries in 3-D cartesian coordinate system and spherical coordinate system, center of gravity and whole energy.
class JoinGroup
Class for joining groups (juts a working intermediate class) (for cluster_join method)
class KindGroup
This class has a represents of RGB types of Groups.
class NeutGroup
Neutrons group (specific for technical reasons)
class SpecialHist2D
Special 2D histograms.
Public Types
enum KIND {
EM =0, TRK, HAD, KIND_COUNT,
NEUTR
}
An enumeration – colors for RGB scheme for hit spectrum RED is most dense hit(calorimeter cell) BLUE is intermediate GREEN is MIP-like, or around the MIP density.
Public Member Functions
DeepAnalysis ()
Constructor.
void cluster_from_singles (KindGroup &gr, bool mark_neutrons)
Create clusters from single hits.
void cluster_finder_2d_split (Hit &hit, unsigned InClust_count, Cluster **InClust)
Distribute hits at the spherical shell onto found 2D cluster seeds.
void cluster_finder_2d (HitGroup &hitGroup, Group &ring)
2D clustering procedure to find clusters by histogramming technique at the one spherical shell in Theta-Phi.
void cluster_finder_3d (KindGroup &gr, bool mark_neutrons)
Find 3D clusters.
void join_group (Cluster *cl, JoinGroup *jg)
Technical function used in cluster_join.
void make_join_group (Cluster *cl0, Cluster *cl1, Cluster *cl2=0)
Technical function used in cluster_join.
void cluster_join (bool for_em)
Join clusters together.
void em_shower_find ()
Find electromagnetic shower: it collects additional (not RED) hits around the EM cluster core.
void reassignment_small_clusters (KIND k)
Reassign small clusters.
void low_e_clean ()
Clean low energy clusters.
Hit * add_hit (double _x, double _y, double _z, double _am, double _ampl_mip, double _thr, unsigned _lay, KIND type, int _addr)
Create Hit object.
void draw ()
Draw ??
void draw_to_layer (unsigned layer)
Draw ??
void color_clusters_stat (KIND k, unsigned &ncl, unsigned &n_sum, double &e_sum)
Calculate cluster statistics.
void color_clusters_print_stat (KIND k)
Print clusters statistics.
void result_check ()
Check result.
void event_move ()
Move event from a pole to equator of spherical coordinate system.
void event_move_back ()
Move back event to the pole of Sp_CS.
void reconstruction ()
Main routine to split event into four different types of clusters: EM - electromagnetic piece of hadronic shower TRK - tracks in hadronic shower HAD - a few tracks in hadronic shower that cannot be splitted into individual tracks.
Public Member Functions inherited from RS
template<class _Tp >
_Tp * alloc ()
void unlink (RSObj *cld, RSObj *prt)
void unlink (RSObj *obj)
void prepend (RSObj *cld, RSObj *prt)
void append (RSObj *cld, RSObj *prt)
template<class _Tp >
void SortChildren (RSObj *obj, int(*compare)(const _Tp **, const _Tp **))
Data Fields
Detector detector
HitGroup * all_hits
All main pointer to structures.
Group * clusters
clusters
Group * joingroups
joined groups
KindGroup * kind [KIND_COUNT]
hit type
NeutGroup * neutrons
neutrons group
unsigned all_hits_count
counter for all hits
Data Fields inherited from RS
void * obj_pool [32]
SpacePool pool
Detailed Description
Cluster finding and analysis.
Hadronic shower analysis using hit density, shower topology and cluster shapes to find shower component of different physical origin, such as pure tracks, electromagnetic cascades inside hadronic shower; and hits that produced by neutrons.
Author
V.L. Morgunov
Date
18 September 2007
Definition at line 52 of file DeepAnalysis.hh.
Member Enumeration Documentation
enum DeepAnalysis::KIND
An enumeration – colors for RGB scheme for hit spectrum RED is most dense hit(calorimeter cell) BLUE is intermediate GREEN is MIP-like, or around the MIP density.
Enumerator
EM
former 2 color red
TRK
former 3 color green
HAD
former 4 color blue
KIND_COUNT
counter for kinds (types)
NEUTR
after count, since it is not KindGroup.
Definition at line 159 of file DeepAnalysis.hh.
Member Function Documentation
void DeepAnalysis::cluster_finder_3d (KindGroup & gr, bool mark_neutrons) inline
Find 3D clusters.
Method is: to create spherilal shells in the event volume, make 2D clustering at each shell, then connect near by 2D clusters into 3D trees.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Definition at line 1003 of file DeepAnalysis.hh.
References DeepAnalysis::Cluster::calc_prop(), DeepAnalysis::HitGroup::calc_stat(), DeepAnalysis::HitGroup::centerOfGravity, DeepAnalysis::Cluster::CHAIN, cluster_finder_2d(), cluster_from_singles(), clusters, DeepAnalysis::Cluster::EMPTY, DeepAnalysis::Detector::ext_cell_size, DeepAnalysis::Detector::join_factor, DeepAnalysis::HitGroup::layer_g, Range< _T >::max, Range< _T >::min, DeepAnalysis::Cluster::ONEHIT, DeepAnalysis::HitGroup::radius_g, DeepAnalysis::Detector::sampling, DeepAnalysis::Hit::sphere3d, and DeepAnalysis::Cluster::type.
Referenced by reconstruction().
void DeepAnalysis::color_clusters_print_stat (KIND k) inline
Print clusters statistics.
Parameters
k kind of cluster
Definition at line 1514 of file DeepAnalysis.hh.
References color_clusters_stat().
void DeepAnalysis::color_clusters_stat (KIND k, unsigned & ncl, unsigned & n_sum, double & e_sum) inline
Calculate cluster statistics.
Parameters
k type of cluster
ncl number of clusters
n_sum total number of hits
e_sum total energy sum
Definition at line 1499 of file DeepAnalysis.hh.
References clusters.
Referenced by color_clusters_print_stat(), and CALICE::DeepAnalysisProcessor::processEvent().
void DeepAnalysis::reconstruction () inline
Main routine to split event into four different types of clusters: EM - electromagnetic piece of hadronic shower TRK - tracks in hadronic shower HAD - a few tracks in hadronic shower that cannot be splitted into individual tracks.
NEUT - neutron component of hadronic shower
Definition at line 1599 of file DeepAnalysis.hh.
References all_hits, DeepAnalysis::HitGroup::calc_stat(), cluster_finder_3d(), cluster_join(), clusters, EM, em_shower_find(), event_move(), event_move_back(), HAD, DeepAnalysis::Detector::init(), kind, Range< _T >::min, DeepAnalysis::HitGroup::radius_g, reassignment_small_clusters(), and TRK.
Referenced by CALICE::DeepAnalysisProcessor::processEvent().
Field Documentation
HitGroup* DeepAnalysis::all_hits
All main pointer to structures.
hit group
Definition at line 772 of file DeepAnalysis.hh.
Referenced by add_hit(), DeepAnalysis(), em_shower_find(), event_move(), event_move_back(), reconstruction(), and result_check().
The documentation for this class was generated from the following file:
DeepAnalysis.hh