CALICE_USERLIB: CALICE::SatCorrItepCutOff Class Reference
CALICE::SatCorrItepCutOff Class Reference
Public Member Functions
SatCorrItepCutOff (EVENT::LCObject *obj)
SatCorrItepCutOff (const HcalTileIndex &hti, const unsigned int nPoints, const float *pixs, const float *pmts)
int getIndex () const
float getScaling () const
get the applied scaling
float deSaturate (const float saturatedSignal) const
apply saturation correction to a signal amplitude
float deSaturatedError (const float saturatedSignal, const float saturatedSignalError) const
error after application of saturation correction to a signal
float saturate (const float unsaturatedSignal) const
apply saturation to a signal amplitude
float saturatedError (const float unsaturatedSignal, const float unsaturatedSignalError) const
error after application of saturation to a signal
const std::string getTypeName () const
const std::string getDataDescription () const
void setIndex (const HcalTileIndex &hti)
void setScaling (const float scaling)
float getPix (const unsigned int i) const
float getPmt (const unsigned int i) const
void setPix (const unsigned int i, const float pix)
void setPmt (const unsigned int i, const float pmt)
Private Attributes
float _scaling
Detailed Description
Definition at line 12 of file SatCorrItepCutOff.hh.
Member Function Documentation
float CALICE::SatCorrItepCutOff::deSaturate (const float saturatedSignal) const virtual
apply saturation correction to a signal amplitude
Parameters
saturatedSignal saturated signal
Returns
unsaturated signal
Implements CALICE::SatCorrFunction.
Definition at line 55 of file SatCorrItepCutOff.cc.
Referenced by deSaturatedError().
float CALICE::SatCorrItepCutOff::deSaturatedError (const float saturatedSignal, const float saturatedSignalError) const virtual
error after application of saturation correction to a signal
Parameters
saturatedSignal saturated signal
saturatedSignalError error of the saturated signal
Returns
error of the unsaturated signal
Implements CALICE::SatCorrFunction.
Definition at line 95 of file SatCorrItepCutOff.cc.
References deSaturate().
float CALICE::SatCorrItepCutOff::saturate (const float unsaturatedSignal) const virtual
apply saturation to a signal amplitude
Parameters
unsaturatedSignal unsaturated signal
Returns
saturated signal
Implements CALICE::SatCorrFunction.
Definition at line 107 of file SatCorrItepCutOff.cc.
Referenced by saturatedError().
float CALICE::SatCorrItepCutOff::saturatedError (const float unsaturatedSignal, const float unsaturatedSignalError) const virtual
error after application of saturation to a signal
Parameters
unsaturatedSignal unsaturated signal
unsaturatedSignalError error of the unsaturated signal
Returns
error of saturated signal
Implements CALICE::SatCorrFunction.
Definition at line 143 of file SatCorrItepCutOff.cc.
References saturate().
The documentation for this class was generated from the following files:
SatCorrItepCutOff.hh
SatCorrItepCutOff.cc