CALICE_USERLIB: CALICE::LinearFitResult Class Reference
CALICE::LinearFitResult Class Reference
Class to store the result of a linear fit within the lcio framework.
#include <LinearFitResultLCIO.hh>
Public Member Functions
LinearFitResult (lcio::LCObject *obj)
LinearFitResult (int ID, double offset, double slope, double chi2, double eMA, double eMB, double eMC, double eMD, int ndf)
double eval (const double x) const
Evaluates the fit.
int getID () const
Get the identifier.
int getNDF () const
Get the number of degress of freedom of the fit.
double getOffset () const
Get the offset/y-intercept of the fit.
double getSlope () const
Get the slope of the fit.
double getChi2 () const
Get the Chi2 of the fit.
void getErrorMatrix (double errorMatrix[2][2]) const
Get the error matrix of the fit.
double getOffsetError () const
Get the error of the offset.
double getSlopeError () const
Get the error of the slope.
void setID (const int ID)
Sets an identifier.
void setNDF (const int NDF)
Sets the number of degress of freedom.
void setOffset (const double offset)
Sets the offset.
void setSlope (const double slope)
Sets the slope.
void setChi2 (const double chi2)
Sets the chi2.
void setErrorMatrix (const double array[2][2])
Sets the full error matrix.
void setOffsetError (double offsetError)
Sets the error of the offset.
void setSlopeError (double slopeError)
Sets the error of the slope.
const std::string getTypeName () const
Get the type name.
const std::string getDataDescription () const
Get the data description.
Detailed Description
Class to store the result of a linear fit within the lcio framework.
This class can be used for example to store the result of a linear fit, e.g. TF1 root fit.
Errors are stored in the error matrix.
Author
Sebastian Richter (sebas.nosp@m.tian.nosp@m..rich.nosp@m.ter@.nosp@m.desy..nosp@m.de)
Version
1.0
Date
9 January 2009
Definition at line 42 of file LinearFitResultLCIO.hh.
Member Function Documentation
double CALICE::LinearFitResult::eval (const double x) const inline
Evaluates the fit.
Parameters
x - point where the fit is evaluated: getOffset() + x * getSlope()
Definition at line 76 of file LinearFitResultLCIO.hh.
References getOffset(), and getSlope().
const std::string CALICE::LinearFitResult::getDataDescription () const inline
Get the data description.
The data description gives the meaning of the data fields.
Definition at line 244 of file LinearFitResultLCIO.hh.
void CALICE::LinearFitResult::getErrorMatrix (double errorMatrix[2][2]) const inline
Get the error matrix of the fit.
The first parameter is the offset, the second one is the slope.
Definition at line 130 of file LinearFitResultLCIO.hh.
Referenced by getOffsetError(), and getSlopeError().
double CALICE::LinearFitResult::getOffset () const inline
Get the offset/y-intercept of the fit.
The offset is equivalent to eval(0).
Definition at line 103 of file LinearFitResultLCIO.hh.
Referenced by eval().
const std::string CALICE::LinearFitResult::getTypeName () const inline
Get the type name.
The type name is used to determine which class interprets the LCGenericObject which holds the pure data.
Definition at line 235 of file LinearFitResultLCIO.hh.
The documentation for this class was generated from the following file:
LinearFitResultLCIO.hh