CALICE_USERLIB: CALICE::TriggerHandlerCalice Class Reference
CALICE::TriggerHandlerCalice Class Reference
Implementation of TriggerHandler base class for calice purposes Trigger conditions are read from a conditions data source or from the event information.
#include <TriggerHandlerCalice.hh>
Data Structures
class Crate_t
Samll helper class which contains a collection of slots and which remebers all the sub detector ids conencted to it.
class TriggerDef_t
Simple class which contains the data of logical trigger.
class TriggerValue_t
The mask and value pair which identifies a physical trigger.
Public Types
typedef std::map
< TriggerValue_t, TriggerDef_t > TriggerDefinitionMap_t
Public Member Functions
virtual ~TriggerHandlerCalice ()
Destructor.
virtual void setTrigger (lcio::LCEvent *)
returns pointer to only instance of the TriggerHandlerCalice
unsigned int searchTriggerMainWord ()
Search for the trigger main word.
void searchTriggerHistory ()
Search the trigger history for triggers firing at and before the main word.
const std::map< unsigned int,
unsigned int > & getPreTriggerHistory () const
Get a list trigger and their positions wrt.
const std::map< unsigned int,
unsigned int > & getPostTriggerHistory () const
Get a list trigger and their positions wrt.
virtual bool isValidTrigger (const lcio::LCEvent *)
Trigger Validation.
virtual void init ()
A initialization method.
void init (const string &col_trigger_assignment, const string &col_trigger_check, const string &colBeTrgConf, const string &col_name_readout_conf, const string &col_name_trgro_conf, const lcio::StringVec &col_name_fe_conf, const lcio::StringVec &col_name_module_connection)
Another initialization method.
void setColNameTriggerEvent (const std::string &col_name)
Set the name of the trigger event collection.
void setTriggerEventClass ()
Set the trigger event class BeTrgEvent/FeTrgEvent.
void printTriggerDefinitions (const lcio::LCEvent *)
A convenient print method to get trigger definitions and assignment.
int getTrgConfigurationMask ()
Return the configuration mask All trigger inputs which are active for a given configuration within a run <-> subsample of the principle mask.
int getPrincipleTriggerMask ()
Return the principle trigger mask basically the or of all trigger inputs which could be active for the given run.
TriggerBits getTriggerConfiguration () const
Return the Trigger Definitions Map (for those who need it)
TriggerBits getAndEnableBits ()
Return the and enable word.
TriggerBits getTriggerEvent () const
Get the event trigger bits.
TriggerBits getOutOfRangeTriggerBits () const
Get the trigger bits which fire simultaniously with the main word but which are not insided the fifo range.
const TriggerDefinitionMap_t & getTriggerDefinitionMap () const
const IntVec & getTriggerFifoContent () const
Return the Fifo Content.
unsigned int getUsedFifoDepth () const
Return the number of usable fifo words.
bool hasTriggerFifo () const
Return if the trigger fifo is not empty.
bool isTriggerFifoDepthGood ()
Return true if the trigger fifo is deep enough.
const int getTriggerFifoContMainWord ()
Return the content of the main word in the Fifo.
int getTriggerFifoContaWord (unsigned int theWord) const
Return a given word in the the Fifo Content.
int getMainWord () const
Return the main word itself i.e.
const unsigned int getSmearedTriggerMainWord ()
Return the trigger main word smeared by +-1.
bool isGenSWTriggerOn () const
Return the status of the general s/w trigger.
bool isIndSWTriggerOn () const
Is at least on one baord a s/w trigger configured.
bool isSWTriggerOn () const
Is there somewhere a software trigger?
bool isCalibrationOn () const
Return the status of the calibration chip.
unsigned int getNConfigurationChanges () const
Return the number of (Trigger) Configuration Changes.
unsigned int getNEventsWithoutTriggerEventData () const
Get the number of events with missing trigger event data.
TriggerHandlerCalice ()
The private constructor.
Public Member Functions inherited from CALICE::TriggerHandler
virtual ~TriggerHandler ()
Destructor.
virtual void setTrigger (LCEvent *)=0
This adds the trigger information to the event.
virtual bool isValidTrigger (const LCEvent *)=0
Trigger Validation.
Private Types
enum ETrgEventClass { kFeTrgEvent, kBeTrgEvent, kUnknown }
typedef std::vector< unsigned int > FrontEndList_t
Collection type which can hold sub detector ids per front end of a slot.
typedef std::vector
< FrontEndList_t > SlotList_t
Collection type which can hold front-end collections per crate slot.
typedef std::map< unsigned int,
Crate_t > CrateList_t
Collection of crates.
Private Member Functions
void TriggerConditionsListener ()
This method verifies the validity of the current trigger configuration mask Was used to manage trigger changes in older versions.
void CreateTriggerDefinitionMap (EVENT::LCCollection *TrAssCol)
This method creates the map of the trigger definition plus the so called principle trigger mask, the trigger bits which have well assigned signals.
void ExtractTriggerEnvironment (EVENT::LCCollection *confCol)
This method extracts the environmental setting of the trigger, the BeTrgConfigurationsData from a conditions data source.
void updateTriggerConfBits ()
Update the configuration trigger bits which will be attached to the event header.
void ExtractTriggerCheckConditions (EVENT::LCCollection *checkCol)
This method extracts the info on how to verify and get the trigger decision, i.e.
void feConfigurationChange (EVENT::LCCollection *feConfCol, unsigned int set_i)
Memorise new front-end configuration conditions dataa.
bool checkForCalibrationOn ()
Analyse the front-end configuration data and set calibration on flags accrodingly.
void readoutConfChange (EVENT::LCCollection *roConfCol)
Memorise readout configuration data.
void ExtractGenSoftTrigConfiguration (EVENT::LCCollection *)
This method checks for individual software triggers i.e.
bool checkForSoftwareTriggerOn ()
Analyse the readout configuration data and set the software trigger flags accordingly.
void PrepareTriggerEventData (const LCEvent *evt)
This method extracts the eventwise trigger data.
void moduleConnectionChange (EVENT::LCCollection *module_connection_col, unsigned int set_i)
listen for module connection changes and build a connection tree to find out about connected front-ends.
void printConnections ()
Print the module connections to the screen (debug).
Private Attributes
ConditionsChangeDelegator
< TriggerHandlerCalice > _triggerAssignment
The listener which will be called in case the trigger assignemnt changes.
ConditionsChangeDelegator
< TriggerHandlerCalice > _triggerConfChange
The listener which will be called in case the trigger configuration changes.
ConditionsChangeDelegator
< TriggerHandlerCalice > _triggerCheck
The listener which will be called in case the trigger check conditions change.
std::vector< LCCollection * > _feConfCol
std::vector
< CALICE::MultipleConditionsChangeDelegator
< TriggerHandlerCalice > > _feConfChange
std::vector< bool > _calibrationOnVec
Variables which contains the status of the calibration bit in the FeConfiguration Data.
bool _calibrationOn
Global calibration on set of calibration on is set for at least one sub detector.
ConditionsChangeDelegator
< TriggerHandlerCalice > _roConfChange
The listener which will be called in case the ReadOut Configuration Changes.
lcio::LCCollection * _roConfCol
points to the last readout configuration conditions data.
ConditionsChangeDelegator
< TriggerHandlerCalice > _trgroConfChange
The listener which will be called in case the TrgReadoutConfiguration Changes.
bool _swTriggerOnInd
Variable which contains the information whether a s/w trigger is configured at least in one board or not.
std::vector< unsigned int > _swTriggerOnVec
Soft trigger flags per sub detector.
bool _swTriggerOnGen
Variable which contains the information whether a s/w trigger is configured in the central trigger board.
int _main_word
The data members which contain the info about the words which are to be checked.
int _tolerance
int _word_up
int _word_down
TriggerDefinitionMap_t _trdefMap
The Trigger Definition map.
int _principleTriggerMask
The trigger mask as defined by the Trigger Definition map.
int _confTriggerMask
The trigger configuration as defined in the configuration data, CrcBeTrgConfiguration Data.
int _andEnable0
The And Enable word(0), only by this word we can recognize which Triggers are suppose to fire in case conincidences are setup.
int _genericTriggerMask
The generic mask.
std::map< std::string,
unsigned int > _knownTrigger
IntVec _theTriggerFifoCont
The famous fifo to verify the trigger quality.
lcio::LCTime _theTime
bool _isInitialized
Some check variables.
TriggerBits _event_triggerBits
Object which holds the event trigger(s)
TriggerBits _conf_triggerBits
Object which holds the configured trigger(s)
TriggerBits _andenable_triggerBits
Object which holds the trigger(s) enabled for coincidence.
TriggerBits _outOfRange_triggerBits
Object which holds the trigger(s) which would be expected outside of the fifo depth.
bool _triggerPollTimeout
variable which holds the result of the trigger polling
unsigned int _nConfigurationChanges
A counter of TriggerConfiguration Changes (suggested by Goetz)
unsigned int _lastConfigurationChange
CrateList_t _connections
std::vector< unsigned int > _nFrontEnds
Number of front-ends connected to one sub detector.
std::vector
< CALICE::MultipleConditionsChangeDelegator
< TriggerHandlerCalice > > _moduleConnectionChange
std::string _colNameTriggerEvent
Name of the trigger event collection.
unsigned int _errorCounter
unsigned int _noTriggerEvents
ETrgEventClass _trgEventClass
bool _verbose
int _this_trigger_main_word
The trigger main word of this event.
unsigned int _this_trigger_length
The width of the trigger enable pulse.
std::map< unsigned int,
unsigned int > _distanceToPreTrigger
std::map< unsigned int,
unsigned int > _distanceToPostTrigger
Detailed Description
Implementation of TriggerHandler base class for calice purposes Trigger conditions are read from a conditions data source or from the event information.
Database accesses and necessary event analysis are completely hidden from the user. The results are made availabe by access functions which can be used to update event parameters The triggerhandler can act as a singleton class and can in principle be plugged in at any point in the processors.
Author
R. Pschl DESY, major update by G.Gaycken (LLR) Aug. 2006
Date
May 20 2005
Definition at line 56 of file TriggerHandlerCalice.hh.
Member Typedef Documentation
typedef std::map<unsigned int, Crate_t > CALICE::TriggerHandlerCalice::CrateList_t private
Collection of crates.
Definition at line 612 of file TriggerHandlerCalice.hh.
typedef std::vector<unsigned int> CALICE::TriggerHandlerCalice::FrontEndList_t private
Collection type which can hold sub detector ids per front end of a slot.
Definition at line 564 of file TriggerHandlerCalice.hh.
typedef std::vector<FrontEndList_t> CALICE::TriggerHandlerCalice::SlotList_t private
Collection type which can hold front-end collections per crate slot.
Definition at line 565 of file TriggerHandlerCalice.hh.
Member Function Documentation
bool CALICE::TriggerHandlerCalice::checkForCalibrationOn () private
Analyse the front-end configuration data and set calibration on flags accrodingly.
Only connected front-ends are consdiered. The calibration flags are set per sub detector and a global flag is set if one of the calibration flag of one sub detector is set.
Definition at line 1414 of file TriggerHandlerCalice.cc.
References _calibrationOn, _calibrationOnVec, and _conf_triggerBits.
Referenced by feConfigurationChange(), and moduleConnectionChange().
bool CALICE::TriggerHandlerCalice::checkForSoftwareTriggerOn () private
Analyse the readout configuration data and set the software trigger flags accordingly.
If at least one front-end soft trigger or the back-end trigger is activated for one front-end which is connected to a sub-detector or one crate which contains front-ends which are conntected to a sub detector, then the soft trigger flag of the corresponding sub detector is set. If the soft trigger of one sub detector is set, then also the global soft trigger flag is set.
Definition at line 1515 of file TriggerHandlerCalice.cc.
References _nFrontEnds, _roConfCol, _swTriggerOnInd, _swTriggerOnVec, CALICE::ReadOutConfigurationBlock::getBeSoftTrigger(), and updateTriggerConfBits().
Referenced by moduleConnectionChange(), and readoutConfChange().
void CALICE::TriggerHandlerCalice::ExtractGenSoftTrigConfiguration (EVENT::LCCollection * trgroConfCol) private
This method checks for individual software triggers i.e.
on each board
Todo:
currently a software trigger is declared whenever a s/w trigger is enabled on one board this has to be individualized
Definition at line 1782 of file TriggerHandlerCalice.cc.
References _swTriggerOnGen, and CALICE::TrgReadoutConfigurationBlock::getBeTrgSoftTrg().
void CALICE::TriggerHandlerCalice::ExtractTriggerCheckConditions (EVENT::LCCollection * checkCol) private
This method extracts the info on how to verify and get the trigger decision, i.e.
which words have to be checked in the fifo to get the trigger decision and which words have to be scanned in the fifo to validate the trigger decision
Definition at line 1910 of file TriggerHandlerCalice.cc.
References _main_word.
TriggerBits CALICE::TriggerHandlerCalice::getAndEnableBits () inline
Return the and enable word.
Todo:
in priniple there are four enable words and in prenicple we need the enable word to a trigger bit in the configuration mask
Definition at line 187 of file TriggerHandlerCalice.hh.
References _andenable_triggerBits.
int CALICE::TriggerHandlerCalice::getMainWord () const inline
Return the main word itself i.e.
the word in fifo in which we look mainly for the event trigger
Definition at line 305 of file TriggerHandlerCalice.hh.
References _main_word.
unsigned int CALICE::TriggerHandlerCalice::getNEventsWithoutTriggerEventData () const inline
Get the number of events with missing trigger event data.
Definition at line 345 of file TriggerHandlerCalice.hh.
const std::map<unsigned int, unsigned int>& CALICE::TriggerHandlerCalice::getPostTriggerHistory () const inline
Get a list trigger and their positions wrt.
to the main word which fired after the main word (future).
Definition at line 101 of file TriggerHandlerCalice.hh.
const std::map<unsigned int, unsigned int>& CALICE::TriggerHandlerCalice::getPreTriggerHistory () const inline
Get a list trigger and their positions wrt.
to the main word which fired before the main word (past).
Definition at line 95 of file TriggerHandlerCalice.hh.
TriggerBits CALICE::TriggerHandlerCalice::getTriggerConfiguration () const inline
Return the Trigger Definitions Map (for those who need it)
Get the trigger configuration.
Definition at line 180 of file TriggerHandlerCalice.hh.
References _conf_triggerBits.
unsigned int CALICE::TriggerHandlerCalice::getUsedFifoDepth () const inline
Return the number of usable fifo words.
The last two words of the fifo are used differently. So, they should not be used in history scans.
Definition at line 263 of file TriggerHandlerCalice.hh.
References _theTriggerFifoCont.
Referenced by getSmearedTriggerMainWord(), searchTriggerHistory(), searchTriggerMainWord(), and setTrigger().
void CALICE::TriggerHandlerCalice::init (const string & col_trigger_assignment, const string & col_trigger_check, const string & colBeTrgConf, const string & col_name_readout_conf, const string & col_name_trgro_conf, const lcio::StringVec & col_name_fe_conf, const lcio::StringVec & col_name_module_connection)
Another initialization method.
Parameters
col_trigger_assignment name of the trigger assignment conditions data.
col_trigger_check name of the trigger check conditions data.
colBeTrgConf name of the conditions data of the back-end trigger configuration.
col_name_readout_conf name of the conditions data of the readout configuration.
col_name_trgro_conf name of the conditions data of the trigger readout configuration.
col_name_fe_conf vector of names of the conditions data of the front-end configuration.
col_name_module_connection vector of names of the conditions data which describes the connections. between detector modules and front-ends (needed to find out about calibration mode).
Definition at line 138 of file TriggerHandlerCalice.cc.
References _calibrationOnVec, _isInitialized, _nFrontEnds, _roConfChange, _swTriggerOnVec, _trgroConfChange, _triggerAssignment, _triggerCheck, _triggerConfChange, feConfigurationChange(), and moduleConnectionChange().
bool CALICE::TriggerHandlerCalice::isCalibrationOn () const inline
Return the status of the calibration chip.
Definition at line 338 of file TriggerHandlerCalice.hh.
References _calibrationOn.
Referenced by searchTriggerHistory().
bool CALICE::TriggerHandlerCalice::isTriggerFifoDepthGood () inline
Return true if the trigger fifo is deep enough.
Todo:
what is the required fifo depth ?
Definition at line 272 of file TriggerHandlerCalice.hh.
References _main_word, and _theTriggerFifoCont.
bool CALICE::TriggerHandlerCalice::isValidTrigger (const lcio::LCEvent *) virtual
Trigger Validation.
It checks whether the event was triggered properly. Note, that this is fairly independent of the trigger requested by the user in the method above. currently it does nothing
Definition at line 488 of file TriggerHandlerCalice.cc.
References _isInitialized, and init().
void CALICE::TriggerHandlerCalice::printConnections () private
Print the module connections to the screen (debug).
This method is indented for debug purposes only.
Definition at line 1744 of file TriggerHandlerCalice.cc.
Referenced by moduleConnectionChange().
void CALICE::TriggerHandlerCalice::readoutConfChange (EVENT::LCCollection * roConfCol) private
Memorise readout configuration data.
The readout configuration data is needed to identify software triggers.
Definition at line 1496 of file TriggerHandlerCalice.cc.
References _roConfCol, and checkForSoftwareTriggerOn().
void CALICE::TriggerHandlerCalice::searchTriggerHistory ()
Search the trigger history for triggers firing at and before the main word.
This will fill a map which contains for each position in the past history where a trigger was firing the trigger bits of all firing triggers. Also the event trigger bits will be set.
Definition at line 510 of file TriggerHandlerCalice.cc.
References _conf_triggerBits, _event_triggerBits, _genericTriggerMask, _outOfRange_triggerBits, _principleTriggerMask, _theTriggerFifoCont, _this_trigger_main_word, _trdefMap, _triggerPollTimeout, getPrincipleTriggerMask(), getSmearedTriggerMainWord(), getTrgConfigurationMask(), getUsedFifoDepth(), isCalibrationOn(), isGenSWTriggerOn(), and isSWTriggerOn().
unsigned int CALICE::TriggerHandlerCalice::searchTriggerMainWord ()
Search for the trigger main word.
The search is conducted starting at the main words in both time directions. First in future direction then past. The trigger handler has to be prepared first.
See Also
setTrigger
Definition at line 327 of file TriggerHandlerCalice.cc.
References _confTriggerMask, _genericTriggerMask, _main_word, _theTriggerFifoCont, _this_trigger_length, _this_trigger_main_word, getUsedFifoDepth(), and CALICE::to_binary_bitops().
void CALICE::TriggerHandlerCalice::setTrigger (lcio::LCEvent *) virtual
returns pointer to only instance of the TriggerHandlerCalice
This adds the trigger information to the event (well it did in older versions, now it only calls the method to get the fifo content)
Definition at line 276 of file TriggerHandlerCalice.cc.
References _event_triggerBits, _isInitialized, _main_word, _nConfigurationChanges, _trdefMap, getUsedFifoDepth(), init(), and PrepareTriggerEventData().
void CALICE::TriggerHandlerCalice::updateTriggerConfBits () private
Update the configuration trigger bits which will be attached to the event header.
This method should be called after trigger configuration changes, trigger assignment changes, readout configuration changes (soft trigger), front-end configuration changes (calib).
See Also
Definition at line 1346 of file TriggerHandlerCalice.cc.
References _andEnable0, _andenable_triggerBits, _calibrationOn, _conf_triggerBits, _confTriggerMask, _swTriggerOnInd, and _trdefMap.
Referenced by checkForSoftwareTriggerOn(), CreateTriggerDefinitionMap(), and ExtractTriggerEnvironment().
Field Documentation
bool CALICE::TriggerHandlerCalice::_calibrationOn private
Global calibration on set of calibration on is set for at least one sub detector.
Definition at line 430 of file TriggerHandlerCalice.hh.
Referenced by checkForCalibrationOn(), isCalibrationOn(), printTriggerDefinitions(), and updateTriggerConfBits().
std::vector<bool> CALICE::TriggerHandlerCalice::_calibrationOnVec private
Variables which contains the status of the calibration bit in the FeConfiguration Data.
calibration on flags per sub detector.
Definition at line 429 of file TriggerHandlerCalice.hh.
Referenced by checkForCalibrationOn(), init(), and printTriggerDefinitions().
std::string CALICE::TriggerHandlerCalice::_colNameTriggerEvent private
Name of the trigger event collection.
Definition at line 627 of file TriggerHandlerCalice.hh.
Referenced by PrepareTriggerEventData(), setColNameTriggerEvent(), and setTriggerEventClass().
int CALICE::TriggerHandlerCalice::_genericTriggerMask private
The generic mask.
We need this since one bit comes always along with the trigger information in an event which is not present in the configuration data
Definition at line 518 of file TriggerHandlerCalice.hh.
Referenced by CreateTriggerDefinitionMap(), printTriggerDefinitions(), searchTriggerHistory(), and searchTriggerMainWord().
std::vector<unsigned int> CALICE::TriggerHandlerCalice::_nFrontEnds private
Number of front-ends connected to one sub detector.
Definition at line 615 of file TriggerHandlerCalice.hh.
Referenced by checkForSoftwareTriggerOn(), init(), moduleConnectionChange(), and printTriggerDefinitions().
TriggerBits CALICE::TriggerHandlerCalice::_outOfRange_triggerBits private
Object which holds the trigger(s) which would be expected outside of the fifo depth.
Definition at line 554 of file TriggerHandlerCalice.hh.
Referenced by getOutOfRangeTriggerBits(), and searchTriggerHistory().
ConditionsChangeDelegator<TriggerHandlerCalice> CALICE::TriggerHandlerCalice::_roConfChange private
The listener which will be called in case the ReadOut Configuration Changes.
Like that we can indentify software triggers.
Definition at line 442 of file TriggerHandlerCalice.hh.
Referenced by init().
lcio::LCCollection* CALICE::TriggerHandlerCalice::_roConfCol private
points to the last readout configuration conditions data.
Definition at line 444 of file TriggerHandlerCalice.hh.
Referenced by checkForSoftwareTriggerOn(), and readoutConfChange().
std::vector< unsigned int > CALICE::TriggerHandlerCalice::_swTriggerOnVec private
Soft trigger flags per sub detector.
Definition at line 477 of file TriggerHandlerCalice.hh.
Referenced by checkForSoftwareTriggerOn(), init(), and printTriggerDefinitions().
unsigned int CALICE::TriggerHandlerCalice::_this_trigger_length private
The width of the trigger enable pulse.
Definition at line 637 of file TriggerHandlerCalice.hh.
Referenced by searchTriggerMainWord().
int CALICE::TriggerHandlerCalice::_this_trigger_main_word private
The trigger main word of this event.
Definition at line 636 of file TriggerHandlerCalice.hh.
Referenced by getSmearedTriggerMainWord(), getTriggerFifoContMainWord(), searchTriggerHistory(), and searchTriggerMainWord().
ConditionsChangeDelegator<TriggerHandlerCalice> CALICE::TriggerHandlerCalice::_trgroConfChange private
The listener which will be called in case the TrgReadoutConfiguration Changes.
Like that we can indentify software triggers.
Definition at line 460 of file TriggerHandlerCalice.hh.
Referenced by init().
The documentation for this class was generated from the following files:
TriggerHandlerCalice.hh
TriggerHandlerCalice.cc