CALICE_USERLIB: CALICE::TcmtConnection Class Reference
CALICE::TcmtConnection Class Reference
Defines the electronic connection of a TCMT strip.
#include <TcmtConnection.hh>
Public Member Functions
TcmtConnection (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
TcmtConnection & setCrate (int crate_number)
int getCrate () const
TcmtConnection & setElecID (int elecID)
int getElecID () const
TcmtConnection & setFastID (int fastID)
int getFastID () const
TcmtConnection & setSlot (int slot)
int getSlot () const
TcmtConnection & setFrontEnd (int fe)
int getFrontEnd () const
TcmtConnection & setChip (int chip)
int getChip () const
TcmtConnection & setChannel (int channel)
int getChannel () const
TcmtConnection & setIndexOfLowerLeftCell (unsigned int index_offset)
Set the cell index (Mokka specification) of the cell in the lower left corner.
int getIndexOfLowerLeftCell () const
Get the cell index (Mokka specification) of the cell in the lower left corner.
TcmtConnection & setModuleType (unsigned char type)
Set the module type.
unsigned char getModuleType () const
Get the module type.
TcmtConnection & setModuleID (int module_id)
Set the serial number of a module.
int getModuleID () const
Get the serial number of a module.
TcmtConnection & setStripID (int strip)
Set the strip ID inside module.
int getStripID () const
Get the strip ID inside module.
int getConnectorType () const
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Defines the electronic connection of a TCMT strip.
A module location defined by ModuleLocation may be connected to a connector of a CERC board. The module location is identified by the index offset.
Definition at line 43 of file TcmtConnection.hh.
Member Function Documentation
int CALICE::TcmtConnection::getIndexOfLowerLeftCell () const inline
Get the cell index (Mokka specification) of the cell in the lower left corner.
This index uniquely defines the module location.
Definition at line 132 of file TcmtConnection.hh.
Referenced by CALICE::MappingAndAlignment::rebuildTcmtConnectionTree().
int CALICE::TcmtConnection::getModuleID () const inline
Get the serial number of a module.
See Also
setModuleID
Definition at line 178 of file TcmtConnection.hh.
Referenced by CALICE::MappingAndAlignment::rebuildTcmtConnectionTree().
unsigned char CALICE::TcmtConnection::getModuleType () const inline
Get the module type.
The module type is not needed but this redundant information allows to verify the configuration correctness.
Todo:
remove this redundant information?
Definition at line 157 of file TcmtConnection.hh.
Referenced by CALICE::MappingAndAlignment::rebuildTcmtConnectionTree().
int CALICE::TcmtConnection::getStripID () const inline
Get the strip ID inside module.
See Also
setStripID
Definition at line 194 of file TcmtConnection.hh.
TcmtConnection& CALICE::TcmtConnection::setIndexOfLowerLeftCell (unsigned int index_offset) inline
Set the cell index (Mokka specification) of the cell in the lower left corner.
The index offset is used to uniquely define the module location.
Definition at line 123 of file TcmtConnection.hh.
TcmtConnection& CALICE::TcmtConnection::setModuleID (int module_id) inline
Set the serial number of a module.
This number together with the module type is used to uniquely identify a module. This unique identification is for example needed to get the correct calibration constants.
Definition at line 167 of file TcmtConnection.hh.
TcmtConnection& CALICE::TcmtConnection::setModuleType (unsigned char type) inline
Set the module type.
The module type is not needed but this redundant information allows to verify the configuration correctness.
Todo:
remove this redundant information?
Definition at line 146 of file TcmtConnection.hh.
TcmtConnection& CALICE::TcmtConnection::setStripID (int strip) inline
Set the strip ID inside module.
Strip ID runs from 0 to 19.
Definition at line 185 of file TcmtConnection.hh.
The documentation for this class was generated from the following file:
TcmtConnection.hh