CALICE_USERLIB: CALICE::AhcMedianFilterTempProvider Class Reference
CALICE::AhcMedianFilterTempProvider Class Reference
This is a very simple temperature provider for the ahcal.
#include <AhcMedianFilterTempProvider.hh>
Public Member Functions
AhcMedianFilterTempProvider (AhcMapper const *mapper)
virtual float getCellTemp (int module, int chip, int chan)
Returns the temperature for the cell in the specified module connected to the given chip and channel.
virtual float getCellTempError (int module, int chip, int chan)
Returns the error on the temperature for the cell in the specified module connected to the given chip and channel.
virtual float getAvgTemp ()
Returns the average calorimeter temperature.
virtual float getAvgModuleTemp (unsigned module)
Returns the average module temperature.
float getSensorTemp (int module, int sensor)
Return the temperature for the specified module and sensor.
Public Member Functions inherited from CALICE::AhcTempProvider
AhcTempProvider ()
Default constructor.
virtual ~AhcTempProvider ()
Default destructor.
virtual void setAhcSroModBlocks (lcio::LCCollection *col)
Set the collection of AhcSlowReadoutModBlock objects to extract the temperature data from.
virtual void setCalibrations (lcio::LCCollection *col)
Set the collection of SimpleValue objects to use for the offset calibrations of the temperature sensors.
virtual void setSanityRange (float min, float max)
Define a sanity range of temperature values that make sense.
Protected Member Functions
virtual void applyCorrection ()
This function applies the correction to the internal 'cache' for the temperature values from the five sensors.
bool isBadValue (float t)
Returns true if argument value is outside the sanity range.
Protected Member Functions inherited from CALICE::AhcTempProvider
virtual void updateCache ()
This function updates the internal 'cache' for the temperature values from the five sensors and applies the calibration offsets, if available.
Private Member Functions
int getSensor (int chip, int chan)
Returns the closest sensor to cell connected to chip, chan according to DESY-THESIS-2008-050.
double median (float a[], int n)
Private Attributes
AhcMapper const * _mapper
float _caloMeanTemp
float _caloMeanTempRMS
int _caloMeanCount
std::vector< float > _moduleMeanTemp
std::vector< float > _moduleMeanTempRMS
std::vector< int > _moduleMeanCount
Additional Inherited Members
Static Public Attributes inherited from CALICE::AhcTempProvider
static const unsigned N_MODULES = 38
static const unsigned N_SENSORS = 5
Protected Attributes inherited from CALICE::AhcTempProvider
bool newSroModCol
If true this indicates that setSroModBlocks() was called and a new collection of AhcSroModBlock objects was set.
bool newCalibCol
If true this indicates that setCalibrations() was called and a new collection of calibrations was set.
bool newSanityRange
If true this indicates that setSanityRange() was called and a new sanity range was set.
std::vector< std::vector< float > > sensorTemp
This is a 'cache' for the values of the temperature sensors after calibration and and correction.
std::vector< std::vector< float > > sensorTempError
This is a 'cache' for the errors on the values of the temperature sensors after calibration and and correction.
std::vector< std::vector< float > > sensorCalib
This is a 'cache' for the calibration offsets for the temperature sensors.
std::vector< std::vector< float > > sensorCalibError
This is a 'cache' for the errors on the calibration offsets for the temperature sensors.
std::vector< std::vector< int > > sensorCalibStatus
Vector to save the status of the calibration offsets.
float _sanityMin
Lower limit of the sanity range.
float _sanityMax
Upper limit of the sanity range.
lcio::LCCollection * _sroModCol
A pointer to the LCCollection containing the AhcSlowReadOut objects.
lcio::LCCollection * _calibCol
A pointer to the LCCollection containing the calibration offsets objects.
Detailed Description
This is a very simple temperature provider for the ahcal.
What it does:
the calibration set is applied
if a temperature sensor gives a value outside the defined sanity range the value is replaced by the average of the four sensors in that module
for each cell the temperature value from the 'closest' sensor, according to the table 3.1, DESY-THESIS-2008-050 is returned
Also see the documentation for the several functions for more detailed information. This new temperature provider with median filter created: Date: August 2013 Author: Sergey Morozov The temperature provider is based on the AhcSimpleTempProvider with some updates:
all temperature sensors are set to the layer average temperature.
the median filter to layer-by-layer profile has been introduced. This will help to remove the out-layers with wrong temperature measurements in some layers of AHCAL. Note: you need smooth (median filtered for example) MIP and gain temperature profiles in the MIP and gain calibrations to use this tempetarure provider for data reconstruction!
Definition at line 38 of file AhcMedianFilterTempProvider.hh.
Member Function Documentation
void CALICE::AhcMedianFilterTempProvider::applyCorrection () protected virtual
This function applies the correction to the internal 'cache' for the temperature values from the five sensors.
It should be called everytime a new collection of temperatures or calibrations have been at set or the sanity range has been changed, i.e. if one of newSroModCol, newCalibCol or newSanityRange is true. This is done in getCellTemp() and getCellTempError().
Definition at line 97 of file AhcMedianFilterTempProvider.cc.
References CALICE::AhcTempProvider::_sroModCol, CALICE::AhcMapper::getK(), CALICE::ScintCaloSlowReadoutModBlock::getModuleNumber(), isBadValue(), CALICE::AhcTempProvider::newCalibCol, CALICE::AhcTempProvider::newSanityRange, CALICE::AhcTempProvider::newSroModCol, CALICE::AhcTempProvider::sensorTemp, CALICE::AhcTempProvider::sensorTempError, and CALICE::AhcTempProvider::updateCache().
Referenced by getAvgModuleTemp(), getAvgTemp(), getCellTemp(), getCellTempError(), and getSensorTemp().
float CALICE::AhcMedianFilterTempProvider::getCellTemp (int module, int chip, int chan) virtual
Returns the temperature for the cell in the specified module connected to the given chip and channel.
For each cell the temperature value from the 'closest' sensor, according to the table 3.1, DESY-THESIS-2008-050 is returned.
Implements CALICE::AhcTempProvider.
Definition at line 19 of file AhcMedianFilterTempProvider.cc.
References applyCorrection(), getSensor(), CALICE::AhcTempProvider::newCalibCol, CALICE::AhcTempProvider::newSanityRange, CALICE::AhcTempProvider::newSroModCol, and CALICE::AhcTempProvider::sensorTemp.
The documentation for this class was generated from the following files:
AhcMedianFilterTempProvider.hh
AhcMedianFilterTempProvider.cc