CALICE_USERLIB: CALICE::CalibrationWriter Class Reference
CALICE::CalibrationWriter Class Reference
Class which handles the module wise storage of conditions data and the access to the lccd framework (i.e.
#include <CalibrationWriter.hh>
Public Member Functions
CalibrationWriter (std::string dbinit, std::string folder, std::string description)
Constructor has parameters:
void putCalibration (unsigned moduleID, unsigned cellKey, LCHcalCalibrationObject *Calibration)
fills the "memory" with a calibration object for a certain moduleID and cellKey
void putCalibration (unsigned moduleID, unsigned chip, unsigned channel, LCHcalCalibrationObject *Calibration)
fills the "memory" with a calibration object for a certain moduleID and cellKey
void flushCalibration (lccd::LCCDTimeStamp from, lccd::LCCDTimeStamp till, bool _writeFile) const
writes the "memory" to the given data base and the given folder, extraction time range is set equal to the validity time range
void flushCalibration (lccd::LCCDTimeStamp from, lccd::LCCDTimeStamp till, lccd::LCCDTimeStamp extractionTime, bool _writeFile) const
writes the "memory" to the given data base and the given folder
void flushCalibration (lccd::LCCDTimeStamp from, lccd::LCCDTimeStamp till, lccd::LCCDTimeStamp extractionFrom, lccd::LCCDTimeStamp extractionTill, bool _writeFile) const
writes the "memory" to the given data base and the given folder
Protected Attributes
std::string _dbinit
access string for the mysql database
std::string _folder
folder path in the data base where the calibration collections should be stored
std::string _description
description text describing the type of calibration provided by the stored constants
Private Attributes
CalibrationWriteMap _writeMap
Detailed Description
Class which handles the module wise storage of conditions data and the access to the lccd framework (i.e.
to the data base)
Author
S.Schmidt DESY
Date
Jun 16 2006
Definition at line 30 of file CalibrationWriter.hh.
Constructor & Destructor Documentation
CALICE::CalibrationWriter::CalibrationWriter (std::string dbinit, std::string folder, std::string description)
Constructor has parameters:
Parameters
dbinit access string for the mysql database
folder path in the data base where the calibration collections should be stored
description text describing the type of calibration provided by the stored constants
Definition at line 12 of file CalibrationWriter.cc.
Member Function Documentation
void CALICE::CalibrationWriter::flushCalibration (lccd::LCCDTimeStamp from, lccd::LCCDTimeStamp till, bool _writeFile) const
writes the "memory" to the given data base and the given folder, extraction time range is set equal to the validity time range
Parameters
from start timestamp of the validity range of the calibration
till end timestamp of the validity range of the calibration
_writeFile write lcio file after filling the data base
Definition at line 58 of file CalibrationWriter.cc.
Referenced by flushCalibration().
void CALICE::CalibrationWriter::flushCalibration (lccd::LCCDTimeStamp from, lccd::LCCDTimeStamp till, lccd::LCCDTimeStamp extractionTime, bool _writeFile) const
writes the "memory" to the given data base and the given folder
Parameters
from start timestamp of the validity range of the calibration
till end timestamp of the validity range of the calibration
extractionTime timestamp describing the time range of the sample used to gather the calibration
_writeFile write lcio file after filling the data base
Definition at line 64 of file CalibrationWriter.cc.
References flushCalibration().
void CALICE::CalibrationWriter::flushCalibration (lccd::LCCDTimeStamp from, lccd::LCCDTimeStamp till, lccd::LCCDTimeStamp extractionFrom, lccd::LCCDTimeStamp extractionTill, bool _writeFile) const
writes the "memory" to the given data base and the given folder
Parameters
from start timestamp of the validity range of the calibration
till stop timestamp of the validity range of the calibration
extractionFrom start timestamp of the sample used to gather the calibration
extractionTill end timestamp of the sample used to gather the calibration
_writeFile write lcio file after filling the data base
Definition at line 70 of file CalibrationWriter.cc.
References _dbinit, _description, and _folder.
void CALICE::CalibrationWriter::putCalibration (unsigned moduleID, unsigned cellKey, LCHcalCalibrationObject * Calibration)
fills the "memory" with a calibration object for a certain moduleID and cellKey
Parameters
moduleID ID of the module "printed" on it
cellKey number describing a certain cell of a module, calculated from the chip and the channel number
Calibration object used to store the calibration data in the data base
Definition at line 39 of file CalibrationWriter.cc.
Referenced by putCalibration().
void CALICE::CalibrationWriter::putCalibration (unsigned moduleID, unsigned chip, unsigned channel, LCHcalCalibrationObject * Calibration)
fills the "memory" with a calibration object for a certain moduleID and cellKey
Parameters
moduleID ID of the module "printed" on it
chip chip number of the cell
channel channel number of the cell
Calibration object used to store the calibration data in the data base
Definition at line 32 of file CalibrationWriter.cc.
References putCalibration().
The documentation for this class was generated from the following files:
CalibrationWriter.hh
CalibrationWriter.cc