CALICE_USERLIB: CALICE::CellQuality Class Reference
CALICE::CellQuality Class Reference
LCIO contions data class to describe the cell quality.
#include <CellQuality.hh>
Public Member Functions
CellQuality (const int id, const int status=0)
Initialise the CellQuality with the CellID.
CellQuality (EVENT::LCObject *)
const int getCellID () const
Get the cell ID.
const int getStatus () const
Get the status.
bool isDead () const
Check if the cell has been marked as dead.
bool isNoisy () const
Check if the cell has been marked as noisy.
void setDead (bool dead=true)
Set the dead flag. By using setDead(false) you can unset the dead status.
void setNoisy (bool noisy=true)
Set the noisy flag. By using setNoisy(false) you can unset the noisy status.
virtual const std::string getTypeName () const
virtual const std::string getDataDescription () const
Static Protected Attributes
static const int _dead = 0x1
the dead bit: 0x1
static const int _noisy = 0x2
the noisy bit: 0x2
Private Member Functions
void setStatus (int status)
The setting of the status is private.
Detailed Description
LCIO contions data class to describe the cell quality.
The cell can be dead or noisy (or both, for instance if a cell is noisy and then dies during a run period).
Note: Internally the status is treated as a bit pattern, which allows setting several flags simulaneously and can easily be extended. Thanks to the user interface the user never has to fiddle around with the bits. The definition is protected inside the class and queried with isDead() or isNoisy().
Author
Niels Meyer, Desy
Martin Killenberg, CERN
Definition at line 23 of file CellQuality.hh.
Constructor & Destructor Documentation
CALICE::CellQuality::CellQuality (const int id, const int status = 0)
Initialise the CellQuality with the CellID.
When the status is already know it can also be given to the constructor (optional).
Definition at line 11 of file CellQuality.cc.
References setStatus().
Member Function Documentation
void CALICE::CellQuality::setStatus (int status) private
The setting of the status is private.
It is only allowed using the conctructor or the set() functions.
Definition at line 19 of file CellQuality.cc.
Referenced by CellQuality(), setDead(), and setNoisy().
The documentation for this class was generated from the following files:
CellQuality.hh
CellQuality.cc