CALICE_USERLIB: FeStatListBase_t Class Reference
FeStatListBase_t Class Reference
Container class which can store statistics objects for all existing front-ends.
#include <FeStatList_t.hh>
Public Member Functions
void show (const char *label)
Print statistics about all front-ends.
Protected Types
typedef StatObj_t * StatObjPtr
Protected Member Functions
StatObjPtr & getStat (unsigned int board_id)
Get the statistics object for the given board id.
Private Attributes
std::map< unsigned int,
std::vector< std::vector
< StatObjPtr > > > _feInfo
Detailed Description
Container class which can store statistics objects for all existing front-ends.
The statistics collected from all front-ends can be printed to an output stream. This class should not be used directly but the template FeStatList_t which gives You type safety.
Definition at line 59 of file FeStatList_t.hh.
Member Function Documentation
StatObjPtr& FeStatListBase_t::getStat (unsigned int board_id) inline protected
Get the statistics object for the given board id.
Parameters
board_id id which tells the crate, slot and front-end. This method should not be used directly but the template FeStatList_t::getStat
Definition at line 86 of file FeStatList_t.hh.
References CALICE::BoardID::getBoardComponentNumber(), CALICE::BoardID::getCrateID(), and CALICE::BoardID::getSlotID().
Referenced by FeStatList_t< T_StatObj_t >::getStat().
void FeStatListBase_t::show (const char * label)
Print statistics about all front-ends.
Parameters
label text to be printed as a header line. The output depends on the statistics objects used. NOTE: This method will call the method StatObj_t::finish i.e. the objects should not be changed afterwords otherwise the result will rather undefined.
Definition at line 24 of file FeStatList_t.cc.
The documentation for this class was generated from the following files:
FeStatList_t.hh
FeStatList_t.cc