CALICE_USERLIB: CALICE::SceSlowReadoutModBlock Class Reference
CALICE::SceSlowReadoutModBlock Class Reference
Interface Class to access the SceSlowReadout Data Here we handle ahc voltages, temperatures et al.
#include <SceSlowReadoutModBlock.hh>
Public Member Functions
SceSlowReadoutModBlock ()
Constructor.
SceSlowReadoutModBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
std::vector< double > & getHbabCurrents ()
Retrieve the hbab Currents.
void print (std::ostream &)
convenient print method
virtual const std::string getTypeName () const
Return the type of the class.
virtual const std::string getDataDescription () const
Return a brief description of the data members.
Public Member Functions inherited from CALICE::ScintCaloSlowReadoutModBlock
ScintCaloSlowReadoutModBlock ()
Constructor.
ScintCaloSlowReadoutModBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
ScintCaloSlowReadoutModBlock & setModuleNumber (int modnumber)
Store the module number.
int getModuleNumber () const
Retrieve the module number.
ScintCaloSlowReadoutModBlock & setTimeStamp (struct tm *timestamp)
Sets the time stamp We store Year, Month, Day and Hour, Minute, Second We store UTC!!!!
LCTime getTimeStamp ()
returns the start stamp
ScintCaloSlowReadoutModBlock & setLedSetting (int ledsetting)
Store the LED setting.
int getLedSetting () const
Retrieve the LED setting.
ScintCaloSlowReadoutModBlock & setCmbWidth (int cmbwidth)
Store the CMB width.
int getCmbWidth () const
Retrieve the CMB width.
ScintCaloSlowReadoutModBlock & setCmbHeight (int cmbheight)
Store the CMB height.
int getCmbHeight () const
Retrieve the CMB height.
std::vector< double > & getCmbTemperatures ()
Retrieve the cmb temperatures.
std::vector< double > & getCmbVoltages ()
Retrieve the cmb voltages.
std::vector< double > & getHbabVoltages ()
Retrieve the hbab voltages.
void setDblArrays (const ScintCaloSlowMeasuresDblMap_t &)
These methods obtain the vectors with the measured values Mainly to store large arrays of a given datatype but in principle this can be extended to every entry in the interface class.
void setIntArrays (const ScintCaloSlowMeasuresIntMap_t &)
void setFloatArrays (const ScintCaloSlowMeasuresFloatMap_t &)
void print (std::ostream &)
convenient print method
Public Member Functions inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImplExt ()
Default c'tor.
LCGenericObjectImplExt (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCGenericObjectImplExt ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Private Member Functions
void setTypes ()
This method defines the (general) types of the measured values A type not present here will not be handled!!!
Private Attributes
std::vector< double > _hbabCurrents
The output vectors.
Additional Inherited Members
Protected Types inherited from CALICE::ScintCaloSlowReadoutModBlock
typedef std::map< string,
std::pair< int, std::vector
< double > * > > ScintCaloSroTypesDblMap_t
Relation between the datatype its position among the tuple of double vals and the vector the data are readinto.
typedef std::map< string,
std::pair< int, std::vector
< int > * > > ScintCaloSroTypesIntMap_t
typedef std::map< string,
std::pair< int, std::vector
< float > * > > ScintCaloSroTypesFloatMap_t
Protected Member Functions inherited from CALICE::ScintCaloSlowReadoutModBlock
void prepareOutputVecs ()
A method which prepares the output vectors.
Protected Attributes inherited from CALICE::ScintCaloSlowReadoutModBlock
ScintCaloSroTypesDblMap_t _theDblTypes
The vector which contains the types and to the position and values of the types doubles.
ScintCaloSroTypesIntMap_t _theIntTypes
ScintCaloSroTypesFloatMap_t _theFloatTypes
std::vector< double > _cmbTemperatures
The output vectors which are common to all data types cmb Temperatures.
std::vector< double > _cmbVoltages
cmb Voltages
std::vector< double > _hbabVoltages
hbab voltages
unsigned _startOfDoubles
Variables to indicate the start of the actual data.
unsigned _startOfFloats
unsigned _startOfInts
Protected Attributes inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Interface Class to access the SceSlowReadout Data Here we handle ahc voltages, temperatures et al.
when filling the class the string identifying the measured values has to be given first, a warning is issued if no identifier is given for a given datatype. On the other hand this concerns just the filler of the class, i.e. the conversion where it is done once for all. See the print method at the end of the class for the meaning of the fields (as of 31/7/06) Use the interface methods to retrieve the data fields
Author
: Roman Pöschl LAL/Orsay
Date
Aug 2006
Definition at line 55 of file SceSlowReadoutModBlock.hh.
Member Function Documentation
void CALICE::SceSlowReadoutModBlock::print (std::ostream & os)
convenient print method
Convenient print method.
Definition at line 32 of file SceSlowReadoutModBlock.cc.
References CALICE::ScintCaloSlowReadoutModBlock::getCmbHeight(), CALICE::ScintCaloSlowReadoutModBlock::getCmbTemperatures(), CALICE::ScintCaloSlowReadoutModBlock::getCmbVoltages(), CALICE::ScintCaloSlowReadoutModBlock::getCmbWidth(), getHbabCurrents(), CALICE::ScintCaloSlowReadoutModBlock::getHbabVoltages(), CALICE::ScintCaloSlowReadoutModBlock::getLedSetting(), CALICE::ScintCaloSlowReadoutModBlock::getModuleNumber(), CALICE::ScintCaloSlowReadoutModBlock::getTimeStamp(), CALICE::ScintCaloSlowReadoutModBlock::prepareOutputVecs(), and CALICE::to_binary_bitops().
Field Documentation
std::vector<double> CALICE::SceSlowReadoutModBlock::_hbabCurrents private
The output vectors.
hbab temperatures
Definition at line 114 of file SceSlowReadoutModBlock.hh.
Referenced by setTypes().
The documentation for this class was generated from the following files:
SceSlowReadoutModBlock.hh
SceSlowReadoutModBlock.cc