CALICE_USERLIB: CALICE::BmlSlowRunDataBlock Class Reference
CALICE::BmlSlowRunDataBlock Class Reference
Interface Class to access the BmlSlowRun Data Here we handle ahc voltages, temperatures et al.
#include <BmlSlowRunDataBlock.hh>
Public Member Functions
BmlSlowRunDataBlock ()
Constructor.
BmlSlowRunDataBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
BmlSlowRunDataBlock & setAbsorberPosition (double abspos)
Store the aborber position device in cern h6b beamline to purify beam, ie.
double getAbsorberPosition () const
Retrieve the absorber position.
BmlSlowRunDataBlock & setTimeStamp (struct tm *timestamp)
Sets the time stamp We store Year, Month, Day and Hour, Minute, Second We store UTC!!!!
LCTime getTimeStamp () const
returns the start stamp
LCTime getTimeStampBml ()
Implementation of the method to obtain the timestamp as given by the beamline operators here identical to the only timestamp which was stored.
LCTime getTimeStampDaq ()
Implementation of the method to obtain the timestamp as given by the calice daq Here 0 as no timestamp has been stored.
BmlSlowRunDataBlock & setT4Position (double t4pos)
Store the t4 position device in cern h6b beamline to produce desired particles out of the secondary beam.
double getT4Position () const
Retrieve the absorber position.
BmlSlowRunDataBlock & setTargetPosition (double targetpos)
Store the target position primary target hit by ythe SPS beam.
double getTargetPosition () const
Retrieve the target position.
const std::vector< double > & getSextapoleCurrents () const
Retrieve the sextapole currents The values are stored in the sequence 'Measurement, Reference e.g.
const std::vector< double > & getBendCurrents () const
Retrieve the bending magnet currents.
const std::vector< double > & getCollimatorPositions () const
Retrieve the collimator positions The values are stored in the sequence 'Measurement x, Reference x, Meaurement y, Reference y e.g.
const std::vector< double > & getQuadrupoleCurrents () const
Retrieve the quadrupole currents.
const std::vector< double > & getTrimCurrents () const
Retrieve the trim currents.
const std::vector< int > & getH6aExperimentCounts () const
Retrieve the h6a experiment count.
const std::vector< int > & getH6bExperimentCounts () const
Retrieve the h6b experiment count.
const std::vector< int > & getH6cExperimentCounts () const
Retrieve the h6c experiment count.
const std::vector< int > & getRpExperimentCounts () const
Retrieve the rp experiment count.
const std::vector< int > & getScintillatorCounts () const
Retrieve the scintillator count.
void setDblArrays (const DaqTypeDataDblMap_t &)
These methods receive the vectors with the measured values Mainly to store large arrays of a given datatype but in principle this can be extended to every entry in the interface class.
void setFloatArrays (const DaqTypeDataFloatMap_t &)
void setIntArrays (const DaqTypeDataUIntMap_t &)
const double getBeamEnergy ()
Implementation of the method to get the beam energy.
void print (std::ostream &)
convenient print method
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Public Member Functions inherited from CALICE::DaqTypeDataBlock
DaqTypeDataBlock ()
Constructor.
DaqTypeDataBlock (LCObject *obj, bool restoreMaps=true)
'Copy constructor' needed to interpret LCCollection read from file/database.
DaqTypeDataBlock & setTimeStamps (std::map< std::string, time_t > timeStampMapRaw)
Set the time stamps or better initialize the timestamp map which will be stored Remember: We store UTC!!!!
TimeStampMap_t getTimeStamps ()
virtual void setIntArrays (const DaqTypeDataIntMap_t &)
DaqTypeDataIntMap_t getIntArrays ()
The following methods allow to retrieve the maps.
DaqTypeDataDblMap_t getDblArrays ()
DaqTypeDataFloatMap_t getFloatArrays ()
DaqTypeDataBlock * finalize ()
A method which finally fills the object which is stored.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Public Member Functions inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImplExt ()
Default c'tor.
LCGenericObjectImplExt (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCGenericObjectImplExt ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Private Types
typedef std::map< string,
std::pair< int, std::vector
< double > * > > BmlSroTypesDblMap_t
Relation between the datatype its position among the tuple of double vals and the vector the data are readinto.
typedef std::map< string,
std::pair< int, std::vector
< int > * > > BmlSroTypesIntMap_t
typedef std::map< string,
std::pair< int, std::vector
< float > * > > BmlSroTypesFloatMap_t
Private Member Functions
void setNumPos (int posindex, int pos, int numvals)
Store the position and number of measured values for a given datatype.
int getPos (int posindex) const
get the position of the given datatype within the array of values
int getNum (int posindex) const
Retrieve the number of measured values for a given datatype.
void setTypes ()
This method defines the (general) types of the measured values A type not present here will not be treated!!!
void prepareOutputVecs ()
A method which prepares the output vectors.
Private Attributes
BmlSroTypesDblMap_t _theDblTypes
The vector which contains the types and to the position and values of the types doubles.
BmlSroTypesIntMap_t _theIntTypes
BmlSroTypesFloatMap_t _theFloatTypes
std::vector< double > _sextapoleCurrents
The output vectors.
std::vector< double > _bendCurrents
Bending Magnets currents.
std::vector< double > _colPositions
Collimator Positions.
std::vector< double > _quadrupoleCurrents
Quadrupole Magnets Current.
std::vector< double > _trimCurrents
Trim Magnets Current.
std::vector< int > _h6aExpCounts
std::vector< int > _h6bExpCounts
std::vector< int > _h6cExpCounts
std::vector< int > _rpExpCounts
std::vector< int > _scintCounts
Additional Inherited Members
Protected Attributes inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Interface Class to access the BmlSlowRun Data Here we handle ahc voltages, temperatures et al.
when filling the class the string identifying the measured values has to be given first, a warning is issued if no indentifier is given for a given datatype. On the other hand this concerns just the filler of the class, i.e. the conversion where it is done once for all. See the print method at the end of the class for the meaning of the fields (as of 31/7/06) Use the interface methods to retrieve the data fields Note that the implemented functionality is essentially kept for backward compatibility only i.e. that if ever the cern 06/07 data will be converted again the data will be written in the same way into the db as before. In principle the functionality like writing to the db is to be made by the base class. Beamline parameters for datataking period > 2007 should be written into the db using the methods of the base class.
Author
: Roman Pschl LAL/Orsay
Date
Aug 2006, modified Sept. 2008
Definition at line 71 of file BmlSlowRunDataBlock.hh.
Member Function Documentation
const std::vector<double>& CALICE::BmlSlowRunDataBlock::getBendCurrents () const inline
Retrieve the bending magnet currents.
See Also
getSextapoleCurrents()
Definition at line 248 of file BmlSlowRunDataBlock.hh.
Referenced by CALICE::BeamMomentum::BeamMomentum(), and print().
const std::vector<double>& CALICE::BmlSlowRunDataBlock::getCollimatorPositions () const inline
Retrieve the collimator positions The values are stored in the sequence 'Measurement x, Reference x, Meaurement y, Reference y e.g.
_colPositions[0] = measured value of coll. 1 - x coord. (counting from 1) e.g. _colPositions[1] = reference value of coll. 1 - x coord. (counting from 1) e.g. _colPositions[2] = measured value of coll. 1 - y coord. (counting from 1) e.g. _colPositions[3] = reference value of coll. 1 - y coord. (counting from 1)
Definition at line 258 of file BmlSlowRunDataBlock.hh.
Referenced by CALICE::BeamMomentum::BeamMomentum(), and print().
const std::vector<double>& CALICE::BmlSlowRunDataBlock::getQuadrupoleCurrents () const inline
Retrieve the quadrupole currents.
See Also
getSextapoleCurrents()
Definition at line 264 of file BmlSlowRunDataBlock.hh.
Referenced by print().
const std::vector<double>& CALICE::BmlSlowRunDataBlock::getSextapoleCurrents () const inline
Retrieve the sextapole currents The values are stored in the sequence 'Measurement, Reference e.g.
_sextapoleCurrents[0] = measured value of sextupole 1 (counting from 1) e.g. _sextapoleCurrents[1] = reference value of sextupole 1 (counting from 1)
Definition at line 242 of file BmlSlowRunDataBlock.hh.
Referenced by print().
const std::vector<double>& CALICE::BmlSlowRunDataBlock::getTrimCurrents () const inline
Retrieve the trim currents.
See Also
getSextapoleCurrents()
Definition at line 270 of file BmlSlowRunDataBlock.hh.
Referenced by print().
void CALICE::BmlSlowRunDataBlock::print (std::ostream & os) virtual
convenient print method
Convenient print method.
Reimplemented from CALICE::DaqTypeDataBlock.
Definition at line 177 of file BmlSlowRunDataBlock.cc.
References getAbsorberPosition(), getBendCurrents(), getCollimatorPositions(), getH6aExperimentCounts(), getH6bExperimentCounts(), getH6cExperimentCounts(), getQuadrupoleCurrents(), getRpExperimentCounts(), getScintillatorCounts(), getSextapoleCurrents(), getT4Position(), getTargetPosition(), getTimeStamp(), getTrimCurrents(), and prepareOutputVecs().
BmlSlowRunDataBlock& CALICE::BmlSlowRunDataBlock::setAbsorberPosition (double abspos) inline
Store the aborber position device in cern h6b beamline to purify beam, ie.
to get rid of electrons
Definition at line 134 of file BmlSlowRunDataBlock.hh.
The documentation for this class was generated from the following files:
BmlSlowRunDataBlock.hh
BmlSlowRunDataBlock.cc