CALICE_USERLIB: CALICE::ErrorBits Class Reference
CALICE::ErrorBits Class Reference
Helper class to query or set the event errors.
#include <ErrorBits.hh>
Public Types
enum EErrorBits {
kNoEventData, kMissingAdcBlock, kMissingVLinkHeader, kInvalidTrigger,
kBadConfigData, kWrongTriggerCounter, kCorruptEventRecord, kMissingTriggerRecord,
kCorruptAcquisition, kTDCOutOfSynch, kDirtyEvent, kLargeNegativeSignal,
kCorruptBmlRecord, kCorruptDifTrigCounter, kNErrorBits
}
Public Member Functions
ErrorBits (int trigger_bits)
bool operator! () const
Return true if NO error was detected.
operator bool () const
Return true if an error was detected.
bool noEventData () const
Was the event data missing for this event? return true if all ADC blocks were missing;.
void setNoEventData ()
Set the missing event data flag.
bool missingADCBlock () const
Is one or more ADC blocks missing? return true if one or more ADC blocks are missing.
void setMissingADCBlock ()
Set the error bit to flag missing ADC blocks.
bool missingVLinkHeader () const
Is the VLink Header missing? return true if the VLink header is missing.
void setMissingVLinkHeader ()
Set the error bit to flag missing VLink headers.
bool wrongTriggerCounter () const
Return true if the trigger counter did not change or is not the same for all "valid" front-ends.
void setWrongTriggerCounter ()
Set the error bit to flag errors in the trigger counter field.
bool corruptEventRecord () const
Return true if the event record of one front-end was corrupt.
void setCorruptEventRecord ()
Set the error bit to flag events with corrupt event records.
bool invalidTrigger () const
Is the Vlink header missing ?.
void setInvalidTrigger ()
Set the error bit to flag missing VLink headers.
bool badConfigurationData () const
Error in the verification of the Configuration Data.
void setBadConfigurationData ()
Set the error bit to flag bad Configuration Data.
bool noTrigger () const
No trigger exists for a given event.
void setNoTrigger ()
Set the error bit to flag bad Configuration Data.
bool corruptAcquisition () const
The acquisition sequence is screwed up i.e.
void setCorruptAcquisition ()
Set the error bit to flag a wrong acquistion.
bool tdcOutOfSynch () const
The event number in the TDC does not agree with the the event number as derived from the CrcBoards.
void setTDCOutOfSynch ()
Set the error bit to flag suspicious TDC data.
bool corruptBmlRecord () const
Return true if the event record of one front-end was corrupt.
void setCorruptBmlRecord ()
Set the error bit to flag events with corrupt event records.
bool largeNegativeSignal () const
The event contained a significant fraction of negative signals.
void setLargeNegativeSignal ()
Set this error bit if the event contains a significant fraction of negative signals.
bool dirtyEvent () const
Thers is additional trigger activity close to or at the main word.
void setDirtyEvent ()
Set this error bit if there is additional trigger activity close to or at the main word.
bool corruptDifTrigCounter () const
Return true if one of the dif trigger counters gets out of synch.
void setCorruptDifTrigCounter ()
Set the error bit to flag events with corrupt dif counter.
bool isSet () const
Has an error occurred?
int getBits () const
return the error bits.
std::ostream & print (std::ostream &out) const
print the current errors.
Static Public Member Functions
static unsigned int getErrorBit (const std::string &name)
Translate an error name into a bit.
static const char * getErrorName (unsigned int bit_i)
Get the name assigned to an error bit.
static unsigned int getErrorBitMask (const std::vector< std::string > &error_names)
Create a error bit mask from a vector of error names.
Private Member Functions
bool getBit (unsigned int bit) const
get an error bit.
void setBit (unsigned int bit)
set an error bit.
Private Attributes
int _errorBits
The error bits.
Static Private Attributes
static const char * __name [kNErrorBits]
static std::map< std::string,
unsigned short > __nameToBit
Detailed Description
Helper class to query or set the event errors.
usage:
ErrorBits error(((LCEvent *) evt)->getParameters().getIntVal(PAR_ERROR_BITS));
Author
Götz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Definition at line 21 of file ErrorBits.hh.
Member Function Documentation
bool CALICE::ErrorBits::corruptAcquisition () const inline
The acquisition sequence is screwed up i.e.
unequal numbers of event and trigger records
Definition at line 134 of file ErrorBits.hh.
References getBit().
bool CALICE::ErrorBits::invalidTrigger () const inline
Is the Vlink header missing ?.
return true if the VLink header is missing.
Definition at line 110 of file ErrorBits.hh.
References getBit().
bool CALICE::ErrorBits::largeNegativeSignal () const inline
The event contained a significant fraction of negative signals.
This may indicate pedestal drift, overlapping events, ...
Definition at line 161 of file ErrorBits.hh.
References getBit().
void CALICE::ErrorBits::setLargeNegativeSignal () inline
Set this error bit if the event contains a significant fraction of negative signals.
This may indicate pedestal drift, overlapping events, ...
Definition at line 166 of file ErrorBits.hh.
References setBit().
bool CALICE::ErrorBits::wrongTriggerCounter () const inline
Return true if the trigger counter did not change or is not the same for all "valid" front-ends.
Front-ends with missing front-end data are not considered also not connected front-ends.
Definition at line 92 of file ErrorBits.hh.
References getBit().
Field Documentation
const char * CALICE::ErrorBits::__name static private
Initial value:
={
  "NoEventData",
  "MissingAdcBlock",
  "MissingVLinkHeader",
  "InvalidTrigger",
  "BadConfigData",
  "WrongTriggerCounter",
  "CorruptEventRecord",
  "MissingTriggerRecord",
  "CorruptAcquisition",
  "TDCOutOfSynch",
  "DirtyEvent",
  "LargeNegativeSignal",
  "CorruptBmlRecord",
  "CorruptDifTriggerCounter"
}
Definition at line 231 of file ErrorBits.hh.
int CALICE::ErrorBits::_errorBits private
The error bits.
If non zero an error has occurred.
Definition at line 227 of file ErrorBits.hh.
Referenced by getBit(), getBits(), isSet(), operator bool(), operator!(), and setBit().
The documentation for this class was generated from the following files:
ErrorBits.hh
ErrorBits.cc