CALICE_USERLIB: CALICE::AhcSlowReadoutModMapping Class Reference
CALICE::AhcSlowReadoutModMapping Class Reference
Class to store the mapping corrections for the AhcSlowReadoutModBlock.
#include <AhcSlowReadoutModMapping.hh>
Public Member Functions
AhcSlowReadoutModMapping (const int module, const int CMBrecordLabel, const int HVrecordLabel, const int LVrecordLabel)
Constructor with initial values.
AhcSlowReadoutModMapping (EVENT::LCObject *object)
Constructor from LCObject.
~AhcSlowReadoutModMapping ()
Destructor.
void setModule (int module)
void setCMBlabel (int label)
void setHVlabel (int label)
void setLVlabel (int label)
int getModule () const
get the module number for which this record is
int getCMBlabel () const
get the label of the AhcSlowReadoutModBlock holding the data with source CMB
int getHVlabel () const
get the label of the AhcSlowReadoutModBlock holding the data with source HV supply
int getLVlabel () const
get the label of the AhcSlowReadoutModBlock holding the data with source LV monitoring
const std::string getTypeName () const
Implementation of LCGenericObject::getTypeName.
const std::string getDataDescription () const
Implementation of LCGenericObject::getDataDescription.
Detailed Description
Class to store the mapping corrections for the AhcSlowReadoutModBlock.
The slow control assembled the data from different modules into the slow control data submitted to the DAQ during 2006 and 2007. This bug was only fixed in the beginning of 2008 data taking at FNAL. This class holds the relation between data from the module and under which label it was stored.
As the data comes from three different hardware sources (CMB, HV supply and LV) the record holds three numbers for the sources. If the data for one source is lost due to mapping errors, the reading will be -1.
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
1.0
Date
November 2008
Definition at line 29 of file AhcSlowReadoutModMapping.hh.
Member Function Documentation
int CALICE::AhcSlowReadoutModMapping::getCMBlabel () const
get the label of the AhcSlowReadoutModBlock holding the data with source CMB
Remarks
returns -1 when the data was lost due to mapping errors
Definition at line 23 of file AhcSlowReadoutModMapping.cc.
Referenced by CALICE::AhcSlowReadoutModMapper::updateMapping().
int CALICE::AhcSlowReadoutModMapping::getHVlabel () const
get the label of the AhcSlowReadoutModBlock holding the data with source HV supply
Remarks
returns -1 when the data was lost due to mapping errors
Definition at line 26 of file AhcSlowReadoutModMapping.cc.
Referenced by CALICE::AhcSlowReadoutModMapper::updateMapping().
int CALICE::AhcSlowReadoutModMapping::getLVlabel () const
get the label of the AhcSlowReadoutModBlock holding the data with source LV monitoring
Remarks
returns -1 when the data was lost due to mapping errors
Definition at line 29 of file AhcSlowReadoutModMapping.cc.
Referenced by CALICE::AhcSlowReadoutModMapper::updateMapping().
The documentation for this class was generated from the following files:
AhcSlowReadoutModMapping.hh
AhcSlowReadoutModMapping.cc