CALICE_USERLIB: CALICE::DecoderSet Class Reference
CALICE::DecoderSet Class Reference
class containing decoders for the three CALICE coordinate systems
#include <DecoderSet.hh>
Data Structures
struct MokkaID_t
Public Member Functions
DecoderSet ()
standard constructor
DecoderSet (const std::string &cellIDencoding, const std::string &moduleEncoding, const std::string &DAQencoding)
constructor with encoding strings
void setCellIDEncoding (const std::string &encoding)
set a new cell ID encoding string if an empty string is given the function will use the default encoding string
void setModuleEncoding (const std::string &encoding)
set a new Module tile encoding string if an empty string is given the function will use the default encoding string
void setDAQEncoding (const std::string &encoding)
set a new DAQ channel ID encoding string if an empty string is given the function will use the default encoding string
const std::string & getCellIDEncoding () const
get the current cell ID encoding string
const std::string & getModuleEncoding () const
get the current Module tile encoding string
const std::string & getDAQEncoding () const
get the current DAQ channel ID encoding string
unsigned int getIFromCellID (const int cellID) const
get I from (Mokka) CellID The right encoding string has to be set before.
unsigned int getJFromCellID (const int cellID) const
get J from (Mokka) CellID The right encoding string has to be set before.
unsigned int getKFromCellID (const int cellID) const
get K from (Mokka) CellID The right encoding string has to be set before.
unsigned int getModuleFromModuleID (const int moduleID) const
get module from (Module) channel ID The right encoding string has to be set before.
unsigned int getChipFromModuleID (const int moduleID) const
get chip from (Module) channel ID The right encoding string has to be set before.
unsigned int getChannelFromModuleID (const int moduleID) const
get channel from (Module) channel ID The right encoding string has to be set before.
unsigned int getChannelFromDAQID (const int DAQconnection) const
get channel from DAQ channel ID The right encoding string has to be set before.
unsigned int getChipFromDAQID (const int DAQconnection) const
get chip from DAQ channel ID The right encoding string has to be set before.
unsigned int getFeFromDAQID (const int DAQconnection) const
get fe from DAQ channel ID The right encoding string has to be set before.
unsigned int getSlotFromDAQID (const int DAQconnection) const
get slot from DAQ channel ID The right encoding string has to be set before.
unsigned int getCrateFromDAQID (const int DAQconnection) const
get crate from DAQ channel ID The right encoding string has to be set before.
int getCellID (const unsigned int I, const unsigned int J, const unsigned int K) const
get CellID from triple I,J,K
int getModuleID (const unsigned int module, const unsigned int chip, const unsigned int channel) const
get (Module) channel ID from triple module, chip, channel
int getDAQID (const unsigned int crate, const unsigned int slot, const unsigned int fe, const unsigned int chip, const unsigned int channel) const
get DAQ channel ID from crate, slot, fe, chip, channel
Private Types
typedef std::map< std::string,
MokkaID_t > mokkaDecoderMap_t
Private Attributes
std::string _cellIDencodingString
std::string _moduleIDEncodingString
std::string _daqIDencodingString
FastDecoder * _IFromCellID
FastDecoder * _JFromCellID
FastDecoder * _KFromCellID
FastDecoder * _moduleFromModuleID
FastDecoder * _chipFromModuleID
FastDecoder * _channelFromModuleID
FastDecoder * _channelFromDAQID
FastDecoder * _chipFromDAQID
FastDecoder * _feFromDAQID
FastDecoder * _slotFromDAQID
FastDecoder * _crateFromDAQID
mokkaDecoderMap_t _mokkaDecoderMap
Static Private Attributes
static const std::string _defaultCellIDEncoding
static const std::string _defaultModuleEncoding
static const std::string _defaultDAQEncoding
Detailed Description
class containing decoders for the three CALICE coordinate systems
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
0.1
Date
November 2009
Definition at line 36 of file DecoderSet.hh.
Constructor & Destructor Documentation
CALICE::DecoderSet::DecoderSet ()
standard constructor
encoding strings will be initialised to defaults
Definition at line 10 of file DecoderSet.cc.
References setCellIDEncoding(), setDAQEncoding(), and setModuleEncoding().
CALICE::DecoderSet::DecoderSet (const std::string & cellIDencoding, const std::string & moduleEncoding, const std::string & DAQencoding)
constructor with encoding strings
Parameters
[in] cellIDencoding encoding string for (Mokka) cell IDs
[in] moduleEncoding encoding string for module channel ID
[in] DAQencoding encoding string for DAQ channel ID
Definition at line 21 of file DecoderSet.cc.
References setCellIDEncoding(), setDAQEncoding(), and setModuleEncoding().
The documentation for this class was generated from the following files:
DecoderSet.hh
DecoderSet.cc