CALICE_USERLIB: CALICE::BmlEventDataSup Class Reference
CALICE::BmlEventDataSup Class Reference
Class to store supplementary BmlEventData.
#include <BmlEventDataSup.hh>
Private Member Functions
BmlEventDataSup ()
Default Constructor.
BmlEventDataSup (LCObject *obj)
A copy constructor.
virtual ~BmlEventDataSup ()
The destructor.
BmlEventDataSup & setTDCType (std::string typeStr)
set the tdc type
void setPointerToIndexOfIntTypeNames (int nameind)
void setLengthIndexOfIntTypeNames (int lengthindex)
int getLengthIndexOfIntTypeNames () const
Retrieve the index at which the lengths of the names of the int data types do start.
int getPointerToIndexOfIntTypeNames () const
Retrieve the index at which the pointer to the names of int data types do start.
void setTypeIndex (int pos, int value)
Set the index of a given data type name.
std::string getTDCType () const
get the tdc type
BmlEventDataSup & setEventFifoCont (int fifocont)
Store the FIFO content.
unsigned short getEventCount () const
get the event count
unsigned short getWordCount () const
get the word count
BmlEventDataSup & setBunchID (int bunchid)
set the bunch id
int getBunchID () const
get the bunch id
BmlEventDataSup & setEventIDTrailer (int eventIDTrailer)
Set the eventid from the TDC trailer.
short getEventIDTrailer () const
Return the eventid from the TDC trailer.
BmlEventDataSup & setTDCErrors (int tdcErrors)
Set the TDC errors.
int getTDCErrors () const
Get the TDC errors.
BmlEventDataSup & setBufferOverflow (int bufferOverflow)
Set the buffer overflow.
int getBufferOverflow () const
Get the buffer overflow.
BmlEventDataSup & setTriggerLost (int triggerlost)
Set the number of words in the trailer.
int getTriggerLost () const
Get the number of lost triggers.
BmlEventDataSup & setTDCWordCountTrailer (int numwords)
Set the number of lost triggers.
int getTDCWordCountTrailer () const
Get the number of words in the trailer.
const std::string getTypeName () const
returns the the type name
const std::string getDataDescription () const
returns a brief description of the data stored
std::ostream & print (std::ostream &ostrmsup)
dumps data content
Friends
class BmlEventData
Additional Inherited Members
Public Member Functions inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImplExt ()
Default c'tor.
LCGenericObjectImplExt (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCGenericObjectImplExt ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Protected Attributes inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Class to store supplementary BmlEventData.
This is tailored to the data extracted from the Caen TDCs in extension of the actual class BmlEventData This class is written such that it should be only accessed via the aforementioned class The user is strongly discouraged to instantiate by him/herself. It has only private functions and declares BmlEventData to be its friend.
Author
R. Pöschl (LAL Orsay)
Date
Oct 13 2010
Definition at line 52 of file BmlEventDataSup.hh.
Member Function Documentation
std::string CALICE::BmlEventDataSup::getTDCType () const inline private
get the tdc type
Currently since only one string in object -> to be modified if more strings
Definition at line 144 of file BmlEventDataSup.hh.
References CALICE::getStringFromInts().
Referenced by print().
BmlEventDataSup& CALICE::BmlEventDataSup::setTDCType (std::string typeStr) inline private
set the tdc type
Store the index at which the pointer to the names of the int data data types do start
This written such that it can be extended in case more strings need to be stored
Would however trigger a bit of re-writing but at least it sure that it remains always
compatible and flexible
We use the same ugly but successful technique as in DaqTypeDataBlock (we may even be able to inherit from it
now we've simply copied a few useful methods -> to be checked
Definition at line 94 of file BmlEventDataSup.hh.
References CALICE::convertStringToInts().
The documentation for this class was generated from the following files:
BmlEventDataSup.hh
BmlEventDataSup.cc