CALICE_USERLIB: CALICE::EcalModuleCalibration Class Reference
CALICE::EcalModuleCalibration Class Reference
Calibration constants for the Calice ECAL detector modules.
#include <EcalModuleCalibration.hh>
Public Member Functions
EcalModuleCalibration ()
Default c'tor.
EcalModuleCalibration (const std::string &module_type_name, UInt_t module_id, UInt_t n_cells)
UsefulConstructor.
std::string getModuleTypeName () const
Get the name assigned to the module type.
EcalModuleCalibration & setModuleID (UInt_t module_id)
Set the unique module ID.
UInt_t getModuleID () const
Get the unique module ID.
EcalModuleCalibration & setCalibrationConstant (UInt_t cell_index, float calibration_constant)
Set the calibration constant of thye given cell.
Float_t getCalibrationConstant (UInt_t cell_index) const
UInt_t getNCells () const
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
EcalModuleCalibration (LCObject *obj)
C'tor to be used for elements of LCGenericObjects read from an LCIO file or the database.
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~EcalModuleCalibration ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Protected Attributes
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Calibration constants for the Calice ECAL detector modules.
Based on LCFixedObject.
Author
Goetz Gayckem, LLR - ecole polytechnique)
Version
$Id $
Definition at line 27 of file EcalModuleCalibration.hh.
Constructor & Destructor Documentation
CALICE::EcalModuleCalibration::EcalModuleCalibration (LCObject * obj) inline
C'tor to be used for elements of LCGenericObjects read from an LCIO file or the database.
Subclasses should 'override' this, e.g.:
Myclass(LCObject* obj) : EcalModuleCalibration(obj) {}
Definition at line 130 of file EcalModuleCalibration.hh.
References CALICE::getNeededInts(), and obj().
Member Function Documentation
UInt_t CALICE::EcalModuleCalibration::getModuleID () const inline
Get the unique module ID.
A module is uniquely identified by the module ID (serial number) and the module type.
Definition at line 62 of file EcalModuleCalibration.hh.
std::string CALICE::EcalModuleCalibration::getModuleTypeName () const inline
Get the name assigned to the module type.
The module type together with the module ID is considered to be unique. Due to the character encoding in an integer array, the function may perform slowly.
Definition at line 48 of file EcalModuleCalibration.hh.
References CALICE::getStringFromInts().
LCGenericObjectImpl* CALICE::EcalModuleCalibration::obj () inline
The LCGenericObjectImpl .
Sublcasses use this to access their data.
Definition at line 173 of file EcalModuleCalibration.hh.
Referenced by EcalModuleCalibration().
EcalModuleCalibration& CALICE::EcalModuleCalibration::setCalibrationConstant (UInt_t cell_index, float calibration_constant) inline
Set the calibration constant of thye given cell.
Parameters
cell_index the cell index (electrical order: first the values of the first sample from all chips, then the second sample from all chips etc.)
calibration_constant the calibration constant which is multiplied to the ADC value.
Definition at line 71 of file EcalModuleCalibration.hh.
EcalModuleCalibration& CALICE::EcalModuleCalibration::setModuleID (UInt_t module_id) inline
Set the unique module ID.
A module is uniquely identified by the module ID (serial number) and the module type.
Definition at line 55 of file EcalModuleCalibration.hh.
The documentation for this class was generated from the following file:
EcalModuleCalibration.hh