CALICE_USERLIB: CALICE::Mapper Class Reference
CALICE::Mapper Class Reference abstract
Mapping for CALICE detectors (currently: HCAL support only)
#include <Mapper.hh>
Public Member Functions
Mapper ()
constructor (default encoding strings)
Mapper (const std::string &cellIDencoding, const std::string &moduleEncoding, const std::string &DAQencoding)
constructor that takes encoding strings
DecoderSet * getDecoder () const
get class which handles the bit en/decoding of the different IDs
virtual unsigned int getModuleFromCellID (const int cellID) const =0
get module (number) in which this cell is included from (Mokka) cellID
virtual unsigned int getModuleFromDAQID (const int DAQchannel) const =0
get module (number) in which this (DAQ) channel is included
virtual unsigned int getModuleFromCellID (const int cellID, bool &valid) const =0
get module (number) in which this cell is included from (Mokka) cellID
virtual unsigned int getModuleFromDAQID (const int DAQchannel, bool &valid) const =0
get module (number) in which this (DAQ) channel is included
virtual unsigned int getModuleFromModuleID (const int moduleID, bool &valid) const =0
get module (number) from this (module) channel ID
virtual unsigned int getISizeFromCellID (const int cellID) const =0
get cell size in I direction of (Mokka) CellID coordinate
virtual unsigned int getJSizeFromCellID (const int cellID) const =0
get cell size in J direction of (Mokka) CellID coordinate
virtual int getTrueCellID (const int virtualCellIndex) const =0
return identifying index of cell
CellIterator begin () const
get an iterator to the first (Mokka) cell ID
CellIterator end () const
get an iterator one after the last (Mokka) cell ID
unsigned int getVersion () const
Protected Member Functions
void mappingModified ()
If this function is called the version will be increased to indicate a change in the mapping.
virtual unsigned int getIndexByCellID (const int cellID) const =0
get a compact index for storing data in vectors
virtual unsigned int getIndexByDAQID (const int ID) const =0
get a compact index for storing data in vectors
virtual unsigned int getIndexByModuleID (const int ID) const =0
get a compact index for storing data in vectors
virtual unsigned int getMaxIndex () const =0
get the maximum value of the compact index for storing data in vectors
virtual int getCellIDOfIndex (unsigned int index) const =0
get the cell ID of a certain compact index
Private Attributes
unsigned int _version
DecoderSet * _decoderSet
Friends
template<class T >
class MappedContainer
class CellIterator
Detailed Description
Mapping for CALICE detectors (currently: HCAL support only)
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
0.4
Date
January 2010
Definition at line 19 of file Mapper.hh.
Constructor & Destructor Documentation
CALICE::Mapper::Mapper (const std::string & cellIDencoding, const std::string & moduleEncoding, const std::string & DAQencoding)
constructor that takes encoding strings
Parameters
[in] cellIDencoding encoding string for (Mokka) cell IDs
[in] moduleEncoding encoding string for module channel ID
[in] DAQencoding encoding string for DAQ channel ID
Definition at line 11 of file Mapper.cc.
Member Function Documentation
DecoderSet* CALICE::Mapper::getDecoder () const inline
get class which handles the bit en/decoding of the different IDs
The encoding strings can be set there.
Definition at line 45 of file Mapper.hh.
Referenced by CALICE::CellDescriptionGenerator::generate(), CALICE::AhcMapper::getCellIDFromModChipChan(), CALICE::Ahc2Mapper::getCellIDFromModChipChan(), CALICE::AhcMapper::getCellIDOfIndex(), CALICE::Ahc2Mapper::getCellIDOfIndex(), CALICE::AhcMapper::getChanFromCellID(), CALICE::Ahc2Mapper::getChanFromCellID(), CALICE::AhcMapper::getChipFromCellID(), CALICE::Ahc2Mapper::getChipFromCellID(), CALICE::AhcMapper::getCrateFromModuleID(), CALICE::Ahc2Mapper::getCrateFromModuleID(), CALICE::MappedContainer< T >::getDecoder(), CALICE::AhcMapper::getFeFromModuleID(), CALICE::Ahc2Mapper::getFeFromModuleID(), CALICE::AhcMapper::getIFromDAQID(), CALICE::Ahc2Mapper::getIFromDAQID(), CALICE::AhcMapper::getIFromModuleID(), CALICE::Ahc2Mapper::getIFromModuleID(), CALICE::AhcMapper::getIndexByCellID(), CALICE::Ahc2Mapper::getIndexByCellID(), CALICE::AhcMapper::getIndexByDAQID(), CALICE::Ahc2Mapper::getIndexByDAQID(), CALICE::AhcMapper::getIndexByModuleID(), CALICE::Ahc2Mapper::getIndexByModuleID(), CALICE::AhcMapper::getISizeFromCellID(), CALICE::Ahc2Mapper::getISizeFromCellID(), CALICE::AhcMapper::getISizeFromDAQID(), CALICE::Ahc2Mapper::getISizeFromDAQID(), CALICE::AhcMapper::getISizeFromModuleID(), CALICE::Ahc2Mapper::getISizeFromModuleID(), CALICE::AhcMapper::getJFromDAQID(), CALICE::Ahc2Mapper::getJFromDAQID(), CALICE::AhcMapper::getJFromModuleID(), CALICE::Ahc2Mapper::getJFromModuleID(), CALICE::AhcMapper::getJSizeFromCellID(), CALICE::Ahc2Mapper::getJSizeFromCellID(), CALICE::AhcMapper::getJSizeFromDAQID(), CALICE::Ahc2Mapper::getJSizeFromDAQID(), CALICE::AhcMapper::getJSizeFromModuleID(), CALICE::Ahc2Mapper::getJSizeFromModuleID(), CALICE::AhcMapper::getKFromModuleID(), CALICE::Ahc2Mapper::getKFromModuleID(), CALICE::AhcMapper::getModule(), CALICE::Ahc2Mapper::getModule(), CALICE::AhcMapper::getModuleFromCellID(), CALICE::Ahc2Mapper::getModuleFromCellID(), CALICE::AhcMapper::getModuleFromDAQID(), CALICE::Ahc2Mapper::getModuleFromDAQID(), CALICE::AhcMapper::getSlotFromModuleID(), CALICE::Ahc2Mapper::getSlotFromModuleID(), CALICE::AhcMapper::getTrueCellID(), CALICE::Ahc2Mapper::getTrueCellID(), CALICE::AhcMapper::getTrueIFromCellID(), CALICE::Ahc2Mapper::getTrueIFromCellID(), CALICE::AhcMapper::getTrueJFromCellID(), and CALICE::Ahc2Mapper::getTrueJFromCellID().
virtual unsigned int CALICE::Mapper::getMaxIndex () const protected pure virtual
get the maximum value of the compact index for storing data in vectors
Returns
maximum compact index
Implemented in CALICE::Ahc2Mapper, and CALICE::AhcMapper.
Referenced by CALICE::MappedContainer< T >::clear(), end(), CALICE::MappedContainer< T >::MappedContainer(), and CALICE::CellIterator::operator++().
unsigned int CALICE::Mapper::getVersion () const inline
Returns
a version number that increases with changes in the mapping
Definition at line 187 of file Mapper.hh.
Referenced by CALICE::MappedContainer< T >::MappedContainer().
The documentation for this class was generated from the following files:
Mapper.hh
Mapper.cc