CALICE_USERLIB: CALICE::AhcMapper Class Reference
CALICE::AhcMapper Class Reference
AHCAL implementation of Mapper class.
#include <AhcMapper.hh>
Public Member Functions
int getCellIDFromModChipChan (const unsigned int module, const unsigned int chip, const unsigned int channel) const
generate (Mokka) cellID from module, chip, channel
unsigned int getModuleFromCellID (const int cellID) const
module number from (Mokka) CellID
unsigned int getModuleFromDAQID (const int DAQchannel) const
module number from DAQ channel ID
unsigned int getModule (const unsigned int crate, const unsigned int slot, const unsigned int fe) const
module number from triple crate, slot, fe
unsigned int getModule (const unsigned int k) const
module number from K
unsigned int getModuleFromCellID (const int cellID, bool &valid) const
get module (number) in which this cell is included from (Mokka) cellID
unsigned int getModuleFromDAQID (const int DAQchannel, bool &valid) const
get module (number) in which this (DAQ) channel is included
unsigned int getModuleFromModuleID (const int moduleID, bool &valid) const
get module (number) from this (module) channel ID
unsigned int getChipFromCellID (const int cellID) const
chip number from (Mokka) CellID
unsigned int getChip (const unsigned int i, const unsigned int j, const unsigned int k) const
chip number from triple I, J, K
unsigned int getChanFromCellID (const int cellID) const
channel number from (Mokka) CellID
unsigned int getChan (const unsigned int i, const unsigned int j, const unsigned int k) const
chip number from triple I, J, K
unsigned int getCrateFromCellID (const int cellID) const
crate number from (Mokka) CellID
unsigned int getCrateFromModuleID (const int moduleID) const
crate number from Module cell ID
unsigned int getCrate (const unsigned int module) const
crate number from module number
unsigned int getSlotFromCellID (const int cellID) const
slot number from (Mokka) CellID
unsigned int getSlotFromModuleID (const int moduleID) const
slot number from Module cell ID
unsigned int getSlot (const unsigned int module) const
slot number from module number
unsigned int getFeFromCellID (const int cellID) const
front end number from (Mokka) CellID
unsigned int getFeFromModuleID (const int moduleID) const
front end number from Module cell ID
unsigned int getFe (const unsigned int module) const
front end number from module number
unsigned int getIFromModuleID (const int moduleID) const
I of (Mokka) cellID.
unsigned int getIFromDAQID (const int DAQchannel) const
I of (Mokka) cellID.
unsigned int getI (const unsigned int module, const unsigned int chip, const unsigned int chan) const
I of (Mokka) cellID.
unsigned int getJFromModuleID (const int moduleID) const
J of (Mokka) cellID.
unsigned int getJFromDAQID (const int DAQchannel) const
J of (Mokka) cellID.
unsigned int getJ (const unsigned int module, const unsigned chip, const unsigned chan) const
J of (Mokka) cellID.
unsigned int getKFromModuleID (const int moduleID) const
K of (Mokka) cellID.
unsigned int getKFromDAQID (const int DAQchannel) const
K of (Mokka) cellID.
unsigned int getK (const unsigned int module) const
K of (Mokka) cellID.
unsigned int getISizeFromCellID (const int cellID) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int getISizeFromModuleID (const int moduleID) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int getISizeFromDAQID (const int DAQchannel) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int getISizeFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int getISize (const unsigned int module, const unsigned int chip, const unsigned int chan) const
get cell size in I direction of (Mokka) CellID coordinate
unsigned int getJSizeFromCellID (const int cellID) const
get cell size in J direction of (Mokka) CellID coordinate
unsigned int getJSizeFromModuleID (const int moduleID) const
get cell size in J direction of (Mokka) CellID coordinate
unsigned int getJSizeFromDAQID (const int DAQchannel) const
get cell size in J direction of (Mokka) CellID coordinate
unsigned int getJSizeFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
get cell size in J direction of (Mokka) CellID coordinate
unsigned int getJSize (const unsigned int module, const unsigned int chip, const unsigned int chan) const
get cell size in J direction of (Mokka) CellID coordinate
int getTrueCellID (const int virtualCellIndex) const
return identifying index of cell
int getTrueCellID (const unsigned int i, const unsigned int j, const unsigned int k) const
return identifying index of cell
unsigned int getTrueIFromCellID (const int virtualCellID) const
return I of identifying index of cell
unsigned int getTrueIFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
return I of identifying index of cell
unsigned int getTrueI (const unsigned int module, const unsigned int i, const unsigned int j) const
return I of identifying index of cell
unsigned int getTrueJFromCellID (const int virtualCellID) const
return J of identifying index of cell
unsigned int getTrueJFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const
return J of identifying index of cell
unsigned int getTrueJ (const unsigned int module, const unsigned int i, const unsigned int j) const
return J of identifying index of cell
unsigned int getMaxModule () const
return maximum module number
unsigned int getMaxChip () const
return maximum chip number
unsigned int getMaxChannel () const
return maximum channel number
unsigned int getMaxI () const
return maximum I index
unsigned int getMaxJ () const
return maximum J index
unsigned int getMaxK () const
return maximum K index
void fill (const lcio::LCCollection *moduleDescriptionCol, const lcio::LCCollection *moduleConnectionCol)
fills all necessary mapping information
void updateConnections (const lcio::LCCollection *moduleConnectionCol)
updates the mapping information in the class (possible after first fill only)
void print (std::ostream &ostream) const
print current data contents
void printStats (std::ostream &ostream) const
print summary of current data contents
Public Member Functions inherited from CALICE::Mapper
Mapper ()
constructor (default encoding strings)
Mapper (const std::string &cellIDencoding, const std::string &moduleEncoding, const std::string &DAQencoding)
constructor that takes encoding strings
DecoderSet * getDecoder () const
get class which handles the bit en/decoding of the different IDs
CellIterator begin () const
get an iterator to the first (Mokka) cell ID
CellIterator end () const
get an iterator one after the last (Mokka) cell ID
unsigned int getVersion () const
Protected Member Functions
unsigned int getIndexByCellID (const int cellID) const
get a compact index for storing data in vectors
unsigned int getIndexByDAQID (const int ID) const
get a compact index for storing data in vectors
unsigned int getIndexByModuleID (const int ID) const
get a compact index for storing data in vectors
unsigned int getMaxIndex () const
get the maximum value of the compact index for storing data in vectors
int getCellIDOfIndex (unsigned int index) const
get the cell ID of a certain compact index
Protected Member Functions inherited from CALICE::Mapper
void mappingModified ()
If this function is called the version will be increased to indicate a change in the mapping.
Private Types
typedef std::map< unsigned int,
unsigned int > indexMap_t
Private Member Functions
bool valid (const unsigned int index, const std::vector< bool > &availableVec) const
bool valid (const unsigned int index, const indexMap_t &indexMap) const
unsigned int getModuleTypeIndex (const unsigned int module) const
unsigned int getIndexModuleConnection (const unsigned int crate, const unsigned int slot, const unsigned int fe) const
unsigned int getCrateFromModuleConnectionIndex (const unsigned int index) const
unsigned int getSlotFromModuleConnectionIndex (const unsigned int index) const
unsigned int getFeFromModuleConnectionIndex (const unsigned int index) const
unsigned int getCompactIndex (const unsigned int module, const unsigned int chip, const unsigned int chan) const
unsigned int getCompactIndex (const unsigned int module, const unsigned int chanIndex) const
unsigned int getModuleFromCompactIndex (const unsigned int index) const
unsigned int getChipFromCompactIndex (const unsigned int index) const
unsigned int getChanFromCompactIndex (const unsigned int index) const
unsigned int getModuleFromIndex (const unsigned int index, bool &valid) const
unsigned int getIndexChan (const unsigned int chip, const unsigned int chan) const
unsigned int getChipFromChanIndex (const unsigned int index) const
unsigned int getChanFromChanIndex (const unsigned int index) const
unsigned int getIndexIJ (const unsigned int i, const unsigned int j) const
unsigned int getIFromIJIndex (const unsigned int index) const
unsigned int getJFromIJIndex (const unsigned int index) const
void clearCrate ()
void clearSlot ()
void clearModuleType ()
template<class T >
void initToSize (std::vector< T > &vec, const unsigned int size, const T initValue)
void initToSize (std::vector< bool > &vec, const unsigned int size)
void initToSize (std::vector< unsigned int > &dataVec, std::vector< bool > &availableVec, const unsigned int size)
void initFe (const unsigned int maxFe=0)
void initModule (const unsigned int maxMod=0)
void initK (const unsigned int maxK=0)
void initIJChipChannel (const unsigned int maxI=0, const unsigned int maxJ=0, const unsigned int maxChip=0, const unsigned int maxChan=0)
void clear ()
void registerCrate (const unsigned int crate)
bool crateAvailable (const unsigned int crate) const
void registerSlot (const unsigned int slot)
bool slotAvailable (const unsigned int slot) const
void registerModuleType (const unsigned int moduleTypeName)
bool moduleTypeAvailable (const unsigned int moduleTypeName) const
unsigned int countAvailable (const std::vector< bool > &vec) const
void setModuleCrateSlotFe (const unsigned int module, const unsigned int crate, const unsigned int slot, const unsigned int fe)
void setModuleType (const unsigned int module, const unsigned int typeName)
void setModuleK (const unsigned int module, const unsigned int K)
void setModuleTypeIJChipChannel (const unsigned int moduleTypeName, const unsigned int I, const unsigned int J, const unsigned int sizeI, const unsigned int sizeJ, const unsigned int chip, const unsigned int channel)
void fillModuleConnection (const lcio::LCCollection *col)
sets the mapping information in the class, call after fillModuleDescription
void fillModuleDescription (const lcio::LCCollection *col)
sets the module layout information in the class, module connection information will be invalidated
void getChipChannelForModuleDescriptionID (const unsigned int id, const unsigned int moduleType, int &chip, int &channel) const
unsigned int getCombinedModuleType (const unsigned int moduleType) const
int correctCellIndex (const unsigned int moduleType, const int cellIndex) const
const std::string printIfAvailable (bool available, unsigned int value) const
Private Attributes
unsigned int _nChan
unsigned int _nChip
unsigned int _nFe
unsigned int _nSlot
unsigned int _maxSlot
unsigned int _nCrate
unsigned int _nMod
unsigned int _nModType
unsigned int _nI
unsigned int _nJ
unsigned int _nK
indexMap_t _crateIndex
std::vector< unsigned int > _crateNumber
std::vector< unsigned int > _slotIndex
std::vector< unsigned int > _slotNumber
std::vector< bool > _slotAvailable
std::vector< bool > _connectionAvailable
std::vector< bool > _moduleAvailable
std::vector< unsigned int > _typeVmodule
std::vector< unsigned int > _connectionVmodule
std::vector< bool > _connectionVmoduleAvailable
std::vector< unsigned int > _moduleVconnection
std::vector< unsigned int > _kVmodule
std::vector< bool > _kVmoduleAvailable
std::vector< unsigned int > _moduleVk
std::vector< bool > _kAvailable
std::vector< unsigned int > _moduleTypeName
std::vector< unsigned int > _moduleTypeIndex
std::vector< bool > _moduleTypeAvailable
std::vector< std::vector
< unsigned int > > _ijVchan
std::vector< std::vector< bool > > _chipChanAvailable
std::vector< std::vector
< unsigned int > > _chanVij
std::vector< std::vector< bool > > _ijAvailable
std::vector< std::vector< bool > > _ijSecondaryAvailable
std::vector< std::vector
< unsigned int > > _sizeIVchan
std::vector< std::vector
< unsigned int > > _sizeJVchan
Detailed Description
AHCAL implementation of Mapper class.
invalid cells and exception handling
Most functions throw a CALICE::BadDataException if an invalid combination or ID is queried. Not all invalid combinations will be detected by all commands, depending on the necessary coordinate transformations in the command. E.g.: When querying the module from a Mokka cell ID, only K is extracted from the ID. If no module exists for this K an exception is thrown. But there will be no exception thrown if K is valid but I and J belong to a channel which does not exist in this module.
The protected getIndexFunctions do not throw exceptions to allow a fast lookup of the index. Invalid channels are signalled with return value maxIndex+1.
Some functions have a second version that does a full check if the ID is valid without throwing an exception.
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
0.3
Date
January 2010
Definition at line 44 of file AhcMapper.hh.
Member Function Documentation
void CALICE::AhcMapper::fill (const lcio::LCCollection * moduleDescriptionCol, const lcio::LCCollection * moduleConnectionCol) inline
fills all necessary mapping information
Module layout types are set from moduleDescription (chip,channel to I,J,K & size) Module connections are set from moduleConnection (crate, slot, fe to module)
Old settings are cleared before new are set.
Parameters
[in] moduleDescriptionCol LCGenericObject collection of ModuleDescription type
[in] moduleConnectionCol LCGenericObject collection of ModuleConnection type
Definition at line 937 of file AhcMapper.hh.
References fillModuleConnection(), and fillModuleDescription().
void CALICE::AhcMapper::fillModuleConnection (const lcio::LCCollection * col) private
sets the mapping information in the class, call after fillModuleDescription
The internal mapping of modules to type and electronics connection is set.
Parameters
[in] col LCGenericObject collection of ModuleConnection type
Definition at line 15 of file AhcMapper.cc.
References CALICE::Mapper::mappingModified().
Referenced by fill(), and updateConnections().
void CALICE::AhcMapper::fillModuleDescription (const lcio::LCCollection * col) private
sets the module layout information in the class, module connection information will be invalidated
The internal layout of modules, like channel to I,J,K and cell sizes are set.
Warning
module connection information will be invalidated, fillModuleConnection has to be called aftwards
Parameters
[in] col LCGenericObject collection of ModuleDescription type
Definition at line 121 of file AhcMapper.cc.
References CALICE::CellIndex::getPadColumn(), CALICE::CellIndex::getPadRow(), and CALICE::Mapper::mappingModified().
Referenced by fill().
int CALICE::AhcMapper::getCellIDOfIndex (unsigned int index) const inline protected virtual
get the cell ID of a certain compact index
Warning
This cell ID will only contain information about I, J and K. If the encoding string contains additional fields this will have value 0.
See Also
setCellIDencoding
Returns
(Mokka) cell ID
Implements CALICE::Mapper.
Definition at line 1061 of file AhcMapper.hh.
References CALICE::DecoderSet::getCellID(), CALICE::Mapper::getDecoder(), getI(), getJ(), and getK().
unsigned int CALICE::AhcMapper::getChan (const unsigned int i, const unsigned int j, const unsigned int k) const inline
chip number from triple I, J, K
Parameters
[in] i I
[in] j J
[in] k K
Exceptions
BadDataException if invalid channel
Returns
channel number
Definition at line 255 of file AhcMapper.hh.
References getModule().
Referenced by getChanFromCellID(), getISizeFromIJK(), and getJSizeFromIJK().
unsigned int CALICE::AhcMapper::getChip (const unsigned int i, const unsigned int j, const unsigned int k) const inline
chip number from triple I, J, K
Parameters
[in] i I
[in] j J
[in] k K
Exceptions
BadDataException if lookup fails
Returns
chip number
Definition at line 219 of file AhcMapper.hh.
References getModule().
Referenced by getChipFromCellID(), getISizeFromIJK(), and getJSizeFromIJK().
unsigned int CALICE::AhcMapper::getCrate (const unsigned int module) const inline
crate number from module number
Parameters
[in] module module number
Exceptions
BadDataException if lookup fails
Returns
crate number
Definition at line 303 of file AhcMapper.hh.
Referenced by getCrateFromCellID(), getCrateFromModuleID(), and print().
unsigned int CALICE::AhcMapper::getFe (const unsigned int module) const inline
front end number from module number
Parameters
[in] module module number
Exceptions
BadDataException if lookup fails
Returns
front end number
Definition at line 390 of file AhcMapper.hh.
Referenced by getFeFromCellID(), getFeFromModuleID(), and print().
unsigned int CALICE::AhcMapper::getI (const unsigned int module, const unsigned int chip, const unsigned int chan) const inline
I of (Mokka) cellID.
Parameters
[in] module module number
[in] chip chip number
[in] chan channel number
Exceptions
BadDataException if lookup fails
Returns
I
Definition at line 435 of file AhcMapper.hh.
Referenced by getCellIDFromModChipChan(), getCellIDOfIndex(), getIFromDAQID(), and getIFromModuleID().
unsigned int CALICE::AhcMapper::getIndexByCellID (const int cellID) const inline protected virtual
get a compact index for storing data in vectors
Parameters
[in] cellID (Mokka) cell ID
Returns
compact index
Implements CALICE::Mapper.
Definition at line 975 of file AhcMapper.hh.
References CALICE::Mapper::getDecoder(), CALICE::DecoderSet::getIFromCellID(), CALICE::DecoderSet::getJFromCellID(), CALICE::DecoderSet::getKFromCellID(), and getMaxIndex().
Referenced by getModuleFromCellID().
unsigned int CALICE::AhcMapper::getIndexByDAQID (const int ID) const inline protected virtual
get a compact index for storing data in vectors
Parameters
[in] ID DAQ channel ID
Returns
compact index
Implements CALICE::Mapper.
Definition at line 998 of file AhcMapper.hh.
References CALICE::DecoderSet::getChannelFromDAQID(), CALICE::DecoderSet::getChipFromDAQID(), CALICE::DecoderSet::getCrateFromDAQID(), CALICE::Mapper::getDecoder(), CALICE::DecoderSet::getFeFromDAQID(), getMaxIndex(), and CALICE::DecoderSet::getSlotFromDAQID().
Referenced by getModuleFromDAQID().
unsigned int CALICE::AhcMapper::getIndexByModuleID (const int ID) const inline protected virtual
get a compact index for storing data in vectors
Parameters
[in] ID Module channel ID
Returns
compact index
Implements CALICE::Mapper.
Definition at line 1033 of file AhcMapper.hh.
References CALICE::DecoderSet::getChannelFromModuleID(), CALICE::DecoderSet::getChipFromModuleID(), CALICE::Mapper::getDecoder(), getMaxIndex(), and CALICE::DecoderSet::getModuleFromModuleID().
Referenced by getModuleFromModuleID().
unsigned int CALICE::AhcMapper::getISize (const unsigned int module, const unsigned int chip, const unsigned int chan) const inline
get cell size in I direction of (Mokka) CellID coordinate
Parameters
[in] module module number
[in] chip chip number
[in] chan channel number
Returns
size in I
Exceptions
BadDataException if lookup fails
Definition at line 605 of file AhcMapper.hh.
Referenced by getISizeFromDAQID(), getISizeFromIJK(), and getISizeFromModuleID().
unsigned int CALICE::AhcMapper::getISizeFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const inline
get cell size in I direction of (Mokka) CellID coordinate
Parameters
[in] i I
[in] j J
[in] k K
Returns
size in I
Exceptions
BadDataException if lookup fails
Definition at line 591 of file AhcMapper.hh.
References getChan(), getChip(), getISize(), and getModule().
Referenced by getISizeFromCellID().
unsigned int CALICE::AhcMapper::getJ (const unsigned int module, const unsigned chip, const unsigned chan) const inline
J of (Mokka) cellID.
Parameters
[in] module module number
[in] chip chip number
[in] chan channel number
Exceptions
BadDataException if lookup fails
Returns
J
Definition at line 484 of file AhcMapper.hh.
Referenced by getCellIDFromModChipChan(), getCellIDOfIndex(), getJFromDAQID(), and getJFromModuleID().
unsigned int CALICE::AhcMapper::getJSize (const unsigned int module, const unsigned int chip, const unsigned int chan) const inline
get cell size in J direction of (Mokka) CellID coordinate
Parameters
[in] module module number
[in] chip chip number
[in] chan channel number
Returns
size in J
Exceptions
BadDataException if lookup fails
Definition at line 683 of file AhcMapper.hh.
Referenced by getJSizeFromDAQID(), getJSizeFromIJK(), and getJSizeFromModuleID().
unsigned int CALICE::AhcMapper::getJSizeFromIJK (const unsigned int i, const unsigned int j, const unsigned int k) const inline
get cell size in J direction of (Mokka) CellID coordinate
Parameters
[in] i I
[in] j J
[in] k K
Returns
size in J
Exceptions
BadDataException if lookup fails
Definition at line 669 of file AhcMapper.hh.
References getChan(), getChip(), getJSize(), and getModule().
Referenced by getJSizeFromCellID().
unsigned int CALICE::AhcMapper::getK (const unsigned int module) const inline
K of (Mokka) cellID.
Parameters
[in] module module number
Returns
K
Exceptions
BadDataException if lookup fails
Definition at line 531 of file AhcMapper.hh.
Referenced by CALICE::AhcMedianFilterTempProvider::applyCorrection(), getCellIDFromModChipChan(), getCellIDOfIndex(), getKFromDAQID(), getKFromModuleID(), and print().
unsigned int CALICE::AhcMapper::getMaxIndex () const inline protected virtual
get the maximum value of the compact index for storing data in vectors
Returns
maximum compact index
Implements CALICE::Mapper.
Definition at line 1057 of file AhcMapper.hh.
Referenced by getIndexByCellID(), getIndexByDAQID(), and getIndexByModuleID().
unsigned int CALICE::AhcMapper::getModule (const unsigned int crate, const unsigned int slot, const unsigned int fe) const inline
module number from triple crate, slot, fe
Parameters
[in] crate crate number (should be 0xac)
[in] slot slot number
[in] fe fe number
Returns
module number
Exceptions
BadDataException if lookup fails
Definition at line 118 of file AhcMapper.hh.
Referenced by getChan(), getChip(), getISizeFromIJK(), getJSizeFromIJK(), getModuleFromCellID(), getModuleFromDAQID(), getTrueIFromIJK(), and getTrueJFromIJK().
unsigned int CALICE::AhcMapper::getModule (const unsigned int k) const inline
module number from K
Parameters
[in] k K
Exceptions
BadDataException if lookup fails
Returns
module number
Definition at line 135 of file AhcMapper.hh.
References CALICE::DecoderSet::getCellIDEncoding(), and CALICE::Mapper::getDecoder().
unsigned int CALICE::AhcMapper::getSlot (const unsigned int module) const inline
slot number from module number
Parameters
[in] module module number
Exceptions
BadDataException if lookup fails
Returns
slot number
Definition at line 346 of file AhcMapper.hh.
Referenced by getSlotFromCellID(), getSlotFromModuleID(), and print().
void CALICE::AhcMapper::print (std::ostream & ostream) const
print current data contents
A detailed printout of the current layout is sent to the given stream.
Parameters
[out] ostream stream for the output
Definition at line 286 of file AhcMapper.cc.
References getCrate(), getFe(), getK(), and getSlot().
void CALICE::AhcMapper::printStats (std::ostream & ostream) const
print summary of current data contents
A summary of the current number of module types, modules, etc... is printed.
Parameters
[out] ostream stream for the output
Definition at line 254 of file AhcMapper.cc.
void CALICE::AhcMapper::updateConnections (const lcio::LCCollection * moduleConnectionCol) inline
updates the mapping information in the class (possible after first fill only)
The internal mapping of modules to type and electronics connection is updated.
Parameters
[in] moduleConnectionCol LCGenericObject collection of ModuleConnection type
Definition at line 949 of file AhcMapper.hh.
References fillModuleConnection().
The documentation for this class was generated from the following files:
AhcMapper.hh
AhcMapper.cc