CALICE_USERLIB: CALICE::ModuleDescription Class Reference
CALICE::ModuleDescription Class Reference
Description of Calice (ECAL) detector modules.
#include <ModuleDescription.hh>
Public Member Functions
ModuleDescription ()
Default c'tor.
ModuleDescription (const ModuleDescription &a)
ModuleDescription (UChar_t module_type, UInt_t n_cells, const std::string &name, EModuleDescriptionOptions options=kModuleDescriptionNormal)
UsefulConstructor.
ModuleDescription & setModuleType (UChar_t type)
UChar_t getModuleType () const
bool isValid () const
return if the ModuleDescription object is defined.
std::string getModuleTypeName () const
Get the name assigned to the module type.
ModuleDescription & setCellXPos (UInt_t cell_index, float x_pos)
ModuleDescription & setCellYPos (UInt_t cell_index, float y_pos)
ModuleDescription & setCellPos (UInt_t cell_index, float x_pos, float y_pos)
ModuleDescription & setCellZPos (UInt_t cell_index, float z_pos)
Set the cell z-position.
Float_t getCellXPos (UInt_t cell_index) const
Float_t getCellYPos (UInt_t cell_index) const
Float_t getCellZPos (UInt_t cell_index) const
Get the z position offset of an individual cell.
UInt_t getNCells () const
bool hasCellDimensionsPerCell () const
Return true if there are cell dimensions (width and height) per cell.
bool hasCellZPos () const
Return true if the cells have also a z-position offset.
ModuleDescription & setCellWidth (float cell_width)
float getCellWidth () const
ModuleDescription & setCellHeight (float cell_height)
float getCellHeight () const
ModuleDescription & setIndividualCellWidth (UInt_t cell_index, float cell_width)
Set the indivual cell width.
float getIndividualCellWidth (UInt_t cell_index) const
Return the width of a specific cell.
ModuleDescription & setIndividualCellHeight (UInt_t cell_index, float cell_height)
Set the indivual cell height.
float getIndividualCellHeight (UInt_t cell_index) const
Return the height of a specific cell.
ModuleDescription & setWidth (float width)
float getWidth () const
ModuleDescription & setHeight (float height)
float getHeight () const
ModuleDescription & setGeometricalCellIndex (UInt_t cell_index, UInt_t geometrical_cell_index)
Set the geometrical cell index of the specified cell.
UInt_t getGeometricalCellIndex (UInt_t cell_index) const
Get the geometrical cell index of the specified cell which respects the Mokka notation.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
ModuleDescription (LCObject *obj)
C'tor to be used for elements of LCGenericObjects read from an LCIO file or the database.
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~ModuleDescription ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Protected Member Functions
void init () noexcept(false)
Protected Attributes
LCGenericObjectImpl * _obj
bool _createdObject
unsigned int _nCells
unsigned int _cellIndexStart
unsigned int _cellDimensionStart
unsigned int _cellZPosStart
Detailed Description
Description of Calice (ECAL) detector modules.
Based on LCFixedObject.
Author
Goetz Gayckem, LLR - ecole polytechnique)
Version
Id:
ModuleDescription.hh,v 1.7 2009-07-02 13:07:56 meyern Exp
Definition at line 42 of file ModuleDescription.hh.
Constructor & Destructor Documentation
CALICE::ModuleDescription::ModuleDescription (LCObject * obj) inline
C'tor to be used for elements of LCGenericObjects read from an LCIO file or the database.
Subclasses should 'override' this, e.g.:
Myclass(LCObject* obj) : ModuleDescription(obj) {}
Definition at line 450 of file ModuleDescription.hh.
References CALICE::getNeededInts(), and obj().
Member Function Documentation
Float_t CALICE::ModuleDescription::getCellZPos (UInt_t cell_index) const inline
Get the z position offset of an individual cell.
The result of this call is only defined if hasCellZPos returns true.
Definition at line 242 of file ModuleDescription.hh.
UInt_t CALICE::ModuleDescription::getGeometricalCellIndex (UInt_t cell_index) const inline
Get the geometrical cell index of the specified cell which respects the Mokka notation.
The geometrical cell index conforms to the Mokka notation. It contains the layer index, the wafer row and column and the the pad row and column. The indices stored in the ModuleDescription object only contain the wafer row, column, pad row and column. The layer index, and on offset to the wafer column and row must be added to form an index in the notation which is Mokka conform.
Todo:
I did not find a more clever way than putting this index into the database.
Definition at line 419 of file ModuleDescription.hh.
float CALICE::ModuleDescription::getIndividualCellHeight (UInt_t cell_index) const inline
Return the height of a specific cell.
This call only is defined if hasCellDimensionsPerCell returns true.
Definition at line 360 of file ModuleDescription.hh.
float CALICE::ModuleDescription::getIndividualCellWidth (UInt_t cell_index) const inline
Return the width of a specific cell.
This call only is defined if hasCellDimensionsPerCell returns true.
Definition at line 335 of file ModuleDescription.hh.
std::string CALICE::ModuleDescription::getModuleTypeName () const inline
Get the name assigned to the module type.
The module type number is generally considered to be unique. It should not be necessary to query the name and map type numbers to module names. Due to the character encoding in an integer array, the function may perform slowly.
Definition at line 167 of file ModuleDescription.hh.
References CALICE::getStringFromInts().
Referenced by CALICE::MappingAndAlignment::correctFullHalfConnectorErrors().
bool CALICE::ModuleDescription::hasCellDimensionsPerCell () const inline
Return true if there are cell dimensions (width and height) per cell.
if there are no cell dimensions per cell the result of the calls getIndividualCellWidth and getIndividualCellHeight will be undefined (most likely this will cause a segmentation violation). If there are cell dimensions per cell then the calls getCellWidth() and getCellHeight will cause an exception.
Definition at line 276 of file ModuleDescription.hh.
bool CALICE::ModuleDescription::hasCellZPos () const inline
Return true if the cells have also a z-position offset.
If the cells do not have a z-position offset then the result of the call getZPos will be undefined (i.e. most likely will cause a segmentation vaiolation).
Definition at line 284 of file ModuleDescription.hh.
LCGenericObjectImpl* CALICE::ModuleDescription::obj () inline
The LCGenericObjectImpl .
Sublcasses use this to access their data.
Definition at line 534 of file ModuleDescription.hh.
Referenced by ModuleDescription().
ModuleDescription& CALICE::ModuleDescription::setCellZPos (UInt_t cell_index, float z_pos) inline
Set the cell z-position.
The result of this call is only defined if hasCellZPos returns true.
Definition at line 204 of file ModuleDescription.hh.
ModuleDescription& CALICE::ModuleDescription::setGeometricalCellIndex (UInt_t cell_index, UInt_t geometrical_cell_index) inline
Set the geometrical cell index of the specified cell.
Parameters
cell_index the cell index (zero to n) which reflects the ADC read order: line zero to line 12 (6 for half equipped lines) of the first sample (each line is connected to one readout chip), then the next sample which is multiplexed on the same 12(6 for half equipped modules) lines. In total 18 samples are read i.e. the index runs from 0 to 215 or from 0 to 107.
geometrical_cell_index the Mokka conform geometrical cell index. The geometrical cell index (should) respects the Mokka notation. It contains the layer index, the wafer row and column and the the pad row and column. The indices stored in the ModuleDescription object only contain the wafer row, column, pad row and column. The layer index, and on offset to the wafer column and row must be added to form an index in the notation which is conforming to Mokka.
Todo:
I did not find a more clever way than putting this index into the database.
Definition at line 398 of file ModuleDescription.hh.
ModuleDescription& CALICE::ModuleDescription::setIndividualCellHeight (UInt_t cell_index, float cell_height) inline
Set the indivual cell height.
The result of the call will be undefined if hasCellDimensionsPerCell is not true.
Definition at line 346 of file ModuleDescription.hh.
ModuleDescription& CALICE::ModuleDescription::setIndividualCellWidth (UInt_t cell_index, float cell_width) inline
Set the indivual cell width.
The result of the call will be undefined if hasCellDimensionsPerCell is not true.
Definition at line 321 of file ModuleDescription.hh.
The documentation for this class was generated from the following file:
ModuleDescription.hh