CALICE_USERLIB: CALICE Namespace Reference
CALICE Namespace Reference
Store strings in LCGenericObjects.
Data Structures
class AcquisitionData
Class to store acquisition data info, i.e.
class AdcBlock
Class for the ADC Data as acquired by the CALICE DAQ.
class Ahc2Calibrations
storing all informations necessary to calibrate a HBU SiPM read channel
class Ahc2CalibrationStatusBits
Bit set to describe the Ahc2 Calibration Status.
class Ahc2HardwareConnection
Class to store int values for HardwareConnection plus integer cell index in LCIO.
class Ahc2SatCorr
class Ahc2TileIndex
Encodes/decodes hardware channel information for the Large CALICE AHCAL prototype.
class AhcAmplitude
class AhcCern2010TempProvider
This is a temperature provider for the AHCAL.based on the studies of the temperature profiles from CERN 2010 data.
class AhcConditions
Class for the CALICE Ahcal conditions information during the reconstruction.
class AhcMedianFilterTempProvider
This is a very simple temperature provider for the ahcal.
class AhcSimpleTempProvider
This is a very simple temperature provider for the ahcal.
class AhcSlowReadoutBlock
Interface Class to access the AhcSlowConfiguration Data For the time being we treat only the movable stage positions Update: 6/7/08 Added z and rotated position of stage (Maintain backward compatibility)
class AhcSlowReadoutModBlock
Interface Class to access the AhcSlowReadout Data Here we handle ahc voltages, temperatures et al.
class AhcSlowReadoutModMapper
Class to correct the mapping of AhcSlowReadoutModBlock-classes.
class AhcSlowReadoutModMapping
Class to store the mapping corrections for the AhcSlowReadoutModBlock.
class AhcTempProvider
This is an abstract class defining an interface to access the temperatures in single AHCAL cells.
class AhcTempSensorIndex
AhcTempSensorIndex represents and Ahcal Temperature Sensor Index So what? it encodes (modules,sensor) into an integer.
class AhcVfeConfigurationBlock
Interface Class to access the AhcVfeConfigurationData.
class Alignment
Class to comunicate/handle the translation into unique layer/cell ids and 3D spacial coordinates.
class BeamMetaData
class BeamMomentum
Class to claculate the beam momentum and momentum spread from beamline slow readout data.
class BeamMomentumException
excpetion during beam momentum calculation
class BeamParameter
Define the experimental setup: beam energy, position, angle and detector position, angle.
class BeamParameterException
This class handles beam parameters which have been written by hand into the database.
class BeEvent
Stores the trigger history (i.e.
class BeTrgConf
Stores the configuration data of the trigger.
class BeTrgEvent
Stores the trigger event data.
class BeTrgPollData
Class to store info on trigger polling, This is useful to detect a softtrigger among e.g.
class BinnedVector
Template class to store data via a linear binned keys.
class BitSet
Base class for easy definition of bit sets.
class BmlCaen1290ConfigurationBlock
class BmlCaen767ConfigurationBlock
Class to store configuration data of the 767 Caen TDC obsolete as of 31/10/10, replaced by BmlCaenConfigurationBlock, kept for backward compatibility of the code.
class BmlCaen767ReadoutConfigurationBlock
Stores the configuration of the Caen767 TDC into the database At the moment I am writing this class I don't know whether they'll serve for something but it is a small uncomplicated class, so here we go.
class BmlCaenConfigurationBlock
Class to store configuration data of the Caen TDCs (767, 1290) Replaces BmlCaen767ConfigurationData.
class BmlEventData
Class to store the BmlEventData.
class BmlEventDataSup
Class to store supplementary BmlEventData.
class BmlSlowRunDataBlock
Interface Class to access the BmlSlowRun Data Here we handle ahc voltages, temperatures et al.
class BoardID
Create a packed board id of crate, slot, component numbers and the label.
class CalibrationWriter
Class which handles the module wise storage of conditions data and the access to the lccd framework (i.e.
class CaliceConditions
Class for the CALICE Ahcal conditions information during the reconstruction.
class CaliceElogInfo
Implementation of the e-log information.
class WrongDataFormatException
exception to be thrown when the data type in a parameter is wrong
class BadDataException
exception to be thrown when data leads to a conflict
class CaliceHit
Class for the CALICE Hcal calorimeter hit information during the reconstruction.
class CellIndex
The Mokka conform cell index.
class CellMappingHcal
Example for a simple mapping class based on the LCFixedObject template.
class CellQuality
LCIO contions data class to describe the cell quality.
class ClusterShapesTyped
class ConditionsChangeDelegator
Listens for conditions data changes and delegates the information to a class.
class ConditionsDataWriteHandler
Handler of conditions data changes which writes the replaced collections to a conditions data base.
class ConnCellMappingHcal
Mapping class based on the LCFixedObject template.
class DAQconnection
Class to store the DAQ address of a singel channel.
class DaqRunSummaryBlock
Stores a summary of a run in terms of Number of Congfiuration Changes, Slow Readouts, Acquisitions and Number of Events in additions it stores the time of a run and for convenience the run number.
class DaqTypeDataBlock
Base Class to handle all daq types (for the time being apart from the actual crc data) This base class constains the functions to store the data The actual handling of the data is left to dedicated classes which have to derive from this class.
class DCIndex
class DeadNoiseConstants
Class to store the results of a selection of dead or noisy cells for a certain chip/channel for a fixed moduleID.
class DetectorTransformation
Define the experimental setup: beam energy, position, angle and detector position, angle.
class DhcRawChipContent
Simple class which stores the dhcal chip content Note that the dchal as it is now delivers the same time stamp for all 64 channels served by a chip.
class DhcReadoutConfBlock
Class to interface the configuration of the Dhcal fes.
class DifTrigger
Simple class which stores the trigger counter retrieved from the DIF cards.
class DriftChamberParameter
Parameters for one drift chamber.
class EcalModuleCalibration
Calibration constants for the Calice ECAL detector modules.
class EmcStageDataBlock
Stores information about the Emc stage Here we need to duplicate a lot of code already written by Paul since we cannot top the 'intelligence' which is introduced already there.
class EncodingStringHelper
Utility class to get the field description according to an lcio BitField64.
class ErrorBits
Helper class to query or set the event errors.
class EUDAQBlock
Class for the SLCIO EUDAQ Data as acquired by the EUDAQ system.
class EUDAQTempSensorBlock
Class for the temperature sensor data as acquired by the AHCAL EUDAQ.
class EventHeader
Class to store event header info, i.e.
class EventVariables
class ExperimentalSetup
Define the experimental setup: beam energy, position, angle and detector position, angle.
struct FastCaliceHitMemoryPool
class FastCaliceHit
Using RawCalorimeterHits as FastCaliceHits.
class FeConfigurationBlock
Stores the configuration data of the front-end of one CERC board.
class FeEvent
Stores the trigger history (i.e.
class FeInfo
Stores the configuration data of the front-end of one CERC board.
class FeTrgData
Stores the trigger history (i.e.
class GainConstants
Class to store the results of a Gain calibration measurement, i.e.
class HcalBoardsConn
Mapping class based on the LCFixedObject template.
class HcalCassVsCrc
Mapping class based on the LCFixedObject template that relates hcal-cassette <-> crc board.
class HcalCellIndex
like CALICE::CellIndex, but with HCAL related funciton names
class HcalModuleIndexReverseLookup
Class to simplify the lookup geometrical index to hardware index.
class HcalTileIndex
Encodes/decodes hardware channel information for the CALICE AHCAL prototype.
class HitVariables
class HodoscopeBlock
Class for the SLCIO hododscope as acquired by the EUDAQ system.
class HodoscopeEventDataBlock
Interface class to the (LAL) Hodoscope data.
class InterConstants
Class to store the results of a inter calibration measurement, i.e.
class LabviewBlock2
Class for the Labview Data as acquired by the AHCAL Labview.
class LayerVariables
class LCGenericObjectImplCloner
Utility class to clone a LCGenericObject this is needed is needed since during the writing of CALICE conditions data a full collection has to be memorized until a new set of this datatype appears.
class LCGenericObjectImplExt
Extends functionality of the LCGenericObjectImpl Class It simply adds a new constructor to the LCGenericObject Class such that we can construct an interface class around without being restricted by the LCFixedObject It uses an instance of LCGenericObjectImpl that holds the data, thus there is no overhead when the data is read from a database or file for copying it to some local structure (Decorator pattern).
class LCHcalCalibrationObject
Object to store information about arbitrary cell wise calibration of the HCAL in LC Objects.
class LCHcalCalibrationObject2D
The results of the calibrations done by LCHcalCalibrationObject2D can depend on two sets of input values (like saturation correction)
class LinearFitCompound
Class to store the constant of a linear fit within the lcio framework.
class LinearFitConstant
Class to store the constant of a linear fit within the lcio framework.
class LinearFitResult
Class to store the result of a linear fit within the lcio framework.
class LinearFitSlope
Class to store the slope of a linear fit within the lcio framework.
class MappingAndAlignment
Class to comunicate/handle the translation into unique layer/cell ids and 3D spacial coordinates.
class MergedHitOrigin
Class for indicating origin of hits in merged event.
class MIPConstants
Class to store the results of a MIP calibration measurement, i.e.
class ModuleConnection
Defines the electric connection of a module.
class ModuleDescription
Description of Calice (ECAL) detector modules.
class ModuleLocation
Define possible positions of modules.
class MultipleConditionsChangeDelegator
Listens for conditions data changes and delegates the information to a class.
class NVector_t
Simple n-dimensional vector (size of the vector is defined at compile time) Provides methods to add and subtract vectors or multiply and divide by scalars.
class PedestalConstants
Class to store the results of a pedestal measurement, i.e.
class ReadOutConfigurationBlock
Stores the general readout configuration.
class RunLocation
run and the generic run type i.e.
class RunLocationWhizard
Simple interface class to retrieve information about the location of a run It accesses the runlocation folder in the database.
class RunOffsetValue
Class to store float value, its error, and status flag plus integer index in LCIO.
class RunTimeConditionsHandler
Implementation of ConditionsHandlerBase that can be used to propagate conditions data that were generated at runtime.
class RunTimeInfo
Simple class which holds the start and stop times of runs.
class RunTimeWhizard
Simple interface class to retrieve the run start and stop times by means of the runnumber.
class SatCorrFunction
interface for a function to correct (or apply) the SiPM saturation
class SatCorrItep
class SatCorrItepCutOff
class SaturationConstants
Class to store the parametrisation of the saturation curve (no error yet) for a certain chip/channel for a fixed moduleID.
class SaturationParameters
Class to store float values for Saturation Correction Curves plus integer cell index in LCIO.
class ScECALGainfit
class ScECALIntercalib
class ScECALMapping
class ScECALMIPfit
Class to store the constant of a ScECAL MIP fit within the lcio framework.
class ScECALNoisyChannel
class ScECALOnePeADC
class ScECALTemperature
class SceSlowReadoutModBlock
Interface Class to access the SceSlowReadout Data Here we handle ahc voltages, temperatures et al.
class ScintCaloSlowReadoutModBlock
Interface Class to access the ScintCaloSlowReadout Data Here we handle ahc voltages, temperatures et al.
class SimpleValue
Class to store float value, its error, and status flag plus integer index in LCIO.
class SimpleValueVector
class SiPMCalibrations
storing all informations necessary to calibrate a SiPM read channel
class SiPMCalibrationStatusBits
Bit set to describe the SiPM Calibration Status.
class SiPMMappingHcal
Mapping class based on the LCFixedObject template.
class SiPMVolCorr
voltage corrections for Hcal SiPMs
class TcmtConnection
Defines the electronic connection of a TCMT strip.
class TcmtEventBits
Bit set to describe the type of event in the TCMT.
class TcmtEventIdentifier
class that can identify type of event in TCMT
struct TcmtHitMemoryPool
class TcmtHit
Using RawCalorimeterHits as TcmtHits.
class TcmtSaturationConstants
Class to store the estimates for the Cpix parameters for saturation corrections of TCMT hits.
class TdcConnection
class TdcIndex
class TempGainConstants
= class GainConstants but with temperature
class TilesItep
Parameters of the sipm delivered by ITEP.
class TilesItepSaturation
Parameters of the sipm delivered by ITEP.
class TilesProduction
Parameters of the sipm delivered by PRODUCTION.
class TrgReadoutConfigurationBlock
Stores the general readout configuration.
class TriggerBits
A small class which allow for the easy analysis of core trigger information.
class TriggerCheck
Example for a simple class based on the LCFixedObject template.
class TriggerHandler
Base Class for the user access to trigger decisions.
class TriggerHandlerCalice
Implementation of TriggerHandler base class for calice purposes Trigger conditions are read from a conditions data source or from the event information.
class TriggerHistory
Utility class to chech the zero suppressed trigger history which will be atteched to the lcio event.
class VetoFraction
Class to store the fraction of events that are cut with a certain purity setting of the veto.
class VetoThreshold
Container class to store the threshold necessary to achive a certain purity.
class Ahc2Mapper
AHCAL implementation of Mapper class.
class AhcMapper
AHCAL implementation of Mapper class.
class CellIterator
iterator to run over all valid (Mokka) cell IDs
class DecoderSet
class containing decoders for the three CALICE coordinate systems
class E4DMapper
AHCAL EPT implementation of Mapper class Functions to get dimensions of detector geometry.
class FastDecoder
decode IDs with encoding string
class MappedContainer
Container for fast access by index.
class Mapper
Mapping for CALICE detectors (currently: HCAL support only)
class CellDescription
class to hold data describing calorimeter cells
class CellDescriptionGenerator
class that generates cell descriptions objects
class CellNeighbourCalculator
class to calculate all neighbour cells
class CellNeighbours
class to hold information of neighbouring cells
Typedefs
typedef int AdcBlockArray [6]
typedef
ScintCaloSlowMeasuresDblMap_t AhcSlowMeasuresDblMap_t
The map which contains the measured values of the different types.
typedef
ScintCaloSlowMeasuresIntMap_t AhcSlowMeasuresIntMap_t
typedef
ScintCaloSlowMeasuresFloatMap_t AhcSlowMeasuresFloatMap_t
typedef std::map< unsigned int,
std::vector< std::pair< bool,
int > > > TDCChannelContainer_t
typedef std::map< unsigned,
lcio::LCCollectionVec * > CalibrationWriteMap
typedef std::map< std::string,
std::vector< double > > DaqTypeDataDblMap_t
The map which contains the measured values of the different data types.
typedef std::map< std::string,
std::vector< int > > DaqTypeDataIntMap_t
typedef std::map< std::string,
std::vector< unsigned int > > DaqTypeDataUIntMap_t
typedef std::map< std::string,
std::vector< float > > DaqTypeDataFloatMap_t
typedef std::map< std::string,
LCTime > TimeStampMap_t
and for the timestamps
typedef std::map< int, int > HodoscopeHitMap_t
typedef std::map< unsigned,
LCHcalCalibrationObject * > HcalCalibrationModuleMap
typedef std::pair
< lcio::LCCollection
*, HcalCalibrationModuleMap * > HcalCalibrationModuleData
typedef std::map< unsigned,
LCHcalCalibrationObject2D * > HcalCalibration2DModuleMap
typedef std::pair
< lcio::LCCollection
*, HcalCalibration2DModuleMap * > HcalCalibration2DModuleData
typedef NVector_t< Float_t, 3 > ThreeVector_t
A three dimensional single precision floating point vector.
typedef std::map< std::string,
std::vector< double > > ScintCaloSlowMeasuresDblMap_t
The map which contains the measured values of the different types.
typedef std::map< std::string,
std::vector< int > > ScintCaloSlowMeasuresIntMap_t
typedef std::map< std::string,
std::vector< float > > ScintCaloSlowMeasuresFloatMap_t
Enumerations
enum EAcqDataValues {
kAcqDataIntValAcqNumberRun, kAcqDataIntValAcqNumberConf, kAcqDataIntValAcqEvtInfo, kAcqDataIntValAcqTimeInfSec,
kAcqDataIntValAcqTimeInfMus, kAcqDataIntValAcqState, kAcqDataIntValHasDifInfo, kAcqDataIntValDifTriggerCounter,
kAcqDataIntValDifNdataBufferWords, kAcqDataIntValues
}
enum AhcSroDblValues {
kxPosition_mm, kyPosition_mm, kzPosition_mm, kcPosition_deg,
kSroDblValues
}
The indices of the the stored values.
enum AhcSroModIntValues { kIntAhcSroModPosCmbVals =kIntSroModPosCmbVolts+2, kIntAhcSroModPosHbabTemps =kIntAhcSroModPosCmbVals+2, kIntAhcSroModIntValues =kIntSroModPosHbabVolts+1 }
The indices of the the stored values.
enum AhcSroModDblValues { kIntAhcSroModDblValues }
enum AhcSroModFloatValues { kAhcIntSroModFloatValues }
enum AhcVfeIntValues { kIntValVfeBoardId, kIntAhcVfeRecLabel, kIntVerificationData, kIntShiftRegisterDataStart }
The indices of the the stored values.
enum EBeamParameterFloatType {
kBeamParameterFloatPeakEnergy, kBeamParameterFloatBeamAngleZX, kBeamParameterFloatBeamAngleZY, kBeamParameterFloatBeamImpactPositionX0,
kBeamParameterFloatBeamImpactPositionY0, kNBeamParameterFloats
}
enum EBeamParameterIntType { kBeamParameterIntBeamType, kNBeamParameterInts }
enum EBeamParameterExceptionIntType { kBeamParameterExceptionIntBeamEnergy, kNBeamParameterExceptionInts }
enum EBeEventIntValues {
kBeEventIntValBoardId, kBeEventIntValRecLabel, kBeEventIntValStatusWord, kBeEventIntValL1aCounter,
kBeEventIntValBxCounter, kBeEventIntValQdrFrameCounter, kBeEventIntValQdrDataCounter, kBeEventIntValTotalFrameCounter,
kNBeEventIntValues, kRunTimeStartMSB, kRunTimeStartLSB, kRunTimeStopMSB,
kRunTimeStopLSB, kNRunTimeIntValues
}
enum EBeTrfConfIntValues {
kBeTrgConfIntValBoardId, kIntRecLabel, kBeTrgConfIntValInputEnable, kBeTrgConfIntValOscillatorEnable,
kBeTrgConfIntValGeneralEnable, kBeTrgConfIntValOscillationPeriod, kBeTrgConfIntValBurstCounter, kBeTrgConfIntValConfiguration,
kBeTrgConfIntValFifoIdleDepth, kBeTrgConfIntValBusyTimeout, kBeTrgConfIntValBurstTimeout, kBeTrgConfIntValExtBeamMode,
kBeTrgConfIntValInputInvert, kBeTrgConfIntValQdrConfig, kBeTrgConfIntValSequencerControl, kBeTrgConfIntValAndEnable,
kNBeTrgConfIntValues =kBeTrgConfIntValAndEnable+NLENGAND
}
The indices of all the stored values.
enum EBeTrgEventIntValues {
kBeTrgEventIntValBoardId, kBeTrgEventIntValRecLabel, kBeTrgEventIntValInputStatus, kBeTrgEventIntValInputCatch,
kBeTrgEventIntValprebusyCatch, kBeTrgEventIntValsignalCatch, kBeTrgEventIntValcontrol, kBeTrgEventIntValInitialFifoStatus,
kBeTrgEventIntValFinalFifoStatus, kBeTrgEventIntValtriggerCounter, kBeTrgEventIntValpreBusyTriggerCounter, kNBeTrgEventIntValues
}
The indices of all the stored values.
enum EBeTrgPollIntValues {
kBeTrgPollBoardID, kBeTrgPollRecordLabel, kBeTrgPollstartTimeymd, kBeTrgPollstartTimehms,
kBeTrgPollstartTimemus, kBeTrgPollendTimeymd, kBeTrgPollendTimehms, kBeTrgPollendTimemus,
kBeTrgPollmaxTimesec, kBeTrgPollmaxTimemus, kBetrgPollnumberOfPolls, kBeTrgPollTimeout,
kBeTrgPollIntValues
}
The indices of all the stored values.
enum EBmlCaen1290IntValues {
kBmlCaen1290ConfBoardID, kBmlCaen1290ConfBaseAddress, kBmlCaen1290ConfRecordLabel, kBmlCaen1290ConfControlRegister,
kBmlCaen1290ConfInterruptRegister, kBmlCaen1290ConfCountRegister, kBmlCaen1290ConfIntValues
}
enum EBmlCaen767IntValues {
kBmlCaen767ConfBoardID, kBmlCaen767ConfBaseAddress, kBmlCaen767ConfRecordLabel, kBmlCaen767ConfControlRegister,
kBmlCaen767ConfInterruptRegister, kBmlCaen767ConfIntValues, kBmlCaen767RoConfCrateNumber, kBmlCaen767RoConfReadPeriod,
kBmlCaen767RoConfBoolCol, kBmlCaen767RoConfMode, kBmlCaen767RoConfIntValues
}
enum EBmlCaen767IntValues {
kBmlCaen767ConfBoardID, kBmlCaen767ConfBaseAddress, kBmlCaen767ConfRecordLabel, kBmlCaen767ConfControlRegister,
kBmlCaen767ConfInterruptRegister, kBmlCaen767ConfIntValues, kBmlCaen767RoConfCrateNumber, kBmlCaen767RoConfReadPeriod,
kBmlCaen767RoConfBoolCol, kBmlCaen767RoConfMode, kBmlCaen767RoConfIntValues
}
The indices of all the stored values.
enum EBmlCaenIntValues {
kBmlCaenConfBoardID, kBmlCaenConfBaseAddress, kBmlCaenConfRecordLabel, kBmlCaenConfControlRegister,
kBmlCaenConfInterruptRegister, kBmlCaenConfCountRegister, kBmlCaenConfSpare, kBmlCaenConfIntValues
}
enum EBmlEventIntValues {
kBmlEventBoardID, kBmlEventBaseAddress, kBmlEventRecordLabel, kBmlEventStatusRegister,
kBmlEventNumberOfWords, kBmlEventgeoAddress, kBmlEventeventNumber, kBmlEventStatus,
kBmlEventEventDataCounter, kBmlEventNumberOfSignalChannels, kBmlEventIntValues
}
The indices of all the stored values.
enum EBmlEventSupIntValues {
kBmlEventSupFifo, kBmlEventSupEventIDTrailer, kBmlEventSupBunchID, kBmlEventSupTDCErrors,
kBmlEventSupBufferOverflow, kBmlEventSupTriggerLost, kBmlEventSupTDCWordCountTrailer, kBmlEventNamesPointer,
kBmlEventNamesLength, kBmlEventSupIntValues
}
The indices of all the stored values.
enum BmlSroRunIntValues {
kIntBmlSroRunPosTimeStampymd, kIntBmlSroRunPosTimeStamphms, kIntBmlSroRunPosSextCur, kIntBmlSroRunPosBendCur =kIntBmlSroRunPosSextCur+2,
kIntBmlSroRunPosColPos =kIntBmlSroRunPosBendCur+2, kIntBmlSroRunPosQuadCur =kIntBmlSroRunPosColPos+2, kIntBmlSroRunPosTrimCur =kIntBmlSroRunPosQuadCur+2, kIntBmlSroRunPosH6aExpCount =kIntBmlSroRunPosTrimCur+2,
kIntBmlSroRunPosH6bExpCount =kIntBmlSroRunPosH6aExpCount+2, kIntBmlSroRunPosH6cExpCount =kIntBmlSroRunPosH6bExpCount+2, kIntBmlSroRunPosRpExpCount =kIntBmlSroRunPosH6cExpCount+2, kIntBmlSroRunPosScintCount =kIntBmlSroRunPosRpExpCount+2,
kIntBmlSroRunIntValues
}
The map which contains the measured values of the different data types.
enum BmlSroRunDblValues { kDblBmlSroRunPosAbsPosition, kDblBmlSroRunPosT4Position, kDblBmlSroRunPosTargetPosition, kIntBmlSroRunDblValues }
enum BmlSroRunFloatValues { kIntBmlSroRunFloatValues }
enum EDaqSumIntValues {
kDaqRunNum, kDaqNumConf, kDaqNumSro, kDaqNumAcq,
kDaqNumEvt, kDaqRunTime, kDaqNumIntVals
}
The indices of all the stored values.
enum DaqTypeIntValues {
kIntDaqTypeTimeStamps, kIntDaqTypeTimeStampNamesPointer, kIntDaqTypeTimeStampNamesLength, kIntDaqTypeIntTypes,
kIntDaqTypeDblTypes, kIntDaqTypeFloatTypes, kIntDaqTypeIntNamesPointer, kIntDaqTypeDblNamesPointer,
kIntDaqTypeFloatNamesPointer, kIntDaqTypeIntNamesLength, kIntDaqTypeDblNamesLength, kIntDaqTypeFloatNamesLength,
kIntDaqTypeIntSizes, kIntDaqTypeDblSizes, kIntDaqTypeFloatSizes, kIntDaqTypeDataStart
}
The indices of the the stored values.
enum DaqTypeDblValues { kIntDaqTypeDblReadings }
enum DaqTypeFloatValues { kIntDaqTypeFloatReadings }
enum EDetectorTransformationFloatType {
kDetectorTransformationFloatDetectorAngleZX, kDetectorTransformationFloatDetectorRotationX0, kDetectorTransformationFloatDetectorRotationZ0, kDetectorTransformationFloatDetectorX0,
kDetectorTransformationFloatDetectorY0, kDetectorTransformationFloatDetectorZ0, kNDetectorTransformationFloats
}
enum EDetectorTransformationIntType { kNDetectorTransformationInts }
enum EDhcRawChipContentIntValues {
kDhcRawChipIntCrateNr, kDhcRawChipIntElecAdr, kDhcRawChipIntHitsHi, kDhcRawChipIntHitsLo,
kDhcRawChipIntTimeStamp, kDhcRawChipIntMiscInfo, kDhcRawChipIntValues
}
enum EDhcreadoutConfigurationIntValues {
kDhcRoConfIntNumbers, kDhcRoConfIntSlotEnableMask, kDhcRoConfIntSlotEnable, kDhcRoConfIntNumSlots,
kDhcRoConfIntBeTimeDif, kDhcRoConfIntValues
}
enum EDifTriggerIntValues { kDifTriggerCounter, kDifTriggerIntValues }
enum EDriftChamberParameterFloatType {
kDriftChamberParameterFloatVelocity, kDriftChamberParameterFloatDelay, kDriftChamberParameterFloatOffsetZ, kDriftChamberParameterFloatOffsetU,
kDriftChamberParameterFloatError, kNDriftChamberParameterFloats
}
enum EDriftChamberParameterIntType { kDriftChamberParameterIntWireType, kNDriftChamberParameterInts }
enum EDriftChamberWireType {
kDriftChamberWireMinus, kDriftChamberWirePlus, kDriftChamberWireXMinus, kDriftChamberWireXPlus,
kDriftChamberWireYMinus, kDriftChamberWireYPlus, kNWireTypes
}
enum EEcalModuleCalibrationIntType { kEcalModuleCalibrationIntModuleID, kEcalModuleCalibrationIntNameLength, kNEcalModuleCalibrationInts }
enum EEcalModuleCalibrationFloatType { kNEcalModuleCalibrationFloats }
enum EEmcStIntValues {
kEmcStHeader, kEmcStxStatus, kEmcStxValue, kEmcStyStatus =kEmcStxValue+NUMXVALUES,
kEmcStyValue, kEmcStCheckSum =kEmcStyValue+NUMYVALUES
}
The indices of all the stored values.
enum EExperimentalSetupFloatType {
kExperimentalSetupFloatPeakEnergy, kExperimentalSetupFloatBeamAngleZX, kExperimentalSetupFloatBeamAngleZY, kExperimentalSetupFloatBeamImpactPositionX0,
kExperimentalSetupFloatBeamImpactPositionY0, kExperimentalSetupFloatDetectorAngleZX, kExperimentalSetupFloatDetectorRotationX0, kExperimentalSetupFloatDetectorRotationZ0,
kExperimentalSetupFloatDetectorX0, kExperimentalSetupFloatDetectorY0, kExperimentalSetupFloatDetectorZ0, kNExperimentalSetupFloats
}
enum EExperimentalSetupIntType { kExperimentalSetupIntBeamType, kNExperimentalSetupInts }
enum EFeConfBlockIntValues {
kFeConfBlockIntValFeBoardId, kIntFeRecLabel, kFeConfBlockIntValCalibStart, kFeConfBlockIntValCalibWidth,
kFeConfBlockIntValHoldStart, kFeConfBlockIntValHoldWidth, kFeConfBlockIntValVfeResetStart, kFeConfBlockIntValVfeResetEnd,
kFeConfBlockIntValVfeSrinStart, kFeConfBlockIntValVfeSrinEnd, kFeConfBlockIntValVfeMplexClockStart, kFeConfBlockIntValVfeMplexClockMark,
kFeConfBlockIntValVfeMplexClockSpace, kFeConfBlockIntValVfeMplexClockPulses, kFeConfBlockIntValAdcStart, kFeConfBlockIntValAdcEnd,
kFeConfBlockIntValAdcControl, kFeConfBlockIntValAdcDelay, kFeConfBlockIntValFrameSyncDelay, kFeConfBlockIntValQdrDataDelay,
kFeConfBlockIntValDacData, kFeConfBlockIntValFlags, kFeConfBlockIntValVfeInfo, kFeConfBlockIntValEmcBot,
kFeConfBlockIntValEmcTop, kFeConfBlockIntValEmcTopLowGainBit, kFeConfBlockIntValEmcBotLowGainBit, kNFeConfBlockIntValues
}
The indices of all the stored values.
enum EFeEventIntValues {
kFeEventIntValBoardId, kFeEventIntValRecLabel, kFeEventIntValTriggerCounter, kFeEventIntValSpyRegister,
kNFeEventIntValues
}
enum EIntValues {
kIntValFeInfoBoardId, kIntValFeInfoLabel, kIntValFeInfoFeID, kIntValFeInfoFrameSyncOutPacked0,
kIntValFeInfoFrameSyncOutPacked2, kIntValFeInfoFeLength, kIntValFeInfoFrameSyncOutPacked4, kIntValFeInfoFifo,
kIntValFeInfoTriggerCounter, kNIntValuesFeInfo
}
The indices of all the stored values.
enum EFeTrgDataIntValues {
kFeTrgDataIntValBoardId, kFeTrgDataIntValRecLabel, kFeTrgDataIntValHeader, kFeTrgDataIntValTrailer,
kFeTrgDataIntValTrigCounter, kNFeTrgDataIntValues
}
enum ERoConfIntValues {
kHodEvtStatus, kHodEvtEvtCounter, kHodEvtTimeCounter, kHodEvtNumHitsX,
kHodEvtNumHitsY, kRoConfIntNumbers, kRoConfIntSlotEnable, kRoConfIntSlotFeEnable,
kRoConfIntVmePeriod =kRoConfIntSlotFeEnable+NLENSLOFE, kRoConfIntBePeriod, kRoConfIntBecPeriod, kRoConfIntFePeriod,
kRoConfIntBeSoftTrigger, kRoConfIntFeSoftTrigger, kRoConfIntFeBrcSoftTrigger, kRoIntConfMode,
kNRoConfIntValues =kRoIntConfMode
}
The indices of all the stored values.
enum EIntLFValues { k_ID_IntLF, kNIntLFValues }
enum EFloatLFValues { kNFloatLFValues }
enum EDoubleLFValues {
k_Constant_DoubleLF, k_Constant_Error_DoubleLF, k_Constant_Reference_Point_DoubleLF, k_Constant_Reference_Point_Error_DoubleLF,
k_Slope_DoubleLF, k_Slope_Error_DoubleLF, kNDoubleLFValues
}
enum EIntLFCValues { k_ID_IntLFC, kNIntLFCValues }
enum EFloatLFCValues { kNFloatLFCValues }
enum EDoubleLFCValues {
k_Constant_DoubleLFC, k_Constant_Error_DoubleLFC, k_Constant_Reference_Point_DoubleLFC, k_Constant_Reference_Point_Error_DoubleLFC,
kNDoubleLFCValues
}
enum EIntLFTValues { k_ID_IntLFT, k_NDF_IntLFT, kNIntLFTValues }
enum EFloatLFTValues { kNFloatLFTValues }
enum EDoubleLFTValues {
k_Offset_DoubleLFT, k_Slope_DoubleLFT, k_Chi2_DoubleLFT, k_ErrorMatrixA_DoubleLFT,
k_ErrorMatrixB_DoubleLFT, k_ErrorMatrixC_DoubleLFT, k_ErrorMatrixD_DoubleLFT, kNDoubleLFTValues
}
enum EIntLFSValues { k_ID_IntLFS, kNIntLFSValues }
enum EFloatLFSValues { kNFloatLFSValues }
enum EDoubleLFSValues { k_Slope_DoubleLFS, k_Slope_Error_DoubleLFS, kNDoubleLFSValues }
enum EModuleConnectionFloatType { kNModuleConnectionFloats }
enum EModuleConnectionIntType {
kModuleConnectionIntCrate, kModuleConnectionIntSlot, kModuleConnectionIntFrontEnd, kModuleConnectionIntConnectorType,
kModuleConnectionIntIndexOfLowerLeftCell, kModuleConnectionIntModuleType, kModuleConnectionIntModuleID, kNModuleConnectionInts
}
enum EModuleConnectorType { kLeftConnector, kRightConnector, kFullConnector, kNConnectorTypes }
enum EModuleDescriptionIntType {
kModuleDescriptionIntModuleType, kModuleDescriptionIntNameIndexOrMinusOne, kModuleDescriptionIntNameLength, kNModuleDescriptionIntsOrNCells,
kModuleDescriptionIntNameIndex, kModuleDescriptionIntCellDimensionStart, kModuleDescriptionIntCellZPositionStart, kNModuleDescriptionInts
}
enum EModuleDescriptionFloatType {
kModuleDescriptionWidth, kModuleDescriptionHeight, kModuleDescriptionCellWidth, kModuleDescriptionCellHeight,
kNModuleDescriptionFloats
}
enum EModuleDescriptionOptions { kModuleDescriptionNormal =0, kModuleDescriptionWithCellDimension =1, kModuleDescriptionWithCellDimensionAndZPos =3 }
enum EModuleLocationFloatType { kModuleLocationFloatX, kModuleLocationFloatY, kModuleLocationFloatZ, kNModuleLocationFloats }
enum EModuleLocationIntType { kModuleLocationIntModuleType, kModuleLocationIntCellIndexOffset, kNModuleLocationInts }
enum ERoConfIntValues {
kHodEvtStatus, kHodEvtEvtCounter, kHodEvtTimeCounter, kHodEvtNumHitsX,
kHodEvtNumHitsY, kRoConfIntNumbers, kRoConfIntSlotEnable, kRoConfIntSlotFeEnable,
kRoConfIntVmePeriod =kRoConfIntSlotFeEnable+NLENSLOFE, kRoConfIntBePeriod, kRoConfIntBecPeriod, kRoConfIntFePeriod,
kRoConfIntBeSoftTrigger, kRoConfIntFeSoftTrigger, kRoConfIntFeBrcSoftTrigger, kRoIntConfMode,
kNRoConfIntValues =kRoIntConfMode
}
The indices of all the stored values.
enum ERunLocationIntType {
kStartIndexRunLocationInt, kLengthIndexRunLocationInt, kStartIndexRunTypeInt, kLengthIndexRunTypeInt,
kStartIndexMonthInfo, kLengthIndexMonthInfo, kNRunLocationInts
}
enum EBeEventIntValues {
kBeEventIntValBoardId, kBeEventIntValRecLabel, kBeEventIntValStatusWord, kBeEventIntValL1aCounter,
kBeEventIntValBxCounter, kBeEventIntValQdrFrameCounter, kBeEventIntValQdrDataCounter, kBeEventIntValTotalFrameCounter,
kNBeEventIntValues, kRunTimeStartMSB, kRunTimeStartLSB, kRunTimeStopMSB,
kRunTimeStopLSB, kNRunTimeIntValues
}
enum SceSroModIntValues { kIntSceSroModPosHbabCurs =kIntSroModPosCmbVolts+2, kIntSceSroModIntValues =kIntSroModPosHbabVolts+1 }
The map which contains the measured values of the different types.
enum SceSroModDblValues { kIntSceSroModDblValues }
enum SceSroModFloatValues { kSceIntSroModFloatValues }
enum ScintCaloSroModIntValues {
kIntSroModModNumber, kIntSroModTimeStampymd, kIntSroModTimeStamphms, kIntSroModLedSetting,
kIntSroModCmbWidth, kIntSroModCmbHeight, kIntSroModPosCmbTemps, kIntSroModPosCmbVolts =kIntSroModPosCmbTemps+2,
kIntSroModPosHbabVolts =kIntSroModPosCmbVolts+6
}
The indices of the the stored values.
enum ETcmtConnectionFloatType { kNTcmtConnectionFloats }
enum ETcmtConnectionIntType {
kTcmtConnectionIntCrate, kTcmtConnectionIntElecID, kTcmtConnectionIntFastID, kTcmtConnectionIntIndexOfLowerLeftCell,
kTcmtConnectionIntModuleType, kNTcmtConnectionInts
}
enum ETrgConfIntValues {
kTrgConfIntNumbers, kTrgConfIntEnable, kTrgConfIntclearBeTrg, kTrgConfIntbeTrgSoftTrg,
kTrgConfIntbeTrgSoftSpill, kTrgConfIntbeTrgSquirt, kTrgConfIntbeTrgVlink, kTrgConfIntspillInvert,
kTrgConfIntreadPeriod, kTrgConfIntreadcPeriod, kTrgConfIntbeTrgPollNumber, kTrgConfIntbeTrgPollTimesec,
kTrgConfIntbeTrgPollTimemus, kTrgConfIntbeTrgSpillNumber, kTrgConfIntbeTrgSpillTimesec, kTrgConfIntbeTrgSpillTimemus,
kNTrgConfIntValues =kTrgConfIntbeTrgSpillTimemus
}
The indices of all the stored values.
Functions
std::ostream & operator<< (std::ostream &out, const CALICE::Ahc2TileIndex &hti)
std::ostream & operator<< (std::ostream &os, const BitSet &bits)
bool const operator> (const BoardID &boardId1, const BoardID &boardId2)
Implemetations of overloaded operators.
bool const operator< (const BoardID &boardId1, const BoardID &boardId2)
std::ostream & operator<< (std::ostream &os, const BoardID &a)
EVENT::LCGenericObject * cloneLCGenericObject (EVENT::LCObject *obj)
Utility functions to clone LCGenericObjects.
EVENT::LCGenericObject * cloneLCGenericObject (EVENT::LCGenericObject *generic_object)
EVENT::LCCollection * cloneCollection (EVENT::LCCollection *col)
Clone a collection.
float calculateDriftVelocity (float drift_time_u, float drift_time_next_u, const DriftChamberParameter &axis_u, const DriftChamberParameter &next_axis_u)
Calculate the drift velocity from the measured drift time of two adjacent chambers (same axis).
std::ostream & operator<< (std::ostream &os, const ErrorBits &error)
std::ostream & operator<< (std::ostream &out, FastCaliceHit fch)
std::ostream & operator<< (std::ostream &os, const FeInfo &a)
std::ostream & operator<< (std::ostream &out, const CALICE::HcalCellIndex &hci)
std::ostream & operator<< (std::ostream &out, const CALICE::HcalTileIndex &hti)
std::ostream & operator<< (std::ostream &out, const CALICE::LinearFitCompound &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::LinearFitConstant &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::LinearFitResult &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::LinearFitSlope &lfr)
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator- (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Subtract two vectors of the same dimension.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator+ (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Add two vectors of the same dimension.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator* (const float c, const NVector_t< _T, _dimension > &a)
Multiply a vector by a scalar.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator* (const NVector_t< _T, _dimension > &a, const float c)
Multiply a vector by a scalar.
template<class _T , int _dimension>
NVector_t< _T, _dimension > operator/ (const NVector_t< _T, _dimension > &a, const float c)
Divide a vector by a scalar.
template<class _T , int _dimension>
Double_t dot (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Scalar product of two vectors of the same dimension.
template<class _T , int _dimension>
Double_t dotOfDifference (const NVector_t< _T, _dimension > &a, const NVector_t< _T, _dimension > &b)
Calculate the norm squared of the difference of the two given vectors.
template<class _T , int _dimension>
Double_t norm (const NVector_t< _T, _dimension > &a)
Euclidean Norm of a vector.
template<class _T , int _dimension>
Float_t distance (const NVector_t< _T, _dimension > &line_origin, const NVector_t< _T, _dimension > &line_direction, const NVector_t< _T, _dimension > &point)
Calculate the perpendicular distance between the line and the point.
ThreeVector_t cross (const ThreeVector_t &a, const ThreeVector_t &b)
cross product of two three dimensional vectors.
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALGainfit &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALIntercalib &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALMapping &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALMIPfit &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALNoisyChannel &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALOnePeADC &lfr)
std::ostream & operator<< (std::ostream &out, const CALICE::ScECALTemperature &lfr)
unsigned int getNeededInts (const std::string &a_string)
Get the number of integer elements needed to store the string.
unsigned int getNeededInts (unsigned int string_length)
Get the number of integer elements needed to store the string.
unsigned int convertStringToInts (lcio::LCGenericObjectImpl *an_obj, const std::string &a_string, unsigned int string_start_index, unsigned int string_length_index)
convert a string to integers which are stored at the given position in the integer array of the given LCGenericObject.
std::string getStringFromInts (lcio::LCGenericObjectImpl *an_obj, unsigned int string_start_index, unsigned int string_length_index)
Get a string which is encoded into an integer array.
std::ostream & operator<< (std::ostream &os, const TcmtConnection &me)
void to_binary_bitops (int toprint)
Utility function to print the bit representation of a integer.
std::ostream & operator<< (std::ostream &os, const TriggerBits &bits)
Variables
FastCaliceHitMemoryPool theFCHMemPool
int k_ID0_IntScEcalOnePe = 0
int k_ID1_IntScEcalOnePe = 1
int k_calibconst_DoubleScEcalOnePe = 0
int k_calibconst_err_DoubleScEcalOnePe = 1
TcmtHitMemoryPool theTHMemPool
int debug = 0
Detailed Description
Store strings in LCGenericObjects.
The namespace CALICE contains calice specific software needed for the processing of CALICE data including the interface classes to the CALICE Raw Data and convenient MARLIN processors.
TODO: Create LCGenericObjects which can store strings.
Enumeration Type Documentation
enum CALICE::BmlSroRunIntValues
The map which contains the measured values of the different data types.
The indices of the the stored values.
Definition at line 31 of file BmlSlowRunDataBlock.hh.
enum CALICE::DaqTypeIntValues
The indices of the the stored values.
Definition at line 32 of file DaqTypeDataBlock.hh.
enum CALICE::EBeamParameterExceptionIntType
Enumerator
kBeamParameterExceptionIntBeamEnergy
main particle type.
Definition at line 17 of file BeamParameterException.hh.
enum CALICE::EBeamParameterFloatType
Author
Gtz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Enumerator
kBeamParameterFloatPeakEnergy
maximum of the beam energy distribution
kBeamParameterFloatBeamAngleZX
angle between beam axis and z-axis in the ZX-plane
kBeamParameterFloatBeamAngleZY
angle between beam axis and z-axis in the ZY-plane
kBeamParameterFloatBeamImpactPositionX0
mean beam impact position in XY-plane
kBeamParameterFloatBeamImpactPositionY0
mean beam impact position in XY-plane
Definition at line 18 of file BeamParameter.hh.
enum CALICE::EBeamParameterIntType
Enumerator
kBeamParameterIntBeamType
main particle type.
Definition at line 25 of file BeamParameter.hh.
enum CALICE::EBeTrgPollIntValues
The indices of all the stored values.
Definition at line 24 of file BeTrgPollData.hh.
enum CALICE::EBmlEventIntValues
The indices of all the stored values.
Definition at line 43 of file BmlEventData.hh.
enum CALICE::EBmlEventSupIntValues
The indices of all the stored values.
Definition at line 25 of file BmlEventDataSup.hh.
enum CALICE::EDetectorTransformationFloatType
Author
Gtz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Enumerator
kDetectorTransformationFloatDetectorAngleZX
angle between the detector and z-axis in the ZX-plane
kDetectorTransformationFloatDetectorRotationX0
origin of the rotation of the detector in ZX-plane
kDetectorTransformationFloatDetectorRotationZ0
origin of the rotation of the detector in ZX-plane
kDetectorTransformationFloatDetectorX0
origin of the detector x-coordinate
kDetectorTransformationFloatDetectorY0
origin of the detector y-coordinate
kDetectorTransformationFloatDetectorZ0
origin of the detector z-coordinate
Definition at line 18 of file DetectorTransformation.hh.
enum CALICE::EDriftChamberParameterFloatType
Author
Gtz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Enumerator
kDriftChamberParameterFloatVelocity
The drift velocity.
kDriftChamberParameterFloatDelay
time shift to subtracted from the measured time.
kDriftChamberParameterFloatOffsetZ
the position in the z-direction (negative) w.r.t.
ECAL front plate.
kDriftChamberParameterFloatOffsetU
The position offset in the drift-direction.
kDriftChamberParameterFloatError
The error on the position measurement.
Definition at line 19 of file DriftChamberParameter.hh.
enum CALICE::EDriftChamberParameterIntType
Enumerator
kDriftChamberParameterIntWireType
The drift direction w.r.t.
to the drift axis Y/X.
Definition at line 27 of file DriftChamberParameter.hh.
enum CALICE::EExperimentalSetupFloatType
Author
Gtz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Enumerator
kExperimentalSetupFloatPeakEnergy
maximum of the beam energy distribution
kExperimentalSetupFloatBeamAngleZX
angle between beam axis and z-axis in the ZX-plane
kExperimentalSetupFloatBeamAngleZY
angle between beam axis and z-axis in the ZY-plane
kExperimentalSetupFloatBeamImpactPositionX0
mean beam impact position in XY-plane
kExperimentalSetupFloatBeamImpactPositionY0
mean beam impact position in XY-plane
kExperimentalSetupFloatDetectorAngleZX
angle between the detector and z-axis in the ZX-plane
kExperimentalSetupFloatDetectorRotationX0
origin of the rotation of the detector in ZX-plane
kExperimentalSetupFloatDetectorRotationZ0
origin of the rotation of the detector in ZX-plane
kExperimentalSetupFloatDetectorX0
origin of the detector x-coordinate
kExperimentalSetupFloatDetectorY0
origin of the detector y-coordinate
kExperimentalSetupFloatDetectorZ0
origin of the detector z-coordinate
Definition at line 18 of file ExperimentalSetup.hh.
enum CALICE::EExperimentalSetupIntType
Enumerator
kExperimentalSetupIntBeamType
main particle type.
Definition at line 31 of file ExperimentalSetup.hh.
enum CALICE::EFeConfBlockIntValues
The indices of all the stored values.
Definition at line 20 of file FeConfigurationBlock.hh.
enum CALICE::EIntValues
The indices of all the stored values.
Definition at line 25 of file FeInfo.hh.
enum CALICE::EModuleConnectionFloatType
Author
Gtz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Definition at line 20 of file ModuleConnection.hh.
enum CALICE::EModuleLocationFloatType
Author
Gtz Gaycken LLR (Ecole Polytechnique)
Date
Apr 2005
Definition at line 21 of file ModuleLocation.hh.
enum CALICE::ETcmtConnectionFloatType
Author
Guilherme Lima (Northern Illinois University)
Date
July 2007
Definition at line 28 of file TcmtConnection.hh.
enum CALICE::SceSroModIntValues
The map which contains the measured values of the different types.
The indices of the the stored values.
Definition at line 30 of file SceSlowReadoutModBlock.hh.
Function Documentation
float CALICE::calculateDriftVelocity (float drift_time_u, float drift_time_next_u, const DriftChamberParameter & axis_u, const DriftChamberParameter & next_axis_u) inline
Calculate the drift velocity from the measured drift time of two adjacent chambers (same axis).
Assuming that the particle track is reasonably parallel to the z-axis, the electrons generated in two adjacent chambers (containing wires pointing in the same direction) will travel in total the distance (in the drift direction) between the adjacent wires. The drift velocity is then: L/(t1+t2), where L is the distance of the wires and t1 and t2 the drift times measured at the two wires.
Definition at line 217 of file DriftChamberParameter.hh.
References calculateDriftVelocity(), CALICE::DriftChamberParameter::getDelay(), and CALICE::DriftChamberParameter::getOffsetU().
Referenced by calculateDriftVelocity().
EVENT::LCCollection * CALICE::cloneCollection (EVENT::LCCollection * col)
Clone a collection.
This will clone all the elements and the int, float and string parameters. This should be everything. NOTE: depending on the size of the collection, and the number of parameters this may be a very expenisve operation.
Definition at line 32 of file cloneUtils.cc.
References cloneLCGenericObject().
Referenced by CALICE::ConditionsDataWriteHandler::conditionsChanged().
EVENT::LCGenericObject * CALICE::cloneLCGenericObject (EVENT::LCObject * obj)
Utility functions to clone LCGenericObjects.
Implementation of cloning functions.
Author
G. Gaycken (LLR) (put into own file by R. Pschl (LAL)
Date
Feb 22 2006Different methods for object cloning
Definition at line 13 of file cloneUtils.cc.
Referenced by cloneCollection().
unsigned int CALICE::convertStringToInts (lcio::LCGenericObjectImpl * an_obj, const std::string & a_string, unsigned int string_start_index, unsigned int string_length_index)
convert a string to integers which are stored at the given position in the integer array of the given LCGenericObject.
Parameters
an_obj the generic LCObject in which the string is going to be stored.
a_string the string to be stored.
string_start_index the index of the element in the integer array to which the first character of the string will be written.
string_length_index the index of the element in the integer array where the length of the string will be stored.
Returns
the index of first unused element of the integer array after the string.
Definition at line 11 of file stringFromToInts.cc.
Referenced by CALICE::DaqTypeDataBlock::finalize(), CALICE::ModuleDescription::ModuleDescription(), CALICE::RunLocation::setRunLocationParameters(), and CALICE::BmlEventDataSup::setTDCType().
template<class _T , int _dimension> Float_t CALICE::distance (const NVector_t< _T, _dimension > & line_origin, const NVector_t< _T, _dimension > & line_direction, const NVector_t< _T, _dimension > & point)
Calculate the perpendicular distance between the line and the point.
Parameters
line_origin the origin of the line
line_direction the direction of the line must have norm 1.
point position of the point.
Returns
the distance between the line and the point (along the perpendicular).
Definition at line 237 of file NVector_t.hh.
References dot(), and norm().
std::string CALICE::getStringFromInts (lcio::LCGenericObjectImpl * an_obj, unsigned int string_start_index, unsigned int string_length_index)
Get a string which is encoded into an integer array.
Get the name assigned to the module type.
Parameters
an_obj the generic LCObject which contains a string.
string_start_index the index of the element in the integer array which contains the first character.
string_length_index the index of the element in the integer array which contains the string length.
The module type together with the module ID is considered to be unique. Due to the character encoding in an integer array, the function may perform slowly.
Definition at line 37 of file stringFromToInts.cc.
Referenced by CALICE::DaqTypeDataBlock::finalize(), CALICE::RunLocation::getGenericRunType(), CALICE::RunLocation::getLocation(), CALICE::EcalModuleCalibration::getModuleTypeName(), CALICE::ModuleDescription::getModuleTypeName(), CALICE::RunLocation::getMonthInfo(), CALICE::BmlEventDataSup::getTDCType(), and CALICE::DaqTypeDataBlock::RestoreMaps().
template<class _T , int _dimension> NVector_t<_T,_dimension> CALICE::operator* (const float c, const NVector_t< _T, _dimension > & a) inline
Multiply a vector by a scalar.
Todo:
replace float by _T?
Definition at line 171 of file NVector_t.hh.
References CALICE::NVector_t< T, dimension >::_x.
template<class _T , int _dimension> NVector_t<_T,_dimension> CALICE::operator* (const NVector_t< _T, _dimension > & a, const float c) inline
Multiply a vector by a scalar.
Todo:
replace float by _T?
Definition at line 182 of file NVector_t.hh.
References CALICE::NVector_t< T, dimension >::_x.
template<class _T , int _dimension> NVector_t<_T,_dimension> CALICE::operator/ (const NVector_t< _T, _dimension > & a, const float c) inline
Divide a vector by a scalar.
Todo:
replace float by _T?
Definition at line 193 of file NVector_t.hh.
References CALICE::NVector_t< T, dimension >::_x.
bool const CALICE::operator> (const BoardID & boardId1, const BoardID & boardId2) inline
Implemetations of overloaded operators.
See above ...
Definition at line 101 of file BoardID.hh.
References CALICE::BoardID::id().
void CALICE::to_binary_bitops (int toprint) inline
Utility function to print the bit representation of a integer.
Author
R. Poeschl (LAL/Orsay) 'stolen' from Fred Swartz - 2001-09-04
Date
Jul 21 2006 'stolen' from Fred Swartz - 2001-09-04 'stolen' from Fred Swartz - 2001-09-04
Definition at line 17 of file to_binary_bitops.hh.
References to_binary_bitops().
Referenced by CALICE::SceSlowReadoutModBlock::print(), CALICE::AhcSlowReadoutModBlock::print(), CALICE::TriggerHandlerCalice::searchTriggerMainWord(), and to_binary_bitops().