DeadAndNoisyTools: createBadChannelsList.cpp File Reference
createBadChannelsList.cpp File Reference
#include "SpectrumPropertiesRunInfo.h"
#include "ChannelExpertQuality.h"
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <TGraph.h>
#include <TVector.h>
#include <TCanvas.h>
#include <TLegend.h>
#include <TStyle.h>
#include <TTree.h>
#include <TDirectory.h>
#include <TROOT.h>
#include <TFile.h>
Functions
void printUsage (void)
void printChannelStatusMap (std::map< int, int > const &channelStatusMap, std::ostream &s=std::cout)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 58 of file createBadChannelsList.cpp.
References ChannelExpertQuality::dead, SpectrumPropertiesRunInfo::getGlobalChannelNumber(), ChannelExpertQuality::highRMS, printChannelStatusMap(), and printUsage().
void printChannelStatusMap (std::map< int, int > const & channelStatusMap, std::ostream & s = std::cout)
Definition at line 39 of file createBadChannelsList.cpp.
References SpectrumPropertiesRunInfo::ChannelID::_channel, SpectrumPropertiesRunInfo::ChannelID::_chip, SpectrumPropertiesRunInfo::ChannelID::_module, and SpectrumPropertiesRunInfo::getChannelID().
Referenced by main().
void printUsage (void)
Definition at line 19 of file createBadChannelsList.cpp.
Referenced by main().