CELLGEOMETRY: CALICE::CorrectPositionProcessor Class Reference
CALICE::CorrectPositionProcessor Class Reference
#include <CorrectPositionProcessor.hh>
Public Member Functions
virtual Processor * newProcessor ()
virtual void init ()
virtual void processEvent (LCEvent *evt)
Protected Member Functions
void createSimRecRelation (LCEvent *evt)
virtual void checkSimRecRelation (LCEvent *evt)
Detailed Description
Processor that generates a collection of CalorimeterHits with corrected position.
processor parameters
steering file parameter name description
CellDescriptionProcessorName name of the CellDescriptionProcessor that provides position information
InputCollection name of the collection that contains the CalorimeterHits to be corrected
OutputCollection name of the collection that will contain the corrected CalorimeterHits
ScaleEnergy scale factor for the energy of the hits
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
0.1
Date
June 2009
Definition at line 40 of file CorrectPositionProcessor.hh.
Member Function Documentation
void CALICE::CorrectPositionProcessor::checkSimRecRelation (LCEvent * evt) protected virtual
Check the LCRelation between Mokka SimCalorimeterHits and reconstructed CalorimeterHits
Definition at line 276 of file CorrectPositionProcessor.cc.
void CALICE::CorrectPositionProcessor::createSimRecRelation (LCEvent * evt) protected
Create a collection of type LCRelation (relation between Mokka SimCalorimeterHits and reconstructed CalorimeterHits), if the processor parameter CreateSimRecRelation is true
Definition at line 202 of file CorrectPositionProcessor.cc.
Referenced by processEvent().
void CALICE::CorrectPositionProcessor::init () virtual
Called at the begin of the job before anything is read.
Definition at line 84 of file CorrectPositionProcessor.cc.
References CALICE::CellDescriptionProcessor::getCellDescriptions(), and CALICE::MappingProcessor::getMapper().
void CALICE::CorrectPositionProcessor::processEvent (LCEvent * evt) virtual
Called for every event.
Definition at line 119 of file CorrectPositionProcessor.cc.
References createSimRecRelation().
The documentation for this class was generated from the following files:
CorrectPositionProcessor.hh
CorrectPositionProcessor.cc