CALIB: CALICE::MipTrackFinder Class Reference
CALICE::MipTrackFinder Class Reference
Processor to extract MIP calibrations from muon beam runs.
#include <MipTrackFinder.hh>
Public Member Functions
virtual Processor * newProcessor ()
Return new instance of this processor.
MipTrackFinder ()
Default constructor.
~MipTrackFinder ()
Destructor.
virtual void init ()
Initialise useful variables.
virtual void processEvent (LCEvent *evt)
Process event (the working horse)
virtual void end ()
Function to be called at the end of the job, after all events have been processed, for clean up.
Private Member Functions
void openInputCollections (LCEvent *evt)
Open the input collections.
void findTrack (LCEvent *evt)
Find the track.
bool doFurtherAnalysis ()
Check if cuts are fullfilled, and if analysis is to be continued.
LCTypedVector< CalorimeterHit > * extractAHCALInformation ()
Extract AHCAL information.
std::pair< int, float > extractNumberOfHitsAndEnergySum (LCCollection *inputCol)
Extract number of hits and the energy sum from the input collection.
EVENT::ClusterVec findTrackClusters (LCTypedVector< CalorimeterHit > *hcalVec)
Find clusters of MIP tracks.
EVENT::ClusterVec selectTrackClusters (EVENT::ClusterVec clusterVec, const std::string trackSelectionMode)
Select good tracks.
ClusterImpl * getWholeTrack (Cluster *trackCluster)
Get the whole track (i.e.
EVENT::ClusterVec getRemainingHits (EVENT::ClusterVec selectedTrackClusters)
Get the vector of track clusters containing all the remaining hits.
void appendParameters (LCEvent *evt, EVENT::ClusterVec finalVec)
Append event parameters with basic track information.
void createOutputCollection (LCEvent *evt, EVENT::ClusterVec finalVec)
Create output collection of track clusters.
Private Attributes
const Mapper * _mapper
the mapper
std::string _mappingProcessorName
name of the processor which provides the mapping
std::string _cellDescriptionProcessorName
name of the processor which provides the cells description
MappedContainer
< CALICE::CellDescription > * _cellDescriptions
mapped container of cells description
LCCollection * _ecalInputCol
ECAL input collection.
LCCollection * _ahcalInputCol
AHCAL input collection.
LCCollection * _ahcalAmpInputCol
AHCAL Amplitude input collection.
LCCollection * _tcmtInputCol
TCMT input collection.
std::string _ecalInputColName
std::string _ahcalInputColName
std::string _ahcalAmpInputColName
std::string _ahcalOutputTrackColName
std::string _tcmtInputColName
std::string _trackSelectionMode
track selection mode: NHITs = based on the number of hits; PERPENDICULAR = select only perpendicular tracks
bool _useECALandTCMT
decide whether to use ECAL and TCMT input information (default: false)
bool _isNonMuonRun
flag for non-muon run
int _ahcalMaxNoHits
maximum number of hits in the AHCAL
int _ecalMinNoHits
minimum number of hits in the ECAL
int _ecalMaxNoHits
maximum number of hits in the ECAL
float _tcmtMinEnergySum
minimum energy sum in the TCMT
float _mipCutValue
MIP cut value (0.5 MIPs)
int _mipCutVariable
int _trackNoHitsThreshold
choose amplitude to be used to perform the mip cut
IntVec _badAhcalModulesVec
vector of bad AHCAL modules numbers
IntVec _firstAhcalModulesVec
vector of numbers of the beginning AHCAL modules which are used for perpendicular track finding
IntVec _lastAhcalModulesVec
vector of numbers of the ending AHCAL modules which are used for perpendicular track finding
EVENT::CalorimeterHitVec _allAhcalHitsInEventVec
vector containing all AHCAL hits from the event
Detailed Description
Processor to extract MIP calibrations from muon beam runs.
Author
N.D'Ascenzo, DESY, S. Richter, DESY
Date
Jul 13 2006, 2008
Definition at line 27 of file MipTrackFinder.hh.
Member Function Documentation
void CALICE::MipTrackFinder::appendParameters (LCEvent * evt, EVENT::ClusterVec finalVec) private
Append event parameters with basic track information.
Parameters
evt the processed event
finalVec final vector of track clusters, after all selections
Definition at line 674 of file MipTrackFinder.cc.
Referenced by findTrack().
void CALICE::MipTrackFinder::createOutputCollection (LCEvent * evt, EVENT::ClusterVec finalVec) private
Create output collection of track clusters.
Parameters
evt the processed event
finalVec final vector of track clusters, after all selections
Definition at line 702 of file MipTrackFinder.cc.
Referenced by findTrack().
bool CALICE::MipTrackFinder::doFurtherAnalysis () private
Check if cuts are fullfilled, and if analysis is to be continued.
Returns
analyse flag to show if the cuts are fullfilled or not
Definition at line 276 of file MipTrackFinder.cc.
References _ahcalInputCol, _ahcalMaxNoHits, _ecalInputCol, _ecalMaxNoHits, _ecalMinNoHits, _isNonMuonRun, _tcmtInputCol, _tcmtMinEnergySum, _useECALandTCMT, and extractNumberOfHitsAndEnergySum().
Referenced by findTrack().
std::pair< int, float > CALICE::MipTrackFinder::extractNumberOfHitsAndEnergySum (LCCollection * inputCol) private
Extract number of hits and the energy sum from the input collection.
Parameters
inputCol the input collection
Definition at line 342 of file MipTrackFinder.cc.
Referenced by doFurtherAnalysis().
void CALICE::MipTrackFinder::findTrack (LCEvent * evt) private
Find the track.
Parameters
evt event to be processed
Definition at line 230 of file MipTrackFinder.cc.
References _trackSelectionMode, appendParameters(), createOutputCollection(), doFurtherAnalysis(), extractAHCALInformation(), findTrackClusters(), getRemainingHits(), and selectTrackClusters().
Referenced by processEvent().
EVENT::ClusterVec CALICE::MipTrackFinder::findTrackClusters (LCTypedVector< CalorimeterHit > * hcalVec) private
Find clusters of MIP tracks.
Parameters
hcalVec input vector of AHCAL hits
Returns
vector of clusters
Definition at line 465 of file MipTrackFinder.cc.
References _cellDescriptions, and _mapper.
Referenced by findTrack().
EVENT::ClusterVec CALICE::MipTrackFinder::getRemainingHits (EVENT::ClusterVec selectedTrackClusters) private
Get the vector of track clusters containing all the remaining hits.
Parameters
selectedTrackClusters vector of selected track clusters
Returns
vector of track clusters containing all the remaining hits
Definition at line 658 of file MipTrackFinder.cc.
References getWholeTrack().
Referenced by findTrack().
ClusterImpl * CALICE::MipTrackFinder::getWholeTrack (Cluster * trackCluster) private
Get the whole track (i.e.
track with no missing hits)
Parameters
trackCluster input track cluster, from which the mean X and Y of the track are calculated
Returns
wholeTrack the track cluster which contains all the hits
Definition at line 614 of file MipTrackFinder.cc.
References _allAhcalHitsInEventVec.
Referenced by getRemainingHits().
void CALICE::MipTrackFinder::openInputCollections (LCEvent * evt) private
Open the input collections.
Parameters
evt event to be processed
Definition at line 189 of file MipTrackFinder.cc.
References _ahcalAmpInputCol, _ahcalInputCol, _ecalInputCol, _tcmtInputCol, and _useECALandTCMT.
Referenced by processEvent().
void CALICE::MipTrackFinder::processEvent (LCEvent * evt) virtual
Process event (the working horse)
Parameters
evt event to be processed
Definition at line 168 of file MipTrackFinder.cc.
References _allAhcalHitsInEventVec, findTrack(), and openInputCollections().
EVENT::ClusterVec CALICE::MipTrackFinder::selectTrackClusters (EVENT::ClusterVec clusterVec, const std::string trackSelectionMode) private
Select good tracks.
Parameters
clusterVec vector of track clusters, on which the selection is performed
trackSelectionMode track selection mode, set by the steering parameter TrackSelectionMode
Definition at line 533 of file MipTrackFinder.cc.
References _firstAhcalModulesVec, _lastAhcalModulesVec, _mapper, and _trackNoHitsThreshold.
Referenced by findTrack().
Field Documentation
int CALICE::MipTrackFinder::_trackNoHitsThreshold private
choose amplitude to be used to perform the mip cut
minimum number of hits for which a track is considered to be a muon track (used only with TrackSelectionMode=NHITS)
Definition at line 141 of file MipTrackFinder.hh.
Referenced by MipTrackFinder(), and selectTrackClusters().
The documentation for this class was generated from the following files:
MipTrackFinder.hh
MipTrackFinder.cc