CALIB: CALICE::AngleTrackFinder Class Reference
CALICE::AngleTrackFinder Class Reference
Processor to extract MIP calibrations from muon beam runs.
#include <AngleTrackFinder.hh>
Public Member Functions
virtual Processor * newProcessor ()
Return new instance of this processor.
AngleTrackFinder ()
Default constructor.
~AngleTrackFinder ()
Destructor.
virtual void init ()
Initialise useful variables.
virtual void processEvent (LCEvent *evt)
Process event (the working horse)
virtual void end ()
Function to be called at the end of the job, after all events have been processed, for clean up.
Private Member Functions
void openInputCollections (LCEvent *evt)
Open the input collections.
void findTrack (LCEvent *evt)
Find the track.
bool doFurtherAnalysis ()
Check if cuts are fullfilled, and if analysis is to be continued.
std::vector< CalorimeterHit * > extractAHCALInformation ()
Extract AHCAL information.
std::pair< int, float > extractNumberOfHitsAndEnergySum (LCCollection *inputCol)
Extract number of hits and the energy sum from the input collection.
void findTrackClusters (std::vector< CalorimeterHit * > &hcalVec, EVENT::ClusterVec &outputVec)
Find clusters of MIP tracks.
void findTrackClustersCoarse (std::vector< CalorimeterHit * > &hcalVec, EVENT::ClusterVec &outputVec)
EVENT::ClusterVec extendTracksToTcmt (LCTypedVector< CalorimeterHit > *tcmtVec, EVENT::ClusterVec trackClusters)
void selectTrackClusters (EVENT::ClusterVec clusterVec, const std::string trackSelectionMode, EVENT::ClusterVec &goodTrackClusters)
Select good tracks.
void mergeCoarseClusters (EVENT::ClusterVec goodclusterVec, EVENT::ClusterVec clusterCoarseVec, EVENT::ClusterVec &outputVec, const std::string trackSelectionMode)
ClusterImpl * getWholeTrack (Cluster *trackCluster)
Get the whole track (i.e.
ClusterImpl * getWholeTrackSegment (Cluster *trackCluster)
ClusterImpl * copyACluster (Cluster *trackCluster)
EVENT::ClusterVec getRemainingHits (EVENT::ClusterVec selectedTrackClusters)
Get the vector of track clusters containing all the remaining hits.
EVENT::ClusterVec getRemainingHitsOfTrackSegment (EVENT::ClusterVec selectedTrackClusters)
EVENT::ClusterVec getFinalCluster (EVENT::ClusterVec selectedTrackClusters)
void createOutputCollection (LCEvent *evt, EVENT::ClusterVec finalVec)
Create output collection of track clusters.
EVENT::ClusterVec obtainSubClusters (EVENT::Cluster *clusterA)
EVENT::ClusterVec removeIsolatedHits (EVENT::ClusterVec subCluster)
bool checkXYAdjacentClusters (Cluster *clusterA, Cluster *clusterB, int numOfAdjacentCells)
Private Attributes
const Mapper * _mapper
the mapper
std::string _mappingProcessorName
name of the processor which provides the mapping
std::string _cellDescriptionProcessorName
name of the processor which provides the cells description
MappedContainer
< CALICE::CellDescription > * _cellDescriptions
LCCollection * _ecalInputCol
ECAL input collection.
LCCollection * _ahcalInputCol
AHCAL input collection.
LCCollection * _ahcalAmpInputCol
AHCAL Amplitude input collection.
LCCollection * _tcmtInputCol
TCMT input collection.
std::string _ecalInputColName
std::string _ahcalInputColName
std::string _ahcalAmpInputColName
std::string _ahcalOutputTrackColName
std::string _tcmtOutputTrackColName
std::string _tcmtInputColName
std::string _encodingString
std::string _trackSelectionMode
track selection mode: NHITs = based on the number of hits; PERPENDICULAR = select only perpendicular tracks
LCRelationNavigator * _navigator
EVENT::ClusterVec _goodTrackClusters
bool _useECAL
bool _useTCMT
bool _tcmtStartVertical
float _tcmtStripWidth
bool _isNonMuonRun
flag for non-muon run
int _ahcalMaxNoHits
maximum number of hits in the AHCAL
int _ecalMinNoHits
minimum number of hits in the ECAL
int _ecalMaxNoHits
maximum number of hits in the ECAL
float _tcmtMinEnergySum
minimum energy sum in the TCMT
float _mipCutValue
MIP cut value (0.5 MIPs)
int _mipCutVariable
int _trackNoHitsThreshold
choose amplitude to be used to perform the mip cut
int _useCoarseSection
int _minActiveTCMTParallelStrips
IntVec _badAhcalModulesVec
vector of bad AHCAL modules numbers
IntVec _firstAhcalModulesVec
vector of numbers of the beginning AHCAL modules which are used for perpendicular track finding
IntVec _lastAhcalModulesVec
vector of numbers of the ending AHCAL modules which are used for perpendicular track finding
EVENT::CalorimeterHitVec _allAhcalHitsInEventVec
vector containing all AHCAL hits from the event
Static Private Attributes
static const unsigned int MAXTCMTLAYERS = 16
static const unsigned int MAXTCMTSTRIPS = 20
Detailed Description
Processor to extract MIP calibrations from muon beam runs.
Author
A.Vargas DESY
Date
November 2010
Definition at line 35 of file AngleTrackFinder.hh.
Member Function Documentation
void CALICE::AngleTrackFinder::createOutputCollection (LCEvent * evt, EVENT::ClusterVec finalVec) private
Create output collection of track clusters.
Parameters
evt the processed event
finalVec final vector of track clusters, after all selections
Definition at line 1204 of file AngleTrackFinder.cc.
References _tcmtInputCol.
Referenced by findTrack().
bool CALICE::AngleTrackFinder::doFurtherAnalysis () private
Check if cuts are fullfilled, and if analysis is to be continued.
Returns
analyse flag to show if the cuts are fullfilled or not
Definition at line 377 of file AngleTrackFinder.cc.
References _ahcalInputCol, _ahcalMaxNoHits, _ecalInputCol, _ecalMaxNoHits, _ecalMinNoHits, _isNonMuonRun, _tcmtInputCol, _tcmtMinEnergySum, and extractNumberOfHitsAndEnergySum().
Referenced by findTrack().
std::pair< int, float > CALICE::AngleTrackFinder::extractNumberOfHitsAndEnergySum (LCCollection * inputCol) private
Extract number of hits and the energy sum from the input collection.
Parameters
inputCol the input collection
Definition at line 457 of file AngleTrackFinder.cc.
Referenced by doFurtherAnalysis().
void CALICE::AngleTrackFinder::findTrack (LCEvent * evt) private
Find the track.
Parameters
evt event to be processed
Definition at line 271 of file AngleTrackFinder.cc.
References _ahcalMaxNoHits, _tcmtInputCol, _trackSelectionMode, createOutputCollection(), doFurtherAnalysis(), extractAHCALInformation(), findTrackClusters(), and selectTrackClusters().
Referenced by processEvent().
void CALICE::AngleTrackFinder::findTrackClusters (std::vector< CalorimeterHit * > & hcalVec, EVENT::ClusterVec & outputVec) private
Find clusters of MIP tracks.
Parameters
hcalVec input vector of AHCAL hits
outputVec vector of clusters (to be filled)
Returns
vector of clusters
Definition at line 564 of file AngleTrackFinder.cc.
References _mapper.
Referenced by findTrack().
EVENT::ClusterVec CALICE::AngleTrackFinder::getRemainingHits (EVENT::ClusterVec selectedTrackClusters) private
Get the vector of track clusters containing all the remaining hits.
Parameters
selectedTrackClusters vector of selected track clusters
Returns
vector of track clusters containing all the remaining hits
Definition at line 1075 of file AngleTrackFinder.cc.
References getWholeTrack().
ClusterImpl * CALICE::AngleTrackFinder::getWholeTrack (Cluster * trackCluster) private
Get the whole track (i.e.
track with no missing hits)
Parameters
trackCluster input track cluster, from which the mean X and Y of the track are calculated
Returns
wholeTrack the track cluster which contains all the hits
Definition at line 1012 of file AngleTrackFinder.cc.
References _allAhcalHitsInEventVec.
Referenced by getRemainingHits().
void CALICE::AngleTrackFinder::openInputCollections (LCEvent * evt) private
Open the input collections.
Parameters
evt event to be processed
Definition at line 217 of file AngleTrackFinder.cc.
References _ahcalAmpInputCol, _ahcalInputCol, _ecalInputCol, and _tcmtInputCol.
Referenced by processEvent().
void CALICE::AngleTrackFinder::processEvent (LCEvent * evt) virtual
Process event (the working horse)
Parameters
evt event to be processed
Definition at line 192 of file AngleTrackFinder.cc.
References _allAhcalHitsInEventVec, findTrack(), and openInputCollections().
void CALICE::AngleTrackFinder::selectTrackClusters (EVENT::ClusterVec clusterVec, const std::string trackSelectionMode, EVENT::ClusterVec & goodTrackClusters) private
Select good tracks.
Parameters
clusterVec vector of track clusters, on which the selection is performed
trackSelectionMode track selection mode, set by the steering parameter TrackSelectionMode
goodTrackClusters vectors of good track clusters (to be filled)
Definition at line 839 of file AngleTrackFinder.cc.
References _trackNoHitsThreshold.
Referenced by findTrack().
Field Documentation
int CALICE::AngleTrackFinder::_trackNoHitsThreshold private
choose amplitude to be used to perform the mip cut
minimum number of hits for which a track is considered to be a muon track (used only with TrackSelectionMode=NHITS)
Definition at line 186 of file AngleTrackFinder.hh.
Referenced by AngleTrackFinder(), and selectTrackClusters().
The documentation for this class was generated from the following files:
AngleTrackFinder.hh
AngleTrackFinder.cc