CALICE_SIM: digisim::TempCalHit Class Reference
digisim::TempCalHit Class Reference
Public Member Functions
TempCalHit (const TempCalHit &oldhit)
TempCalHit (long long simid, double energy, double time)
TempCalHit (long long rawid, long long simid, double energy, double time)
TempCalHit & operator= (const TempCalHit &rhs)
double getTotalEnergy () const
void scaleEnergy (double factor)
Scales the global energy.
void setEnergy (double energy)
Changes global energy.
void setTime (double tstamp)
Changes global time stamp – use it with care, as it then becomes different than the timings of any individual contribution.
double getPrimaryTime () const
Primary time: either earliest time or time from largest contribution.
void addContribution (long long id, double energy, double time)
Add a contribution from a simulated hit.
std::map< long long, HitContrib > & getContributions ()
Reduce contribution from original hit, due to crosstalk into neighbors.
std::vector< double > getEnergyContributions () const
Return a vector with the energy contributions to the current TempCalHit.
std::vector< long long > getContributingIDs () const
Return a vector with the CellIDs for the sim hits' contributions to the current TempCalHit.
void setCellID0 (int id)
Set cell ID.
void setCellID1 (int id)
void setCellID (long long id)
int getCellID0 () const
int getCellID1 () const
int getCellID () const
Private Member Functions
int findContribution (long long cellID)
Private Attributes
long long _rawID
double _energy
double _time
std::map< long long, HitContrib > * _simHits
std::vector< HitContrib >
::const_iterator i
Detailed Description
Definition at line 13 of file TempCalHit.hpp.
Member Function Documentation
map< long long, HitContrib > & digisim::TempCalHit::getContributions ()
Reduce contribution from original hit, due to crosstalk into neighbors.
Return the contributions from simulated hits to the current TempCalHit
Definition at line 160 of file TempCalHit.cpp.
double digisim::TempCalHit::getPrimaryTime () const
Primary time: either earliest time or time from largest contribution.
It is currently set as the earliest time.
Definition at line 121 of file TempCalHit.cpp.
Referenced by digisim::SmearedTiming::transformTime().
void digisim::TempCalHit::scaleEnergy (double factor)
Scales the global energy.
This changes the energy of each contribution by the same factor.
Parameters
factor Applied to each contribution separately
Definition at line 94 of file TempCalHit.cpp.
Referenced by setEnergy().
void digisim::TempCalHit::setEnergy (double energy)
Changes global energy.
Actually, this changes the energy of each contribution by the same factor, so that final energy gets updated to the value provided.
Parameters
energy Final value of total energy
Definition at line 101 of file TempCalHit.cpp.
References scaleEnergy().
The documentation for this class was generated from the following files:
TempCalHit.hpp
TempCalHit.cpp