CALICE_SIM: CALICE::Ahc2SiPMStatisticProcessor Class Reference
CALICE::Ahc2SiPMStatisticProcessor Class Reference
Class for doing the AHCAL digitisation (SiPM treatment)
#include <Ahc2SiPMStatisticProcessor.hh>
Public Member Functions
virtual Processor * newProcessor ()
Ahc2SiPMStatisticProcessor ()
Constructor.
~Ahc2SiPMStatisticProcessor ()
Destructor.
virtual void init ()
Initialise.
virtual void processRunHeader (LCRunHeader *run)
Process header.
virtual void processEvent (LCEvent *evt)
Process event (the working horse)
virtual void check (LCEvent *evt)
Check.
virtual void end ()
End of processing.
virtual void printParameters ()
Print Parameters.
Protected Member Functions
void fillContainer (LCCollection *inputCol)
Fill a mapped container with the AHCAL cells.
void simulateOpticalCrossTalk ()
Simulate the optical cross-talk (i.e.
void simulateSiPMBehaviour ()
Simulate the SiPM binomial behaviour.
void addNoise (LCCollection *noiseCol)
Add noise events from data.
void createOutputCollection (LCEvent *evt, const std::string colName)
Create output collection of digitised AHCAL hits.
Private Attributes
std::string _calorimInpCollection
input collection name
std::string _calorimOutCollection
output collection name
vector< std::string > _calorimInpCollections
input collection name
vector< std::string > _calorimOutCollections
output collection name
std::string _noiseColName
Noise collection name.
std::string _mappingProcessorName
Mapping Processor Name.
std::string _cellNeighboursProcessorName
name of the processor which provides the cells neighbours
std::string _cellDescriptionProcessorName
CellDescription Processor name.
std::string _calibProcessorName
Calibration Processor Name.
bool _filterDeadCells
filter dead cells
bool _doMipTempCorr
do MIP temperature correction
bool _doGainTempCorr
do Gain temperature correction
bool _filterDefaultCells
filter cells with default values
bool _doSaturation
do SiPM Saturation
bool _doBinomialSmearing
do Binomial Smearing
bool _doAdditionalSmearing
do additional Smearing
bool _doAddNoise
Add Noise.
float _pixSpread
value in pixel spread
bool _correctDefaultGainToLY
Correct LY if default gain.
bool _physicsMode
physics mode for new ITEP
bool _noiseEnergyMIP
energy of noise hits are in MIP
bool _doOpticalCrossTalk
flag to disable/enable optical cross talk among neighbour tiles
float _fixedLY
fix light yield if default gain
StringVec _lightLeakage
light leakage factor vector
std::map< int, float > m_leakage
map containing ight leakage factor for each layer
TRandom3 * _randomGenerator
pointer to ROOTs random generator for pixel statistics
int _randomSeed
random seed for the random generator.
std::string _mokkaEncodingString
the Mokka encoding string
const Ahc2Mapper * _mapper
pointer to the used mapped
unsigned int _mapperVersion
mapper version
MappedContainer
< CALICE::CellDescription > * _cellDescriptions
mapped container of cells description
MappedContainer
< CALICE::CellNeighbours > * _cellNeighbours
mapped container of cells neighbours
MappedContainer
< Ahc2Calibrations > * _calibContainer
mapped container of SiPM calibrations
MappedContainer
< CalorimeterHitImpl > * _HitContainer
mapped container of AHCAL cells
int _nRun
int _nEvt
Static Private Attributes
static const unsigned int MAXADC = 4096
Max ADC for High Gain.
Detailed Description
Class for doing the AHCAL digitisation (SiPM treatment)
Author
eldwa.nosp@m.n.br.nosp@m.ianne.nosp@m.@des.nosp@m.y.de
Version
1.0
Date
December 2015
Definition at line 43 of file Ahc2SiPMStatisticProcessor.hh.
Member Function Documentation
void CALICE::Ahc2SiPMStatisticProcessor::addNoise (LCCollection * noiseCol) protected
Add noise events from data.
Parameters
noiseCol the noise collection
Definition at line 791 of file Ahc2SiPMStatisticProcessor.cc.
References _calibContainer, _doAddNoise, _doSaturation, _HitContainer, _mokkaEncodingString, _noiseEnergyMIP, and MAXADC.
Referenced by processEvent().
void CALICE::Ahc2SiPMStatisticProcessor::createOutputCollection (LCEvent * evt, const std::string colName) protected
Create output collection of digitised AHCAL hits.
Parameters
evt LCEvent to which the collection will be added
colName name of the output collection
Definition at line 870 of file Ahc2SiPMStatisticProcessor.cc.
References _HitContainer, and _mokkaEncodingString.
Referenced by processEvent().
void CALICE::Ahc2SiPMStatisticProcessor::fillContainer (LCCollection * inputCol) protected
Fill a mapped container with the AHCAL cells.
Parameters
inputCol the input collection, with the AHCAL Mokka hits
Definition at line 358 of file Ahc2SiPMStatisticProcessor.cc.
References _HitContainer, _mapper, and _mokkaEncodingString.
Referenced by processEvent().
void CALICE::Ahc2SiPMStatisticProcessor::simulateOpticalCrossTalk () protected
Simulate the optical cross-talk (i.e.
light leakage) between the tiles
Definition at line 406 of file Ahc2SiPMStatisticProcessor.cc.
References _cellDescriptions, _cellNeighbours, _cellNeighboursProcessorName, _HitContainer, _mokkaEncodingString, and m_leakage.
Referenced by processEvent().
Field Documentation
int CALICE::Ahc2SiPMStatisticProcessor::_randomSeed private
random seed for the random generator.
Steerable.
Definition at line 141 of file Ahc2SiPMStatisticProcessor.hh.
Referenced by Ahc2SiPMStatisticProcessor(), and init().
The documentation for this class was generated from the following files:
Ahc2SiPMStatisticProcessor.hh
Ahc2SiPMStatisticProcessor.cc