CALICE_SIM: CALICE::AhcDigitisationProcessor Class Reference
CALICE::AhcDigitisationProcessor Class Reference
Class for doing the AHCAL digitisation.
#include <AhcDigitisationProcessor.hh>
Public Member Functions
AhcDigitisationProcessor (const std::string processorName="AhcDigitisationProcessor")
Constructor.
virtual ~AhcDigitisationProcessor ()
Destructor.
AhcDigitisationProcessor * newProcessor ()
virtual void init ()
Initialise.
virtual void processEvent (lcio::LCEvent *)
Process event (the working horse)
virtual void end ()
End of processing.
Protected Member Functions
void fillGangedContainer (LCCollection *inputCol)
Fill a mapped container with the ganged AHCAL cells.
void simulateOpticalCrossTalk ()
Simulate the optical cross-talk (i.e.
void simulateSiPMBehaviour ()
Simulate the SiPM binomial behaviour.
void addNoise (LCCollection *noiseCol)
Add noise events from data.
void createOutputCollection (LCEvent *evt)
Create output collection of digitised AHCAL hits.
void writeCollectionForDebug (LCEvent *evt, const std::string colName)
Write collections after each step in digitisation, for debugging purposes.
Private Attributes
std::string _inputColName
name of the input collection
std::string _outputColName
name of the output collection
std::string _noiseColName
name of the AHCAL noise collection
std::string _mappingProcessorName
name of the mapping processor name
std::string _cellNeighboursProcessorName
name of the processor which provides the cells neighbours
std::string _cellDescriptionProcessorName
name of the processor which provides the cells description
std::string _calibProcessorName
name of the processor which provides the SiPM calibrations
std::string _temperatureProcessorName
name of the processor which provides the cell temperature
std::string _simRecRelationColName
name of the relation between Mokka SimCalorimeterHits and reconstructed CalorimeterHits
MappedContainer
< CALICE::CellDescription > * _cellDescriptions
mapped container of cells description
MappedContainer
< CALICE::CellNeighbours > * _cellNeighbours
mapped container of cells neighbours
MappedContainer
< SiPMCalibrations > * _calibContainer
mapped container of SiPM calibrations
MappedContainer
< CalorimeterHitImpl > * _gangedContainer
mapped container of ganged AHCAL cells
float _mipPerGeVFactor
the MIP to GeV factor (determined with muon events in Monte Carlo)
float _lightLeakage
light leakage factor
bool _createSimRecRelation
flag to disable/enable the creation of an LCRelation between the Mokka SimCalorimeterHits and the reconstructed CalorimeterHits
bool _doBinomialSmearing
flag to disable/enable binomial smearing
bool _doSaturation
flag to disable/enable SiPM saturation behaver to ture MC
bool _doOpticalCrossTalk
flag to disable/enable optical cross talk among neighbour tiles
bool _doAddNoise
flag to disable/enable adding detector noise
bool _doWriteCollectionForDebug
flag to disable/enable the writing of collections after each step in digitisation, for debugging
bool _doMipTempCorr
bool _doGainTempCorr
const Mapper * _mapper
pointer to the used mapped
unsigned int _mapperVersion
mapper version
bool _correctDefaultGainToLY
float _fixedLY
TRandom3 * _randomGenerator
pointer to ROOTs random generator for pixel statistics
int _randomSeed
random seed for the random generator.
std::string _mokkaEncodingString
the Mokka encoding string
Static Private Attributes
static const unsigned int MAXADC = 31768
conservative maximum number of ADC channels the hardware provides, 32768 - 1000 (average pedestal)
Detailed Description
Class for doing the AHCAL digitisation.
For more details, have a look here: http://www-flc.desy.de/hcal/documents/2008/diplom.2008.richter.pdf
Author
lucac.nosp@m.i@ma.nosp@m.il.de.nosp@m.sy.d.nosp@m.e
Version
1.0
Date
April 2010
Definition at line 30 of file AhcDigitisationProcessor.hh.
Member Function Documentation
void CALICE::AhcDigitisationProcessor::addNoise (LCCollection * noiseCol) protected
Add noise events from data.
Parameters
noiseCol the noise collection
Definition at line 676 of file AhcDigitisationProcessor.cc.
References _doAddNoise, _doSaturation, _gangedContainer, _mokkaEncodingString, and MAXADC.
Referenced by processEvent().
void CALICE::AhcDigitisationProcessor::createOutputCollection (LCEvent * evt) protected
Create output collection of digitised AHCAL hits.
Parameters
evt LCEvent to which the collection will be added
Definition at line 744 of file AhcDigitisationProcessor.cc.
References _gangedContainer, _mokkaEncodingString, and _outputColName.
Referenced by processEvent().
void CALICE::AhcDigitisationProcessor::fillGangedContainer (LCCollection * inputCol) protected
Fill a mapped container with the ganged AHCAL cells.
By default, Mokka creates 10x10 mm^2 cells. During ganging (i.e. grouping), the Mokka cells are grouped into 30x30 mm^2, 60x60 mm^2 and 120x120 mm^2 cells
Parameters
inputCol the input collection, with the AHCAL Mokka hits
Definition at line 290 of file AhcDigitisationProcessor.cc.
References _gangedContainer, _mapper, _mipPerGeVFactor, and _mokkaEncodingString.
Referenced by processEvent().
void CALICE::AhcDigitisationProcessor::simulateOpticalCrossTalk () protected
Simulate the optical cross-talk (i.e.
light leakage) between the tiles
Definition at line 329 of file AhcDigitisationProcessor.cc.
References _cellDescriptions, _cellNeighbours, _cellNeighboursProcessorName, _gangedContainer, _lightLeakage, and _mokkaEncodingString.
Referenced by processEvent().
void CALICE::AhcDigitisationProcessor::writeCollectionForDebug (LCEvent * evt, const std::string colName) protected
Write collections after each step in digitisation, for debugging purposes.
Parameters
evt LCEvent to which the collection will be added
colName name of the collection to be written
Definition at line 785 of file AhcDigitisationProcessor.cc.
References _gangedContainer, and _mokkaEncodingString.
Referenced by processEvent().
Field Documentation
int CALICE::AhcDigitisationProcessor::_randomSeed private
random seed for the random generator.
Steerable.
Definition at line 127 of file AhcDigitisationProcessor.hh.
Referenced by AhcDigitisationProcessor(), and init().
The documentation for this class was generated from the following files:
AhcDigitisationProcessor.hh
AhcDigitisationProcessor.cc