DeadAndNoisyTools: SimpleMapper Class Reference
SimpleMapper Class Reference
The SimpleMapper helper class reads in the AHC.cfg text file and provides the mapping (slot, frontend) -> (module, chip)
#include <SimpleMapper.h>
Data Structures
struct ModuleDescription
Internal helper struct for the value: a module description consisting of.
Public Types
typedef std::pair< int, int > ModuleLayerID
A pair of ints, the first one being the moduleID, the second one the layer number.
typedef std::pair< int, int > SlotFrontendID
A pair of ints, the first one being the slot number, the second one the front end ID.
Public Member Functions
SimpleMapper (std::string configFileName)
ModuleLayerID getModuleLayerID (SlotFrontendID sfID)
Get the ModuleLayerID from knowing the SlotFrontendID.
bool isAHC8 (SlotFrontendID sfID)
Check if a module is AHC8 (larger 6x6 cells also in the middle of the module, thus only 8 chips are needed instead of 12 on a normal module).
bool isTCMT (SlotFrontendID sfID)
Check if a module is from the tail catcher (normal module with 12 chips)
void print ()
A debug function. Dumps the map to the console.
unsigned int getModuleType (SlotFrontendID sfID)
Get the module type from the SlotFrontEndID.
Data Fields
std::map< SlotFrontendID,
ModuleDescription > _sf2mlMap
A map with the SlotFrontendID as key.
Detailed Description
The SimpleMapper helper class reads in the AHC.cfg text file and provides the mapping (slot, frontend) -> (module, chip)
Definition at line 11 of file SimpleMapper.h.
Member Typedef Documentation
typedef std::pair<int, int> SimpleMapper::ModuleLayerID
A pair of ints, the first one being the moduleID, the second one the layer number.
Definition at line 18 of file SimpleMapper.h.
typedef std::pair<int, int> SimpleMapper::SlotFrontendID
A pair of ints, the first one being the slot number, the second one the front end ID.
Definition at line 22 of file SimpleMapper.h.
Constructor & Destructor Documentation
SimpleMapper::SimpleMapper (std::string configFileName)
Definition at line 10 of file SimpleMapper.cxx.
References _sf2mlMap, ModuleType::AHC, ModuleType::AHC8, AHCAL_MAX_LAYERS, and ModuleType::TCMT.
Member Function Documentation
SimpleMapper::ModuleLayerID SimpleMapper::getModuleLayerID (SimpleMapper::SlotFrontendID sfID)
Get the ModuleLayerID from knowing the SlotFrontendID.
Definition at line 135 of file SimpleMapper.cxx.
References _sf2mlMap.
Referenced by SpectrumPropertiesRunInfo::SpectrumPropertiesRunInfo().
unsigned int SimpleMapper::getModuleType (SimpleMapper::SlotFrontendID sfID)
Get the module type from the SlotFrontEndID.
Definition at line 156 of file SimpleMapper.cxx.
References _sf2mlMap.
Referenced by SpectrumPropertiesRunInfo::SpectrumPropertiesRunInfo().
bool SimpleMapper::isAHC8 (SimpleMapper::SlotFrontendID sfID)
Check if a module is AHC8 (larger 6x6 cells also in the middle of the module, thus only 8 chips are needed instead of 12 on a normal module).
Definition at line 141 of file SimpleMapper.cxx.
References _sf2mlMap, and ModuleType::AHC8.
Referenced by SpectrumPropertiesRunInfo::SpectrumPropertiesRunInfo().
bool SimpleMapper::isTCMT (SimpleMapper::SlotFrontendID sfID)
Check if a module is from the tail catcher (normal module with 12 chips)
Definition at line 146 of file SimpleMapper.cxx.
References _sf2mlMap, and ModuleType::TCMT.
void SimpleMapper::print ()
A debug function. Dumps the map to the console.
Definition at line 111 of file SimpleMapper.cxx.
References SimpleMapper::ModuleDescription::_layer, SimpleMapper::ModuleDescription::_module, SimpleMapper::ModuleDescription::_moduleType, _sf2mlMap, ModuleType::AHC, ModuleType::AHC8, and ModuleType::TCMT.
Referenced by main().
Field Documentation
std::map< SlotFrontendID, ModuleDescription > SimpleMapper::_sf2mlMap
A map with the SlotFrontendID as key.
The value consists of the ModuleLayerID and a flag word with the module type
Definition at line 56 of file SimpleMapper.h.
Referenced by getModuleLayerID(), getModuleType(), isAHC8(), isTCMT(), print(), and SimpleMapper().
The documentation for this class was generated from the following files:
SimpleMapper.h
SimpleMapper.cxx