DeadAndNoisyTools: testRunComparator.cpp File Reference
testRunComparator.cpp File Reference
#include "SpectrumPropertiesRunInfo.h"
#include "RunComparator.h"
#include "TGraph.h"
#include "TH1D.h"
#include <unistd.h>
Functions
int main ()
Function Documentation
int main ()
Definition at line 6 of file testRunComparator.cpp.
References RunComparator::calculateChannelAndPedestalCorrectedMean(), RunComparator::getGraph(), RunComparator::getXAxisHisto(), RunComparator::getYAxisHisto(), and RunComparator::prepareGraph().