CALICEANALYSIS: CALICEOverlayPreparation Class Reference
CALICEOverlayPreparation Class Reference
#include <CALICEOverlayPreparation.hh>
Public Member Functions
CALICEOverlayPreparation ()
virtual ~CALICEOverlayPreparation ()
CALICEOverlayPreparation * newProcessor ()
virtual void init ()
virtual void processRunHeader (LCRunHeader *run)
virtual void processEvent (lcio::LCEvent *)
virtual void end ()
unsigned getStartingLayer (CLayer *)
First interaction layer and primary track finder.
bool FindTrack (unsigned, CLayer *)
bool isMuon (float, float)
bool isTrash (unsigned, float)
CALICE event selection (muon and trash)
float distXY (CHit *, CHit *)
Detailed Description
CALICEOverlayPreparation processor class
Constructor & Destructor Documentation
CALICEOverlayPreparation::CALICEOverlayPreparation ()
Default constructor
CALICEOverlayPreparation::~CALICEOverlayPreparation () virtual
Default destructor
Member Function Documentation
float CALICEOverlayPreparation::distXY (CHit * h1, CHit * h2)
Calculates and returns distance between two hits in XY-plane
References CHit::x, and CHit::y.
Referenced by FindTrack().
void CALICEOverlayPreparation::end () virtual
Function to close root-file and print some statistic results
bool CALICEOverlayPreparation::FindTrack (unsigned start, CLayer * lr)
Finds hits belonging to primary track taking in account the earlier found shower starting point. The "nearest neighbour" criteria is used. Maximum distance parameters are defined taking in account the cell size. First parameter is the number of shower starting layer. Second parameter is an array with objects CLayer that contain layer parameters.
References CHit::b, distXY(), CHit::l, CHit::r, CHit::x, CHit::y, and CHit::z.
Referenced by processEvent().
unsigned CALICEOverlayPreparation::getStartingLayer (CLayer * lr)
First interaction layer and primary track finder.
Finds and returns the number of layer where shower started using the following criteria:
Moving average sum of MIPs inside the window = 10 layers for two successive layers is greater than _avMIPxxxx value.
Number of hits in two consequent layers is greater than _hitLimxxx value. Both constraints are energy dependent.
Author
M.V. Chadeeva @ date November 2010
Referenced by processEvent().
void CALICEOverlayPreparation::init () virtual
Initialization of class members,root-file opening and histogramm booking
bool CALICEOverlayPreparation::isMuon (float e_eh, float e_t)
Finds muon-like events
Referenced by processEvent().
bool CALICEOverlayPreparation::isTrash (unsigned start, float esum)
CALICE event selection (muon and trash)
Selects trash events (including multiparticle)
Author
M.V. Chadeeva @ date November 2010
Referenced by processEvent().
void CALICEOverlayPreparation::processEvent (lcio::LCEvent *) virtual
Mail function to loop over events from which all other functions are called for every event
References CALICE::CLayer::emip, FindTrack(), getStartingLayer(), isMuon(), isTrash(), CALICE::CHit::r, CALICE::CHit::x, CALICE::CHit::y, and CALICE::CHit::z.
void CALICEOverlayPreparation::processRunHeader (LCRunHeader * run) virtual
Get run information
The documentation for this class was generated from the following files:
/nfs/dust/ilc/user/marquezh/CaliceSoft_w_ILCSoft_v02-03-02/calice_analysis/addonProcs/include/CALICEOverlayPreparation.hh
/nfs/dust/ilc/user/marquezh/CaliceSoft_w_ILCSoft_v02-03-02/calice_analysis/addonProcs/include/Select.hh
/nfs/dust/ilc/user/marquezh/CaliceSoft_w_ILCSoft_v02-03-02/calice_analysis/addonProcs/include/StartAndTrack.hh
/nfs/dust/ilc/user/marquezh/CaliceSoft_w_ILCSoft_v02-03-02/calice_analysis/addonProcs/src/CALICEOverlayPreparation.cc