CALICEANALYSIS: PrimaryTrackFinder Class Reference
PrimaryTrackFinder Class Reference
Marlin processor that finds shower start and primary track.
#include <PrimaryTrackFinder.hh>
Public Member Functions
PrimaryTrackFinder ()
virtual ~PrimaryTrackFinder ()
PrimaryTrackFinder * newProcessor ()
virtual void init ()
virtual void processRunHeader (LCRunHeader *)
virtual void processEvent (lcio::LCEvent *)
virtual void end ()
float distXY (CHit *, CHit *)
unsigned getStartingLayer (CLayer *)
bool FindTrack (unsigned, CLayer *)
bool isMuon (float, float)
Detailed Description
Marlin processor that finds shower start and primary track.
In this processor CalorimeterHit collections for ECAL and HCAL are used to find shower starting layer and hits belonging to ingoing track, these hits are then put into output collection of class CalorimeterHit. In track output collection the following class members are set: Type - hit layer number, Position - XYZ hit coordinates, Energy - deposited energy in MIPs. For shower starting layer, LCGenericObject collection has two integer members: calorimeter type (0 - ECAL, 1 - first 30 HCAL layers, 2 - last coarse part of HCAL) shower starting layer number (in each calorimeter) and two float members: weighted average of x coordinate of track hits weighted average of y coordinate of track hits
Version
4.01
Author
M.V. Chadeeva
Date
November 2010
Constructor & Destructor Documentation
PrimaryTrackFinder::PrimaryTrackFinder ()
Default constructor
PrimaryTrackFinder::~PrimaryTrackFinder () virtual
Default destructor
Member Function Documentation
float PrimaryTrackFinder::distXY (CHit * h1, CHit * h2)
Calculates and returns distance between two hits in XY-plane
References CALICE::CHit::x, and CALICE::CHit::y.
Referenced by FindTrack().
void PrimaryTrackFinder::end () virtual
Function to close root-file and print some statistic results
bool PrimaryTrackFinder::FindTrack (unsigned start, CLayer * lr)
Finds hits belonging to primary track taking in account the earlier found shower starting layer. The "nearest neighbour" criteria is used. Maximum distance parameters are defined taking in account the cell size. First parameter is the number of shower starting layer. Second parameter is an array with of objects CLayer that contain layer parameters.
References distXY(), CALICE::CHit::r, CALICE::CHit::x, CALICE::CHit::y, and CALICE::CHit::z.
Referenced by processEvent().
unsigned PrimaryTrackFinder::getStartingLayer (CLayer * lr)
Finds and returns the number of layer where shower started using the following criteria:
Moving average sum of MIPs inside the window = 10 layers for two successive layers is greater than _avMIPxxxx value.
Number of hits in two successive layers is greater than _hitLimxxx value. Both constraints are set in steering file. They are energy dependent and similar for ECAL and HCAL.
Referenced by processEvent().
void PrimaryTrackFinder::init () virtual
Initialization of class members,root-file opening and histogramm booking
bool PrimaryTrackFinder::isMuon (float e_eh, float e_t)
Indentifies event as muon-like according to criterium proposed by Vasiliy Morgunov and based on low amount of total deposited energy: E1<first parameter<E2 && E3<second parameter<E4 first parameter = Esum(ECAL)+Esum(HCAL) second parameter = Esum(TCMT) values E1, E2, E3 and E4 are taken from run data
Referenced by processEvent().
void PrimaryTrackFinder::processEvent (lcio::LCEvent *) virtual
Base function to loop over events from which all other functions are called for every event
References CALICE::CHit::c, CALICE::CHit::e, CALICE::CLayer::emip, FindTrack(), getStartingLayer(), isMuon(), CALICE::CHit::r, CALICE::CHit::x, CALICE::CHit::y, and CALICE::CHit::z.
void PrimaryTrackFinder::processRunHeader (LCRunHeader * run) virtual
Processing of run header
The documentation for this class was generated from the following files:
/nfs/dust/ilc/user/marquezh/CaliceSoft_w_ILCSoft_v02-03-02/calice_analysis/addonProcs/include/PrimaryTrackFinder.hh
/nfs/dust/ilc/user/marquezh/CaliceSoft_w_ILCSoft_v02-03-02/calice_analysis/addonProcs/src/PrimaryTrackFinder.cc