CALICE_USERLIB: CALICE::ModuleConnection Class Reference
CALICE::ModuleConnection Class Reference
Defines the electric connection of a module.
#include <ModuleConnection.hh>
Public Member Functions
ModuleConnection (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
ModuleConnection & setCrate (int crate_number)
int getCrate () const
ModuleConnection & setSlot (int slot_number)
int getSlot () const
ModuleConnection & setFrontEnd (int front_end_number)
int getFrontEnd () const
ModuleConnection & setConnectorType (EModuleConnectorType connector)
Set the type of the connector (full, left, right).
int getConnectorType () const
Get the connector type full, left, right.
ModuleConnection & setIndexOfLowerLeftCell (unsigned int index_offset)
Set the cell index (Mokka specification) of the cell in the lower left corner.
int getIndexOfLowerLeftCell () const
Get the cell index (Mokka specification) of the cell in the lower left corner.
ModuleConnection & setModuleType (unsigned char type)
Set the module type.
unsigned char getModuleType () const
Get the module type.
ModuleConnection & setModuleID (int module_id)
Set the serial number of a module.
int getModuleID () const
Set the serial number of a module.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
const char * getConnectorTypeName () const
Return the name of the connector.
Static Private Attributes
static const char * _connectorNames [kNConnectorTypes+1]
Detailed Description
Defines the electric connection of a module.
A module location defined by ModuleLocation may be connected to a connector of a CERC board. The module location is identified by the index offset.
Definition at line 34 of file ModuleConnection.hh.
Member Function Documentation
int CALICE::ModuleConnection::getIndexOfLowerLeftCell () const inline
Get the cell index (Mokka specification) of the cell in the lower left corner.
This index uniquely defines the module location.
Definition at line 116 of file ModuleConnection.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
int CALICE::ModuleConnection::getModuleID () const inline
Set the serial number of a module.
See Also
setModuleID
Definition at line 172 of file ModuleConnection.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
unsigned char CALICE::ModuleConnection::getModuleType () const inline
Get the module type.
The module type is not needed but this redundant information allows to verify the correctness of the configuration.
Todo:
remove this redundant information?
Definition at line 153 of file ModuleConnection.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
ModuleConnection& CALICE::ModuleConnection::setIndexOfLowerLeftCell (unsigned int index_offset) inline
Set the cell index (Mokka specification) of the cell in the lower left corner.
The index offset is used to uniquely define the module location.
Definition at line 107 of file ModuleConnection.hh.
ModuleConnection& CALICE::ModuleConnection::setModuleID (int module_id) inline
Set the serial number of a module.
This number together with the module type is used to uniquely identfy a module. This unique identification is for example needed to get the correct calibration constants.
Definition at line 163 of file ModuleConnection.hh.
ModuleConnection& CALICE::ModuleConnection::setModuleType (unsigned char type) inline
Set the module type.
The module type is not needed but this redundant information allows to some verification whether the configuration makes sense.
Todo:
remove this redundant information?
Definition at line 142 of file ModuleConnection.hh.
Field Documentation
const char * CALICE::ModuleConnection::_connectorNames static private
Initial value:
=
  {
    "left",
    "right",
    "full",
    "unknwon"
  }
Definition at line 207 of file ModuleConnection.hh.
The documentation for this class was generated from the following files:
ModuleConnection.hh
ModuleConnection.cc