CALICE_USERLIB: CALICE::CaliceElogInfo Class Reference
CALICE::CaliceElogInfo Class Reference
Implementation of the e-log information.
#include <CaliceElogInfo.hh>
Public Member Functions
CaliceElogInfo (EVENT::LCCollection *col)
constructor from LCCollection (this way, the user does not need to cast anymore)
CaliceElogInfo (const unsigned int runNumber, const int pdgType, const float energy, const int qualityFlag, const int triggerType, const int triggerSetting, const float cherenkovPressure, const float cherenkov2Pressure, const float positionX, const float positionY, const float rotationAngle)
constructor from elements
void setRunNumber (const unsigned int runNumber)
Set the run number.
unsigned int getRunNumber ()
Get the run number.
void setPdgType (const int pdgType)
Set the PDG ID.
int getPdgType ()
Get the PDG ID.
void setTriggerType (const int triggerType)
Set the trigger type.
int getTriggerType ()
Get the trigger type.
void setTriggerSetting (const int triggerSetting)
Set the trigger setting.
int getTriggerSetting ()
Get the trigger setting.
void setQualityFlag (const int qualityFlag)
Set the quality flag (0=good, 1=bad).
int getQualityFlag ()
Get the quality flag.
void setEnergy (const float energy)
Set the energy of this run.
float getEnergy ()
Get the energy of this run.
void setCherenkovPressure (const float cherenkovPressure)
Set the pressure in Cherenkov counter A.
float getCherenkovPressure ()
Get the pressure in Cherenkov counter A.
void setCherenkov2Pressure (const float cherenkov2Pressure)
Set the pressure in Cherenkov counter B.
float getCherenkov2Pressure ()
Get the pressure in Cherenkov counter B.
void setPositionX (const float positionX)
Set the x-position of the stage.
float getPositionX ()
Get the x-position of the stage.
void setPositionY (const float positionY)
Set the y-position of the stage.
float getPositionY ()
Get the y-position of the stage.
void setRotationAngle (const float rotationAngle)
Set the rotation angle of the stage.
float getRotationAngle ()
Get the rotation angle of the stage.
void setRunType (const std::string runType)
Set the run type (beamData, calibration etc)
const std::string getRunType ()
Get the run type (beamData, calibration etc)
void setTargetString (const std::string targetString)
Set the target string.
const std::string getTargetString (const EVENT::LCParameters &params)
Get the target string.
void setAbsorberString (const std::string absorberString)
Set the absorber string.
const std::string getAbsorberString (const EVENT::LCParameters &params)
Get the absorber string.
void setComment (const std::string comment)
Set the comment.
const std::string getComment (const EVENT::LCParameters &params)
Get the comment from the e-log.
const std::string getTypeName () const
Implementation of the virtual method from LCGenericObject.
const std::string getDataDescription () const
Implementation of the virtual method from LCGenericObject.
EVENT::LCCollection * getCollection () const
Get the LCCollection.
Private Types
enum Ints {
kRunNumber, kPdgType, kQualityFlag, kTriggerType,
kTriggerSetting, kNInts
}
enum Floats {
kEnergy, kCherenkovPressure, kCherenkov2Pressure, kPositionX,
kPositionY, kRotationAngle, kNFloats
}
enum Doubless { kNDoubles }
Private Attributes
std::string _runType
run type, e.g.
std::string _targetString
target string, e.g.
std::string _absorberString
absorber string, e.g.
std::string _comment
e-log comment, e.g.
Detailed Description
Implementation of the e-log information.
Author
lucac.nosp@m.i@ma.nosp@m.il.de.nosp@m.sy.d.nosp@m.e
Date
June 2010
Definition at line 18 of file CaliceElogInfo.hh.
Constructor & Destructor Documentation
CALICE::CaliceElogInfo::CaliceElogInfo (EVENT::LCCollection * col)
constructor from LCCollection (this way, the user does not need to cast anymore)
Constructor from LCObject: use LCObject, and do the cast from the LCGenericObject; this way, the users do not have to do the cast anymore.
Definition at line 13 of file CaliceElogInfo.cc.
References _runType, setCherenkov2Pressure(), setCherenkovPressure(), setEnergy(), setPdgType(), setPositionX(), setPositionY(), setQualityFlag(), setRotationAngle(), setRunNumber(), setTriggerSetting(), and setTriggerType().
CALICE::CaliceElogInfo::CaliceElogInfo (const unsigned int runNumber, const int pdgType, const float energy, const int qualityFlag, const int triggerType, const int triggerSetting, const float cherenkovPressure, const float cherenkov2Pressure, const float positionX, const float positionY, const float rotationAngle)
constructor from elements
Parameters
runNumber run number
pdgType PDG ID of the beam particle (e.g. -211 for pi-)
energy energy of the run, in GeV (according to elog information)
qualityFlag quality Flag: 0 = good, 1 = junk or garbage
triggerType trigger type: 10 for the '10x10' trigger, 20 for the '20x20' trigger, 100 for the '100x100' trigger
triggerSetting trigger setting (available only for FNAL data, see elog)
cherenkovPressure pressure in cherenkov counter A, in psia
cherenkov2Pressure pressure in cherenkov counter B, in psia
positionX x position of the beam, in mm
positionY y position of the beam, in mm
rotationAngle rotation angle (in degrees)
Member Function Documentation
float CALICE::CaliceElogInfo::getCherenkov2Pressure ()
Get the pressure in Cherenkov counter B.
Returns
the Cherenkov pressure
Definition at line 162 of file CaliceElogInfo.cc.
float CALICE::CaliceElogInfo::getCherenkovPressure ()
Get the pressure in Cherenkov counter A.
Returns
the Cherenkov pressure
Definition at line 151 of file CaliceElogInfo.cc.
const std::string CALICE::CaliceElogInfo::getComment (const EVENT::LCParameters & params)
Get the comment from the e-log.
Parameters
params the LCParameters (since the comment is saved as a parameter of the collection of CaliceElogInfo objects)
Definition at line 239 of file CaliceElogInfo.cc.
const std::string CALICE::CaliceElogInfo::getDataDescription () const
Implementation of the virtual method from LCGenericObject.
Returns
data description, i.e description of the LCObject elements: "i:runNumber,i:pdgType,i:energy,i:qualityFlag,i:triggerType,i:triggetSetting," "f:cherenkovPressure,f:positionX,f:positionY,f:rotationAngle";
Definition at line 209 of file CaliceElogInfo.cc.
float CALICE::CaliceElogInfo::getEnergy ()
Get the energy of this run.
Returns
the energy
Definition at line 139 of file CaliceElogInfo.cc.
int CALICE::CaliceElogInfo::getPdgType ()
Get the PDG ID.
Returns
the PDG ID
Definition at line 90 of file CaliceElogInfo.cc.
float CALICE::CaliceElogInfo::getPositionX ()
Get the x-position of the stage.
Returns
the x-position of the stage
Definition at line 174 of file CaliceElogInfo.cc.
float CALICE::CaliceElogInfo::getPositionY ()
Get the y-position of the stage.
Returns
the y-position of the stage
Definition at line 185 of file CaliceElogInfo.cc.
int CALICE::CaliceElogInfo::getQualityFlag ()
Get the quality flag.
Returns
get the quality flag
Definition at line 102 of file CaliceElogInfo.cc.
float CALICE::CaliceElogInfo::getRotationAngle ()
Get the rotation angle of the stage.
Returns
the rotation angle
Definition at line 197 of file CaliceElogInfo.cc.
unsigned int CALICE::CaliceElogInfo::getRunNumber ()
Get the run number.
Returns
the run number
Definition at line 78 of file CaliceElogInfo.cc.
int CALICE::CaliceElogInfo::getTriggerSetting ()
Get the trigger setting.
Returns
the trigger setting
Definition at line 125 of file CaliceElogInfo.cc.
int CALICE::CaliceElogInfo::getTriggerType ()
Get the trigger type.
Returns
the trigger type (10 for the '10x10' trigger, 20 for the '20x20' trigger, 100 for the '100x100' trigger)
Definition at line 114 of file CaliceElogInfo.cc.
const std::string CALICE::CaliceElogInfo::getTypeName () const
Implementation of the virtual method from LCGenericObject.
Returns
type name, i.e. name of the class
Definition at line 204 of file CaliceElogInfo.cc.
void CALICE::CaliceElogInfo::setAbsorberString (const std::string absorberString)
Set the absorber string.
Parameters
absorberString the target string to be set
void CALICE::CaliceElogInfo::setCherenkov2Pressure (const float cherenkov2Pressure)
Set the pressure in Cherenkov counter B.
Parameters
cherenkov2Pressure the Cherenkov pressure to be set
Definition at line 157 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setCherenkovPressure (const float cherenkovPressure)
Set the pressure in Cherenkov counter A.
Parameters
cherenkovPressure the Cherenkov pressure to be set
Definition at line 146 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setComment (const std::string comment)
Set the comment.
Parameters
comment the comment to be set
void CALICE::CaliceElogInfo::setEnergy (const float energy)
Set the energy of this run.
Parameters
energy the energy to be set
Definition at line 134 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setPdgType (const int pdgType)
Set the PDG ID.
Parameters
pdgType PDG ID to be set
Definition at line 85 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setPositionX (const float positionX)
Set the x-position of the stage.
Parameters
positionX the x-position of the stage
Definition at line 169 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setPositionY (const float positionY)
Set the y-position of the stage.
Parameters
positionY the y-position of the stage
Definition at line 180 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setQualityFlag (const int qualityFlag)
Set the quality flag (0=good, 1=bad).
Please note that this is a general quality flag, based on the comments done by the people on shift. If they mentioned that the run was 'bad', 'junk' or 'garbage', the quality flag for this run is set to 1 (i.e. bad). This is different from the data quality flag set by the DQ bits (for more information, please see here: http://www-flc.desy.de/flc/flcwiki/RunLogDataQuality
Parameters
qualityFlag the quality flag to be set
Definition at line 97 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setRotationAngle (const float rotationAngle)
Set the rotation angle of the stage.
Parameters
rotationAngle the rotation angle
Definition at line 192 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setRunNumber (const unsigned int runNumber)
Set the run number.
Parameters
runNumber the run number to be set
Definition at line 73 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setRunType (const std::string runType)
Set the run type (beamData, calibration etc)
Parameters
runType
Definition at line 220 of file CaliceElogInfo.cc.
References _runType.
void CALICE::CaliceElogInfo::setTargetString (const std::string targetString)
Set the target string.
Parameters
targetString the target string to be set
void CALICE::CaliceElogInfo::setTriggerSetting (const int triggerSetting)
Set the trigger setting.
Parameters
triggerSetting
Definition at line 120 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
void CALICE::CaliceElogInfo::setTriggerType (const int triggerType)
Set the trigger type.
Parameters
triggerType the trigger type: 10 for the '10x10' trigger, 20 for the '20x20' trigger, 100 for the '100x100' trigger
Definition at line 109 of file CaliceElogInfo.cc.
Referenced by CaliceElogInfo().
Field Documentation
std::string CALICE::CaliceElogInfo::_absorberString private
absorber string, e.g.
"6 mm Pb"
Definition at line 215 of file CaliceElogInfo.hh.
std::string CALICE::CaliceElogInfo::_comment private
e-log comment, e.g.
"10 deg, 100k"
Definition at line 216 of file CaliceElogInfo.hh.
std::string CALICE::CaliceElogInfo::_runType private
run type, e.g.
"beamData", noise, etc
Definition at line 213 of file CaliceElogInfo.hh.
Referenced by CaliceElogInfo(), getCollection(), getRunType(), and setRunType().
std::string CALICE::CaliceElogInfo::_targetString private
target string, e.g.
"air"
Definition at line 214 of file CaliceElogInfo.hh.
The documentation for this class was generated from the following files:
CaliceElogInfo.hh
CaliceElogInfo.cc