CALICE_USERLIB: CALICE::MappingAndAlignment Class Reference
CALICE::MappingAndAlignment Class Reference
Class to comunicate/handle the translation into unique layer/cell ids and 3D spacial coordinates.
#include <MappingAndAlignment.hh>
Public Member Functions
MappingAndAlignment ()
default constructor.
void init ()
Does noting for the time beeing.
std::pair< UInt_t, UInt_t > getModuleIndex (UInt_t crate_id, UInt_t slot_id, UInt_t front_end_nr) const noexcept(false)
Get the module indices connected to the right and left side of the given front-end.
UInt_t getCellIndex (UInt_t module_index, UInt_t multiplex_position, UInt_t line_i) const
get the cell index for the given module according to the current multiplex position and line index.
UInt_t getModuleID (UInt_t module_index) const
Get the ID of module which uniquely identifies a certain module of one module type.
string getModuleName (UInt_t module_index) const noexcept(false)
Get the name containing the type specifier and the module ID.
bool isModuleConnected (UInt_t module_index) const noexcept(false)
Verify whether the module location is connected to an active front-end.
Int_t getModuleIndexFromCellIndex (UInt_t)
Return the module index for a given (Mokka) Cellindex All this assumes that the ModuleLocation class has got set properly the index of the lower left cell e.g.
UInt_t getNCellsTotal () const
Return the total number of defined cells.
UInt_t getNConnectedCells () const
Return the number of cells connected to the DAQ.
Bool_t isCellDead (UInt_t module_index, UInt_t cell_index)
Verify whether the given cell is dead.
void moduleTypeChanged (lcio::LCCollection *col)
Inform the object about changes of the module types.
void moduleLocationChanged (lcio::LCCollection *col)
Inform the object about changes of the module locations.
void moduleConnectionChanged (lcio::LCCollection *col)
Inform the object about changes of the module connection.
void print (std::ostream &os)
To debug.
void printTcmtConnections (std::ostream &os)
bool isValidCrate (UInt_t crate) const
Validates a crate number based on mapping.
void setViewConnectionTree (bool view_connection=true)
Toggle printing of the connecting tree after each rebuild (conditions data change: ModuleConnection, ModuleLocation).
bool hasRightSide (const std::pair< UInt_t, UInt_t > &module_indices) const
Return true if the front-end has a right side connected.
UInt_t getNumberOfLines (const std::pair< UInt_t, UInt_t > &module_indices, bool right_instead_of_left) const
Return the number above the last line which should be used for the left or the right index.
UInt_t getLineIndexOfLeftSide () const
Return the first line associated to the module connected to the left side of the front-end.
UInt_t getLineIndexOfRightSide () const
Return the first line associated to the module connected to the right side of the front-end.
Bool_t isModuleConditionsDataComplete () const
Basic completeness test of conditions data.
UInt_t getMaxCellsPerFrontEnd () const
const TcmtConnection * getTcmtConnection (UInt_t crate, UInt_t slot, UInt_t fe, UInt_t chip, UInt_t chan) const
Get the connection object associated to an electronic channel.
void rebuildConnectionTree ()
Builds Ecal/Hcal connection mappings.
const std::string getCellIDEncoding ()
Returns the cell id encoding for the given detector.
Public Member Functions inherited from CALICE::Alignment
Alignment ()
default constructor.
void init ()
Does nothing for the time being.
UInt_t getGeometricalCellIndex (UInt_t module_index, UInt_t cell_index) const
Get the unique cell index of the cell specified by the module and the cell index.
bool isValid (UInt_t module_index) const
Return true if the type of the given module is valid.
UChar_t getModuleType (UInt_t module_index) const
Get the type of a certain module.
ThreeVector_t getPosition (UInt_t module_index, UInt_t cell_index) const
ThreeVector_t transformPosition (ThreeVector_t &a_position) const
UInt_t getNModules () const
Bool_t isModule (UInt_t module_index) const
Return false if the module index is out of range.
const ModuleDescription & getModuleDescription (UInt_t module_index) const
Return the description object for the given module.
UInt_t getNCellsPerModule (UInt_t module_index) const
Float_t getModuleWidth (UInt_t module_index) const
Get the cell width of the given module and cell.
Float_t getModuleHeight (UInt_t module_index) const
Get the cell width of the given module and cell.
Float_t getCellWidth (UInt_t module_index, UInt_t cell_index) const
Get the cell width of the given module and cell.
Float_t getCellHeight (UInt_t module_index, UInt_t cell_index) const
Get the cell width of the given module.
ThreeVector_t getPosition () const
Get the position of the detector in its proper coordinate system.
ThreeVector_t getModuleProperCenter (UInt_t module_index) const
Get the upper right corner of a module.
ThreeVector_t getModuleProperPosition (UInt_t module_index) const
Get the position of a module in the proper coordinate system of the detector.
ThreeVector_t getModulePosition (UInt_t module_index) const
Get the position of a module in the reference coordinate system.
ThreeVector_t getModuleCenter (UInt_t module_index) const
Get the center of a module in the reference coordinate system.
Float_t getDetectorAngleZX () const
Return the effective rotation angle of the detector.
virtual void stagePositionChanged (lcio::LCCollection *col)
Inform the object about changes in the stage positions on which the detector is mounted.
virtual void detectorTransformation (lcio::LCCollection *col)
Inform the object about changes of the detector position and rotation.
virtual void referenceTransformation (lcio::LCCollection *col)
Inform the object about changes of the reference position and rotation.
UInt_t getCellIndexOffset (UInt_t module_index) const
Get the cell index offset of a module.
Protected Member Functions
void rebuildTcmtConnectionTree ()
Builds TCMT connection mappings.
void clearTcmtConnections ()
Reset TCMT connection mappings.
Private Types
typedef SimpleArray_t< UInt_t > FrontEndList_t
Array which contains the module ID of the front-end to which it is connected.
typedef SimpleArray_t
< FrontEndList_t > SlotList_t
List of slots.
typedef SimpleArray_t< pair
< UInt_t, SlotList_t > > CrateList_t
list of crates: first argument crate ID.
typedef SimpleArray_t
< ModuleConnection > ModuleConnectionList_t
List which stores the module connection information provided by the conditions data handler (TODO: just store a pointer to the collection?)
typedef map< int,
TcmtConnection * > TcmtConnectionList_t
map of TCMT connections, keyed by elecID (slot,fe,chip,chan)
typedef map< UInt_t, UInt_t > ModuleIndex_t
The first component is a uniqe module index (the index offset) , the second component the array index in _moduleLocationList.
typedef std::map< UInt_t, UInt_t > MapCelltoModuleIndex_t
A map which relates indices (M,K) of a given cell to a module.
Private Member Functions
void correctFullHalfConnectorErrors ()
Cludge to correct configuration errors.
void determineMaximumCellNumberPerFrontEnd ()
Determine the maximum number of cells per front end.
Private Attributes
ModuleConnectionList_t _moduleConnectionList
TcmtConnectionList_t _tcmtConnectionList
ModuleIndex_t _moduleIndex
CrateList_t _crateList
UInt_t _nCells
total number of cells;
UInt_t _nConnectedCells
total number of cells which are connected to the DAQ;
Bool_t _viewConnectionTree
MapCelltoModuleIndex_t _mapCelltoModuleIndex
std::string _cellIDEncoding
A string which constains the cell id encoding.
UInt_t _maxNCells
Static Private Attributes
static const UInt_t __nLines =12
some constants
static const UInt_t __nLinesHalf =6
static const UInt_t __nFrontEnds =8
Friends
class VRawADCValueProcessor
class ModuleIndexReverseLookup
class HcalModuleIndexReverseLookup
Additional Inherited Members
Protected Types inherited from CALICE::Alignment
typedef SimpleArray_t< pair
< UInt_t, ModuleLocation > > ModuleList_t
Defined module locations (not necessarily connected to a front-end.
typedef SimpleArray_t
< ModuleDescription > ModuleTypeList_t
Protected Attributes inherited from CALICE::Alignment
ModuleList_t _moduleLocationList
ModuleTypeList_t _moduleTypeList
Detailed Description
Class to comunicate/handle the translation into unique layer/cell ids and 3D spacial coordinates.
The class has to be informed about changes of the detector configuration using the methods CALICE::MappingAndAlignment::moduleTypeChanged, CALICE::MappingAndAlignment::moduleLocationChanged and CALICE::MappingAndAlignment::moduleConnectionChanged This information is used to map the DAQ signals to cells and calculate 3D spacial coordinates for hits.
The class performs range checks only if BOUNDARY_CHECK is defined.
Definition at line 43 of file MappingAndAlignment.hh.
Member Typedef Documentation
typedef SimpleArray_t<pair<UInt_t,SlotList_t > > CALICE::MappingAndAlignment::CrateList_t private
list of crates: first argument crate ID.
Definition at line 386 of file MappingAndAlignment.hh.
typedef SimpleArray_t<UInt_t> CALICE::MappingAndAlignment::FrontEndList_t private
Array which contains the module ID of the front-end to which it is connected.
The frond-end ID*2+ front-end sid (0/1) is used as an array index
Definition at line 382 of file MappingAndAlignment.hh.
typedef map<UInt_t , UInt_t > CALICE::MappingAndAlignment::ModuleIndex_t private
The first component is a uniqe module index (the index offset) , the second component the array index in _moduleLocationList.
Definition at line 397 of file MappingAndAlignment.hh.
typedef SimpleArray_t<FrontEndList_t> CALICE::MappingAndAlignment::SlotList_t private
List of slots.
It is assumed that the slot ID is small and can be used as an array index (without requiring very large unused arrays)
Definition at line 384 of file MappingAndAlignment.hh.
Constructor & Destructor Documentation
CALICE::MappingAndAlignment::MappingAndAlignment ()
default constructor.
The default constructor configures the conditions data change delegators.
Definition at line 24 of file MappingAndAlignment.cc.
Member Function Documentation
void CALICE::MappingAndAlignment::clearTcmtConnections () protected
Reset TCMT connection mappings.
Automatically called before these connection mappings are (re)built.
Definition at line 562 of file MappingAndAlignment.cc.
Referenced by moduleConnectionChanged().
void CALICE::MappingAndAlignment::correctFullHalfConnectorErrors () private
Cludge to correct configuration errors.
Initially there was only support for full connectors
Definition at line 509 of file MappingAndAlignment.cc.
References CALICE::ModuleDescription::getModuleTypeName(), and CALICE::Alignment::isModule().
Referenced by moduleConnectionChanged(), moduleLocationChanged(), and moduleTypeChanged().
void CALICE::MappingAndAlignment::determineMaximumCellNumberPerFrontEnd () private
Determine the maximum number of cells per front end.
The maxmimum number of cells per front-end is defined such that this number is equal or larger than the number of cells per front end of all front ends which only have left sides and half this number is equal or large than the maximum number of cells of all right sides and all left sides respectively.
Definition at line 457 of file MappingAndAlignment.cc.
References isModuleConditionsDataComplete().
Referenced by moduleConnectionChanged(), moduleLocationChanged(), and moduleTypeChanged().
UInt_t CALICE::MappingAndAlignment::getCellIndex (UInt_t module_index, UInt_t multiplex_position, UInt_t line_i) const inline
get the cell index for the given module according to the current multiplex position and line index.
Parameters
module_index a valid index of a conencted module (getModuleIndex)
multiplex_position the multiplex sequence number (0-17).
line_i the number of the input line/ chip (0-11).
Returns
the cell index for the given multiplex position and line index. The cell index can be savely increment for the remaining lines (0 < line_i < getNLinesOfLeftIndex, getNLinesOfRightIndex).
Todo:
need more robust method to determine the number of lines per modules
Definition at line 130 of file MappingAndAlignment.hh.
UInt_t CALICE::MappingAndAlignment::getModuleID (UInt_t module_index) const inline
Get the ID of module which uniquely identifies a certain module of one module type.
Different modules of one type always have different IDs but modules of different types may have the same ID. In case of the ECAL the module ID is the serial number of the PCBs.
Parameters
module_index the index of the module within the detector (not necessarily the same as the module ID)
Returns
the ID of a module.
Exceptions
range_error if the module specified by module_index is not defined but only if BOUNDARY_CHECK is defined.
See Also
getModuleType()
Definition at line 188 of file MappingAndAlignment.hh.
std::pair<UInt_t,UInt_t> CALICE::MappingAndAlignment::getModuleIndex (UInt_t crate_id, UInt_t slot_id, UInt_t front_end_nr) const inline noexcept
Get the module indices connected to the right and left side of the given front-end.
Parameters
crate_id the identifier of the crate.
slot_id the identifier of the slot of the vme crate (usually 0-22)
front_end_nr the identifier of the front-end (0-7, 8 has special meaning which is not supported).
Returns
pair containing the module indices of the modules connected to the left and the right side of the front-end.
Exceptions
std::runtime_error if the crate is not registered or the slot of the crate has no connected front-ends.
std::range_error if the BOUNDARY_CHECK is defined and the crate and slot numbers are valid but the front-end number is out of the considered range.
Each front-end has two sides. the left side can be connected with a full connector (12 lines) or both sides can be connected with half connectors (6 lines). In case the left side is connected to a full connector the left and the rigtht module index will be the same.
Definition at line 76 of file MappingAndAlignment.hh.
Int_t CALICE::MappingAndAlignment::getModuleIndexFromCellIndex (UInt_t cellindex)
Return the module index for a given (Mokka) Cellindex All this assumes that the ModuleLocation class has got set properly the index of the lower left cell e.g.
CALICE::CellIndex(0,1,0,0,layer_i+1) , CALICE::CellIndex(a,1,0,0,layer_i+1) where the first argument is the wafer row (in case of SiW Ecal).
Todo:
Extend function to handle situation in which a layer k does not exist in data but is simulated
Definition at line 351 of file MappingAndAlignment.cc.
string CALICE::MappingAndAlignment::getModuleName (UInt_t module_index) const noexcept
Get the name containing the type specifier and the module ID.
A string is formed from th ID of the specified module and the module type name.
Parameters
module_index the index of the module within the detector (not necessarily the same as the module ID)
Returns
a string which uniquely identifies a module
Exceptions
range_error if the module specified by module_index is not defined but only if BOUNDARY_CHECK is defined.
See Also
ModuleDescription::getModuleTypeName(), ModuleConnection::getModuleID()
Definition at line 38 of file MappingAndAlignment.cc.
UInt_t CALICE::MappingAndAlignment::getNCellsTotal () const inline
Return the total number of defined cells.
The total number of cells includes cells of all modules also modules which are not connected to the DAQ but which are defined.
Definition at line 244 of file MappingAndAlignment.hh.
UInt_t CALICE::MappingAndAlignment::getNumberOfLines (const std::pair< UInt_t, UInt_t > & module_indices, bool right_instead_of_left) const inline
Return the number above the last line which should be used for the left or the right index.
Parameters
module_indices the left and the right module indec.
right_instead_of_left if true the right index is used instead of the left.
Returns
the line after the last line which may be use for the specified module index.
Definition at line 313 of file MappingAndAlignment.hh.
const TcmtConnection * CALICE::MappingAndAlignment::getTcmtConnection (UInt_t crate, UInt_t slot, UInt_t fe, UInt_t chip, UInt_t chan) const
Get the connection object associated to an electronic channel.
Parameters
crate Crate number
slot Slot number
fe Front end number
chip Chip number
chan Channel number
Definition at line 571 of file MappingAndAlignment.cc.
bool CALICE::MappingAndAlignment::hasRightSide (const std::pair< UInt_t, UInt_t > & module_indices) const inline
Return true if the front-end has a right side connected.
Returns
true if the right side is connected and is not conencted to the same module as the left side. If the left and the right side is connected to the same module, then it is considered that a full connector was connected to the left side and the right side was not directly connected.
Definition at line 304 of file MappingAndAlignment.hh.
Bool_t CALICE::MappingAndAlignment::isCellDead (UInt_t module_index, UInt_t cell_index) inline
Verify whether the given cell is dead.
Parameters
module_index the index of the module location
cell_index the index of the cell on the module.
Returns
true if the cell is dead.
Definition at line 255 of file MappingAndAlignment.hh.
bool CALICE::MappingAndAlignment::isModuleConnected (UInt_t module_index) const inline noexcept
Verify whether the module location is connected to an active front-end.
Parameters
module_index the index of the module location.
Returns
true if the module location is connected to a front-end otherwise false.
Definition at line 217 of file MappingAndAlignment.hh.
Referenced by print().
bool CALICE::MappingAndAlignment::isValidCrate (UInt_t crate) const
Validates a crate number based on mapping.
It can be used to skip processing of unused crates as early as possible.
Parameters
crate Crate number to be validated
Definition at line 599 of file MappingAndAlignment.cc.
void CALICE::MappingAndAlignment::moduleConnectionChanged (lcio::LCCollection * col)
Inform the object about changes of the module connection.
Parameters
col collection of ModuleConnection objects This class must be called before using any(most) of the other methods. The function call will cause a rebuild of the module DAQ front-end connection tree.
Definition at line 92 of file MappingAndAlignment.cc.
References clearTcmtConnections(), correctFullHalfConnectorErrors(), determineMaximumCellNumberPerFrontEnd(), and rebuildConnectionTree().
void CALICE::MappingAndAlignment::moduleLocationChanged (lcio::LCCollection * col) virtual
Inform the object about changes of the module locations.
Parameters
col collection of ModuleLocation objects This class must be called before using any(most) of the other methods. The function call will cause a rebuild of the module DAQ front-end connection tree.
Reimplemented from CALICE::Alignment.
Definition at line 77 of file MappingAndAlignment.cc.
References correctFullHalfConnectorErrors(), determineMaximumCellNumberPerFrontEnd(), CALICE::ModuleLocation::getCellIndexOffset(), CALICE::Alignment::moduleLocationChanged(), and rebuildConnectionTree().
void CALICE::MappingAndAlignment::moduleTypeChanged (lcio::LCCollection * col) virtual
Inform the object about changes of the module types.
Parameters
col collection of ModuleDescription objects This class must be called before using any(most) of the other methods. The function call will cause a rebuild of the module DAQ front-end connection tree.
Reimplemented from CALICE::Alignment.
Definition at line 65 of file MappingAndAlignment.cc.
References _cellIDEncoding, correctFullHalfConnectorErrors(), determineMaximumCellNumberPerFrontEnd(), CALICE::Alignment::moduleTypeChanged(), and rebuildConnectionTree().
void CALICE::MappingAndAlignment::setViewConnectionTree (bool view_connection = true) inline
Toggle printing of the connecting tree after each rebuild (conditions data change: ModuleConnection, ModuleLocation).
Set to true if the connection tree should be displayed after each call to rebuild the connection tree. The latter is initiated after module location or module connection changes.
Definition at line 297 of file MappingAndAlignment.hh.
The documentation for this class was generated from the following files:
MappingAndAlignment.hh
MappingAndAlignment.cc