CALICE_USERLIB: CALICE::Ahc2TileIndex Class Reference
CALICE::Ahc2TileIndex Class Reference
Encodes/decodes hardware channel information for the Large CALICE AHCAL prototype.
#include <Ahc2TileIndex.hh>
Public Member Functions
Ahc2TileIndex ()
Empty constructor.
Ahc2TileIndex (std::string moduleEncodingString)
Ahc2TileIndex (int index, std::string moduleEncodingString="")
Constructor from an integer for decoding.
Ahc2TileIndex (short mod, short chip, short chan, std::string moduleEncodingString="")
Constructor from the minimum set of parameters required for unique identification.
Ahc2TileIndex (short mod, short chip, short chan, short sipm, std::string moduleEncodingString="")
Constructor from the full set of parameters.
~Ahc2TileIndex ()
Destructor - does nothing.
unsigned int getModule () const
Decode module identifier.
unsigned short getModuleType () const
Derive module type from module and chip identifier.
unsigned short getChip () const
Decode ASIC identifier.
unsigned short getChannel () const
Decode multiplex channel.
unsigned short getSipm () const
Decode SiPM number.
unsigned int getIndex () const
Return THE index.
Ahc2TileIndex & setModuleEncodingString (std::string moduleEncodingString)
set module encoding stirng
Ahc2TileIndex & setIndex (unsigned int index)
Ahc2TileIndex & setModule (short mod)
Encode module identifier.
Ahc2TileIndex & setChip (short chip)
Encode ASIC identifier.
Ahc2TileIndex & setChannel (short chan)
Encode multiplex channel.
Ahc2TileIndex & setSipm (short sipm)
Encode SiPM number.
std::string getEncodingString (const unsigned int startbit)
Return the cellid encoding string according to an lcio BitField64.
Protected Attributes
unsigned int _index
std::string _moduleEncodingString
UTIL::BitField64 * _bf_cellID
Detailed Description
Encodes/decodes hardware channel information for the Large CALICE AHCAL prototype.
This class encodes and decodes module, chip and channel as well as the SiPM number into/from a single integer. This integer is intended to be stored in the CellID1 field of LCIO CalorimeterHit objects for easy reference to and unique identification of the hardware information of reconstructed hits.
This class is adapted from the HcalTileIndex.hh class in order to make it flexible for different CellID encodings
Author
Christian Graf
Date
2018, Jan
Version
1.0
Definition at line 29 of file Ahc2TileIndex.hh.
Constructor & Destructor Documentation
CALICE::Ahc2TileIndex::Ahc2TileIndex () inline
Empty constructor.
All parameters default to zero.
Definition at line 33 of file Ahc2TileIndex.hh.
References setChannel(), setChip(), setModule(), setModuleEncodingString(), and setSipm().
CALICE::Ahc2TileIndex::Ahc2TileIndex (short mod, short chip, short chan, std::string moduleEncodingString = "") inline
Constructor from the minimum set of parameters required for unique identification.
The SiPM number defaults to zero.
Parameters
mod Module identifier
chip ASIC chip identifier
chan Multiplex channel identifier
moduleEncodingString encoding string
Definition at line 90 of file Ahc2TileIndex.hh.
References setChannel(), setChip(), setModule(), setModuleEncodingString(), and setSipm().
CALICE::Ahc2TileIndex::Ahc2TileIndex (short mod, short chip, short chan, short sipm, std::string moduleEncodingString = "") inline
Constructor from the full set of parameters.
Parameters
mod Module identifier
chip ASIC chip identifier
chan Multiplex channel identifier
sipm SiPM identifier
moduleEncodingString encoding string
Definition at line 113 of file Ahc2TileIndex.hh.
References setChannel(), setChip(), setModule(), setModuleEncodingString(), and setSipm().
The documentation for this class was generated from the following file:
Ahc2TileIndex.hh