CALICE_USERLIB: CALICE::TcmtEventBits Class Reference
CALICE::TcmtEventBits Class Reference
Bit set to describe the type of event in the TCMT.
#include <TcmtEventBits.hh>
Public Member Functions
TcmtEventBits ()
standard constructor
TcmtEventBits (const int value)
constructor with initialisaton of the the bits
bool hasMinNumberMuonLikeTowers ()
check if event has at least minimum number of muon like towers
bool hasMaxNumberMuonLikeTowers ()
check if event has more than maximun number of muon like towers
bool hasMinNumberMuonLikeLayers ()
check if event has at least minimum number of muon like layers
bool hasMinNumberHitsMuon ()
check if event has at least minimum number hits required by a muon like signal
bool hasMaxNumberHitsMuon ()
check if event has not more than maximum number hits required by a muon like signal
bool hasMinSumEnergyMuon ()
check if event has at least minimum energy sum required by a muon like signal
bool hasMaxSumEnergyMuon ()
check if event has not more than maximum energy sum required by a muon like signal
bool isMuon ()
bool isPedestal ()
bool isLeakage ()
void setMinNumberMuonLikeTowers (bool state)
void setMaxNumberMuonLikeTowers (bool state)
void setMinNumberMuonLikeLayers (bool state)
void setMinNumberHitsMuon (bool state)
void setMaxNumberHitsMuon (bool state)
void setMinSumEnergyMuon (bool state)
void setMaxSumEnergyMuon (bool state)
Public Member Functions inherited from CALICE::BitSet
int getInt () const
get integer corresponding to the bits
void setBits (const int value)
set all bits with an integer
std::vector< int > getIntVec () const
get vector of ints with elements corresponding to the single bits (1 for true and 0 for false)
void clear ()
clear all bits to 0
Protected Types
enum ETcmtEventBitNo {
kMinNumberMuonLikeTowers, kMaxNumberMuonLikeTowers, kMinNumberMuonLikeLayers, kMaxNumberTotalHitsMuon,
kMinNumberTotalHitsMuon, kMaxSumEnergyMuon, kMinSumEnergyMuon, kNumberOfBits
}
Additional Inherited Members
Protected Member Functions inherited from CALICE::BitSet
BitSet (const unsigned int maxBits, const int value=0x0)
constructur
bool getBit (unsigned int bitNo) const
get function for bit number
void setBit (unsigned int bitNo, bool state)
set function for bit number
Detailed Description
Bit set to describe the type of event in the TCMT.
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Date
November 2009
Version
1.0
Definition at line 16 of file TcmtEventBits.hh.
Member Enumeration Documentation
enum CALICE::TcmtEventBits::ETcmtEventBitNo protected
Enumerator
kMinNumberMuonLikeTowers
min number of muon like towers reached
kMaxNumberMuonLikeTowers
within max number of muon like towers
kMinNumberMuonLikeLayers
min number of muon like layers reached
kMaxNumberTotalHitsMuon
within max number of total hits
kMinNumberTotalHitsMuon
min number of total hits reached
kMaxSumEnergyMuon
within max energy sum
kMinSumEnergyMuon
min energy sum reached
Definition at line 18 of file TcmtEventBits.hh.
Constructor & Destructor Documentation
CALICE::TcmtEventBits::TcmtEventBits () inline
standard constructor
all bits are off
Definition at line 33 of file TcmtEventBits.hh.
CALICE::TcmtEventBits::TcmtEventBits (const int value) inline
constructor with initialisaton of the the bits
Parameters
[in] value bits to be set
Definition at line 40 of file TcmtEventBits.hh.
Member Function Documentation
bool CALICE::TcmtEventBits::hasMaxNumberHitsMuon () inline
check if event has not more than maximum number hits required by a muon like signal
Returns
state of kMaxNumberTotalHitsMuon
Definition at line 66 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMaxNumberTotalHitsMuon.
bool CALICE::TcmtEventBits::hasMaxNumberMuonLikeTowers () inline
check if event has more than maximun number of muon like towers
Returns
state of kMaxNumberMuonLikeTowers
Definition at line 51 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMaxNumberMuonLikeTowers.
bool CALICE::TcmtEventBits::hasMaxSumEnergyMuon () inline
check if event has not more than maximum energy sum required by a muon like signal
Returns
state of kMaxSumEnergyMuon
Definition at line 76 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMaxSumEnergyMuon.
bool CALICE::TcmtEventBits::hasMinNumberHitsMuon () inline
check if event has at least minimum number hits required by a muon like signal
Returns
state of kMinNumberTotalHitsMuon
Definition at line 61 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMinNumberTotalHitsMuon.
bool CALICE::TcmtEventBits::hasMinNumberMuonLikeLayers () inline
check if event has at least minimum number of muon like layers
Returns
state of kMinNumberMuonLikeLayers
Definition at line 56 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMinNumberMuonLikeLayers.
bool CALICE::TcmtEventBits::hasMinNumberMuonLikeTowers () inline
check if event has at least minimum number of muon like towers
Returns
state of kMinNumberMuonLikeTowers
Definition at line 46 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMinNumberMuonLikeTowers.
bool CALICE::TcmtEventBits::hasMinSumEnergyMuon () inline
check if event has at least minimum energy sum required by a muon like signal
Returns
state of kMinSumEnergyMuon
Definition at line 71 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), and kMinSumEnergyMuon.
bool CALICE::TcmtEventBits::isLeakage () inline
Returns
true if signal is higher than pedestal (muon AND other signals)
Definition at line 104 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), kMaxNumberMuonLikeTowers, kMaxNumberTotalHitsMuon, kMaxSumEnergyMuon, kMinNumberMuonLikeLayers, kMinNumberMuonLikeTowers, kMinNumberTotalHitsMuon, and kMinSumEnergyMuon.
bool CALICE::TcmtEventBits::isMuon () inline
Returns
true if signal fullfills all muon tests
Definition at line 81 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), kMaxNumberMuonLikeTowers, kMaxNumberTotalHitsMuon, kMaxSumEnergyMuon, kMinNumberMuonLikeLayers, kMinNumberMuonLikeTowers, kMinNumberTotalHitsMuon, and kMinSumEnergyMuon.
bool CALICE::TcmtEventBits::isPedestal () inline
Returns
true if signal is lower in energy and hits than a muon
Definition at line 94 of file TcmtEventBits.hh.
References CALICE::BitSet::getBit(), kMaxNumberTotalHitsMuon, kMaxSumEnergyMuon, kMinNumberTotalHitsMuon, and kMinSumEnergyMuon.
The documentation for this class was generated from the following file:
TcmtEventBits.hh