CALICE_USERLIB: EventStat_t Class Reference
EventStat_t Class Reference
Statistics about event data record errors.
#include <EventStatList_t.hh>
Public Member Functions
void finish ()
does nothing.
void printTableHeader (std::ostream &out) const
Print the table header.
void print (std::ostream &out)
Print the statistics of one object (one table row).
bool hasInfo () const
Return true if at least one error was detected for the corresponding front-end.
void sameEvent ()
Notify that the same event was read out twice.
void corruptRecord ()
Notify that the record is corrupt.
void triggerCounterMismatch ()
Notify about a trigger counter mismitch wrt.
void slotTriggerCounterMismatch ()
Notify about a trigger counter mismitch wrt.
void noFeData ()
Notify missing front-end event data.
void feData ()
Notify about available front-end event data.
void setBadVLinkHeader ()
Notify bad Vlink Headers according to Pauls verify function.
void setDestroyedCrcVLinkRecords ()
Notify completetly corrupt ADC records (e.g.
unsigned int refreshErrors () const
The total number of events for which the previous event was read again instead of a new one.
unsigned int recordErrors () const
The total number of events for which the event data record was corrupt.
unsigned int triggerCounterErrors () const
The total number of events for which the trigger counter did not match the one of the previous front-end.
unsigned int slotTriggerCounterErrors () const
The total number of events for which the trigger counter did not match the one of the previous slot.
unsigned int eventsWithoutFeData () const
The total number of events for which the front-end event data was missing.
unsigned int badVLinkHeaders ()
Return the number of bad VLink Headers.
unsigned int destroyedCrcVLinkRecords ()
Return the number of destroyed CrcVLinkData.
unsigned int error () const
The total number of errors.
Public Member Functions inherited from StatObj_t
virtual ~StatObj_t ()
objects with virtual methods should also have a virtual destructor.
Private Attributes
unsigned int _sameEvent
unsigned int _corruptRecord
unsigned int _triggerCounterMismatch
unsigned int _slotTriggerCounterMismatch
unsigned int _missingFeData
unsigned int _nFeData
unsigned int _nBadHeader
variables counting missing header info
unsigned int _nDesCrcVLink
Detailed Description
Statistics about event data record errors.
The object is meant to be used together with FeStatList_t. This object collects statistics about bad event data records The following errors are counted: the same event was read out twice; the trigger counter does not match the trigger counter of another Crc Board; the record is corrupt.
Author
Goetz Gaycken, LLR - Ecole polytechnique
Date
feb, 2006
Definition at line 16 of file EventStatList_t.hh.
Member Function Documentation
void EventStat_t::feData () inline
Notify about available front-end event data.
If front-end data is missing always than it is not an error.
Definition at line 61 of file EventStatList_t.hh.
bool EventStat_t::hasInfo () const inline virtual
Return true if at least one error was detected for the corresponding front-end.
Implements StatObj_t.
Definition at line 35 of file EventStatList_t.hh.
References error().
void EventStat_t::noFeData () inline
Notify missing front-end event data.
The front-end event data is needed to identify corrupt records and find trigger counter mismatches.
Definition at line 56 of file EventStatList_t.hh.
void EventStat_t::print (std::ostream & out) virtual
Print the statistics of one object (one table row).
Implements StatObj_t.
Definition at line 16 of file EventStatList_t.cc.
References badVLinkHeaders(), destroyedCrcVLinkRecords(), eventsWithoutFeData(), recordErrors(), refreshErrors(), slotTriggerCounterErrors(), and triggerCounterErrors().
void EventStat_t::setDestroyedCrcVLinkRecords () inline
Notify completetly corrupt ADC records (e.g.
at beginning of config
Definition at line 70 of file EventStatList_t.hh.
void EventStat_t::slotTriggerCounterMismatch () inline
Notify about a trigger counter mismitch wrt.
to the previous Crc board.
Definition at line 51 of file EventStatList_t.hh.
void EventStat_t::triggerCounterMismatch () inline
Notify about a trigger counter mismitch wrt.
to the last "good" front-end.
Definition at line 47 of file EventStatList_t.hh.
The documentation for this class was generated from the following files:
EventStatList_t.hh
EventStatList_t.cc