CALICE_USERLIB: CALICE::AhcSlowReadoutModMapper Class Reference
CALICE::AhcSlowReadoutModMapper Class Reference
Class to correct the mapping of AhcSlowReadoutModBlock-classes.
#include <AhcSlowReadoutModMapper.hh>
Public Member Functions
lcio::LCCollection * mapCollection (const lcio::LCCollection *const col) const
returns collection with corrected AhcSlowReadoutModBlock-elements for an unmapped collection of AhcSlowReadoutModBlock
void updateMapping (const lcio::LCCollection *const col)
Function to update the mapping.
Private Member Functions
void init ()
void ensureSize (unsigned int i)
bool isAvailable (int module)
void setValues (AhcSlowReadoutModBlock *output, const std::vector< AhcSlowReadoutModBlock * > &input, unsigned int module) const
Private Attributes
std::vector< bool > _isAvailable
std::vector< int > _CMBlabel
std::vector< int > _HVlabel
std::vector< int > _LVlabel
Detailed Description
Class to correct the mapping of AhcSlowReadoutModBlock-classes.
The class AhcSlowReadoutModBlock containes the module number for which the records stands. Due to problems in the slow control in the years 2006 and 2007 the values from the different data sources have been written with wrong module number. Therefore, the single AhcSlowReadoutModBlock contains a collection of values from different modules. e.g. record with label "module = 17" contains CMB readings from module 23, HV readings from module 19 and corrupted LV readings
This class collects, as far as possible, the datas for the modules from the different records these ended up. If the mapping for one part is missing the values for this source will not be filled.
See Also
AhcSlowReadoutModBlock
AhcSlowReadoutModMapping
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Date
Nov 2008
Version
1.0
Definition at line 34 of file AhcSlowReadoutModMapper.hh.
Member Function Documentation
lcio::LCCollection * CALICE::AhcSlowReadoutModMapper::mapCollection (const lcio::LCCollection *const col) const
returns collection with corrected AhcSlowReadoutModBlock-elements for an unmapped collection of AhcSlowReadoutModBlock
Exceptions
WrongDataFormatException When the collection type is not LCGenericObjects or the collection parameter "TypeName" is not "AhcSlowReadoutModBlock"
Parameters
[in] col collection of AhcSlowReadoutModBlock
Returns
corrected collection of AhcSlowReadoutModBlock
See Also
WrongDataFormatException
AhcSlowReadoutModBlock
Definition at line 88 of file AhcSlowReadoutModMapper.cc.
References CALICE::ScintCaloSlowReadoutModBlock::getModuleNumber(), and CALICE::ScintCaloSlowReadoutModBlock::setModuleNumber().
void CALICE::AhcSlowReadoutModMapper::updateMapping (const lcio::LCCollection *const col)
Function to update the mapping.
Exceptions
CALICE::WrongDataFormatException When the collection type is not LCGenericObjects or the collection parameter "TypeName" is not "AhcSlowReadoutModMapping"
Parameters
[in] col The collection of AhcSlowReadoutModMapping objects
See Also
WrongDataFormatException
AhcSlowReadoutModMapping
Definition at line 133 of file AhcSlowReadoutModMapper.cc.
References CALICE::AhcSlowReadoutModMapping::getCMBlabel(), CALICE::AhcSlowReadoutModMapping::getHVlabel(), CALICE::AhcSlowReadoutModMapping::getLVlabel(), and CALICE::AhcSlowReadoutModMapping::getModule().
The documentation for this class was generated from the following files:
AhcSlowReadoutModMapper.hh
AhcSlowReadoutModMapper.cc