CALICE_USERLIB: ConfStat_t Class Reference
ConfStat_t Class Reference
Statistics about configuration record errors.
#include <ConfStatList_t.hh>
Public Member Functions
void finish ()
Add statistics of the last 10 records.
void printTableHeader (std::ostream &out) const
Print the table header.
void print (std::ostream &out)
Print the statistics of one object (one table row).
bool hasInfo () const
Return true if at least one error was detected for the corresponding front-end.
void addGood ()
The configuration data of the corresponding front-end is okay.
void addBad ()
The configuration data of the corresponding front-end is broken.
void addConsecutiveWrites ()
The configuration data of the corresponding front-end could bot be verified.
void checkPoint ()
Add the statistics gathered from the last 10 records to the total statistic and start a fresh sample.
void unCheckedCheckPoint ()
Add the statistics of the last sample to the total statistic.
unsigned int n () const
The size of the last sample.
unsigned int bad () const
The number of bad configuration records for this front-end in the last sample.
unsigned int consecutiveWrites () const
The number of unverified configuration records for this front-end in the last sample.
unsigned int error () const
The number of configuration errors for this front-end in the last sample.
unsigned int nTotal () const
The total sample size.
unsigned int badTotal () const
The total number of bad configuration records for this front-end.
unsigned int consecutiveWritesTotal () const
The total number of unverified configuration records for this front-end.
Public Member Functions inherited from StatObj_t
virtual ~StatObj_t ()
objects with virtual methods should also have a virtual destructor.
Private Attributes
unsigned int _n
unsigned int _feBad
unsigned int _consecutiveWrites
unsigned int _nTotal
unsigned int _feBadTotal
unsigned int _consecutiveWritesTotal
Detailed Description
Statistics about configuration record errors.
The object is meant to be used together with FeStatList_t. This object collects statistics about bad configuration data. The following errors are counted: the data which is read back does not agree with the data which was written; configuration data was written twice but never read back.
Author
Goetz Gaycken, LLR - Ecole polytechnique
Date
feb, 2006
Definition at line 15 of file ConfStatList_t.hh.
Member Function Documentation
void ConfStat_t::addBad () inline
The configuration data of the corresponding front-end is broken.
Definition at line 38 of file ConfStatList_t.hh.
References checkPoint().
void ConfStat_t::addConsecutiveWrites () inline
The configuration data of the corresponding front-end could bot be verified.
Definition at line 41 of file ConfStatList_t.hh.
References checkPoint().
void ConfStat_t::addGood () inline
The configuration data of the corresponding front-end is okay.
Definition at line 35 of file ConfStatList_t.hh.
References checkPoint().
bool ConfStat_t::hasInfo () const inline virtual
Return true if at least one error was detected for the corresponding front-end.
Implements StatObj_t.
Definition at line 32 of file ConfStatList_t.hh.
References error().
void ConfStat_t::print (std::ostream & out) virtual
Print the statistics of one object (one table row).
Implements StatObj_t.
Definition at line 11 of file ConfStatList_t.cc.
References badTotal(), consecutiveWritesTotal(), and nTotal().
The documentation for this class was generated from the following files:
ConfStatList_t.hh
ConfStatList_t.cc