CALICE_USERLIB: CALICE::DaqTypeDataBlock Class Reference
CALICE::DaqTypeDataBlock Class Reference
Base Class to handle all daq types (for the time being apart from the actual crc data) This base class constains the functions to store the data The actual handling of the data is left to dedicated classes which have to derive from this class.
#include <DaqTypeDataBlock.hh>
Public Member Functions
DaqTypeDataBlock ()
Constructor.
DaqTypeDataBlock (LCObject *obj, bool restoreMaps=true)
'Copy constructor' needed to interpret LCCollection read from file/database.
DaqTypeDataBlock & setTimeStamps (std::map< std::string, time_t > timeStampMapRaw)
Set the time stamps or better initialize the timestamp map which will be stored Remember: We store UTC!!!!
TimeStampMap_t getTimeStamps ()
virtual void setDblArrays (const DaqTypeDataDblMap_t &daqTypeDataDblMap)
These methods receive the vectors with the measured values Mainly to store large arrays of a given datatype but in principle this can be extended to every entry in the interface class.
virtual void setFloatArrays (const DaqTypeDataFloatMap_t &daqTypeDataFloatMap)
virtual void setIntArrays (const DaqTypeDataUIntMap_t &)
virtual void setIntArrays (const DaqTypeDataIntMap_t &)
DaqTypeDataIntMap_t getIntArrays ()
The following methods allow to retrieve the maps.
DaqTypeDataDblMap_t getDblArrays ()
DaqTypeDataFloatMap_t getFloatArrays ()
DaqTypeDataBlock * finalize ()
A method which finally fills the object which is stored.
virtual const double getBeamEnergy ()
A method to calculate the beam energy which has to be implemented by the derived classes.
virtual void print (std::ostream &)
convenient print method
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Public Member Functions inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImplExt ()
Default c'tor.
LCGenericObjectImplExt (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCGenericObjectImplExt ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Private Member Functions
void setNumberOfIntTypes (int numvals)
Store the number of int data types.
int getNumberOfIntTypes () const
Retrieve the number of int data types.
void setNumberOfTimeStamps (int numvals)
Store the number of timestamps.
int getNumberOfTimeStamps () const
Retrieve the number of int data types.
void setPointerToIndexOfIntTypeNames (int nameind)
Store the index at which the pointer to the names of the int data data types do start.
int getPointerToIndexOfIntTypeNames () const
Retrieve the index at which the pointer to the names of int data types do start.
void setPointerToIndexOfTimeStampNames (int nameind)
Store the index at which the pointer to the names of the time stamps do start.
int getPointerToIndexOfTimeStampNames () const
Retrieve the index at which the pointer to the names of the time stamps do start.
void setTypeIndex (int pos, int value)
Set the index of a given data type name.
void setLengthIndexOfIntTypeNames (int lengthindex)
Store the index at which the lengths of the names of the int data types do start.
int getLengthIndexOfIntTypeNames () const
Retrieve the index at which the lengths of the names of the int data types do start.
void setLengthIndexOfTimeStampNames (int lengthindex)
Store the index at which the lengths of the names of the time stamps do start.
int getLengthIndexOfTimeStampNames () const
Retrieve the index at which the lengths of the names of the int data types do start.
void setSizeIndexOfIntType (int size)
Store the Index where the sizes of the int data data types do start.
int getSizeIndexOfIntType () const
Retrieve index where the sizes of int data types do start.
void setNumberOfDblTypes (int numvals)
Store the number of double data types.
int getNumberOfDblTypes () const
Retrieve the number of double data types.
void setPointerToIndexOfDblTypeNames (int nameind)
Store the at which the names the double data data types do start.
int getPointerToIndexOfDblTypeNames () const
Retrieve index at which the names of double data types do start.
void setLengthIndexOfDblTypeNames (int length)
Store the index at which lengths of the names of the double data types do start.
int getLengthIndexOfDblTypeNames () const
Retrieve the index at which the lengths of the names of the double data types do start.
void setSizeIndexOfDblType (int size)
Store the Index where the sizes of the double data data types do start.
int getSizeIndexOfDblType () const
Retrieve index where the sizes of double data types do start.
void setNumberOfFloatTypes (int numvals)
Store the number of float data types.
int getNumberOfFloatTypes () const
Retrieve the number of float data types.
void setPointerToIndexOfFloatTypeNames (int nameind)
Store the index at which the names of the float data types do start.
int getPointerToIndexOfFloatTypeNames () const
Retrieve index at which the names of the float data types do start.
void setLengthIndexOfFloatTypeNames (int length)
Store the index at which the lengths of the names of the float data types do start.
int getLengthIndexOfFloatTypeNames () const
Retrieve the index at which the lengths of the names of the float data types do start.
void setSizeIndexOfFloatType (int size)
Store the Index where the sizes of the float data data types do start.
int getSizeIndexOfFloatType () const
Retrieve index where the sizes of double data types do start.
void calculateTimeStamp (struct tm *)
Simple method to decompose the struct tm containing the timestamp into ints which can be stored in the LCGenericObject and therefore in the database.
LCTime composeTimeStamp ()
turn the two ints containing the timestamp info into a LCTime Object
void RestoreMaps ()
A method which restores the map from the generic object.
Private Attributes
std::map< std::string, time_t > _timeStampMapRaw
A map holds the nature and the value of the timestamps.
TimeStampMap_t _timeStampMap
Another map now with the time stamp using LCIO Utils.
int _timestamptoint [2]
A simple array which holds the timestamp decomposed into two ints containing a) ymd and b) hms.
DaqTypeDataDblMap_t _bufferOfDbls
Variables which buffer the maps passed by the converter Buffering is needed since we don't know a priori when the objects are passed to us and which data types they contain the 'finalize' method (see below) will finally create the object from the buffers Buffer for doubles.
DaqTypeDataFloatMap_t _bufferOfFloats
Buffer for Floats.
DaqTypeDataIntMap_t _bufferOfInts
Buffer for Ints.
Additional Inherited Members
Protected Attributes inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Base Class to handle all daq types (for the time being apart from the actual crc data) This base class constains the functions to store the data The actual handling of the data is left to dedicated classes which have to derive from this class.
The implementation and the interpretation of the stored values is left to the derived classes. The actual meaning of the entries is propagated from a daq class into the database. Note, that in principle really all data types (apart from crc data) can be handled by this class However, existing interface classes (written before Oct. 2008) will remain untouched or exchanged gradually. if considered to be useful. This class allows for a quick reply to changes in the daq. In particular on the appearance of new data types.
Author
: Roman Pschl LAL/Orsay
Date
Oct 2008
Definition at line 61 of file DaqTypeDataBlock.hh.
Member Function Documentation
DaqTypeDataBlock * CALICE::DaqTypeDataBlock::finalize ()
A method which finally fills the object which is stored.
Todo:
can the algorithms in this method be templated?
Definition at line 37 of file DaqTypeDataBlock.cc.
References _bufferOfDbls, _bufferOfFloats, _bufferOfInts, _timeStampMap, _timeStampMapRaw, _timestamptoint, calculateTimeStamp(), CALICE::convertStringToInts(), getLengthIndexOfFloatTypeNames(), getNumberOfDblTypes(), getNumberOfFloatTypes(), getNumberOfIntTypes(), getNumberOfTimeStamps(), getPointerToIndexOfDblTypeNames(), getPointerToIndexOfFloatTypeNames(), getPointerToIndexOfIntTypeNames(), getPointerToIndexOfTimeStampNames(), CALICE::getStringFromInts(), CALICE::LCGenericObjectImplExt::obj(), RestoreMaps(), setLengthIndexOfDblTypeNames(), setLengthIndexOfFloatTypeNames(), setLengthIndexOfIntTypeNames(), setLengthIndexOfTimeStampNames(), setNumberOfDblTypes(), setNumberOfFloatTypes(), setNumberOfIntTypes(), setNumberOfTimeStamps(), setPointerToIndexOfDblTypeNames(), setPointerToIndexOfFloatTypeNames(), setPointerToIndexOfIntTypeNames(), setPointerToIndexOfTimeStampNames(), setSizeIndexOfDblType(), setSizeIndexOfFloatType(), setSizeIndexOfIntType(), and setTypeIndex().
DaqTypeDataIntMap_t CALICE::DaqTypeDataBlock::getIntArrays () inline
The following methods allow to retrieve the maps.
Todo:
: Should these methods really be public or only accessible by friend functions or ...?
: Do we have to check whether they has been filled or not before we hand it to the user?
Definition at line 120 of file DaqTypeDataBlock.hh.
The documentation for this class was generated from the following files:
DaqTypeDataBlock.hh
DaqTypeDataBlock.cc