CALICE_USERLIB: CALICE::TriggerHistory Class Reference
CALICE::TriggerHistory Class Reference
Utility class to chech the zero suppressed trigger history which will be atteched to the lcio event.
#include <TriggerHistory.hh>
Public Member Functions
TriggerHistory (const EVENT::LCEvent &evt, const std::string &history_name)
unsigned int getNumberOfElements () const
Get the number of elements in the zero suppressed trigger history.
int getTimeDifferenceAt (unsigned int element_i) const
Get the time difference to the main word in ns.
int getBitsAt (unsigned int element_i) const
Get the trigger bits which were set for the given element.
unsigned int cleanUntil (int length_in_ns, unsigned int trigger_bit_mask) const
Return the position with in the given range where there is trigger activity.
Protected Attributes
std::vector< int > _position
std::vector< int > _bits
Detailed Description
Utility class to chech the zero suppressed trigger history which will be atteched to the lcio event.
Author
G. Gaycken LLR
Date
Dec 2 2005
Definition at line 23 of file TriggerHistory.hh.
Member Function Documentation
unsigned int CALICE::TriggerHistory::cleanUntil (int length_in_ns, unsigned int trigger_bit_mask) const inline
Return the position with in the given range where there is trigger activity.
Parameters
length_in_ns the range of the trigger fifo in ns which should reflect inactivity.
trigger_bit_mask a bit mask of all the trigger bits which indicate activity.
Returns
the position in the fifo where there is trigger activity. If there is no trigger activity in the given range then zero is returned. Note: it is not verified whether the main word is far enough away from the corresponding end of the fifo.
Definition at line 76 of file TriggerHistory.hh.
References getBitsAt(), getNumberOfElements(), and getTimeDifferenceAt().
The documentation for this class was generated from the following file:
TriggerHistory.hh