CALICE_USERLIB: CALICE::LinearFitCompound Class Reference
CALICE::LinearFitCompound Class Reference
Class to store the constant of a linear fit within the lcio framework.
#include <LinearFitCompound.hh>
Public Member Functions
LinearFitCompound (lcio::LCObject *obj)
LinearFitCompound (const LinearFitConstant *lfc, const LinearFitSlope *lfs)
LinearFitCompound (int ID, double constant, double constant_error, double constant_reference_point, double constant_reference_point_error, double slope, double slope_error)
double eval (double x)
Evaluates the linear fit at the given point.
double evalErr (double x, double x_error)
int getID () const
Get the identifier.
double getConstant () const
Get the constant/y-intercept of the fit.
double getConstantError () const
Get the error of the constant.
double getSlope () const
Get slope of the linear fit.
double getSlopeError () const
Get error of the slope.
double getConstantReferencePoint () const
Get the reference point of the constant.
double getConstantReferencePointError () const
Get the error of the reference point of the constant.
void setID (const int ID)
Sets an identifier.
void setConstant (const double constant)
Sets the constant.
void setConstantError (double constantError)
Sets the error of the constant.
void setSlope (const double slope)
Sets the slope.
void setSlopeError (const double slope_error)
Sets the error of the slope.
void setConstantReferencePoint (const double constantReferencePoint)
Sets the reference point of the constant.
void setConstantReferencePointError (double constantReferencePointError)
Sets the error of the reference point of the constant.
const std::string getTypeName () const
Get the type name.
const std::string getDataDescription () const
Get the data description.
Detailed Description
Class to store the constant of a linear fit within the lcio framework.
Author
LNTAI
Version
1.0
Date
27 October 2009
Definition at line 37 of file LinearFitCompound.hh.
Member Function Documentation
double CALICE::LinearFitCompound::eval (double x) inline
Evaluates the linear fit at the given point.
Parameters
x - the point at which the fit is evaluated
Definition at line 97 of file LinearFitCompound.hh.
References getConstant(), getConstantReferencePoint(), and getSlope().
const std::string CALICE::LinearFitCompound::getDataDescription () const inline
Get the data description.
The data description gives the meaning of the data fields.
Definition at line 247 of file LinearFitCompound.hh.
const std::string CALICE::LinearFitCompound::getTypeName () const inline
Get the type name.
The type name is used to determine which class interprets the LCGenericObject which holds the pure data.
Definition at line 238 of file LinearFitCompound.hh.
The documentation for this class was generated from the following file:
LinearFitCompound.hh