CALICE_USERLIB: CALICE::CellDescription Class Reference
CALICE::CellDescription Class Reference
class to hold data describing calorimeter cells
#include <CellDescription.hh>
Public Member Functions
void setPosition (const float x, const float y, const float z)
set position (mm)
void setSize (const float sizeX, const float sizeY)
set size (mm)
void setAngle (const float angle)
set angle (degree)
float getX () const
float getY () const
float getZ () const
float getSizeX () const
float getSizeY () const
float getAngle () const
Private Attributes
float _x
float _y
float _z
float _angle
float _sizeX
float _sizeY
Detailed Description
class to hold data describing calorimeter cells
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
0.1
Date
June 2009
Definition at line 13 of file CellDescription.hh.
Member Function Documentation
float CALICE::CellDescription::getAngle () const inline
Returns
angle in degree
Definition at line 73 of file CellDescription.hh.
float CALICE::CellDescription::getSizeX () const inline
Returns
x-size in mm
Definition at line 64 of file CellDescription.hh.
float CALICE::CellDescription::getSizeY () const inline
Returns
y-size in mm
Definition at line 68 of file CellDescription.hh.
float CALICE::CellDescription::getX () const inline
Returns
x-coordinate in mm
Definition at line 51 of file CellDescription.hh.
float CALICE::CellDescription::getY () const inline
Returns
y-coordinate in mm
Definition at line 55 of file CellDescription.hh.
float CALICE::CellDescription::getZ () const inline
Returns
z-coordinate in mm
Definition at line 59 of file CellDescription.hh.
void CALICE::CellDescription::setAngle (const float angle) inline
set angle (degree)
Parameters
angle angle
Definition at line 44 of file CellDescription.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
void CALICE::CellDescription::setPosition (const float x, const float y, const float z) inline
set position (mm)
Parameters
[in] x x-coordinate
[in] y y-coordinate
[in] z z-coordinate
Definition at line 23 of file CellDescription.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
void CALICE::CellDescription::setSize (const float sizeX, const float sizeY) inline
set size (mm)
Parameters
[in] sizeX cell size in x direction
[in] sizeY cell size in y direction
Definition at line 34 of file CellDescription.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
The documentation for this class was generated from the following file:
CellDescription.hh