CALICE_USERLIB: CALICE::Alignment Class Reference
CALICE::Alignment Class Reference
Class to comunicate/handle the translation into unique layer/cell ids and 3D spacial coordinates.
#include <Alignment.hh>
Public Member Functions
Alignment ()
default constructor.
void init ()
Does nothing for the time being.
UInt_t getGeometricalCellIndex (UInt_t module_index, UInt_t cell_index) const
Get the unique cell index of the cell specified by the module and the cell index.
bool isValid (UInt_t module_index) const
Return true if the type of the given module is valid.
UChar_t getModuleType (UInt_t module_index) const
Get the type of a certain module.
ThreeVector_t getPosition (UInt_t module_index, UInt_t cell_index) const
ThreeVector_t transformPosition (ThreeVector_t &a_position) const
UInt_t getNModules () const
Bool_t isModule (UInt_t module_index) const
Return false if the module index is out of range.
const ModuleDescription & getModuleDescription (UInt_t module_index) const
Return the description object for the given module.
UInt_t getNCellsPerModule (UInt_t module_index) const
Float_t getModuleWidth (UInt_t module_index) const
Get the cell width of the given module and cell.
Float_t getModuleHeight (UInt_t module_index) const
Get the cell width of the given module and cell.
Float_t getCellWidth (UInt_t module_index, UInt_t cell_index) const
Get the cell width of the given module and cell.
Float_t getCellHeight (UInt_t module_index, UInt_t cell_index) const
Get the cell width of the given module.
ThreeVector_t getPosition () const
Get the position of the detector in its proper coordinate system.
ThreeVector_t getModuleProperCenter (UInt_t module_index) const
Get the upper right corner of a module.
ThreeVector_t getModuleProperPosition (UInt_t module_index) const
Get the position of a module in the proper coordinate system of the detector.
ThreeVector_t getModulePosition (UInt_t module_index) const
Get the position of a module in the reference coordinate system.
ThreeVector_t getModuleCenter (UInt_t module_index) const
Get the center of a module in the reference coordinate system.
Float_t getDetectorAngleZX () const
Return the effective rotation angle of the detector.
virtual void moduleTypeChanged (lcio::LCCollection *col)
Inform the object about changes of the module types.
virtual void moduleLocationChanged (lcio::LCCollection *col)
Inform the object about changes of the module locations.
virtual void stagePositionChanged (lcio::LCCollection *col)
Inform the object about changes in the stage positions on which the detector is mounted.
virtual void detectorTransformation (lcio::LCCollection *col)
Inform the object about changes of the detector position and rotation.
virtual void referenceTransformation (lcio::LCCollection *col)
Inform the object about changes of the reference position and rotation.
UInt_t getCellIndexOffset (UInt_t module_index) const
Get the cell index offset of a module.
Protected Types
typedef SimpleArray_t< pair
< UInt_t, ModuleLocation > > ModuleList_t
Defined module locations (not necessarily connected to a front-end.
typedef SimpleArray_t
< ModuleDescription > ModuleTypeList_t
Protected Attributes
ModuleList_t _moduleLocationList
ModuleTypeList_t _moduleTypeList
Private Types
enum ETransformation { kDetector, kReference, kEffective, kNTransformations }
typedef void(Alignment::* StageChangeHandleFunc_t)(lcio::LCCollection *col)
A map which holds pointers to functions to access the parameters of teh movable stage(s)
Private Member Functions
void setTransformation (lcio::LCCollection *col, ETransformation transformation_type)
Set the transformation parameters from the conditions data collection.
void calculateEffectiveTransformation ()
Calculate the effective transformation from the detector and reference transformation.
void handleEmcStage (LCCollection *)
void handleAhcStage (LCCollection *)
Private Attributes
Float_t _detectorPos [kNTransformations][3]
the position of the detector
Float_t _detectorAngleZX [kNTransformations]
configuration angle w.r.t.
Double_t _detectorAngleZXSin
sin of the effective rotation angle in the z-x plane
Double_t _detectorAngleZXCos
cos of the effective rotation angle in the z-x plane
Float_t _detectorRotationX0 [kNTransformations]
origin of the detector ratation (x-direction)
Float_t _detectorRotationZ0 [kNTransformations]
origin of the detector ratation (z-direction)
std::map< std::string,
StageChangeHandleFunc_t > _knownStageTypes
float _stageOffset_x
The offsets due to the movable stage.
float _stageOffset_y
Static Private Attributes
static const Double_t __degToRad =M_PI/180.
Detailed Description
Class to comunicate/handle the translation into unique layer/cell ids and 3D spacial coordinates.
The class has to be informed about changes of the detector configuration using the methods CALICE::Alignment::moduleTypeChanged, CALICE::Alignment::moduleLocationChanged, CALICE::MappingAndAlignment::moduleConnectionChanged and Alignment::experimentalSetup. This information is used to map the DAQ signals to cells and calculate 3D spacial coordinates for hits.
The class performs range checks only if BOUNDARY_CHECK is defined.
Definition at line 42 of file Alignment.hh.
Member Typedef Documentation
typedef SimpleArray_t<pair<UInt_t,ModuleLocation> > CALICE::Alignment::ModuleList_t protected
Defined module locations (not necessarily connected to a front-end.
First component contains the module ID, the second the module location information.
Definition at line 475 of file Alignment.hh.
Constructor & Destructor Documentation
CALICE::Alignment::Alignment ()
default constructor.
The default constructor configures the conditions data change delegators.
Definition at line 29 of file Alignment.cc.
References setTransformation().
Member Function Documentation
void CALICE::Alignment::calculateEffectiveTransformation () private
Calculate the effective transformation from the detector and reference transformation.
Definition at line 171 of file Alignment.cc.
References _detectorAngleZX, _detectorAngleZXCos, _detectorAngleZXSin, _detectorPos, _detectorRotationX0, and _detectorRotationZ0.
Referenced by setTransformation().
virtual void CALICE::Alignment::detectorTransformation (lcio::LCCollection * col) inline virtual
Inform the object about changes of the detector position and rotation.
Parameters
col collection of DetectorTransformation objects This class must be called before querying the postion of cells. The position is calculated in the reference coorindate system.
Definition at line 457 of file Alignment.hh.
Float_t CALICE::Alignment::getCellHeight (UInt_t module_index, UInt_t cell_index) const inline
Get the cell width of the given module.
It is assumed that the cells of one module all have the same width.
Definition at line 325 of file Alignment.hh.
UInt_t CALICE::Alignment::getGeometricalCellIndex (UInt_t module_index, UInt_t cell_index) const inline
Get the unique cell index of the cell specified by the module and the cell index.
Parameters
module_index unique index for modules which should run from 0..total number of modules
cell_index within the module (0.. number of cells of this module type)
Returns
unique cell index.
Exceptions
range_error if the module index is out of range and BOUNDARY_CHECK is defined
The cell index conforms to the Mokka specification (see for example CellIndex). It is composed of the layer number, the wafer column and row, and the pad column and row.
Definition at line 68 of file Alignment.hh.
const ModuleDescription& CALICE::Alignment::getModuleDescription (UInt_t module_index) const inline
Return the description object for the given module.
Parameters
module_index the index of the moduel.
Definition at line 229 of file Alignment.hh.
UChar_t CALICE::Alignment::getModuleType (UInt_t module_index) const inline
Get the type of a certain module.
The module type together with the module ID uniquly identifies a module. Different modules of one type always have different IDs but modules of different types may have the same ID. In case of the ECAL the module ID is the serial number of the PCBs.
Parameters
module_index the index of the module within the detector (not necessarily the same as the module ID)
Returns
the module type
Exceptions
range_error if the module specified by module_index is not defined but only if BOUNDARY_CHECK is defined.
See Also
getModuleID()
Definition at line 114 of file Alignment.hh.
Referenced by CALICE::MappingAndAlignment::print().
bool CALICE::Alignment::isValid (UInt_t module_index) const inline
Return true if the type of the given module is valid.
Parameters
module_index the index of the given module.
Definition at line 90 of file Alignment.hh.
Referenced by CALICE::MappingAndAlignment::print().
void CALICE::Alignment::moduleLocationChanged (lcio::LCCollection * col) virtual
Inform the object about changes of the module locations.
Parameters
col collection of ModuleLocation objects This class must be called before using any(most) of the other methods. The function call will cause a rebuild of the module DAQ front-end connection tree.
Reimplemented in CALICE::MappingAndAlignment.
Definition at line 76 of file Alignment.cc.
Referenced by CALICE::MappingAndAlignment::moduleLocationChanged().
void CALICE::Alignment::moduleTypeChanged (lcio::LCCollection * col) virtual
Inform the object about changes of the module types.
Parameters
col collection of ModuleDescription objects This class must be called before using any(most) of the other methods. The function call will cause a rebuild of the module DAQ front-end connection tree.
Reimplemented in CALICE::MappingAndAlignment.
Definition at line 47 of file Alignment.cc.
Referenced by CALICE::MappingAndAlignment::moduleTypeChanged().
virtual void CALICE::Alignment::referenceTransformation (lcio::LCCollection * col) inline virtual
Inform the object about changes of the reference position and rotation.
Parameters
col collection of DetectorTransformation objects This class must be called before querying the postion of cells. The position is calculated in the reference coordinate system.
Definition at line 466 of file Alignment.hh.
void CALICE::Alignment::stagePositionChanged (lcio::LCCollection * col) virtual
Inform the object about changes in the stage positions on which the detector is mounted.
Parameters
col collection of StageParameters objects This class must be called before calculating the actual cell positions The function will provide the xy values for a correct transversal alignment of the detectors.
Definition at line 218 of file Alignment.cc.
Field Documentation
Float_t CALICE::Alignment::_detectorAngleZX[kNTransformations] private
configuration angle w.r.t.
to the beam axis in the horizontal plane
Definition at line 501 of file Alignment.hh.
Referenced by calculateEffectiveTransformation(), and setTransformation().
The documentation for this class was generated from the following files:
Alignment.hh
Alignment.cc