CALICE_USERLIB: CALICE::HcalTileIndex Class Reference
CALICE::HcalTileIndex Class Reference
Encodes/decodes hardware channel information for the CALICE AHCAL prototype.
#include <HcalTileIndex.hh>
Public Member Functions
HcalTileIndex ()
Empty constructor.
HcalTileIndex (int index)
Constructor from an integer for decoding.
HcalTileIndex (short mod, short chip, short chan)
Constructor from the minimum set of parameters required for unique identification.
HcalTileIndex (short mod, short chip, short chan, short sipm)
Constructor from the full set of parameters.
~HcalTileIndex ()
Destructor - does nothing.
unsigned short getModule () const
Decode module identifier.
unsigned short getModuleType () const
Derive module type from module and chip identifier.
unsigned short getChip () const
Decode ASIC identifier.
unsigned short getChannel () const
Decode multiplex channel.
unsigned short getSipm () const
Decode SiPM number.
unsigned int getIndex () const
Return THE index.
HcalTileIndex & setModule (short mod)
Encode module identifier.
HcalTileIndex & setChip (short chip)
Encode ASIC identifier.
HcalTileIndex & setChannel (short chan)
Encode multiplex channel.
HcalTileIndex & setSipm (short sipm)
Encode SiPM number.
Static Public Member Functions
static std::string getEncodingString (const unsigned int startbit)
Return the cellid encoding string according to an lcio BitField64.
Protected Attributes
unsigned int _index
Detailed Description
Encodes/decodes hardware channel information for the CALICE AHCAL prototype.
This class encodes and decodes module, chip and channel as well as the SiPM number into/from a single integer. This integer is intended to be stored in the CellID1 field of LCIO CalorimeterHit objects for easy reference to and unique identification of the hardware information of reconstructed hits.
Author
Niels.nosp@m..Mey.nosp@m.er@de.nosp@m.sy.d.nosp@m.e
Date
Nov. 17, 2007
Version
1.0
Definition at line 39 of file HcalTileIndex.hh.
Constructor & Destructor Documentation
CALICE::HcalTileIndex::HcalTileIndex () inline
Empty constructor.
All parameters default to zero.
Definition at line 43 of file HcalTileIndex.hh.
References setChannel(), setChip(), setModule(), and setSipm().
CALICE::HcalTileIndex::HcalTileIndex (short mod, short chip, short chan) inline
Constructor from the minimum set of parameters required for unique identification.
The SiPM number defaults to zero.
Parameters
mod Module identifier
chip ASIC chip identifier
chan Multiplex channel identifier
Definition at line 60 of file HcalTileIndex.hh.
References setChannel(), setChip(), setModule(), and setSipm().
CALICE::HcalTileIndex::HcalTileIndex (short mod, short chip, short chan, short sipm) inline
Constructor from the full set of parameters.
Parameters
mod Module identifier
chip ASIC chip identifier
chan Multiplex channel identifier
sipm SiPM identifier
Definition at line 71 of file HcalTileIndex.hh.
References setChannel(), setChip(), setModule(), and setSipm().
The documentation for this class was generated from the following file:
HcalTileIndex.hh