CALICE_USERLIB: CALICE::SatCorrItep Class Reference
CALICE::SatCorrItep Class Reference
Public Member Functions
SatCorrItep (EVENT::LCObject *obj)
SatCorrItep (const HcalTileIndex &hti, const unsigned int nPoints, const float *pixs, const float *pmts)
const int getIndex () const
float getScaling () const
get the applied scaling
float deSaturate (const float saturatedSignal) const
apply saturation correction to a signal amplitude
float deSaturatedError (const float saturatedSignal, const float saturatedSignalError) const
error after application of saturation correction to a signal
float saturate (const float unsaturatedSignal) const
apply saturation to a signal amplitude
float saturatedError (const float unsaturatedSignal, const float unsaturatedSignalError) const
error after application of saturation to a signal
const std::string getTypeName () const
const std::string getDataDescription () const
void setIndex (const HcalTileIndex &hti)
void setScaling (const float scaling)
void setProcedureType (const int procedureType)
int getProcedureType () const
float getPix (const unsigned int i) const
float getPmt (const unsigned int i) const
void setPix (const unsigned int i, const float pix)
void setPmt (const unsigned int i, const float pmt)
float getFunParam0 () const
float getFunParam1 () const
float getFunParam2 () const
void setFunParameters (const float p0, const float p1, const float p2)
Private Attributes
float _scaling
int _procedureType
float _funParam0
float _funParam1
float _funParam2
Detailed Description
Definition at line 13 of file SatCorrItep.hh.
Member Function Documentation
float CALICE::SatCorrItep::deSaturate (const float saturatedSignal) const virtual
apply saturation correction to a signal amplitude
Parameters
saturatedSignal saturated signal
Returns
unsaturated signal
Implements CALICE::SatCorrFunction.
Definition at line 59 of file SatCorrItep.cc.
Referenced by deSaturatedError().
float CALICE::SatCorrItep::deSaturatedError (const float saturatedSignal, const float saturatedSignalError) const virtual
error after application of saturation correction to a signal
Parameters
saturatedSignal saturated signal
saturatedSignalError error of the saturated signal
Returns
error of the unsaturated signal
Implements CALICE::SatCorrFunction.
Definition at line 128 of file SatCorrItep.cc.
References deSaturate().
float CALICE::SatCorrItep::saturate (const float unsaturatedSignal) const virtual
apply saturation to a signal amplitude
Parameters
unsaturatedSignal unsaturated signal
Returns
saturated signal
Implements CALICE::SatCorrFunction.
Definition at line 140 of file SatCorrItep.cc.
Referenced by saturatedError().
float CALICE::SatCorrItep::saturatedError (const float unsaturatedSignal, const float unsaturatedSignalError) const virtual
error after application of saturation to a signal
Parameters
unsaturatedSignal unsaturated signal
unsaturatedSignalError error of the unsaturated signal
Returns
error of saturated signal
Implements CALICE::SatCorrFunction.
Definition at line 218 of file SatCorrItep.cc.
References saturate().
The documentation for this class was generated from the following files:
SatCorrItep.hh
SatCorrItep.cc