CALICE_USERLIB: Average_t Class Reference
Average_t Class Reference
Calculate mean and standard deviation and find minimum and maximum value.
#include <Average_t.hh>
Public Member Functions
Average_t ()
Default constructor initialses all arrays to be ready to gather statastics of a variable.
void add (Float_t value, Float_t weight=1.)
Build the sum and the sum of squares and find the minimum and maximum value.
void calculate ()
Calculate the standard deviation and the mean.
Double_t mean () const
Return the mean value.
Double_t sigma () const
Return the standard deviation.
Float_t min () const
Return the minimum value.
Float_t max () const
Return the maximum value.
Double_t weight () const
Get the total accumulated weight.
Double_t sum () const
Get the total accumulated data.
Protected Attributes
Double_t _weight
Float_t _min
Float_t _max
union {
Double_t _sum
Double_t _mean
};
union {
Double_t _sum2
Double_t _sigma
};
Friends
std::ostream & operator<< (std::ostream &os, const Average_t &a)
Detailed Description
Calculate mean and standard deviation and find minimum and maximum value.
The minimum and maximum is not searched/memorised if AVERAGE_WITHOUT_MIN_MAX is defined.
Definition at line 21 of file Average_t.hh.
Member Function Documentation
void Average_t::add (Float_t value, Float_t weight = 1.) inline
Build the sum and the sum of squares and find the minimum and maximum value.
The sums can be used later to calculate the mean and the standard deviation
Parameters
value the value to be added to the sum and the sum of squares
weight the weight given to this value in the sums. (
See Also
calculate)
Definition at line 39 of file Average_t.hh.
References weight().
void Average_t::calculate () inline
Calculate the standard deviation and the mean.
The mean and the standard deviation are stored in the locations which are also used for the sums. Therefore if further values are added after calculate() was called, the result is undefined.
Definition at line 51 of file Average_t.hh.
References mean(), and sigma().
Double_t Average_t::mean () const inline
Return the mean value.
returns only a correct result after at least 1 value was added and calculate was called.
Definition at line 63 of file Average_t.hh.
Referenced by calculate().
Double_t Average_t::sigma () const inline
Return the standard deviation.
returns only a correct result after at least 1 value was added and calculate was called.
Definition at line 68 of file Average_t.hh.
Referenced by calculate().
The documentation for this class was generated from the following file:
Average_t.hh