CALICE_USERLIB: CALICE::ModuleLocation Class Reference
CALICE::ModuleLocation Class Reference
Define possible positions of modules.
#include <ModuleLocation.hh>
Public Member Functions
ModuleLocation (LCObject *obj)
'Copy constructor', create the ModuleLocation interface for the generic objects read from file/database.
ModuleLocation & setX (float value)
float getX () const
ModuleLocation & setY (float value)
float getY () const
ModuleLocation & setZ (float value)
float getZ () const
ModuleLocation & setCellIndexOffset (int first_cell_index)
Set the offset to the cell index to form the full cell index of the layer.
int getCellIndexOffset () const
Get the offset to the cell index to form the full cell index of the layer.
ModuleLocation & setModuleType (UChar_t type)
Set the module type.
UChar_t getModuleType () const
Get the type of a module.
void print (std::ostream &os)
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Define possible positions of modules.
A module position is not necessarily connected. A connected to the DAQ is established via ModuleConnection. A module position is uniquely defined by the index offset i.e. two modules may not have the same index offset.
Definition at line 30 of file ModuleLocation.hh.
Constructor & Destructor Documentation
CALICE::ModuleLocation::ModuleLocation (LCObject * obj) inline
'Copy constructor', create the ModuleLocation interface for the generic objects read from file/database.
The objects stored in the file or database are of type LCGenericObject. To generate the interface of the object ModuleLocation:
ModuleLocation a_module_location(lc_collection->getElementAt(index));
Todo:
Currenlty, there is no serious type checking. Only the number of integers, floats and doubles is used to verify whether the LCGenericObject is of the type ModuleLocation
Definition at line 43 of file ModuleLocation.hh.
Member Function Documentation
int CALICE::ModuleLocation::getCellIndexOffset () const inline
Get the offset to the cell index to form the full cell index of the layer.
See Also
setCellIndexOffset
Definition at line 91 of file ModuleLocation.hh.
Referenced by CALICE::CellDescriptionGenerator::generate(), and CALICE::MappingAndAlignment::moduleLocationChanged().
UChar_t CALICE::ModuleLocation::getModuleType () const inline
Get the type of a module.
See Also
setModuleType
Definition at line 109 of file ModuleLocation.hh.
Referenced by CALICE::CellDescriptionGenerator::generate().
ModuleLocation& CALICE::ModuleLocation::setCellIndexOffset (int first_cell_index) inline
Set the offset to the cell index to form the full cell index of the layer.
The cell index is formed by a cell index calculated for a certain module type plus this offset. The result is a unique cell index to identify a cell unambiguously.
See Also
CellIndex
Definition at line 82 of file ModuleLocation.hh.
ModuleLocation& CALICE::ModuleLocation::setModuleType (UChar_t type) inline
Set the module type.
Currently, a module location is identified by the layer number and the module type i.e. each module type may be used at most once per layer.
Definition at line 100 of file ModuleLocation.hh.
The documentation for this class was generated from the following files:
ModuleLocation.hh
ModuleLocation.cc