CALICE_USERLIB: CALICE::ReadOutConfigurationBlock Class Reference
CALICE::ReadOutConfigurationBlock Class Reference
Stores the general readout configuration.
#include <ReadOutConfigurationBlock.hh>
Public Member Functions
ReadOutConfigurationBlock ()
Default Constructor.
ReadOutConfigurationBlock (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
ReadOutConfigurationBlock & setCrateID (int number)
Set the crate number.
int getCrateID () const
Get the crate number.
ReadOutConfigurationBlock & setSlotEnable (int slotEnable)
Set the slot enable.
int getSlotEnable () const
Get the slot enable.
bool isSlotEnabled (unsigned int slot_i) const
is the slot enabled?
ReadOutConfigurationBlock & setFeSlotEnable (int slotFeEnable, int pos)
Set the Slot FeEnable.
int getFeSlotEnable (int pos) const
Get the Slot FeEnable.
bool isFeEnabled (unsigned int slot_i, unsigned int fe_i) const
is the slot enabled?
ReadOutConfigurationBlock & setVmePeriod (int vmePeriod)
Set the vme period.
int getVmePeriod () const
Get the vme period.
ReadOutConfigurationBlock & setBePeriod (int bePeriod)
Set the be period.
int getBePeriod () const
Get the be period.
ReadOutConfigurationBlock & setBecPeriod (int becPeriod)
Set the bec period.
int getBecPeriod () const
Get the bec period.
ReadOutConfigurationBlock & setFePeriod (int fePeriod)
Set the fe period.
int getFePeriod () const
Get the fe period.
ReadOutConfigurationBlock & setBeSoftTrigger (int beSoftTrigger)
Set the Be Soft Trigger.
int getBeSoftTrigger () const
Get the Be Soft Trigger Config.
ReadOutConfigurationBlock & setFeSoftTrigger (int feSoftTrigger)
Set the Fe Soft Trigger(s) Config.
int getFeSoftTrigger () const
Get the Fe Soft Trigger Config.
bool getFeSoftTrigger (unsigned int fe_i) const
Get the front-end soft trigger.
ReadOutConfigurationBlock & setFeBrcSoftTrigger (int feBrcSoftTrigger)
Set the Broadcast Soft Trigger.
int getFeBrcSoftTrigger () const
Get the Broadcast Soft Trigger Config.
ReadOutConfigurationBlock & setConfMode (int confMode)
Set the Conf Mode.
int getConfMode () const
Get the Conf Mode.
void print (std::ostream &os)
Convenient print method.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Public Member Functions inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImplExt ()
Default c'tor.
LCGenericObjectImplExt (LCObject *obj)
LCGenericObjectImpl * obj ()
The LCGenericObjectImpl .
virtual ~LCGenericObjectImplExt ()
Clean up if we created a new LCGenericObjectImpl.
virtual int id ()
Return the id of the underlying LCGenericObjectImpl.
int getNInt () const
int getNFloat () const
int getNDouble () const
int getIntVal (int index) const
float getFloatVal (int index) const
double getDoubleVal (int index) const
bool isFixedSize () const
Static Public Member Functions
static unsigned int getFirstSlot ()
static unsigned int getLastSlot ()
Additional Inherited Members
Protected Attributes inherited from CALICE::LCGenericObjectImplExt
LCGenericObjectImpl * _obj
bool _createdObject
Detailed Description
Stores the general readout configuration.
e.g. to decide whether a softtrigger was enabled In addition information about general hardware configuration can be retrieved. For a give crate the enabled slots can be obtained by the getSlotEnable method For this slot in turn the enabled Fe can be found by withe getFeSlotEnable(int) method e.g. fe = getFeSlotEnable((slot-2)/4) byte = (slot-2)%4 => bits_enabled = (ife>>(8*byte))&0xff; The eight bits of enabled tells you which fe's were enabled in the given slot The eight LSB returned by the getFeSoftTrigger method tells you whether softtriggers were enabled for a given set of fe's.
See Also
ConditionsChangeDelegator
Author
R. Poeschl LAL (based on the other interface classes)
Date
May 2006
Definition at line 60 of file ReadOutConfigurationBlock.hh.
Member Function Documentation
int CALICE::ReadOutConfigurationBlock::getBeSoftTrigger () const inline
Get the Be Soft Trigger Config.
Definition at line 200 of file ReadOutConfigurationBlock.hh.
Referenced by CALICE::TriggerHandlerCalice::checkForSoftwareTriggerOn(), and print().
int CALICE::ReadOutConfigurationBlock::getFeBrcSoftTrigger () const inline
Get the Broadcast Soft Trigger Config.
Definition at line 233 of file ReadOutConfigurationBlock.hh.
Referenced by print().
int CALICE::ReadOutConfigurationBlock::getFeSoftTrigger () const inline
Get the Fe Soft Trigger Config.
Definition at line 212 of file ReadOutConfigurationBlock.hh.
ReadOutConfigurationBlock& CALICE::ReadOutConfigurationBlock::setFeSoftTrigger (int feSoftTrigger) inline
Set the Fe Soft Trigger(s) Config.
Definition at line 206 of file ReadOutConfigurationBlock.hh.
The documentation for this class was generated from the following files:
ReadOutConfigurationBlock.hh
ReadOutConfigurationBlock.cc