CALICE_USERLIB: CALICE::CellNeighbourCalculator Class Reference
CALICE::CellNeighbourCalculator Class Reference
class to calculate all neighbour cells
#include <CellNeighbourCalculator.hh>
Public Member Functions
CellNeighbourCalculator (const Mapper *mapper)
constructor
lcio::LCCollection * getNeighbours () const
get cell neighbours for all valid cells
void getNeighbours (MappedContainer< CellNeighbours > *container) const
get cell neighbours for all valid cells
Protected Member Functions
void checkForCell (const unsigned int i, const unsigned int j, const unsigned int k, std::set< int > &cellIDset) const
CellNeighbours * getNeighbours (const int cellID) const
Private Attributes
const Mapper * _mapper
Detailed Description
class to calculate all neighbour cells
Author
Benja.nosp@m.min..nosp@m.Lutz@.nosp@m.desy.nosp@m..de
Version
0.1
Date
June 2009
Definition at line 22 of file CellNeighbourCalculator.hh.
Constructor & Destructor Documentation
CALICE::CellNeighbourCalculator::CellNeighbourCalculator (const Mapper * mapper)
constructor
Parameters
mapper Mapper that holds the mapping information from which the neighbours can be generated.
Definition at line 10 of file CellNeighbourCalculator.cc.
Member Function Documentation
lcio::LCCollection * CALICE::CellNeighbourCalculator::getNeighbours () const
get cell neighbours for all valid cells
Returns
LCCollection of CellNeighbours objects
Definition at line 88 of file CellNeighbourCalculator.cc.
References CALICE::Mapper::begin(), and CALICE::Mapper::end().
Referenced by getNeighbours().
void CALICE::CellNeighbourCalculator::getNeighbours (MappedContainer< CellNeighbours > * container) const
get cell neighbours for all valid cells
Parameters
[out] container MappedContainer where the CellNeighbours objects should be stored
Definition at line 103 of file CellNeighbourCalculator.cc.
References CALICE::Mapper::begin(), CALICE::MappedContainer< T >::clear(), CALICE::Mapper::end(), CALICE::MappedContainer< T >::fillByCellID(), and getNeighbours().
The documentation for this class was generated from the following files:
CellNeighbourCalculator.hh
CellNeighbourCalculator.cc