CALICE_USERLIB: CALICE::AhcCern2010TempProvider Class Reference
CALICE::AhcCern2010TempProvider Class Reference
This is a temperature provider for the AHCAL.based on the studies of the temperature profiles from CERN 2010 data.
#include <AhcCern2010TempProvider.hh>
Public Member Functions
AhcCern2010TempProvider (AhcMapper const *mapper)
void applyCorrection ()
float getSensorTemp (int module, int sensor)
Returns the temperature of the specified sensor in the given module.
float getCellTemp (int module, int chip, int chan)
Returns the temperature for the cell in the specified module connected to the given chip and channel.
float getCellTempError (int module, int chip, int chan)
Returns the error on the temperature for the cell in the specified module connected to the given chip and channel.
float getAvgTemp ()
Return the average calorimeter temperature.
float getAvgModuleTemp (unsigned module)
Return the average temperature for the specified module.
int getSensor (int chip, int chan)
Returns the closest sensor to cell connected to chip, chan according to DESY-THESIS-2008-050.
Public Member Functions inherited from CALICE::AhcTempProvider
AhcTempProvider ()
Default constructor.
virtual ~AhcTempProvider ()
Default destructor.
virtual void setAhcSroModBlocks (lcio::LCCollection *col)
Set the collection of AhcSlowReadoutModBlock objects to extract the temperature data from.
virtual void setCalibrations (lcio::LCCollection *col)
Set the collection of SimpleValue objects to use for the offset calibrations of the temperature sensors.
virtual void setSanityRange (float min, float max)
Define a sanity range of temperature values that make sense.
Protected Member Functions
void applyCorrectionForUnreasonableSensors (int module, int sensor)
bool applyCorrectionForUnreasonableModules (int module, int sensor)
Protected Member Functions inherited from CALICE::AhcTempProvider
virtual void updateCache ()
This function updates the internal 'cache' for the temperature values from the five sensors and applies the calibration offsets, if available.
Private Member Functions
bool isModuleOff (int module)
double median (float a[], int n)
Private Attributes
AhcMapper const * _mapper
float _calorimeterAverageTemperature
average temperature of the calorimeter
float _calorimeterAverageTemperatureRMS
float _calorimeterAverageTemperatureCount
std::vector< float > _moduleAverageTemperature
std::vector< float > _moduleAverageTemperatureRMS
std::vector< int > _moduleAverageTemperatureCount
Additional Inherited Members
Static Public Attributes inherited from CALICE::AhcTempProvider
static const unsigned N_MODULES = 38
static const unsigned N_SENSORS = 5
Protected Attributes inherited from CALICE::AhcTempProvider
bool newSroModCol
If true this indicates that setSroModBlocks() was called and a new collection of AhcSroModBlock objects was set.
bool newCalibCol
If true this indicates that setCalibrations() was called and a new collection of calibrations was set.
bool newSanityRange
If true this indicates that setSanityRange() was called and a new sanity range was set.
std::vector< std::vector< float > > sensorTemp
This is a 'cache' for the values of the temperature sensors after calibration and and correction.
std::vector< std::vector< float > > sensorTempError
This is a 'cache' for the errors on the values of the temperature sensors after calibration and and correction.
std::vector< std::vector< float > > sensorCalib
This is a 'cache' for the calibration offsets for the temperature sensors.
std::vector< std::vector< float > > sensorCalibError
This is a 'cache' for the errors on the calibration offsets for the temperature sensors.
std::vector< std::vector< int > > sensorCalibStatus
Vector to save the status of the calibration offsets.
float _sanityMin
Lower limit of the sanity range.
float _sanityMax
Upper limit of the sanity range.
lcio::LCCollection * _sroModCol
A pointer to the LCCollection containing the AhcSlowReadOut objects.
lcio::LCCollection * _calibCol
A pointer to the LCCollection containing the calibration offsets objects.
Detailed Description
This is a temperature provider for the AHCAL.based on the studies of the temperature profiles from CERN 2010 data.
Definition at line 15 of file AhcCern2010TempProvider.hh.
Member Function Documentation
float CALICE::AhcCern2010TempProvider::getCellTemp (int module, int chip, int chan) virtual
Returns the temperature for the cell in the specified module connected to the given chip and channel.
This is only the definition of the interface, a concrete funtion has to be implemented in a derived class. Note: Modules are counted from 1! The valid range for module numbers thus is 1 to 38.
Implements CALICE::AhcTempProvider.
Definition at line 29 of file AhcCern2010TempProvider.cc.
References getSensor(), CALICE::AhcTempProvider::newCalibCol, CALICE::AhcTempProvider::newSanityRange, CALICE::AhcTempProvider::newSroModCol, and CALICE::AhcTempProvider::sensorTemp.
float CALICE::AhcCern2010TempProvider::getCellTempError (int module, int chip, int chan) virtual
Returns the error on the temperature for the cell in the specified module connected to the given chip and channel.
This is only the definition of the interface, a concrete funtion has to be implemented in a derived class. Note: Modules are counted from 1! The valid range for module numbers thus is 1 to 38.
Implements CALICE::AhcTempProvider.
Definition at line 51 of file AhcCern2010TempProvider.cc.
References getSensor(), CALICE::AhcTempProvider::newCalibCol, CALICE::AhcTempProvider::newSanityRange, CALICE::AhcTempProvider::newSroModCol, and CALICE::AhcTempProvider::sensorTempError.
int CALICE::AhcCern2010TempProvider::getSensor (int chip, int chan)
Returns the closest sensor to cell connected to chip, chan according to DESY-THESIS-2008-050.
For the connection between the tile, chip and temperature sensors numbers, see http://www.desy.de/~richters/IJ-to-chip-channel/
Definition at line 74 of file AhcCern2010TempProvider.cc.
Referenced by getCellTemp(), and getCellTempError().
float CALICE::AhcCern2010TempProvider::getSensorTemp (int module, int sensor) virtual
Returns the temperature of the specified sensor in the given module.
Implements CALICE::AhcTempProvider.
Definition at line 490 of file AhcCern2010TempProvider.cc.
References CALICE::AhcTempProvider::newCalibCol, CALICE::AhcTempProvider::newSanityRange, CALICE::AhcTempProvider::newSroModCol, and CALICE::AhcTempProvider::sensorTemp.
The documentation for this class was generated from the following files:
AhcCern2010TempProvider.hh
AhcCern2010TempProvider.cc