LABVIEW2LCIO: CALICE::EUDAQBlock2016 Class Reference
CALICE::EUDAQBlock2016 Class Reference
Class for the SLCIO EUDAQ Data as acquired by the EUDAQ system.
#include <EUDAQBlock2016.hh>
Public Member Functions
EUDAQBlock2016 (int CycleNr, int BunchXID, int EvtNr, int ChipID, int NChannels, int TDC_0, int TDC_1, int TDC_2, int TDC_3, int TDC_4, int TDC_5, int TDC_6, int TDC_7, int TDC_8, int TDC_9, int TDC_10, int TDC_11, int TDC_12, int TDC_13, int TDC_14, int TDC_15, int TDC_16, int TDC_17, int TDC_18, int TDC_19, int TDC_20, int TDC_21, int TDC_22, int TDC_23, int TDC_24, int TDC_25, int TDC_26, int TDC_27, int TDC_28, int TDC_29, int TDC_30, int TDC_31, int TDC_32, int TDC_33, int TDC_34, int TDC_35, int ADC_0, int ADC_1, int ADC_2, int ADC_3, int ADC_4, int ADC_5, int ADC_6, int ADC_7, int ADC_8, int ADC_9, int ADC_10, int ADC_11, int ADC_12, int ADC_13, int ADC_14, int ADC_15, int ADC_16, int ADC_17, int ADC_18, int ADC_19, int ADC_20, int ADC_21, int ADC_22, int ADC_23, int ADC_24, int ADC_25, int ADC_26, int ADC_27, int ADC_28, int ADC_29, int ADC_30, int ADC_31, int ADC_32, int ADC_33, int ADC_34, int ADC_35)
Very ugly constructor because we use a Generic Object with many integers.
EUDAQBlock2016 (LCObject *obj)
'Copy constructor' needed to interpret LCCollection read from file/database.
virtual ~EUDAQBlock2016 ()
Important for memory handling.
int GetCycleNr () const
get the CycleNr.
int GetBunchXID () const
get the BunchXID.
int GetEvtNr () const
get the EvtNr.
int GetChipID () const
get the ChipID.
int GetNChannels () const
get the Channel.
std::vector< int > GetTDC () const
get the TDC.
std::vector< int > GetADC () const
get the HitBit_tdc.
void print (std::ostream &os, int)
get the HitBit_adc.
const std::string getTypeName () const
Return the type of the class.
const std::string getDataDescription () const
Return a brief description of the data members.
Detailed Description
Class for the SLCIO EUDAQ Data as acquired by the EUDAQ system.
Author
A. Irles, based on the EUDAQBlock writen by A. Irles DESY Hamburg
Date
January 12 2016 Created for 2016 testbeams EUDAQ data format.
Definition at line 23 of file EUDAQBlock2016.hh.
Member Function Documentation
std::vector<int> CALICE::EUDAQBlock2016::GetADC () const inline
get the HitBit_tdc.
get the GainBit_tdc.get the ADC.
Definition at line 195 of file EUDAQBlock2016.hh.
Referenced by CALICE::EUDAQEventBuilder2016::processEvent(), CALICE::EUDAQEventBuilder2018_cosmics::processEvent(), and CALICE::EUDAQEventBuilder2016_woBIF::processEvent().
void CALICE::EUDAQBlock2016::print (std::ostream & os, int)
get the HitBit_adc.
get the GainBit_adc.Convenient print method
The documentation for this class was generated from the following file:
EUDAQBlock2016.hh